app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Follow up for #1970
**Changes**
- Use view binding directly in BrowseGridFragment
- Inject UserRepository in class instead of in method
- Fix JumplistPopup initialized with null parent view
**Issues**
=> Use view binding directly in BrowseGridFragment

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/LibraryDreamService.kt, app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LiveTvPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/constant/LiveTvChannelOrder.kt, app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
This is mostly binary compatible so some files only show the import line changing.
**Changes**
- Replace legacy apiclient ItemSortBy, MediaType and CollectionType with SDK supplied constants
- Replace some hardcoded strings with the above mentioned constants
- Remove games collection type usage
**Issues**
=> Use constants from SDK

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
The SearchHint model is quite garbage, a bunch of it's values should be nullable but the server sends `00000000-0000-0000-0000-000000000000` as UUID instead lol. It also contains duplicate fields (id and itemId) and the "album" property is the name of an album instead of the id! That one is in the albumId field which the legacy apiclient didn't have.
**Changes**
- Always use SDK SearchHint
- There is actually only one single place it's retrieved from the API so it should be fairly easy to convert that call in a future PR
**Issues**
=> Always use SDK SearchHint

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
=> Support previous button in video playlist

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
**Changes**
- Removed the two unused parameters in reportPlaybackStopped
- Remove dependency on current session in ReportingHelper.reportStopped
**Issues**
=> Simplify reportPlaybackStopped code

app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java, app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
- Remove commented log statements
**Issues**
=> Remove commented log statements

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
**Changes**
- Keep ordering from album view in picture viewer
**Issues**
=> Keep ordering from album view in picture viewer

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
- Check for both the media adapter items and the video queue instead of video queue only in MediaManager
**Issues**
Regression from #1951
=> Fix crash when trying to start a picture slideshow

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
There's still some stuff with old apiclient types because they are used in other files and are a PITA to migrate right now.
**Changes**
- Migrate most of KeyProcessor to SDK types
**Issues**
=> Migrate most of KeyProcessor to SDK types

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
The code abuses item id's to open custom screens. It's horrible.
**Changes**
- Fix crash when opening favorites and video queue
**Issues**
=> Fix crash when opening favorites and video queue

app/build.gradle.kts, playback/core/build.gradle.kts, playback/core/src/main/AndroidManifest.xml, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/AndroidManifest.xml, playback/jellyfin/build.gradle.kts, playback/jellyfin/src/main/AndroidManifest.xml, playback/ui/build.gradle.kts, playback/ui/src/main/AndroidManifest.xml, settings.gradle.kts
_Yeah I'm still working on it and yes it takes a lot of time._
**Changes**
Update the Gradle modules to the current wip playback rewrite code. Instead of a single module it uses 4 now; core (logic), ui (player activity/fragment), exoplayer (player implementation) and jellyfin (SDK implementation for item retrieval etc).
The Gradle build files are copied, the manifests are emptied because no actual code is included in this PR.
**Issues**
Part of #1057
=> Add empty playback modules for rewrite

app/src/main/res/drawable-v26/app_icon.xml
Android 13 feature, doesn't make that much sense on a TV but it's an easy change so yeah
**Changes**
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2305178/188321690-637dff83-fcea-4b4f-a6ac-da74f043802e.png) | ![image](https://user-images.githubusercontent.com/2305178/188321719-33819b78-447c-47bc-9e93-3c4287995f1c.png) |
**Issues**
=> Add monochrome layer to adaptive icon

app/src/main/java/org/jellyfin/androidtv/ui/card/DefaultCardView.kt
Fixes an incompatibility with Android 13
**Changes**
- Set defaultFocusHighlightEnabled to false in DefaultCardView
**Issues**
=> Set defaultFocusHighlightEnabled to false in DefaultCardView

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
Some left over code from the earlier removal of the delete option caused the crash because item 6 didn't exist.
**Changes**
- Fix app crashing when opening "other options" menu in FullDetailsActivity
**Issues**
=> Fix app crashing when opening "other options" menu in FullDetailsActivity

app/src/main/java/org/jellyfin/androidtv/ui/TextUnderButton.kt
Same as #2027 but for TextUnderButton
**Changes**
- Set defaultFocusHighlightEnabled to false in TextUnderButton
**Issues**
=> Set defaultFocusHighlightEnabled to false in TextUnderButton

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
- Replace most usages of BaseItemType with BaseItemKind
**Issues**
=> Replace BaseItemType usages with BaseItemKind (SDK)

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Required for playback rewrite module to share the same WebSocket connection
**Changes**
- Add SocketInstance to dependency injection
**Issues**
Somewhat a part of #1057
=> Add SocketInstance to dependency injection

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
- Fix crash when opening a person via ItemLauncher, id was not converted to string
- Fix crash when trying to display birthdate (premieredate) or date of death (enddate) using wrong date type for the data format utility.
**Issues**
=> Fix two crashes when trying to view a person

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/NotificationsHomeFragmentRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchProvider.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRunnable.java
Depends on #2074
**Changes**
Use our custom ObjectAdapter that is more flexible for all item rows, right now this shouldn't change the behavior.
**Issues**
=> Use MutableObjectAdapter<Row> for rows

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt
Depends on #2075
**Changes**
Use MutableObjectAdapter<Object> as base for ItemRowAdapter. In a future PR we can leverage the replaceAll function to properly handle item mutations in rows. Right now most code does a clear() and then add all items again, this is inefficient and screws with the focused item.
**Issues**
=> Use MutableObjectAdapter<Object> as base for ItemRowAdapter

app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExternalPlayerProfile.kt
…ayer, VLC, nPlayer.
**Changes**
modifies ExternalPlayerActivity.java and ExternalPlayerProfile.kt to support high-priority external subtitles for External players, e.g. MX Player, VLC, nPlayer.
**Issues**
=> Support external subtitles in external player

app/src/main/AndroidManifest.xml, playback/core/build.gradle.kts, playback/core/src/main/AndroidManifest.xml, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/AndroidManifest.xml, playback/jellyfin/build.gradle.kts, playback/jellyfin/src/main/AndroidManifest.xml, playback/ui/build.gradle.kts, playback/ui/src/main/AndroidManifest.xml, preference/build.gradle.kts, preference/src/main/AndroidManifest.xml
The package attribute in the manifest XML is deprecated.
**Changes**
- Move package declaration to Gradle build files
**Issues**
=> Move package declaration to Gradle build files

app/src/main/java/org/jellyfin/androidtv/data/querying/StdItemQuery.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarView.kt, app/src/main/java/org/jellyfin/androidtv/util/Utils.kt
**Changes**
- Don't use KoinJavaComponent in Kotlin files
**Issues**
=> Don't use KoinJavaComponent in Kotlin files

app/src/main/java/org/jellyfin/androidtv/data/compat/AudioOptions.java, app/src/main/java/org/jellyfin/androidtv/data/compat/PlaybackException.java, app/src/main/java/org/jellyfin/androidtv/data/compat/StreamBuilder.java, app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java, app/src/main/java/org/jellyfin/androidtv/data/compat/SubtitleStreamInfo.java, app/src/main/java/org/jellyfin/androidtv/data/compat/VideoOptions.java, app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.java
**Changes**
- Remove deprecated setBackground function in BackgroundService - updated the call side
- Remove `@deprecated` annotations from legacy playback code - yes it's deprecated and we shouldn't use it, but no there is no need to add that annotation when we still need to use it.
**Issues**
=> Remove most deprecation annotations

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeToolbarFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
The launchWhenX functions have a performance penalty, using repeatOnLifecycle is the recommended function to use.
**Changes**
- Always use repeatOnLifecycle instead of launchWhenX functions
**Issues**
=> Always use repeatOnLifecycle instead of launchWhenX functions

app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
- Refactor ItemListActivity to fragment
**Issues**
=> Refactor ItemListActivity to fragment

app/build.gradle.kts, gradle/libs.versions.toml
Glide finally supports KSP. KSP is a replacement for Kapt which should result in faster (and less buggy) builds.
**Changes**
- Replace Kapt with KSP
**Issues**
=> Replace Kapt with KSP

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericGridActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GroupedItemsActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/UserViewActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchActivity.kt
We should now be able to start moving to a single activity architecture. There are still a few activities that might need some changes (moving logic to fragment) but overall I think it should be fairly easy now.
**Changes**
- Use fragment arguments instead of activity intent
- Always use our own fragment layout
**Issues**
=> Use fragment arguments instead of activity intent

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Also migrates a bunch of stuff to the SDK so we can use kotlinx.serialization
**Changes**
- Remove GsonJsonSerializer
- Migrate a bunch of stuff to SDK types
- Add `FakeBaseItem` for hacky code
**Issues**
=> Remove GsonJsonSerializer

app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchProvider.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRunnable.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/EmptyLifecycleAwareResponse.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/LifecycleAwareResponse.kt
The lifecycle of an activity/fragment keeps track of whether it's still available or not. In Kotlin we  launch coroutines in the scope of a lifecycle so they automatically cancel. In Java land we just have callback hell.
This PR adds two classes that extend the ApiClient's response classes and uses a lifecycle instance to check whether it's still available or not. Using these new response classes we can avoid running any code in the onResponse() function when a fragment is dead.
This fixes most crashes from #2132. This PR only replaces EmptyResponse with EmptyLifecycleAwareResponse. I did add a LifecycleAwareResponse as well but it's not used (yet).
**Changes**
- Add LifecycleAwareResponse
- Add EmptyLifecycleAwareResponse
- And use it
**Issues**
=> Add LifecycleAwareResponse

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/EmptyLifecycleAwareResponse.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/LifecycleAwareResponse.kt
Fixes some crashes that still happened after #2148 and #2155.
**Changes**
- Check Lifecycle.State.STARTED instead of Lifecycle.State.INITIALIZED
**Issues**
=> Check Lifecycle.State.STARTED instead of Lifecycle.State.INITIALIZED

app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Sort by and order are not set when opening photo directly instead of via media manager
**Changes**
- Fix PictureViewerFragment crashing when opening photo from latest row
**Issues**
=> Fix PictureViewerFragment crashing when opening photo from latest row

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Same as #2148 but for responses with generic in fragments. Still some usages left in custom views and other places.
**Changes**
- Replace Response<> usages with LifecycleAwareResponse<> in fragments
**Issues**
=> Replace Response<> usages with LifecycleAwareResponse<> in fragments

app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
With the new destination code we always have a single activity so we don't need to check if it's finished, we need to check the fragment lifecycle instead.
**Changes**
- Don't use activity.isFinishing()
**Issues**
=> Don't use activity.isFinishing()

app/src/main/AndroidManifest.xml, app/src/main/res/layout/fragment_search_text.xml
Moving the keyboard (gboard, android tv only) to the right makes it easier to see results.
**Changes**
- Show keyboard on right on text search fragment
- Add `android:windowSoftInputMode="adjustNothing"` to main activity for search
- Reorder android manifest
**Issues**
=> Show keyboard on right on text search fragment

app/build.gradle.kts, gradle/libs.versions.toml
Creating UI with compose is a billion time easier to do. We're already using it on our mobile app and I've used it for some of my own already. This PR is a starter that just adds the dependencies and build configuration to allow usage of compose in the Android TV app.
Of course because we're a television app there are some issues, like with everything Android TV:
- Compose is not officially supported for TV (yet)
- There is no default focus
- Using compose mixed in Android views is supported, but it doesn't work properly with dpad controls (needs one additional keypress after focusing the compose view)
With these caveats we can't switch our interactive UI (everything that supports dpad controls) but we can rewrite stuff like the backgroundmanager, screensaver, audio now playing …
=> Add Jetpack Compose support

app/build.gradle.kts, gradle/libs.versions.toml
We don't use it in the app anymore, it's still added indirectly because the old apiclient uses it.
**Changes**
- Remove direct GSON dependency
**Issues**
Closes #2207
=> Remove direct GSON dependency

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt, app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
This PR adds a content provider to act as a proxy when serving images to platform integrations. This resolves an issue where the Google Assistant rejects http urls and allows us to authenticate the image calls at some point.
One important implemenation detail is that we actually expose the content provider so it also works with third party launchers. Some other apps (\*cough*nvidia) don't do that and use a whitelist instead making it impossible for third party launchers to retrieve the images.
**Changes**
- Add ImageProvider for retrieval of images in platform integration
- Use ImageProvider in LeanbackChannelWorker
- Use ImageProvider in MediaContentProvider
**Issues**
=> Add ImageProvider for retrieval of images in platform integration

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorListPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorPickerDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsColorList.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt, app/src/main/res/drawable/subtitle_background.xml, app/src/main/res/layout/preference_color_list.xml, app/src/main/res/layout/preference_color_list_category.xml, app/src/main/res/layout/preference_color_list_option.xml, app/src/main/res/values/strings.xml
This adds more display and subtitle customization options to the preferences list,  needed to see which subtitle color you are selecting, and modifies the subtitle text renderer to display the text with the set options, as this is my first ever Android application and my first Java program in 10 years, I hopefully did not make any mistakes, I have tried to match the source code as much as possible to make the merge easier.
If possible I would request the pull request approver please check the resource attributes I have used to ensure they are correct especially the R.color.button_default_normal_text value 
**Changes**
- Modifies the RichListDialogFragment/RichListDialogOption preferences to be able to display colors
- Modifies StrokeTextView.kt and CustomPlaybackOverlayFragment.java to …
=> Add Subtitle Color Customization Features

playback/core/src/main/kotlin/queue/EmptyQueue.kt, playback/core/src/main/kotlin/queue/PagedQueue.kt, playback/core/src/main/kotlin/queue/Queue.kt, playback/core/src/main/kotlin/queue/QueueManager.kt, playback/core/src/main/kotlin/queue/SequenceQueue.kt, playback/core/src/main/kotlin/queue/item/QueueEntry.kt, playback/core/src/main/kotlin/queue/item/QueueEntryMetadata.kt, playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueue.kt, playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueue.kt, playback/jellyfin/src/main/kotlin/queue/AudioTrackQueue.kt, playback/jellyfin/src/main/kotlin/queue/EpisodeQueue.kt, playback/jellyfin/src/main/kotlin/queue/item/BaseItemDtoUserQueueEntry.kt
There we go, the first real code for the playback rewrite! This code was relatively stable (didn't see much changes in my occasional refactoring) so it's good enough to PR upstream.
**Changes**
**playback.core**
- Add Queue interface
A queue contains the items to play, simple as that. Queues are always lazy loaded to allow for big queues or changing future items on demand.
- Add EmptyQueue implementation
It's a queue that is empty.
- Add PagedQueue implementation
This one is kinda cool, it loads (sequential) pages of items and cache them. So when the player wants to know the next queue item it might have (pre-)loaded already so no network request is needed. Most of the Jellyfin specific queue implementations use this one as base.
- Add SequenceQueue implementation
Like PagedQueue but with …
=> Add playback rewrite queue system

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
```
2022-08-30 23:42:05.406   772-772   AndroidRuntime          org.jellyfin.androidtv.debug         E  FATAL EXCEPTION: main
Process: org.jellyfin.androidtv.debug, PID: 772
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at org.jellyfin.androidtv.ui.playback.VideoManager.setExoPlayerTrack(VideoManager.java:549)
at org.jellyfin.androidtv.ui.playback.PlaybackController.switchAudioStream(PlaybackController.java:955)
at org.jellyfin.androidtv.ui.playback.PlaybackController.onPrepared(PlaybackController.java:1491)
at org.jellyfin.androidtv.ui.playback.VideoManager$1.onIsPlayingChanged(VideoManager.java:134)
at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$24(ExoPlayerImpl.java:1944)
at …
```
=> Fix setExoPlayerTrack exception when allStreams is empty

app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeClickedListener.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeSelectedListener.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
1. open library
2. open item
3. go back
4. open item
The navigation state is now corrupt because the item was opened twice. This PR fixes that issue.
**Changes**
- Fix EnhancedBrowseFragment registering multiple listeners
**Issues**
=> Fix EnhancedBrowseFragment registering multiple listeners

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* Don't pause and stop reporting when skips are queued up.
* In `refreshCurrentPosition()`, use `currentSkipPos` to consider whether `mSeekPosition` should be used to report the playback position instead of querying the position from the player.
**Issues**
* Fixes #2214
=> fix seekbar not updating when using ff/rw buttons

playback/jellyfin/src/main/kotlin/queue/AudioTrackQueue.kt
**Changes**
- Always load item data from API in AudioTrackQueue.
This fixes an issue where an apiclient item converted to SDK item would have lost some data causing playback to fail.
**Issues**
=> Load fresh item data in AudioTrackQueue

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
When opening items via search/leanback integration the MainActivity would reset the navigation history so the item never showed. It just opened the home screen.
**Changes**
- Fix StartupActivity set destination is ignored
**Issues**
=> Fix StartupActivity set destination is ignored

app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
fixes some edge cases where the wrong destination would open and it became impossible to go to the home screen again.
**Changes**
- Always reset navigation in StartupActivity
**Issues**
=> Always reset navigation in StartupActivity

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
The app crashed because `gotoSeries()` was called when it shouldn't due to 
a missing return statement.
**Changes**
- Add missing return statement in FullDetailsFragment
**Issues**
=> Fix app crash when playing trailers

app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Add Video Codec Tag to Item View Page
**Changes**
Adds an additional tag to Created `addVideoCodecDetails` function to InfoLayoutHelper.java. The function is called by `addRatingAndRes` in the same file to add a tag with the codec name after the resolution tag.
**Issues**
Fixes  #2244
=> Add Video Codec Tag

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Subtract the subtitle delay from the playback position that is used to calculate when to show/hide external subtitles.
I have tested changing the subtitle delay on:
* a video with embedded subtitles
* a video with external subtitles
Both of them behaved as expected in my limited testing.
**Issues**
Fixes #2200
=> Apply subtitle delay to external subs

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
_Beta blocker 2 / ~~2~~ 3_
After the fragment migration the grid fragment started to act weird when resuming. The focus would get lost where it previously wouldn't. I had to rewrite a bunch of code to properly refresh existing grid items instead of replacing everything. From my testing it works now as expected, but the code is messy and this should definitely be rewritten at some point.
**Changes**
- Avoid clearing all items on ItemRowAdapter load
**Issues**
=> Avoid clearing all items on ItemRowAdapter load

gradle/libs.versions.toml
**Changes**
- Changed `"androidx.compose"` to `"androidx-compose"`
- Probably fixes Renovate not updating Compose
- Using a dot actually worked fine in Gradle but it was still wrong
**Issues**
=> Fix bad version.ref in dependency catalog

app/src/main/java/org/jellyfin/androidtv/data/model/AppNotification.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/res/values/strings.xml
_Will obviously show "0.15.0-beta.1" on actual beta release_
**Changes**
Add a notification that shows after each beta update. Pressing it will dismiss it until the next beta version. It does not show for development or stable builds (it searches for the "beta" string in the version name).
We have 2000+ beta participants on Google Play, but the beta program is only meant for users that actively report issues. Adding this notification will remind users that they participate in the beta program.
**Issues**
=> Add dismissible notification for beta releases

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
`setGroupCheckable` should be called after adding items to the menu, not before adding them.
**Changes**
- Fix missing checkboxes in player audio, subtitle and zoom menu
**Issues**
Fixes #2253
=> Fix missing checkboxes in player audio, subtitle and zoom menu

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
In 0.14 and earlier the HomeFragment would delay it's refresh-on-resume function by 1.5 seconds. This is because code crappy of race conditions in. This PR brings back this annoying behavior that makes the app look slow (well actually is sort of is..) because when starting playback from the home screen (via the context menu) will fail to hide an item when it's marked watched after the player closes (because race conditions).
**Changes**
- Delay home fragment refreshing again
**Issues**
=> Delay home fragment refreshing

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
When resuming a fragment with an paged adapter that had an item focused after the first page the leanback library would try to focus an item that wasn't ready yet. I fixed this in #2246 for ItemQuery but we also use pages for artists and a few other types.
**Changes**
- Use ItemRowAdapterHelper.setItems for artists
- Use ItemRowAdapterHelper.setItems for views
- Use ItemRowAdapterHelper.setItems for search results
- Use ItemRowAdapterHelper.setItems for latest items
- Filter out null values in ItemRowAdapterHelper.setItems
**Issues**
Fixes #2260
=> Use ItemRowAdapterHelper.setItems for more row types

app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
Used by smartscreen, movie suggestions and a few more. Navigating back would add all rows again instead of re-using existing rows.
**Changes**
- Fix EnhancedBrowseFragment duplicating items on resume
**Issues**
=> Fix EnhancedBrowseFragment duplicating items on resume

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Unable to test this (I don't have librarties without a collectiontype) but should theoretically solve the NPE from the issue.
**Changes**
- Fix opening user view with no collection type
**Issues**
Fixes #2262
=> Fix opening user view with no collection type

app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
Untested but should fix the NPE from the logs in the issue.
**Changes**
- Check null value in StreamInfo.getSubtitleProfiles
**Issues**
Fixes #2269
=> Fix NPE in ExternalPlayerActivity when getMediaSource() returns null

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
Something went wrong during the nav migration and it no longer used the dedicated fragment, which was also broken.
**Changes**
- Add BrowseRecordingsFragment to destinations
- Fix opening Live TV recordings
**Issues**
Partially fixes #2281
=> Fix opening Live TV recordings

app/src/main/res/layout/view_card_notification.xml
Just Android things
**Changes**
- Fix notification card not focusable on older Android versions
**Issues**
Fixes #2298
=> Fix notification card not focusable on older Android versions

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
**Changes**
- Remove mActivity from EnhancedBrowseFragment
- Use requireContext() or requireActivity() instead
- Remove onResponse handler in BrowseScheduleFragment (changing the activity title doesn't do anything on Android TV)
**Issues**
=> Remove mActivity from EnhancedBrowseFragment

app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt
Fixes remembering the last selected button so that it's reselected when coming back to the buttons row. As far as I can tell from other places in the app and other TV apps in general, this seems to be standard behaviour.
Side note: big fan of Jellyfin, keep up the good work 👍
=> Remember button focus on summary page

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Found this one a few days ago when I created a new emulator to test something on an old Android TV version and I chose a 720p display instead of 1080p.
**Changes**
Properly scale LegacyCardView with the screen density instead of hardcoding 2x. This fixes the scaling for pretty much all cards in app to be a consistent size across different display sizes. Previously only devices that rendered UI at 1080p (like most 4k/1080p devices) showed as intended.
AFAIk this bug was present in all previous app versions and actually makes the app unusable on 720p devices because the cards are way to big. A single episode card in the home screen would cover about 85% of the display.
**Issues**
=> Fix LegacyImageCardView scaling on non-1080p devices

gradle/libs.versions.toml
The acra-toast package depends on acra-core so this doesn't really change much. Just fixes a copy-paste mistake.
**Changes**
- Fix acra-core dependency using wrong name
- Update acra version (closes #2296)
**Issues**
=> Fix acra-core dependency using wrong name

app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Need testers for the second fix, please check if 1) you can open a recording and 2) the UI is the same as in 0.14.z.
**Changes**
- Fix Live TV program end time in FullDetailsFragment
- Fix opening Live TV recordings in FullDetailsFragment
- Fix Live TV program time in RecordPopup
**Issues**
Fixes #2311
Fixes #2312
Fixes #2319
=> Live TV program end time & recording page fixes

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Race condition magic
**Changes**
- Fix crash when stopping playback with back button when refresh rate switching is enabled
Calling onStop() releases libvlc and then calls finish()
**Issues**
Fixes #2291
Fixes #1855
Fixes #2060
Fixes #2283
=> Fix crash when stopping playback with back button when refresh rate switching is enabled

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/res/values/strings.xml
Direct paths have been deprecated in the server a while back (and is pending removal). Now that it broke in 0.15 it's easier to remove then to fix it.
**Changes**
- Remove direct path option from external player
- Remove unused constants from ExternalPlayerActivity
- Format ExternalPlayerActivity
**Issues**
Fixes #2269
=> Remove direct path option from external player

app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt
**Changes**
Reworked #2297 in way that does not cause regressions.
The previous implementation added a global focus listener that worked even if the buttons row was offscreen. The linked bug happened because a "last button" was stored when navigating to the movie screen and then when navigating to the person screen, that same button would request focus even if was offscreen. Detaching the listener when navigating between screens was not sufficient because it would always be called too late, ie. after the incorrect focus request happened. TIL global focus listener is very dangerous.
The rework involves a targeted focus listener for each button which does not operate while offscreen. The last focused button is only stored when navigating away from the buttons row, and only restored when …
=> Remember button focus on details screen

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
**Changes**
- Load requested item after the view is created because the `loadItem()` function calls `setBaseItem()` which updates the UI, it needs to be inflated before it can be used.
**Issues**
Fixes #2349
=> Fix race condition in ItemListFragment causing favorite music screen to crash

app/build.gradle.kts, playback/core/build.gradle.kts, playback/exoplayer/build.gradle.kts, playback/jellyfin/build.gradle.kts, playback/ui/build.gradle.kts, preference/build.gradle.kts, settings.gradle.kts
**Changes**
- Set root project name
- Don't add kotlin sourceset in build files (already added by default for a while now)
- Fix playback modules not supporting unstable/local SDK
**Issues**
=> Update build files

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
- Fix scaling of album images in audio queue on now playing screen
**Issues**
=> Fix scaling of album images in audio queue on now playing screen

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
I've only tested this one a single video item that needed transcoding for subs but also transcoded the audio. Not sure why the transcoding profile didn't allow all audio codecs.
**Changes**
- Allow all supported audio codecs in ExoPlayer transcoding profile
**Issues**
=> Allow all supported audio codecs in ExoPlayer transcoding profile

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
**Changes**
Add another row to the smart screen of show libraries displaying resumable episodes (similar to the implemenation for movies).
**Issues**
Fixes #2275
=> Show resumable episodes in smart screen for shows

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
TL;DR; removing code fixes issue 🤷 
**Changes**
Because the onCreateView function scheduled a callback for after the first render it caused some problems. The biggest one being that the focused item would not restore when going back and a side-effect was that the grid was kinda slow. When I reviewed the PR that introduced this change I probably missed this code, because it doesn't make sense anyway - you need to use onViewCreated to read measurements etc. and the fragment already does that. So removing this codeblock doesn't introduce any  issues because it was just duplicate code....
**Issues**
Fixes #2363
=> Fix BrowseGridFragment focus not restoring when going back

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Regression from #2381
**Changes**
- Remove DCA / TrueHD from ExoPlayer transcoding profile
**Issues**
Client-side fix for #2396
=> Remove experimental audio codecs from transcoding profile

app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt
Some stacktraces with Kotlin coroutines can get big. Right now we have 100 lines and this often is not enough to see what happened before the exception. Increasing the count to 250 should hopefully fix that.
**Changes**
- Increase amount of logs added to crash reports
**Issues**
=> Increase amount of logs added to crash reports

android-lint.xml
Ignores the missing `android.permission.POST_NOTIFICATIONS` permission caused by some Glide class that's not used in this project. There's a issue already raised but it hasn't been actioned yet: https://github.com/bumptech/glide/issues/4940
This should allow upgrading AGP to 7.4.0 without any issues.
=> Ignore missing notification permission from Glide

playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
There we go, the second third big PR for the playback rewrite! This one adds play session support which is pretty essential for Jellyfin.
**Changes**
- Add JellyfinPlugin
- Adds all Jellyfin specific stuff like PlaySession, Media resolving, QuickConnect etc.
- Add PlaySessionService
- Reports media progress to the backend
- This is what makes the dashboard show what a user is playing
- There might be some bugs in this implementation because our API isn't documented greatly
- Needs jellyfin/jellyfin#8971 to function properly
- Add PlaySessionSocketService
- Listens for PlayState commands on the WebSocket connection
- This is what allows for remote control
- Currently doesn't support playing queues yet
- This will come after video support is added and we can determine the queue type etc.
- …
=> Add PlaySessionService to playback rewrite

playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/exoplayer/src/main/kotlin/ExoPlayerPlugin.kt
There we go, the third big PR for the playback rewrite! Well actually not that big but it adds an important part. This PR is a follow up on #2401 where I didn't include the ExoPlayer backend intentionally.
**Changes**
- Add ExoPlayerBackend
- Supports all current features
- This will be the only backend in the forseeable future, multi-backend support and smart-backend selection are a low priority for now (but will likely be high priority when video support is added)
- Some features related to video are removed from this PR
**Issues**
Part of #1057
=> Add ExoPlayer backend to playback rewrite

app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
By default Glide did not set an `Accept` header. The SDK now provides one that includes both `image/*` and `*/*` as values. This fixes an issue where the server would fail to check which image types are supported.
**Changes**
- Use HEADER_ACCEPT from SDK as Glide Accept header value
**Issues**
=> Use HEADER_ACCEPT from SDK as Glide Accept header value

app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
This adds the ability for ExoPlayer to play AV1 without transcoding on API level 29 and up.
**Issues**
There's a few issues that reference AV1 support, but nothing really specific to ExoPlayer. LibVLC still appears to just black screen attempting to play AV1, but it doesn't appear to be related to the profiles stuff that was modified here.
There may be more/better ways of doing this, in theory ExoPlayer supports AV1 at even lower API levels, this might not correctly detect/advertise 10-bit support, but the only device I have available to test this on works correctly. This PR is bringing attention to this missing feature and to get the ball rolling on it.
Tested on: Chromecast with Google TV **HD** (which has hardware AV1 support; Chromecast with Google TV _4K_ does not do …
=> Add AV1 direct play support.

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
This changes the behavior back to what it was in 0.14. Unfortunately Amazon behaves weird when opening the PopupMenu when the keypress starts so this "fixes" that issue.
**Changes**
- Open item menu when keypress ends instead of when it starts
**Issues**
Fixes #2436
=> Change opening menu to ACTION_UP instead of ACTION_DOWN

app/src/main/java/org/jellyfin/androidtv/data/model/DataRefreshService.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt, app/src/main/res/values/strings.xml
This new preference shows a delete option for items when the user has permissions to delete the displaying item. This is a rewritten implementation of the previous delete option that was removed in 0.15.
**Changes**
- Add preference "enable media management"
- Add "delete" option to item details screen (when management is enabled)
- Only shows when the user has permission to delete the item
- Also checks per-library delete permission now
- Catches issues and shows a toast for it, to prevent crashes when deletion fails
- Change DataRefreshService.lastDeletedItemId to UUID
- Item deleted toast is now translatable
**Issues**
Fixes #2368
=> Add media management preference

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt
Supersedes #2452
Splitting the current MediaManager into an interface will allow for a new implementation of the existing functions with the new playback module as backing.
**Changes**
- Split MediaManager into interface and implementation
- Remove unused properties/functions from MediaManager
**Issues**
=> Split MediaManager into interface and implementation

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/res/values/strings.xml
Working on integrating playback rewrite module into existing UI.
**Changes**
- Change `playbackRewriteEnabled` to `playbackRewriteVideoEnabled`
- Add playbackRewriteAudioEnabled
- Remove `enable_playback_module_title` string resource (string is unused in beta/release builds)
**Issues**
Part of #1057
=> Add option to enable playback rewrite for audio

playback/core/build.gradle.kts, playback/core/src/main/kotlin/mediasession/MediaSessionOptions.kt, playback/core/src/main/kotlin/mediasession/MediaSessionPlayerGlue.kt, playback/core/src/main/kotlin/mediasession/MediaSessionPlugin.kt, playback/core/src/main/kotlin/mediasession/MediaSessionService.kt, playback/core/src/main/kotlin/mediasession/MetadataExtensions.kt
We're slowly getting a usable playback module! This PR adds [MediaSession](https://developer.android.com/guide/topics/media-apps/working-with-a-media-session) support. A media session is what enables stuff like the media notification, google assistant integration, controlling media from other apps / tv remote and more. It's quite a big deal.
For some reason, the default Android TV launcher doesn't load the images from URL (mobile Android does) so we need to fetch the bitmaps and put them in the data as well. We should also proxy the image requests via our own ImageProvider at some point to allow authenticated image requests. But this should probably be initiated from the BaseItemDtoUserQueueEntry builder.
**Changes**
- Add initial media session plugin
**Issues**
Part of #1057
=> Add MediaSessionPlugin to playback rewrite

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoQueueManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Working on a MediaManager implementation for rewrite. Didn't want to implement the stuff for video twice so here is the PR splitting that.
Ignore everything that looks hacky, just a part of the migration process :(
I tested this for like 30 seconds and nothing crashed.. yet
**Changes**
- Fix some nullability stuff in MadiaManager
- Add VideoQueueManager
- Does stuff that video queue managers do
**Issues**
everything I do these days is part of #1057
=> Split MediaManager into MediaManager and VideoQueueManager

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Cleaning some more in the MediaManager interface. It was basically a storage box for all kinds of stuff. Now it's 100% only audio things.
**Changes**
- Remove selected photo item from MediaManager and do some more cleaning
- Remove some unused code from MediaManager
- Remove some unused code from LegacyMediaManager
- Remove some unused code from PlaybackController
- Remove some unused code from BrowseGridFragment
- Smarter picture viewer starting in ItemLauncher
**Issues**
Also a part of #1057
=> Remove selected photo item from MediaManager and do some more cleaning

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
**Changes**
Shows the "shuffle" button when video player is set to "always ask". Selecting the shuffle button prompts the player types to be selected.
**Issues**
Implements #2321
**Some questions for the reviewers**
- The button is now labelled: "Shuffle" not "shuffle with". is that desired?
- I'm not used to java: I've created a seperate function: `playWithItemMenu` which is used within shuffleMenu and PlayMenu. Is this the correct way to implement such a feature?
- There are some other functions that are also hidden if "always ask" is selected. Would you like me to implement those too? If yes: should that be in this PR or seperate PR's per "feature"?
- What is the conversion policy for when/how to convert to Kotlin?
=> adds "shuffle with" button if "always ask" is selected as preferred player.

gradle/libs.versions.toml
Reverts jellyfin/jellyfin-androidtv#2466
Update caused immediate crashes when starting the app. Bug is already fixed by Google and should be releases soonish in 2.0.2: https://issuetracker.google.com/issues/267483394
=> Revert "Update dependency com.android.tools:desugar_jdk_libs to v2.0.1"

app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
**Changes**
- Fix rare picture viewer crash when album is empty
**Issues**
Fixes #2456 on the client
=> Fix rare picture viewer crash when album is empty

app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, playback/core/src/main/kotlin/PlaybackManager.kt, playback/core/src/main/kotlin/PlaybackManagerBuilder.kt, playback/core/src/main/kotlin/PlaybackManagerOptions.kt, playback/core/src/main/kotlin/PlayerState.kt
Small one today.
**Changes**
- Add PlaybackManagerOptions for defaultRewindAmount and defaultFastForwardAmount
- Update MediaManager (make createManagedAudioQueue private and some nullability fixes)
**Issues**
Part of #1057
=> Add PlaybackManagerOptions for defaultRewindAmount and defaultFastForwardAmount

app/src/main/java/org/jellyfin/androidtv/auth/model/LoginState.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
Right now when signing in goes wrong with an SDK exception we return `RequireSignInState`, which will show the "Invalid username and/or password" message. This is misleading because the credentials are most likely correct. This PR adds a new `ApiClientErrorLoginState` which re-uses the "Unable to connect to server" message.
Ideally the message should be different but we can't add strings in .z releases so that will be in another PR.
**Changes**
- Add `ApiClientErrorLoginState` when SDK exception happens during authentication
- Listen for TimeoutException in some more places
**Issues**
Related #2503
=> Don't show "invalid credentials" message when authentication fails with an SDK exception

app/src/main/java/org/jellyfin/androidtv/integration/dream/LibraryDreamService.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLogo.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/ZoomBox.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
**Changes**
- Separate the LibraryDreamService into separate files for each composable
- Improve animations
- Improve LibraryShowcase by loading the image before showing (fixes flickering)
- Add "now playing" to the screensaver
- Shows the currently playing track with track/album cover and artist(s)
- Uses the (darkened) blurhash as background
- See screenshot below
**Issues**
=> Show currently playing music on screensaver

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/res/layout/fragment_audio_now_playing.xml, app/src/main/res/values/strings.xml
Apparently this function is broken (I guess something with the 10.7 API migration?) and the implementation was bad anyway. Playlist managing will make a return when we revamp the UI.
**Changes**
- Remove saveAudioQueue from MediaManager
**Issues**
Fixes #2500
=> Remove playlist creation from NowPlaying screen

app/src/main/res/values/strings.xml
There's a lot of crashes when using LibVLC because our implementation is just bad. This PR changes the preference to end with "(experimental)" so users are less likely to use it.
**Changes**
- Mark LibVLC as experimental
**Issues**
=> Mark LibVLC as experimental

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Some theme properties, like the background, need to be applied before inflating the layout.
**Changes**
- Call applyTheme() before inflating layout
**Issues**
Fixes #2541 (together with #2542)
=> Fix theme not applied before creating views

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
**Changes**
Adds KEYCODE_ENTER wherever we accept KEYCODE_DPAD_CENTER. This was reported in #2526 where third-party remotes will use the former instead of the latter value.
I've added this to all places we accept CENTER, since our most of our Kotlin code already accepts this as an alternative and I can't forsee a case where we would want these to accept different things.
This was tested in the emulator to ensure we've not broken the existing mapping, but short of using the enter key (which works) I can't verify this fixes the original issue.
**Issues**
(Hopefully) Fixes: #2526
=> Accept KEYCODE_ENTER as alt to KEYCODE_CENTER

app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java, app/src/main/res/values/strings.xml
I introduced plurals in #2539 and they work great in Weblate. This allows different locales to use their own way of displaying time units.
**Changes**
- Rewrite `TimeUtils.formatSeconds` to use plurals
- Remove old strings for seconds,minute(s) and hour(s)
- Replaced usages with `getQuantityString()`
**Issues**
=> Always use getQuantityString() for time units

app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt
**Changes**
- Default to FIT_CENTER when scaleType is not set
**Issues**
=> Fix crash when scaleType is null in AsyncImage

app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
**Changes**
to match the same parameters in both queries, which seems to solve the problem by displaying the content with the numerical title in the "By letter" screen.
**Issues**
Fixes #2403
=> Add IncludeType param when sending number query

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLogo.kt
When the dream failed to display content and went from a library showcase to the logo it would flicker because there was no background for the logo content during the animation, and when the animation finished the library showcase would suddenly disappear. Adding a background color fixes this issue.
**Changes**
- Addmissing background in DreamContentLogo
**Issues**
=> Fix missing background in DreamContentLogo

app/baselineWorkaround.gradle, app/build.gradle.kts
**Changes**
- Add the workaround made by @obfusk to fix the reproducibility of the baseline profiles
**Issues**
Now really fixes #1639 (I tested it by making two clean builds locally and comparing them with `diff -r`)
=> Add workaround for non reproducible baseline profiles in AGP

app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt
**Changes**
- Fix an issue where the behavior of SearchFragment updating the child fragment in onViewCreated caused state restoration to fail.
**Issues**
Closes #2561
=> Fix SearchFragment not restoring properly

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
**Changes**
- Fix screensaver crash when loading an invalid backdrop image
- Add logging to getRandomLibraryShowcase
**Issues**
```log
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 5150516 markLimit: 5242880)
call GlideException#logRootCauses(String) for more detail
at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
at org.jellyfin.androidtv.integration.dream.composable.DreamHostKt$getRandomLibraryShowcase$backdrop$1.invokeSuspend(DreamHost.kt:89)
at …
```
=> Fix screensaver crash when loading an invalid backdrop image

app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerUserRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/store/AccountManagerStore.kt, app/src/main/java/org/jellyfin/androidtv/auth/store/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemUserPicker.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
**Side effects**
Unfortunately the changes in this PR have some side effects:
- When the "auto login" option is used and set to a specific user the PR disables it. You need to manually set the user again.
- When the "auto login" option is used and set to use the last active user, you need to select a user once after updating. No further action is required.
**Changes**
- Always check server id when retrieving user data from AccountManagerStore
- **This fixes a security issue** when 2 servers use a same user id, this should normally not happen but a malicious server could technically do this. There are no known instances of this happening.
**Issues**
=> Always check server id when retrieving user data from AccountManagerStore

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt
**Changes**
- Add a `blurHashPainter` composable function to create a painter for blur hashes. This allows the use of the blur hash in the Image composable or other composables that use a painter.
I've added this function to the AsyncImage file because eventually AsyncImage will use it.
**Issues**
=> Add blurHashPainter composable

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
When an item is empty (e.g. series without any seasons or season without any episodes) the server returns the following userData:
```json
{
"UserData": {
"UnplayedItemCount": 0,
"PlaybackPositionTicks": 0,
"PlayCount": 0,
"IsFavorite": false,
"Played": true,
"Key": "57125afe-ff17-942b-760d-3ab3185e9aff"
}
}
```
This is stupid because obviously the item cannot be "played" when there are no items. The app would always show a checkmark because `Played==true`, this is the same behavior as jellyfin-web but IMO the completely wrong behavior. Ideally this behavior would be changed on the server side but until that's a thing, here's a fix for the ATV app.
**Changes**
- Don't show watched indicator when item (series/season/other) is empty 
**Issues**
=> Remove watched indicator from empty series

app/src/main/java/org/jellyfin/androidtv/auth/model/AccountManagerAccount.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/store/AccountManagerStore.kt
Previously we would only use the username. Unfortunately this username should be unique per app. So if you have multiple servers with the same username the app would (accidentally) always overwrite the existing account when signing in. This PR updates the name we send to the account manager by appending the server URL.
The changes in this PR do not affect existing logins, it will update the name the next time you authenticate (so not on account use). We don't use those account manager names ourselves because we store our values in the user data.
**Changes**
- Use the combination of username+server address when storing users to the account manager
**Issues**
Fixes #2586
=> Save accounts to account manager by address

playback/core/src/main/AndroidManifest.xml, playback/core/src/main/kotlin/mediasession/AndroidMediaService.kt, playback/core/src/main/kotlin/queue/QueueService.kt
**Changes**
- Add androidx.media2 MediaSessionService implementation
This class is used to allow background playback and controlling playback from launcher / other apps.
- Fix QueueService backend listener registration shouldn't be in coroutine scope
**Issues**
Part of #1057
=> Add androidx.media2 MediaSessionService implementation

.github/workflows/app-build.yaml, .github/workflows/app-lint.yaml, .github/workflows/app-publish.yaml, .github/workflows/app-test.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/repo-stale.yaml
Supersedes #2596
actions/checkout `ac59398` -> `24cb908`
Supersedes #2595 
github/codeql-action `16964e9` -> `168b99b`
Additionally bumps [gradle/wrapper-validation-action to v1.0.6](https://github.com/gradle/wrapper-validation-action/releases/tag/v1.0.6)
=> Update and specify full action versions

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/AndroidAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ChannelBarChannelAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ChapterAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/CustomAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/FastForwardAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/GuideAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PlayPauseAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PlaybackSpeedAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PreviousLiveTvChannelAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/RecordAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/RewindAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SettingAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SkipNextAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SkipPreviousAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
**Changes**
Refactors the `CustomPlaybackTransportControlGlue` by:
- Removing static dispatch for custom actions and built-in actions
- Encapsulating the logic for each action into the action class
This will make it much easier to unit test actions, because we only need to inject the mocks for the method signature rather than everything the glue class could possibly need.
I've done this with as minimal changes to `videoAdapter` to not interfere with any playback rewrites going on. It's not perfect but (hopefully) it creates so better separation of concerns that will allow us to write tests at a later date.
In the future I want to shift as much logic out of the glue class into the relevant actions, but this diff is already quite large...
**To Test**
- Check all buttons work whilst playing …
=> Refactor CustomPlaybackTransportControlGlue to extract logic into actions

app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt
**Changes**
- Fix "null" on Live TV guide "load channels" button
Sometimes a channel doesn't have a number so we need to check for that. Ideally the text would be replaced with something like "load **more** channels" but string changes cannot be backported.
**Issues**
Fixes #2633
=> Fix "null" on Live TV guide "load channels" button

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/res/values/strings.xml
**Changes**
- Add (experimental) reactive homepage
When enabled, the home fragment will watch for updates from the server and reload **all** rows. The rows that use the ItemRowAdapterHelper will update their items while others will flicker. This functionality will do stuff like "live" reload the "next up" row when an episode is added to the server or watched on another device.
**Issues**
=> Add (experimental) reactive homepage

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
**Changes**
- Merge currentAudioQueue & managedAudioQueue (for now)
- Remove everything before currently playing item from currentAudioQueue
- Set "playing" on BaseRowItem for currently playing item
- Set index on BaseRowItem because why
**Issues**
Part of #1057
=> Fix playback rewrite audio queue in UI

app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
Not sure why it was hidden, I guess because the string "Born" is hardcoded but that will be fixed in an upcoming PR where I'm refactoring the InfoLayoutHelper.
**Changes**
- Enable BaseItemInfoRow for persons
**Issues**
=> Fix BaseItemInfoRow not showing for persons

build.gradle.kts, buildSrc/build.gradle.kts
**Changes**
Pins the implicit JDK version to 17 (based on our CI settings) to avoid gradle sync errors with 8.x
This is because Gradle has bumped the DSL to 1.8 with version 8.x, so it highlighted the implicit mismatch going on
**Issues**
Fixes #2495
=> Explicitly use JDK 17 through gradle toolchains

app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorPickerDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/DurationSeekBarPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/res/values/strings.xml, gradle.properties
AGP 8 enables the nonTransitiveRClass by default. We had to temporarily disable it again because our code wasn't migrated yet. This PR fixes that, this should result in a small performance increase during compilation.
**Changes**
- Enable nonTransitiveRClass
Mostly done by adding the android/androidx.leanback packages, but one string that we used from the leanback library is now added to our own string file.
**Issues**
=> Enable nonTransitiveRClass

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/AlbumArtistsQuery.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/res/drawable/tile_album_artists.xml, app/src/main/res/values/strings.xml
**Changes**
- Add separate buttons for artists and album artists in music smart screen
- Old "Artists" is renamed to "Album artists"
- Newly added "Artists" shows artists
Also adds some garbage because we couldn't retrieve artists from the ItemRowAdapter yet.
**Issues**
=> Add separate buttons for artists and album artists in music smart screen

app/src/main/java/org/jellyfin/androidtv/ui/GridButton.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
**Changes**
- Rewrite GridButton with Compose
- Add image-less grid button
- Use image-less grid button for everything except the "favorites" playlist in the music smart screen
Unfortunately the "active" effect cannot be changed for specific items without rewriting a lot of code so for now it uses the zoom effect instead of our regular background color change with buttons. This can be fixed when we convert even more stuff to compose.
**Issues**
top: music favorite button
bottom: image-less grid button
=> Rewrite GridButton with Compose

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Found this while testing #2690. In my test file I had the following streams:
| Index | ExoPlayer index | Description |
| --- | --- | --- |
| 0 | 1 | Video |
| 1 | 2 | Audio |
| 2 | 3 | Subtitle (PGS) |
As you can see, the subtitle track had id 3 but the check in the return didn't like that.
**Changes**
- Fix offsetStreamIndex when selecting last track
**Issues**
=> Fix offsetStreamIndex when selecting last track

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
We didn't support switching to an embedded subtitle track in ExoPlayer. This is needed for the PGS support in #2690.
**Changes**
- Fix switching ExoPlayer subtitle track
**Issues**
=> Fix support for switching embedded subtitle tracks in ExoPlayer

app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Similar to #2690. Could only find ts files for testing which is not a supported container format but I could see in the JF dashboard that the file went from transcoding (subs baking+container change) to just remuxing (container change) with this change.
**Changes**
- Enable DVB subtitles in ExoPlayer
**Issues**
=> Enable DVB subtitles in ExoPlayer

app/src/main/res/layout/popup_expandable_text_view.xml
**Changes**
- Fix ExpandableTextView cutting content
The layout_gravity was redundant and actually caused the layout measurement to be incorrect, this then made the behavior of the scrollview weird.
**Issues**
Fixes #2708
=> Fix ExpandableTextView cutting content

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
This should fix a regression in #2693 where SRT and SubRip would (often, but not always) use the ExoPlayer text rendering instead of our custom implementation.
**Changes**
- Fix ExoPlayerProfile not always listing SubRip and SRT as external
**Issues**
Fixes #2699
=> Fix ExoPlayerProfile not always listing SubRip and SRT as external

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Same as #2711 but for the 0.15.z branch.
**Changes**
- Fix ExoPlayer extensions not used for music playback
**Issues**
Fixes #2048
=> Fix ExoPlayer extensions not used for music playback (backport)

app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
There is no reason to not allow users to disable the option (it's enabled by default).
**Changes**
- Allow changing the (a)ac3 bitstreaming option on all devices
**Issues**
=> Allow changing the (a)ac3 bitstreaming option on all devices

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Feeding the dragon
**Changes**
- Add new `Resume` type to our fancy query system
- Implemented with the Kotlin SDK using the GetResumeItemsRequest model
- Uses the process lifecycle which will definitely not help preventing crashes but the item row adapter doesn't have a lifecycle :(
**Issues**
Fixes #2677
Fixes #600
Fixes #2077
=> Add support for retrieving resume items in BaseRowAdapter using the SDK

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Remove SSA tags when rendering text subtitles.
**Issues**
Partially fixes #1804, it doesn't implement the tags but hides them instead.
=> Hide SSA tags from SRT subtitles

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
**Changes**
- Fix HomeFragmentLatestRow using wrong import for runBlocking function
**Issues**
=> Fix HomeFragmentLatestRow using wrong import for runBlocking function

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
- Only allow screensaver to show when the player is paused
- Always disable screensaver when using LibVLC (we don't use the events we'd need to hook into)
The implementation adds yet another "helper" file written in Kotlin. This time because the `activityViewModel` extension function from Koin can only be used in Kotlin code.
**Issues**
Fixes #2225
=> Fix screensaver support in video player

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
**Changes**
- Make sure that channel items always have an image by using our "tile_land_tv" image as fallback
- This was the previous behavior for the "my media" channel but was removed with #2515
- This change also adds this image for other channel items
**Issues**
Fixes a regression from #2515
=> Add fallback image to LeanbackChannelWorker

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/res/layout/vlc_player_interface.xml
Doesn't really change much except making the migration to androidx.media3 easier.
**Changes**
- Migrate ExoPlayer to StyledPlayerView
**Issues**
=> Migrate ExoPlayer to StyledPlayerView

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Removing a hidden surprise feature from #2745.
**Changes**
- Rename "finish()" function in CustomPlaybackOverlayFragment to "closePlayer" so it won't be confused with Android's finish function
- Update some activity finish calls to use closePlayer in the PlaybackController & VideoManager
**Issues**
=> Fix app closing when media finishes playing

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
**Changes**
- Use navigation.goBack instead of activity finish in FullDetailsFragment when deleting a series timer (I believe that's a scheduled recording for live tv?)
- Remove an obsolete check in HomeRowsFragment (the MainActivity already checks auth)
**Issues**
=> Use navigation.goBack instead of activity finish in FullDetailsFragment

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ColorPickerDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerAddFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/StartupToolbarFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
See https://developer.android.com/topic/libraries/view-binding#fragments
**Changes**
- Don't use `lateinit var` for view binding in fragments
- Clean up view binding instance when destroying fragment view
We still have some fragments written in Java that don't store the binding as class property that need migration. Out of the scope for this PR though.
**Issues**
=> Fix view binding leak in fragments

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
**Changes**
- Use Duration in BackgroundService
- Only use a single StateFlow in BackgroundService
- Don't use main thread in BackgroundService
- Fix background flickering when scrolling fast
- This was because the UPDATE_INTERVAL was 0.5 s but the animation was 0.8s, using a single constant for both values fixes the problem for good.
**Issues**
=> Fix BackgroundService flickering

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
When the user image was loaded after the fragment view was destroyed the app could crash. To fix this we send the fragment to Glide instead of the context so it can check if the fragment view is still visible.
**Changes**
- Fix rare race condition crash in HomeFragment
**Issues**
=> Fix rare race condition crash in HomeFragment

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/model/PlaybackOrder.kt, playback/core/src/main/kotlin/queue/EmptyQueue.kt, playback/core/src/main/kotlin/queue/Queue.kt, playback/core/src/main/kotlin/queue/QueueService.kt, playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueue.kt, playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueue.kt, playback/jellyfin/src/main/kotlin/queue/AudioTrackQueue.kt, playback/jellyfin/src/main/kotlin/queue/EpisodeQueue.kt
**Changes**
This change adds a new "playbackOrder" property to the playback state. The currently supported values are:
- default - this plays back items in the default order of the queue
- random - this plays random items, infinitely
- shuffle - this plays items in a shuffled order, this is the same as random but every item in the queue can only be played once
Changing the order property only affects the upcoming items in a queue. This means you can play the first 3 items using default order and then switch to shuffling. The queue service keeps track of this and manages the ordering.
To implement this ordering we now need to know the size of a queue, for this a new "size" property is added to the queue interface. I've implemented this properly for the queue used by the RewriteMediaManager …
=> Add playback order support to playback rewrite

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
Crash occurred when the profile picture loads when the view is already destroyed.
**Changes**
- Fix race condition in HomeFragment 
**Issues**
I guess #2780 wasn't enough
=> Fix race condition in HomeFragment causing a crash

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
This fixes a case where both the system and the app would act on key presses at the same time. So when you pressed the "PAUSE_PLAY" button on a remote it would toggle the state twice, so you'd never pause/play the item.
**Changes**
- Disable custom key handling when using playback rewrite
**Issues**
Companion for #2803. Part of #797
=> Disable custom key handling when using playback rewrite

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt, playback/core/src/main/kotlin/model/RepeatMode.kt, playback/core/src/main/kotlin/queue/PlayerQueueState.kt, playback/core/src/main/kotlin/queue/order/DefaultOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
**Changes**
- Add repeatMode
- Can be turned off, set to repeat the entry once or repeat the entry infinitely
- Will likely add REPEAT_QUEUE_INFINITE at some point
- Media sessions can change this (off/entry-infinite)
- AudioFragment thingy can change this (off/entry-infinite)
- Move index providers for playback order to separate files to clean up the PlayerQueueState class
**Issues**
Part of #1057
=> Add repeat mode to playback rewrite

app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/RecommendedServerIssueExtensions.kt, app/src/main/res/values/strings.xml
**Changes**
- Remove server_unsupported
- Reword server_issue_outdated_version and server_unsupported_notification
- Both now use the recommended server version instead of the minimum version. The recommended version is the version used to generate the API. We generally update the SDK for each server release and update the app in about 2 weeks, so the recommended version is the latest server version most of the time.
**Issues**
=> Update unsupported server messages

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/res/values/strings.xml
This PR will be in draft until full feature parity is reached, which should be soon.
**Changes**
- Enable playback rewrite for all music playback by default
- Also enable this for existing installs via a migration
- Add new option to disable playback rewrite for music (will use the old media manager)
**Issues**
edit: of course a part of #1057!
=> Enable playback rewrite by default for music

app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
When reporting the progress of a live tv stream the position was technically correct (time since the stream started) but that would end up causing issues like [this](https://www.reddit.com/r/jellyfin/comments/13ywrfl/i_wish_i_could_claim_credit_for_the_uptime/). This change always reports 0 as progress for live tv.
We might want to add additional changes to jellyfin-web eventually to now show progress if runtime is 0.
**Changes**
- Fix Live TV progress reporting
**Issues**
=> Fix Live TV progress reporting

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
On Android TV some tags are shown such as 'R', '4K' 'HEVC', etc.
Titles which have external subtitles, are missing the resolution and video codec tags (e.g. '1080' and 'H264').
The source of the issue is `org.jellyfin.androidtv.util.InfoLayoutHelper.addRatingAndRes` getting all media streams, and assuming that the video stream will be the first one, when in fact external subtitles are first (also verifiable by looking at the debug info at the bottom).
**Changes**
Instead of assuming the video is the first stream, take the first stream tagged as `MediaStreamType.VIDEO`.
**Issues**
#2811
=> Fix InfoLayoutHelper not using first video stream, update details when selecting version

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
**Backports** a single line from #2461 that should fix some issues.
**Changes**
- Fix ItemLauncher retrieving base item via from media manager when launching a photo
**Issues**
Should fix #2764
=> Fix ItemLauncher retrieving base item via from media manager when launching a photo

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/di/AndroidModule.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, playback/core/src/main/kotlin/PlaybackManagerBuilder.kt, playback/core/src/main/kotlin/PlaybackManagerOptions.kt, playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/PlayerVolumeState.kt, playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt, playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
**Changes**
Add volume state and manipulation to the playback code. It is also exposed to media sessions, play sessions and remote control. This means you can change the volume of your TV from jellyfin-web or the mobile app. Useful when playing music!
**Issues**
yes #1057
=> Add volume state to playback rewrite

app/src/main/java/org/jellyfin/androidtv/data/model/AppNotification.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/res/layout/fragment_select_server.xml, buildSrc/src/main/kotlin/Properties.kt
This PR shows the UI mode warning on the startup screen. The login UI is not really usable on phones so we can't rely on the notification after sign in anymore.
**Changes**
- Add "public" option to AppNotification
- Currently only used for the UI mode warning
- Show public notification on server selection screen
- This is the initial screen that shows on a fresh install
- Sneak in a little build script warning fix
**Issues**
=> Show UI mode notification on startup screen

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt
When navigating between fragments we have various options to how the navigation should act. One specific navigation flow could cause some issues. When navigating as follows:
Home -> Player -> Next Up -> Player
You'll notice the home fragment flickering in the background. This was because of multiple issues:
1) The `addOnBackStackChangedListener` function could sometimes falsely trigger itself
2) the `popBackStackImmediate` call would run before the next transaction, causing the revert of that transaction to add the HomeFragment again before the transaction would run
To solve this I had to offer my soul to the developer gods and then make two changes:
1) Use `popBackStack` instead, this will then run just before the next transaction instead of immediately
2) Use the `replace` function …
=> Fix navigation reset called during back stack pop call

app/src/main/AndroidManifest.xml
This fixes an issue on Android 13 and newer where the channels on the home screen could not be launched because the view action was not added to the manifest.
**Changes**
- Add missing view action to StartupActivity
**Issues**
=> Add missing view action to StartupActivity

app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt, app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/ContextExtensions.kt, app/src/main/res/values/strings.xml
**Changes**
- Add preference to disable device type detection notification
- Shows under "developer options"
- Only shows when the warning would normally show (on phones)
- Requires app restart to take effect
**Issues**
Fixes #2881
=> Add preference to disable device type detection notification

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/res/layout/vlc_player_interface.xml
I just started a 21:9 video on my 16:9 TV and instead of black bars the backdrop showed behind the player.. oops
**Changes**
- Fix player background not black
- Reformat vlc_player_interface.xml
**Issues**
=> Fix video player background not black

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
- Move CC ~~after audio codec info~~ before format info
- Specify interlaced or progressive in resolution
- Specify if Dolby Vision or other HDR
- Specify if Dolby Atmos or DTS:X
- Specify if DD+ or DTS-HD, rename Dolby to DD
=> Improve codec info

app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
Previously we only stopped playback after the user is changed, with this change we also stop media immediately after usiong the switch users button in the home toolbar
**Changes**
- Stop media playback when switching users
Previously we only stopped playback after the user is changed, with this change we also stop media immediately after usiong the switch users button in the home toolbar
- Don't clear ApiClient credentials when destroying a session
This fixes various crashes where API calls would fail after a session was destroyed. Most notable was the crash that occurred when stopping music playback when switching users
**Issues**
=> Fix crash when switching users while playing music

app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/res/drawable/shape_card.xml, app/src/main/res/layout/fragment_audio_now_playing.xml, app/src/main/res/layout/view_row_details.xml
**Changes**
- Use rounded corner for item details image
~~Only works on Android 12 and up for now~~
| Before | After |
| --- | --- |
| ![image](https://github.com/jellyfin/jellyfin-androidtv/assets/2305178/ad7034ae-4b93-4272-b874-f6cba7ff4534) | ![image](https://github.com/jellyfin/jellyfin-androidtv/assets/2305178/12e891fd-c355-4beb-ba90-709064bded7d) |
=> Use rounded corner for item details image

app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt
This is a bit of a hack but the FullDetailsFragment is too messy to fix it properly right now...
**Changes**
- Remove current parent first if set to avoid a crash (parent already set)
**Issues**
=> Fix crash when reusing actions in MyDetailsOverviewRowPresenter

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
Basically every time the fragment resumed (e.g. going back to it from another screen) it would add another rows fragment instead of replacing it.
**Changes**
- Fix UI corruption when resuming the FullDetailsFragment
**Issues**
=> Fix UI corruption when resuming the FullDetailsFragment

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
**Changes**
- Fix race conditions where selected item would change during refresh
- Catch API exceptions
- Remove item from adapter when refresh fails (~~should actually only happen with a 404 but the server returns a 500 🤷~~)
- Format some files
**Issues**
Fixes #2948
=> Improve BaseRowItem refreshing (fix crash after item deletion)

playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
- Fix ExoPlayerBackend not triggering onMediaStreamEnd correctly
We not use a smarter approach by using `onPlayWhenReadyChanged` which will now always be called to set `playWhenReady=false` when an item ends because of the `setPauseAtEndOfMediaItems` option.
This also fixes the repeat feature broken in #2935
**Issues**
=> Fix ExoPlayerBackend not triggering onMediaStreamEnd correctly

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/res/layout/horizontal_grid_browse.xml
**Changes**
It has always annoyed me how the grid and the title are not aligned so this PR matches their margin values
=> Add margin to media grid

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
Tested the specific case where the subtitles are on by default and require transcoding. Disabling those will set the index to `-1` which was ignored in the PlaybackManager `getVideoStreamInfo` function so the server would happily reply the video info with default subtitles enabled.
**Changes**
- Fix disabling subtitles not always working
**Issues**
Fixes #2045
Fixes #2631
=> Fix disabling subtitles not always working

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
**Changes**
Right now the timers are updated in such a way that, depending on the song, they may update up to half a second apart.
This PR rounds the current time value to seconds so that the rounding that happens when the milliseconds are displayed doesn't cause the timers to be out of sync.
=> Synochronise music timers

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Removed some unnecessary Thread.sleep usages and slightly refactored the PlaybackController.stop function
**Issues**
=> Remove Thread.sleep usages

playback/core/src/main/kotlin/mediastream/MediaConversionMethod.kt, playback/core/src/main/kotlin/mediastream/MediaStream.kt, playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
**Changes**
- Add MediaConversionMethod to MediaStream
Right now there are 3 modes that correspond to the existing play methods but the idea is to extend them in the future to more detailed variants, e.g. `MediaConversionMethod.Transcode.BakeSubs`. This information can then be used for easy troubleshooting
- Support remuxing and transcoding in AudioMediaStreamResolver
We request media info from the server and previously used it to construct a direct play URL. Now we actually use the provided information to choose a suitable media conversion method, including remux and transcode.
- Report playMethod and repeatMode in PlaySessionService
Server is dumb and if we don't set the playMethod it will tell everyone "HEY THIS DUDE IS DIRECT PLAYING!" while it is transcoding 🤷
**Remux & Transcoding …
=> Add transcoding and remuxing

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt
**Changes**
Check marks are usually used for settings where the user is allowed to select multiple options.
In this case only one way of fitting the video onto the screen can be used at a time.
Thus radio buttons are a better fit.
=> Make aspect ratio setting use radio buttons

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
**Changes**
- Fix sync issue in ItemRowAdapterHelper
Basically the item row adapter is garbage and my helper failed with an edge case because the code is garbage
- Add some changes to experimental reactive home to have it reload faster
Previous fix introduced a new (or actually it now happened more often..) race condition where having two retrievals running for the same row would duplicate items because once again the item row adapter is garbage
**Issues**
Fixes #3021
=> Fix sync issue in ItemRowAdapterHelper

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt, playback/core/build.gradle.kts, playback/exoplayer/build.gradle.kts, playback/jellyfin/build.gradle.kts, playback/ui/build.gradle.kts, preference/build.gradle.kts
**Changes**
- Use Android 14 SDK (API 34)
- Also removes the targets from library modules as those are deprecated
- Fix one compile issue related to a signature change in the new SDK
- Fix Koin deprecation warnings when using `get<>()` in Compose code
**Issues**
=> Use Android 14 SDK (API 34)

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
**Changes**
Right now the grid checks the total item amount, not the item amount after filtering. This results in the grid being focused on even if it is empty.
Side-note: I'm not sure how good of an idea it is to hijack the focus even when there are items in the grid.
=> Fix grid getting focus when empty

app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
The reset function uses the default value in case we ever change it.
**Changes**
- Fix ExternalPlayerActivity not using PreferenceStore.reset
**Issues**
=> Fix ExternalPlayerActivity not using PreferenceStore.reset

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
**Changes**
Fix the app grabbing 4k background images even when the screen is just 1080p.
As a side-effect that also saves a lot of cache space :)
=> Grab background images no larger than the screen

app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/res/drawable/tile_square_user.xml, app/src/main/res/drawable/tile_user.xml, app/src/main/res/layout/fragment_server.xml, app/src/main/res/values/attrs_tiles.xml, app/src/main/res/values/theme_jellyfin.xml, app/src/main/res/values/theme_mutedpurple.xml
**Changes**
On first open of the user select menu the transition between the placeholder and the user image forced the image to use the dimensions of the placeholder. This resulted in the image being far too cropped in.
**Before**
**After**
This is _kinda_ a hack as I simply converted the placeholder image into a square, but it works and I'm not sure what else could be done.
=> Fix user image being too cropped in

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
**Changes**
- Restore session on MainActivity stop, this fixes an issue where resuming the app from a paused state won't show the login screen when automatic sign in is disabled.
**Issues**
Fixes #3038
=> Restore session on MainActivity stop

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
welcome to race condition hell, the stop function is called in **11** places
**Changes**
- Fix playback stop reported twice
actually a regression from #3000
- Add some more logging
**Issues**
Nobody reported this in the 14 days this beta was live, why do we have a beta program?
=> Fix playback stop reported twice

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Add Opus and FLAC to ExoPlayer's list of codecs so they can direct-play.
Remake of https://github.com/jellyfin/jellyfin-androidtv/pull/2376 since the original author seems to be absent.
**Issues**
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/2359 https://github.com/jellyfin/jellyfin-androidtv/issues/2366
=> Enable support for Opus and FLAC in ExoPlayer

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
In `setExoPlayerTrack`, filter for the correct index instead of addressing the index directly. This ensures the correct subtitle steam is selected, even when some tracks are filtered out.
**Issues**
#3089
=> Fix embedded subtitles not loading when subtitle filter on library

playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/backend/BackendService.kt, playback/core/src/main/kotlin/backend/PlayerBackend.kt, playback/core/src/main/kotlin/backend/PlayerBackendEventListener.kt, playback/core/src/main/kotlin/mediastream/MediaStream.kt, playback/core/src/main/kotlin/mediastream/MediaStreamResolver.kt, playback/core/src/main/kotlin/mediastream/MediaStreamState.kt, playback/core/src/main/kotlin/queue/PlayerQueueState.kt, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
Add automatic transcoding support to new playback code based on the capability testing from #3062. This is the final release blocker, unless something else comes up.
I'm not entirely happy with how it works but unfortunately the server doesn't give us much to work with. Direct play & remux can be tested client side because we know what the media information will look like but a proposed transcode from the server does not give us any information except for the container & protocol which is too little to properly do capability testing with.
**Changes**
- Add IMediaStream interface for the base definition of a media stream
- Implemented by MediaStream and PlayableMediaStream
- What we previously called MediaStream is now PlayableMediaStream - it adds the queueEntry & url propertyes on top of …
=> Support remux/transcode fallback in new music player

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Regression from the activity->fragment change. When the video player starts up it will change the preferred display mode on the window object. This should be set back to 0 ("no preference") when the player closes, which previously happened automagically because the activity closed.
**Changes**
- Fix display mode not changing back when closing player
**Issues**
Fixes #3114
=> Fix display mode not changing back when closing player

app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
Two issues:
1) Old Android versions need `isFocusableInTouchMode` for some stupid reason
2) The focus was actually sent to the ComposeView so we had to block it
**Changes**
- Fix GridButtons not working on Android ~7ish and below
**Issues**
Fixes #3118
=> Fix GridButtonPresenter focus on old Android platforms

app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt
So I found out that I didn't implement this yet a week ago... oops. Also found (and fixed) some bugs while working on it.
**Changes**
- Support custom `areItemsTheSame` and `areContentsTheSame` functions in MutableObjectAdapter
- Implement queue management in RewriteMediaManager
- Adding to an existing queue will always add after the current playing item (or current if no item is playing)
- Adding to an empty/stopped queue will play immediately
- I deliberately did not look at the old implementation for this behavior and used what made the most sense to me
- Optimize queue->currentAudioQueue sync
- Use AudioQueueItem instead of BaseRowItem so the KeyProcessor shows the correct menu items for queue management
- Simplify the mapping
- Use custom `areContentsTheSame` function that always …
=> Implement queue management in RewriteMediaManager

app/src/main/java/org/jellyfin/androidtv/ui/ScreensaverViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
`FLAG_KEEP_SCREEN_ON` was never set if not using the new in-app screensaver. This caused the system screensaver to start during video playback... whoops.
From my initial testing this does however crash the video player once the (system-)screensaver is closed and the app needs to resume. ~~Will need to do some more testing and potentially fix that (separate PR)~~ see #3207.
**Changes**
- Dynammically set FLAG_KEEP_SCREEN_ON based on both the lock count and whether the in-app screensaver is enabled or not
**Issues**
Fixes #3193
=> Fix system screensaver starting during video playback

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
In some cases the video player may be stopped when the activity is paused. This ends up crashing the app on resume. Check for this kind of invalid state and close the video player to prevent crashing.
**Changes**
- Close video player on resume with invalid state
**Issues**
=> Close video player on resume with invalid state

app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Several codecs support HDR, so the codec info is useful to display even for HDR streams.
**Changes**
- Keep codec info displayed for HDR streams
- Display codec info before any HDR info
=> Keep codec info displayed for HDR streams

app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
I'm fairly new to Java/Kotlin/Android, so I'm not sure if this approach is the best, or if it should be used in other instances (such as in `TimeUtils`). It at least appears to fix the linked issue.
Is it reasonable to cut out usage of `Date` and stick with `LocalDateTime`, here and perhaps in `TimeUtils`?
Also: the "Premiere" date for TV seasons inside `InfoLayoutHelper::addDate` is in UTC, but the "Premiere"/"Born" date for actors is... odd. For example, in UTC-6: `1950-01-01T06:00`, and UTC+3: `1950-01-01T15:00`. Is this coming from the server, or was it changed in the client? Perhaps it acts oddly when the client is set to a different TZ than the server?
**Changes**
`TimeUtils.getDate` internally calls `Date.format`, which translates the UTC timestamp into local TZ timestamp. If a …
=> util: Don't use TZ offset for media Premiere Date

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
**Changes**
This code is messy but basically we do a lot of magic to send the "PlaybackController" instance from the CustomPlaybackOverlayFragment to LeanbackOverlayFragment. This happened in two ways: via the PlaybackControllerContainer and the initFromView function. Then both classes contained a (m)playbackController variable to store the value.
In this PR I did a few things:
- Removed the local (m)playbackController variables
- Changed the initFromView function to not take a playback controller instance
- Check if the playback controller is null in LeanbackOverlayFragment.onCreate - which can happen when the video player in rare instances (empty queue / no audio manager in the android system)
- Always get the controller from the container
While I cannot reproduce the issue and thus …
=> Fix crash when starting player where playback controller may be null

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
Just found this by accident... whoops
**Changes**
- Fix RewriteMediaManager never used in production builds
**Issues**
=> Fix RewriteMediaManager never used in production builds

app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
**Changes**
- Manually close IME and set focus when using IME_ACTION_PREVIOUS
- Focus on search results when submitting search
**Issues**
Fixes #3242
=> Fix focus issue when pressing back in Fire TV soft keyboard

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
**Changes**
- Add special case in ItemLauncher to only play a single track when the item is a search result. This prevents the app from queuing all search results
**Issues**
Fixes #3243
=> Fix playing audio from search queues entire row

app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java
**Changes**
- Fix opening collections via search results showing empty screen
- The childCount property is not set for search results so when the collection screen opened it would never load data. Removed a (unnecessary?) check.
- Reformat file / remove useless onActivityCreated function that just calls super
- Use BaseItemKind enum instead of strings for queries
**Issues**
=> Fix opening collections via search results showing empty screen

playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt, playback/core/src/main/kotlin/queue/PlayerQueueState.kt, playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
Some issues that probably happened because I was developing the playback rewrite on multiple branches and at some point merging some incompatible stuff came together to create this issue.
**Changes**
- Make sure we never set `currentMediaItemIndex` to 1 when there is no next item in the generated media3 playlist
- Always use index 0 in replaceQueue as the index mapping (via sortOrder) will give a randomized value already. Setting a random index in `replaceQueue` will just skip a bunch of queue items
- Do all value setting in replaceQueue with the coroutineScope to prevent race conditions when the coroutine is delayed
- Fix ShuffleOrderIndexProvider not really shuffling. The first two items were shuffled but everything after that was just repeating the second item... oops
**Issues** …
=> Fix crash and inconsistent ordering when using ShuffleOrderIndexProvider

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/ui/playback/LegacyMediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/res/layout/vlc_player_interface.xml, gradle/libs.versions.toml, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/exoplayer/src/main/kotlin/mapping/audio.kt, playback/exoplayer/src/main/kotlin/mapping/container.kt, playback/exoplayer/src/main/kotlin/support/AdaptiveSupport.kt, playback/exoplayer/src/main/kotlin/support/DecoderSupport.kt, playback/exoplayer/src/main/kotlin/support/ExoPlayerPlaySupportReport.kt, playback/exoplayer/src/main/kotlin/support/FormatSupport.kt, playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
**Changes**
Replace our usages of ExoPlayer with androidx.media3. This affects the old playback code and the rewritten code. It's pretty much only package name changes because I fixed the breaking changes in earlier PR's.
**To do**
- ~~Migrate `exoplayer-ffmpeg-extension` to media3~~
**Issues**
Also a part of #1057 I guess
=> Replace ExoPlayer with androidx.media3

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
Right now both the SocketHandler and RewriteMediaManager respond to play state messages. When sending a "pause" message it will pause and play again due to this. Also likely other issues I didn't test.
This PR updates the SocketHandler to make it a bit smarter.
**Changes**
- Switch `isAudioPlayerInitialized` (always true) to `hasAudioQueueItems()` (only true when there is a queue, so music playback is currently being used).
- When RewriteMediaManager is active: do nothing
- Refactor to use a `when` expression
**Issues**
=> Disable SocketHandler when using RewriteMediaManager

app/src/main/AndroidManifest.xml
Starting with Android 11 we cannot query the package manager without specifying what we're going to query in the manifest first. For some reason this behavior is not enforced in the Android TV emulator and my Nvidia Shield with Android 11 also works without it 🤷 
I was able to test with a mobile emulator though.
**Changes**
- Add <queries> element to Manifest for remote trailers
This is for the code in `TrailerUtils.kt`.
**Issues**
Might fix #3131
=> Add <queries> element to Manifest for remote trailers

app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchViewModel.kt, app/src/main/res/values/strings.xml
**Changes**
- Add new item types: Live TV channel, Playlist, Photo Album, Photo
- Split Movies and Collections to separate rows
- Add special case for "Videos" row to be inline with jellyfin-web (Search using media type instead of item type)
- Re-order to be consistent with jellyfin-web (https://github.com/jellyfin/jellyfin-web/blob/3164e80276190b5624446827ab0b3811b75fbb20/src/components/search/SearchResults.tsx#L249-L335)
Only missing rows are books & audio books but those are currently unsupported in the app. Some rows might not render amazingly, for example: live tv channels show as posters instead of squares.
**Issues**
Fixes #3260
=> Add more item types to search

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Backports tunneling & audio offloading support from playback rewrite branch to master. Also added the support to the old VideoManager implementation in case we still have that with 0.17.
See [media3 glossary](https://developer.android.com/guide/topics/media/exoplayer/glossary) for more information about these features.
**Changes**
- Add tunneling
- Add audio offloading
- Add TS file extractor configuration (partially based on VideoManager and partially on the mobile app implementation with the memory detection)
**Issues**
Fixes #3261
=> Support tunneling and audio offloading

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
When a video is playing and on another device you browse libraries on a casting device it cause the app to crash.
The onDisplayContent method is trying to read ExoPlayer state but from the socket thread and not the main thread.
```
java.lang.IllegalStateException: Player is accessed on the wrong thread. Current thread: 'DefaultDispatcher-worker-4'
Expected thread: 'main'
See https://developer.android.com/guide/topics/media/issues/player-accessed-on-wrong-thread
at androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2842)
at androidx.media3.exoplayer.ExoPlayerImpl.getPlaybackState(ExoPlayerImpl.java:514)
at androidx.media3.common.BasePlayer.isPlaying(BasePlayer.java:124)
at org.jellyfin.androidtv.ui.playback.VideoManager.isPlaying(VideoManager.java:341)
at …
```
=> Fix crash when DISPLAY_CONTENT while playing

app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt, app/src/main/res/layout/view_card_legacy_image.xml
**Changes**
- Support a value of `0` to disable crossfade in AsyncImageView
- Disable crossfade in the legacy image card view because it scales thumbnails incorrectly (aspect ratio differs between the placeholder and actual image)
**Issues**
Fixes #3251
=> Disable crossfading for CardLegacyImageView to fix scaling issue

app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
If you play a title from a device and play another without quitting the player and then quit the player the app crash.
Its because the NavigationRepository stacks two players and when coming to the last one, the app crash because the last player is terminated.
**Changes**
My fix just replace the last destination if an fragment is active, juste like for NextUp.
```
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.OnBackPressedDispatcher.addCallback, parameter onBackPressedCallback
at androidx.activity.OnBackPressedDispatcher.addCallback(Unknown Source:3)
at org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.onActivityCreated(CustomPlaybackOverlayFragment.java:346)
at androidx.fragment.app.Fragment.performActivityCreated(Fragment …
```
=> Fix crash when quitting player after two plays

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Release branch only**
Although I tested this on my own devices, it turns out that enabling tunneling does in fact have some big issues on various devices. After more testing I was able to also get playback issues with some media on my Fire TV with tunneling enabled. For now, disable tunneling in 0.16.
**Changes**
- Disable tunneling
**Issues**
Fixes #3295
=> Disable tunneling

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
Turns out it was possible, just needed to [touch some spaghet](https://www.youtube.com/watch?v=r7DQDrRwNgI).
**Changes**
- Support SpecialsQuery in BrowseRowDef/EnhancedBrowseFragment
- Show specials row in GenericFolderFragment when type is season
**Issues**
Fixes #3009
=> Show specials for seasons

app/src/main/java/org/jellyfin/androidtv/preference/constant/WatchedIndicatorBehavior.kt, app/src/main/res/values/strings.xml
**Changes**
The settings strings are now clearer in what they mean.
For reference, the setting is titled `Show watched indicators`
`Hide unwatched count` -> `When the show has been watched`;
The new string follows up the setting to create sentence `Show watched indicator when the show has been watched`. The previous string was very hard to understand as the word "Hide" opposes the word "Show" and "Watched indicators" and "Unwatched count" are referring to the same thing.
`On episodes only` -> `When there are episodes remaining`
In this case the original is not clear in whether it only changes the behavior when there are episodes you haven't seen yet or whether it shows on all forms of media that have episodes.
=> Watched indicator settings string clarity improvements

app/src/main/res/layout/vlc_player_interface.xml
**Changes**
Similar to  [#4895](https://github.com/jellyfin/jellyfin-web/pull/4895) setting the text direction LTR will place the punctuations in the correct direction for RTL text. 
**Issues**
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/3257
=> Use LTR for default subtitle direction

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Previously the HEVC codec profile only flagged support for HEVC Main 10 when MediaCodec advertised its support for level 5 (main tier) or above. This meant devices that support only levels 4 or 4.1 (such as the Chromecast with Google TV HD) would transcode HEVC Main 10 content even when supported.
This change lowers the requirement from level 5 to level 4 and also adds additional profiles specifically for HEVC Main and Main 10 with conditions on the level so that levels beyond what is supported by MediaCodec get transcoded.
The result is that HEVC Main 10 level 5 videos get transcoded on devices supporting only 4.1, but HEVC Main 10 level 4.1 content plays back directly.
=> Widen support for HEVC Main 10

app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt, app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt, app/src/test/kotlin/util/DeviceUtilsTests.kt
**Changes**
Allow m3u8 links embedded in the .strm files to be direct played
**Issues**
Two fixes mainly, one was that the devices are not fully recognized as appropriate for h264 levels which is forcing the transcoding. Second is to allow the m3u8 links to be direct play instead of rencode.
=> android tv hls playback direct play fix

app/src/main/java/org/jellyfin/androidtv/auth/model/LoginState.kt, app/src/main/java/org/jellyfin/androidtv/auth/model/QuickConnectState.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/ViewQuery.kt, playback/core/src/main/kotlin/queue/EmptyQueue.kt
[Data objects](https://kotlinlang.org/docs/object-declarations.html#data-objects) are similar to data classes and the compiler will generate a default toString, equals and hashCode functions. Using data objects helps primarily with debugging when logging an object.
**Changes**
- Use data object when applicable
**Issues**
=> Use data object when applicable

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Add a condition to set max audio channels to 2 when downmixing support is enabled.
**Issues**
Fixes #3227
=> Fix downmixing AAC to stereo audio in exoplayer

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
This is the first of two pull requests to add filtering based on age rating to the screensaver. This one is backportable (no string changes). The second one will add preferences and is for 0.17.
**Changes**
- Add maxOfficialRating=PG-13 to library showcase in screensaver
- ~~Add hasParentalRating=true to library showcase in screensaver~~ <-- this one will come with the preference in 0.17
**Issues**
Partially resolves #3320
=> Only show PG-13 content in screensaver

.github/workflows/app-publish.yaml
**Changes**
Fixes publishing
**Issues**
https://github.com/r0adkll/sign-android-release/issues/84
=> Specify BUILD_TOOLS_VERSION for r0adkll/sign-android-release step in publish workflow

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
**Changes**
- Check if view holder is set (it won't be when the base item is not set) before trying to update the "ends at" of an item
- Add `onError` implementation for item refresh that logs the issue and navigates back
**Issues**
=> Fix crash when updating clock in FullDetailsFragment while item information is unavailable

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
This will prevent the main thread from blocking, which in extreme cases can kill the app. It should also improve performance of the library view when changing the filters.
**Changes**
- Add CoroutineUtils.runOnLifecycle
- Remove CoroutineUtils.runBlocking
- Update KeyProcessor and BrowseGridFragment to run async operations on their lifecycle
**Issues**
Fixes #3252
=> Replace CoroutineUtils.runBlocking with new CoroutineUtils.runOnLifecycle

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyEventExtensions.kt
**Changes**
- Override some dispatch functions in the MainActivity to prevent them & close the screensaver instead
**Issues**
Fixes #3377
=> Fix DPAD_CENTER on screensaver not handled

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
**Changes**
- Fix crash in SocketHandler.onPlayMessage when user id is not set
**Issues**
Related #3387
=> Fix crash in SocketHandler.onPlayMessage when user id is not set

app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
Spoiler: they are not (mostly).
**Changes**
- Fix a crash in ItemLauncher when isFolder() returns null
- Add item fields to all queries in CollectionFragment, didn't fix the crash but they are probably needed somewhere in this spaghetti.
**Issues**
Fixes #3397
=> Fix crash when checking whether a person is a folder or not

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/res/values/strings.xml
This preference was unreliable at best.
**Changes**
- Remove "automatically choose" option from video player preference
- Set default for Live TV player to ExoPlayer (which auto was basically an alias for with live tv)
**Issues**
=> Remove "automatically choose" option from video player preference

app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/res/values/strings.xml
Useful during development but also in general to clear app cache without going to system preferences. It clears both disk and memory cache of Coil (our image library).
**Changes**
- Add "clear image cache" button to developer preferences
**Issues**
=> Add "clear image cache" button to developer preferences

playback/exoplayer/src/main/kotlin/mapping/audio.kt, playback/exoplayer/src/main/kotlin/mapping/container.kt, playback/exoplayer/src/main/kotlin/mapping/video.kt
**Changes**
Add fall through to media3's MimeType getters when our own mapping does not have a specific codec. This also adds an (empty) implementation for video codecs.
**Issues**
part of #1057
=> Add fallthrough to media3 MimeTypes in codec->mime type mapping

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/res/layout/preference_button_remap.xml, app/src/main/res/layout/preference_color_list.xml, app/src/main/res/layout/preference_rich_list.xml, app/src/main/res/layout/vlc_player_interface.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/theme_emerald.xml, app/src/main/res/values/theme_jellyfin.xml
**Changes**
- Always use transparent windowBackground
- Move themed background to new attribute (defaultBackground)
- Add option to disable the BackgroundService entirely
- Used in video player
- Using any function to set a background will re-enable it automatically
- Remove background override in some preference layouts (why was it there??)
- 
**Issues**
Supersedes to #3384
Fixes #2967
=> Use fully transparent background during video playback

app/src/main/res/layout/preference_button_remap.xml, app/src/main/res/layout/preference_color_list.xml, app/src/main/res/layout/preference_rich_list.xml
Fix a regression from #3411, reported in https://github.com/jellyfin/jellyfin-androidtv/issues/2967#issuecomment-1987524728
**Changes**
- Add back background color to preference list views so they are not transparent
**Issues**
=> Fix background color for preference list views

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/res/layout/fragment_search_text.xml
**Changes**
- Update search destination to take an optional search query
- Update StartupActivity to send query to search destination
- Update leanback/text search implementations to use a given non-empty query automatically
- Use -ktx extensions to set fragments
- Refactor view creation slightly for text search fragment to try and fix auto-focus (spoiler: it does not)
**Issues**
Fixes #3444
=> Fix search action ignoring received query

app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowColors.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt
**Changes**
Update the colors used in the new InfoRow (#3379) to some better ones. I've shamefully stolen them from the Figma lab project. The background colors all have 50% transparency, creating some sort of "glassy" effect.
The biggest improvement is in the used red/green colors because I really hated those. They're missing in the screenshots though.
Before
After
**Issues**
=> Improve info row colors

app/src/main/java/org/jellyfin/androidtv/constant/Codec.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Adds support for the Vorbis audio codec in direct video playback in the exoplayer profile.
The decoder seems to be supported according to the [Android documentation](https://developer.android.com/guide/topics/media/media-formats#core). Also, it's been supported on Amazon devices since the [first ](https://www.developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-streaming-media-player.html?v=ftvgen1) gen.
**Issues**
=> Enable Vorbis audio in video direct play

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
We already had a lot of null checks in this function but some branches still tried to use mFragment causing a NPE. Refactored the function to check for null once in the top and return if is it null.
**Changes**
Check if fragment is null in PlaybackController.play and noop if it is.
**Issues**
Fixes #3471
=> Check if fragment is null in PlaybackController.play

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/res/values/strings.xml
Works for movies, tv series and music (random album)
**Changes**
- Add button to pick a random item to the smart screen
- Use BaseItemKind enum in some more places
**Issues**
=> Add button to pick a random item to the smart screen

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
The "PlayAccess" field for BaseItemDto is not populated by default, it needs to be explicitly requested (for some stupid reason). We don't do that in a bunch of places which may cause playback to fail if started from a source that didn't have that field set. We don't really need the checks because client side security is stupid.
**Changes**
- Remove PlayAccess checks as playback works fine even when disallowed
**Issues**
=> Remove PlayAccess checks

app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt, app/src/main/res/values/strings.xml
This change adds age rating preferences for the screensaver. It depends on jellyfin/jellyfin#11367.
This is not the exact implementation that I wanted, ideally the maximum age rating preference would show the parental ratings from the server. There are two problems with it though:
- There is a breaking API change in 10.9 and the SDK we're currently using breaks because of it
- Not a huge problem as 0.17 is most likely going to require 10.9, still annoying now that we're using the older SDK version
- The responses are not localized, some names are hardcoded (unrated/approved/banned)
- And even if they used the server language, the client might want a different language. We'd need to add `Accept-Language` support to both the API and SDK for this to work properly. Which might be something to …
=> Add preferences for screensaver age rating

app/build.gradle.kts, gradle/libs.versions.toml
It is behind a property I never enable and quite sure nobody else does.
**Changes**
- Remove leakcanary dependency
- Remove unused gson/junit versions from version catalog
**Issues**
=> Remove leakcanary

app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Fix `getAllChannelsIndex` function in TvManager causing an NPE if allChannels is null (now returns -1)
- Fix `getAllChannelsIndex` function in TvManager always returning -1 because the UUID format for the channels was different from the UUID.toString() format
- Fix channel row in player overlay not using the string resource for channels
- Fix check for program end failing because of timezone issues, causing the channel row to refresh infinitely in the player overlay
I believe the UUID issue is a regression from an earlier 0.17 pull request. The others will be backported.
**Issues**
Fixes #2375
=> Fix Live TV channels refreshing to infinity

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamServiceCompat.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SplashFragment.kt, gradle/libs.versions.toml
**Changes**
- Use androidx fragment-compose, currently only useful for SplashScreen
- Set view composition strategy in DreamServiceCompat
**Issues**
=> Use androidx fragment-compose

app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreServer.kt, app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreUser.kt, app/src/main/java/org/jellyfin/androidtv/auth/model/Server.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/data/model/DataRefreshService.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/ItemMutationRepository.kt, app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/composable/time.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/ContextExtensions.kt, app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
**Changes**
- Migrate a bunch of code to java.time
**Issues**
=> Migrate from java.util.Date to java.time

playback/core/src/main/kotlin/mediastream/MediaStreamState.kt, playback/core/src/main/kotlin/mediastream/QueueEntryMediaStream.kt
**Changes**
- Cache computed PlayableMediaStream in QueueEntry element
Right now this improves performance when the same queue entry is played a second time, either via the previous/next buttons or when using repeat mode. We'll eventually use this to preload media stream information and reintroduce gappless playback.
**Issues**
Part of #1057
=> Cache computed PlayableMediaStream in QueueEntry element

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt, playback/core/src/main/kotlin/PlaybackManager.kt, playback/core/src/main/kotlin/backend/BackendService.kt, playback/core/src/main/kotlin/backend/PlayerBackend.kt, playback/core/src/main/kotlin/ui/PlayerSurfaceView.kt, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
These are the initial changes to get video playback working. Currently only direct-play is actually functional and you need to make sure your media can play yourself as codec detection is not working.
When media does play it already integrates with remote control and media sessions. Playback progress is also properly tracked. There are also funny bugs, like the screensaver showing the video your playing because we don't filter for music only.
Also, no subtitles at all right now.
**Changes**
- Add PlayerSurfaceView to display video output
- Check for mediaType in AudioMediaStreamResolver
- Fix PlaybackLauncher not converting item id to string
- Add hls dependency to media3 module
- Fix typo in AudioMediaStreamResolver
- Update PlaybackForwardingActivity to show video output
- Add …
=> Initial video support in playback rewrite

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
**Changes**
- Fix the screensaver showing video entries, it should only show audio entries (music)
- Fix the "now playing" thingy while browsing showing video entries
**Issues**
Part of #1057
=> Fix screensaver and media manager displaying video entries

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt
This is still hacky but it's for development purposes only. I've also added an additional check to not intercept for audio items. That way music playback will open it's regular UI.
**Changes**
- Replace PlaybackForwardingActivity with PlaybackRewriteFragment
**Issues**
Part of #1057
=> Replace PlaybackForwardingActivity with PlaybackRewriteFragment

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java, playback/core/src/main/kotlin/backend/BackendService.kt, playback/core/src/main/kotlin/backend/PlayerBackend.kt, playback/core/src/main/kotlin/ui/PlayerSubtitleView.kt, playback/exoplayer/build.gradle.kts, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
- Read items to play from legacy video queue
Replaces the "play single item" behavior. There's still some cases where it won't play next episodes because of the weird queue behaviors in the old player.
- Remove interceptPlayRequest
- Add basic lifecycle events to PlaybackRewriteFragment
Basically, stop playback when closing player
- Use screensaverLock in PlaybackRewriteFragment
Don't show screensaver while playing
- Add initial subtitle implementation
Uses the subtitle rendering from ExoPlayer (for text cues) and does **not** use our bad custom renderer.
**Issues**
Part of #1057
=> Initial subtitle support in playback rewrite

playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/UniversalAudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/queue/mediaSourceIdElement.kt
**Changes**
Add media source selection. We don't set this right now but the stream resolvers will use it.
**Issues**
part of #1057
=> Add media source selection

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragmentDelegate.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
Wanted to add replay gain support to playback rewrite but need to convert all item calls to use the SDK first so we can actually read the value from BaseItemDto. sad
**Changes**
- Use dependency injection for ItemLauncher
- Move addBlockText to ProgramGridCell
- Use dependency injection for KeyProcessor
- Use dependency injection for ReportingHelper
- Remove unused methods from StreamHelper
**Issues**
=> Use dependency injection for ItemLauncher, KeyProcessor and ReportingHelper

app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
**Changes**
- Refactor ItemListFragment to use SDK types (BaseItemDto)
- Add ItemListFragmentHelper for API calls in ItemListFragment
- Remove unused addItems function in ItemListView
**Issues**
=> Fully migrate ItemListFragment to use SDK

app/src/main/java/org/jellyfin/androidtv/constant/Extras.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
The primary goal here was to remove the FakeBaseItem hack. Bunch of related sacrifices had to be made to complete this pentagram though.
**Changes**
- Split MusicFavoritesListFragment from ItemListFragment
- Basically a glorified duplicate fragment class with obsolete code removed
- Add an extra to BrowseViewFragment to indicate it should show series timers instead of a fake base item
- And some related changes in places that would crash if item is null
- Fix context menu showing for last selected base item when opening on gridbutton (e.g. music favorites button)
- Remove FakeBaseItem
- Dropped tears from eyes
**Issues**
=> Remove FakeBaseItem hack

app/src/main/res/layout/fragment_select_server.xml
The average user has 1 Jellyfin server configured. That's why I have 7, because I'm above average.
**Changes**
- Fix the visibility of the "Enter server address" button in the server selection screen when there are 5+ servers (Will be 5px tall with 6 and gone with 7 or more).
- This effectively moves the "enter server address" button down to the bottom of the screen when you have only 1 server configured. It's something I can live with though.
**Issues**
=> Fix "Add server" button not visible when there are too many servers

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
There is only 2 destinations that open BrowseViewFragment, one is the "liveTvSeriesRecordings" and the other is "librarySmartScreen". The latter is only opened via ItemLauncher for movies, tvshows, music and livetv item types. So it's impossible to hit this code branch.
**Changes**
- Remove unused code branch in BrowseViewFragment
**Issues**
=> Remove unused code branch in BrowseViewFragment

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
**Changes**
This PR updates the FullDetailsFragment to use the SDK for all non-livetv code. There's still 15 direct API calls left for Live TV. Will tackle those at some point in the future.
Some behavior changes had to be made because of some Live TV hacks (SeriesTimers is not a valid BaseItem type). Also some (small) cleaning done. Overall this file is a PITA to deal with as it tries to literally support all the item types we have.
**Issues**
=> Refactor FullDetailsFragment to use SDK

app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
**Changes**
- Add a new app notification that notifies the user about upcoming Jellyfin server version requirements. Currently set to 10.9.0 (ATV 0.17), will have no effect on master branch as that already requires 10.9.0 to sign in.
_Sample screenshot with higher version requirement for testing purposes_
**Issues**
=> Add app notification to notify about upcoming server requirement

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Although I couldn't reproduce the issue myself, I suspect it was a race condition. If the activity was loaded twice, the instance that was faster to launch the next activity wins.
**Changes**
- Only allow a single instance of StartupActivity
**Issues**
Most likely fixes #3536.
=> Support new intent in StartupActivity

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SplashFragment.kt, gradle/libs.versions.toml
The androidx.compose.material library is for mobile/tablet. The androidx.tv.material library is for televisions. This PR switches our current compose over to the tv library, although it doesn't really affect much as we didn't really use material components (yey).
**Changes**
- Remove `androidx.compose.material`
- Add `androidx.tv.material`
- Replace LinearProgressIndicator with Box + draw instructions
- Replace Card with Box (the TV card is not usable for a message box)
**Issues**
=> Migrate to androidx.tv.material

app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt
The java.text.DateFormat can't handle java.time.Instant resulting in a crash when loading the EditServerScreen.
Trigger crash:
1. Login to a server
2. Preferences > Login
3. Press server under "manage servers"
=> Fix app crash in EditServerScreen

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Found while working on #3624 
**Changes**
- Fix resumable episodes showing up twice in "Play next" integration
**Issues**
=> Fix resumable episodes showing up twice in "Play next" integration

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
**Changes**
- Use the SDK to retrieve "next up" requests for the home fragment and series details screens
- Set `enableResumable=false` for home next up row to prevent episodes from showing in both the continue watching and next up rows
- Add error handling to retrieveResumeItems in ItemRowAdapterHelper
- Fix notifyRetrieveFinished never called in retrieveResumeItems in ItemRowAdapterHelper
- Cry a lot
**Issues**
=> Migrate "next up" row to SDK

app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
The arguments for sorting are provided as a String, not as JSON. Attemping to decode the String crashes the app. Fix it by using the SDK provided methods to convert to an enum instead.
Trigger crash:
1. Open an image from an image library
Stack trace:
```
E  ACRA caught a JsonDecodingException for org.jellyfin.androidtv.debug
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected quotation mark '"', but had 'S' instead at path: $
JSON input: SortName
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
at …
```
=> Fix JSON decode crash in PictureViewerFragment

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Gradle kept complaining about it on each build.
**Changes**
- Fix unchecked warning in FullDetailsFragment
**Issues**
=> Fix unchecked warning in FullDetailsFragment

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
**Changes**
- Fix FullDetailsFragment crashing when play is called with empty list
- Query for first unwatched episode instead of using the next up API when using the "play next up" button. This is a slight behavior difference compare to before but it is the behavior I would expect when using that button.
- The item query is based on the query that is internally executed in the server (TVSeriesManager)
**Issues**
Fixes #3626
=> Start series from first unwatched in "play next up"

app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/UserRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
Few login related issues found while trying to fix one of them. In short, when you remove a session from the Jellyfin dashboard the app can no longer sign into that account due to race conditions, magic and more.
**Changes**
- Fix UserLoginFragment not using lifecycle correctly
- Fix AuthenticationRepository leaking access token to logs
- Fix SessionRepository applying crash reporting information before validating token
- Fix StartupActivity preventing invalid login from opening login fragment
- Remove redundant if statement in UserRepository
- Use ApiClient.update in UserLoginViewModel (not backportable)
- 
**Issues**
=> Fix login with pruned sessions

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/res/values/strings.xml
**Changes**
- Fix now playing fragment not using string resource for current queue title
**Issues**
=> Fix now playing fragment not using string resource for current queue title

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
**Changes**
- Remove some unused code related to ItemRowAdapter
- Fix "upcoming" row not removing itself when it filtered our all items from the response
- Reduce visibility of methods in ItemRowAdapter where possible
**Issues**
=> Remove some unused code related to ItemRowAdapter

app/src/main/java/org/jellyfin/androidtv/data/querying/AdditionalPartsQuery.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/SpecialsQuery.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/TrailersQuery.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
**Changes**
- Migrate "Specials" to SDK
- Migrate "Additional parts" to SDK
- Migrate "user views" to SDK
- Migrate "Seasons" to SDK
- Migrate "Upcoming episodes" to SDK
- Migrate "More like this" to SDK
- Migrate "Trailers" to SDK
**Issues**
=> Migrate various item rows to SDK

app/src/main/java/org/jellyfin/androidtv/data/model/FilterOptions.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/GetAdditionalPartsRequest.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/GetSpecialsRequest.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/GetTrailersRequest.kt, app/src/main/java/org/jellyfin/androidtv/data/querying/GetUserViewsRequest.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
only itemquery left...
**Changes**
- Migrate (album) artists and live tv channel rows to SDK
**Issues**
=> Migrate (album) artists and live tv channel rows to SDK

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Moved the Play Trailer(s) button so it should no longer get hidden in the other options menu when going into a show.
Fixes #3450
=> Reordering the trailer button

app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt
**Changes**
- Fix ItemRowAdapter.getStartLetter for (album) artists
- Fix "favorites" playlist not showing
**Issues**
=> Fix start letter & favorite playlist implementations for item row

app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
Right now we never get rid of the Quick Connect state. That means it only works as intended on the first selected server.
When we choose another server afterwards we display the same connect code. Even if the second server doesn't even support Quick Connect.
Use the clearLoginState method to clear the Quick Connect state as well.
=> Fix QuickConnect sticky login state

app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt, app/src/main/res/values/strings.xml
**Changes**
This setting I think was intended to match the `Play next episode automatically` setting like in the web interface. I updated the language to match that setting, and it not will queue the entire series, vs just the current season. Behavior is maintained when the setting is disabled.
**Issues**
Addresses #3389
=> Change 'Queue all subsequent episodes' setting to queue all episodes in a series

playback/core/src/main/kotlin/PlaybackManager.kt, playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/backend/PlayerBackend.kt, playback/core/src/main/kotlin/mediastream/MediaStreamState.kt, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
**Changes**
Recently I changed the way we work with data in the playback code to use elements. As a result we can now more easily pass the complete queue entry everywhere and read the data we want from it. So the big state classes will slowly empty out.
With this PR the media stream state is no longer a thing. Instead you can just read the media stream from the queue entry. The player backend now receives an entry to allow full access. This is required for my next PR that adds audio normalization support.
I'm still working on some more changes to the media stream resolving, so I've left the existing implementation without much changes. It will need to be changed quite a bit to allow track switching for video playback (selecting subtitles or audio tracks).
**Issues**
Part of #1057
=> Send QueueEntry to playback backend

playback/core/src/main/kotlin/mediastream/normalizationGainElement.kt, playback/exoplayer/src/main/kotlin/ExoPlayerAudioPipeline.kt, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/jellyfin/src/main/kotlin/queue/createBaseItemQueueEntry.kt
First 10.9 feature!
**Changes**
- Add new "normalizationGain" element
- Populate normalization gain for BaseItemDto
- Currently sets it for the playable item, so for music this means each track. Support for album gain will be possible once we switch queue building to the SDK (currently converts the generated queue from legacy playback)
- Add "audio pipeline" to ExoPlayer implementation. This will be used for all audio effects going forward. Currently implements the normalization gain element.
**Issues**
Part of #1057
=> Implement normalization gain for music tracks

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Broke it back in January with #3322 and finally fixed it. The `isPlayingAudio` function is pretty much always `true` when music playback has started. Even when in a paused state.
**Changes**
- Fix play after pause in MediaManager implementation
**Issues**
=> Fix play after pause in MediaManager implementation

app/src/main/java/org/jellyfin/androidtv/data/model/FilterOptions.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
**Changes**
- Use SDK version of ItemFilter in FilterOptions now that all usages are migrated
- Remove some unused code from JavaCompat/ModelCompat
**Issues**
=> Use SDK for FilterOptions

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamServiceCompat.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
**Changes**
- Add support for view models in DreamServiceCompat
- Refactor DreamHost to use a (Dream)ViewModel
**Issues**
=> Use ViewModel in DreamService

app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, preference/src/main/kotlin/store/SharedPreferenceStore.kt
Fixes a bug where sort options would always reset to the default value. Caused by the recent SDK migrations.
**Changes**
- Use Enum.name instead of Enum.toString in preference stores
- Refactor sort option code in BrowseGridFragment
**Issues**
=> Use Enum.name instead of Enum.toString in preference stores

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
**Changes**
- Fix crash when re-opening app during music playback
**Issues**
=> Fix crash when re-opening app during music playback

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
Previously, in the old MediaManager, the isPlayinAudio property would be true only when audio is actually currently playing. It would be false if paused/stopped. I accidentally introduced a behavior change in the rewrite where it would only return false when stopped. This caused some small appearance issues in the NowPlayingFragment where it would show the "pause" button when already paused.
**Changes**
- Fix isPlayingAudio behavior
**Issues**
=> Fix isPlayingAudio behavior

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
race conditions etc
**Changes**
- Fix crash when refreshing current item
**Issues**
```log
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
at java.util.ArrayList.set(ArrayList.java:455)
at org.jellyfin.androidtv.ui.presentation.MutableObjectAdapter.set(MutableObjectAdapter.kt:40)
at org.jellyfin.androidtv.ui.itemhandling.ItemRowAdapterHelperKt$refreshItem$2$2$1.invokeSuspend(ItemRowAdapterHelper.kt:677)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7668)
at …
```
=> Fix crash when refreshing current item

app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
We've added quite some stuff to the BaseItemInfoRow over time. With 0.17 there's now enough to have it overflow in some scenarios. Let's shrink it down!
**Changes**
- Remove "ends at" in BaseItemInfoRow
- Note that it still shows this information in the FullScreenDetails & player
- Shorten duration format
- Add clock icon to duration
**Issues**
=> Shrink BaseItemInfoRowRuntime size

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MusicFavoritesListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.kt, app/src/main/res/drawable/expanded_text.xml, app/src/main/res/layout/view_row_details.xml
**Changes**
- Add rounding to ExpandableTextView focus background
- Rewrite DetailsRowView with a constraint layout
- Mostly looks the same, with some small differences
- Content area is now wider (e.g. item description)
- Title/infoview/genres are now wider
- Remove progress overlay in DetailsRowView (resume button already indicates progress and it was hidden items with logos already)
**Issues**
Fixes #3721
=> Rewrite details row with constraint layout

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
When the playback actually starts we query the server for the playback stuff so we don't use current media source for that.
**Changes**
- Fix crash when item has no media sources
**Issues**
Fix #3730 (crash)
=> Fix crash when item has no media sources

app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopupHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopupHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Use context instead of activity reference
- Use LayoutInflator via context
- Set LifecycleOwner in LiveProgramDetailPoup because Compose requires that (and we use Compose via the info row)
**Issues**
Partially addresses #3732. Need to figure out a way to get actual guide data to test further....
=> Refactor Live TV popups

playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/JellyfinStreamResolver.kt, playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
SDK 1.5 no longer adds ApiKey to query parameter. I don't want the app to that anywhere, but ExoPlayer doesn't support per-item request headers so implementing auth via headers is a bit of a challenge that I'm still working on. Dirty fix for now.
**Changes**
- Fix authorization for transcoding
**Issues**
Fixes #3734 (although a proper fix would be to implement direct play for wav..)
=> Fix authorization for transcoding

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
I added pagination to all queries during the SDK migration. This fails when you set chunkSize to 0, and overwrites the startIndex and limit parameters from a query... whoops.
**Changes**
- Fix "Next episode(s)" row not showing
**Issues**
Fixes #3745
=> Fix "Next episode(s)" row not showing

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
When the "next up" screen hides, the previous screen will activate for a brief moment (limitation of how our current navigation code works). If you opened the video player via the FullDetailsFragment this will cause the item to reload, and once that loading finishes it will set a backdrop. However, during this asynchronous operation the app will already have started the video player again. This ends up showing the backdrop in the video player... oops
**Changes**
- Validate lifecycle in FullDetailsFragment.setBaseItem
**Issues**
Fixes #3728
=> Fix race condition in player backdrop

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
**Changes**
- Fix AudioNowPlayingFragment showing "From null" when there is no album name
- Use `getString()` instead of `getResource().getString()` in AudioNowPlayingFragment 
**Issues**
=> Fix AudioNowPlayingFragment showing "From null" when there is no album name

app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Someone mentioned playback didn't work for them when "cinema mode" is enabled. The only part where that preference is used is in the SdkPlaybackHelper to determine whether to load intros or not.
**Changes**
- Improve intro loading in SdkPlaybackHelper
**Issues**
=> Improve intro loading in SdkPlaybackHelper

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/exoplayer/src/main/kotlin/ExoPlayerOptions.kt, playback/exoplayer/src/main/kotlin/ExoPlayerPlugin.kt
By default media3.exoplayer uses a 8 second timeout for connecting & reading. In some cases the Jellyfin server will take longer to respond. @Bond-009 pointed out this is particularly the case with BDMV. This PR sets our own timeouts based on the values in the Kotlin SDK.
The new playback code reads the values from the SDK, the old code got it hardcoded because it's end of life anyway.
**Changes**
- Add new ExoPlayerOptions
- Re-use HTTP timeouts from ApiClient for ExoPlayer
- Set HTTP timeouts in VideoManager ExoPlayer
**Issues**
=> Increase ExoPlayer HTTP timeouts

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
**Changes**
- Migrate all code using Calendar to use LocalDateTime to fix all kinds of timezone related issues in the Live TV guide
**Issues**
Fixes #3732
Fixes #3748
=> Fix timezone issues in Live TV guide

app/src/main/java/org/jellyfin/androidtv/ui/FriendlyDateButton.java, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuide.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/util/ContextExtensions.kt, app/src/main/java/org/jellyfin/androidtv/util/DateTimeExtensions.kt, app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
sample text
**Changes**
- Remove all left over usages of java.util.Date
**Issues**
=> Replace all left-over Date usages with java.time

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.kt
In some specific scenarios a race condition could cause the actions in the FullDetailsFragment to duplicate. Make sure to clear the list of actions first before adding new ones.
**Changes**
- Fix FullDetailsFragment duplicating buttons on resume
**Issues**
Fixes #3772
=> Fix FullDetailsFragment duplicating buttons on resume

app/src/main/java/org/jellyfin/androidtv/ui/card/MediaInfoCardView.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/res/layout/view_card_media_info.xml
**Changes**
- Add some audio related info
- Show media info for all item types
- Update the design slightly (tweak colors/decrease padding/use dynamic sizing)
**Issues**
=> Update debug media details

app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt
Copy-paste developer
**Changes**
- Fix "other" items in ByLetterFragment not using `nameLessThan`
**Issues**
Fixes #3796
=> Fix "other" items in ByLetterFragment

app/build.gradle.kts, gradle/libs.versions.toml, playback/core/build.gradle.kts, playback/jellyfin/build.gradle.kts, playback/media3/exoplayer/build.gradle.kts, playback/media3/session/build.gradle.kts, preference/build.gradle.kts
We already compiled with SDK 34 but still targetted SDK 33.
**Changes**
- Update targetSdk to 34
- Move minSdk, compileSdk and targetSdk to version catalog
**Issues**
=> Update targetSdk to 34

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
When you open the popup before the detailUpdateTask completes, the value of mSelectedProgram is still incomplete. Add some additional logic to update the popup info when detailUpdateTask completes to fix this.
**Changes**
- Fix Live TV program popup not populating when opening early
**Issues**
=> Fix Live TV program popup not populating when opening early

app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt
Using the showNext/showPrevious functions while the album is still loading can cause an IndexOutOfBoundsException. Check if the album is empty (default value) first before trying to read from it to avoid these crashes.
**Changes**
- Fix race condition in PictureViewerViewModel when using the next/previous button before album information is loaded
**Issues**
Fixes #3773
=> Fix race condition in PictureViewerViewModel

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Added the Google Chromecast HD to the list of devices unable to support 4K, as it reports it is capable of downscaling but is incapable of doing so in realtime. Change has been discussed with Niels in the discord.
**Note**
There still may be a bug on the jellyfin server, as the tv app is telling it to send a maximum of 1920x1080 (verified via tcpdump [TCPDump Data](https://pastebin.com/SdWGmyzP)) but it is still streaming 4k.
=> Add Google Chromecast HD limitation

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, playback/core/src/main/kotlin/PlaybackManager.kt, playback/core/src/main/kotlin/PlaybackManagerBuilder.kt, playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/mediastream/MediaStreamService.kt, playback/core/src/main/kotlin/queue/EmptyQueue.kt, playback/core/src/main/kotlin/queue/Queue.kt, playback/core/src/main/kotlin/queue/QueueService.kt, playback/core/src/main/kotlin/queue/order/DefaultOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/supplier/PagedQueueSupplier.kt, playback/core/src/main/kotlin/queue/supplier/QueueSupplier.kt, playback/core/src/main/kotlin/queue/supplier/SequenceQueueSupplier.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt, playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt, playback/jellyfin/src/main/kotlin/queue/AudioAlbumQueueSupplier.kt, playback/jellyfin/src/main/kotlin/queue/AudioInstantMixQueueSupplier.kt, playback/jellyfin/src/main/kotlin/queue/AudioTrackQueueSupplier.kt, playback/jellyfin/src/main/kotlin/queue/EpisodeQueueSupplier.kt, playback/media3/session/src/main/kotlin/MediaSessionPlayer.kt, playback/media3/session/src/main/kotlin/MediaSessionService.kt
Update the architecture of playback queues to have a single queue(service) per playback manager which is filled with entries via suppliers. This is required for some upcoming functionality to support more upcoming functionality that is needed for lyric loading (and eventually media segments and other fancy stuff).
**Changes**
- Rename current `Queue` to `QueueSupplier`
- Add a new `QueueService` which is based on the previous `QueueState`
- This is a required service and automatically added in the `PlaybackManagerBuilder`
- Refactor `MediaStreamState` to `MediaStreamService`
- This is a required service and automatically added in the `PlaybackManagerBuilder`
**Issues**
Part of #1057
=> Rewrite media queuing

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Fix NullPointerException in CustomPlaybackOverlayFragment.onResume
**Issues**
Fixes the crash part of #3835
=> Fix NullPointerException in CustomPlaybackOverlayFragment.onResume

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
**Changes**
* Fix NullPointerException in CustomPlaybackOverlayFragment.onResume
**Issues**
Fixes the second crash of #3835
=> Fix NullPointerException in LeanbackOverlayFragment.onPause

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
In 0.17 I changed the default audio behavior to downmix by default while refactoring out device model checks (previously it only downmixed by default on ccwgtv). In hindsight this wasn't a great idea because that only allows AAC, MP3 and MP2 to direct play, causing a lot of remux/transcode requests.
This change sets the default to be always direct play, which should cause less issues.
**Changes**
- Use "direct play" as default audio behavior
**Issues**
Fixes #3838
Fixes #3834
=> Use direct stream as default audio behavior

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
The reactive homepage option subscribes to websocket messages for library updates and refreshes the homepage accordingly. This way, whenever a new episode is added to the server the next up section will update without re-opening the app. It also updates after something is watched etc.
This option was unstable in 0.16 but with the many SDK refactorings and item row improvements it has become stable in 0.17 and I somewhat forgot about it because it never caused issues.
A WebSocket connection is required for it to work, otherwise it will just do nothing.
**Changes**
- Remove experimental "reactive homepage" developer option
- Always enable reactive homepage
**Issues**
=> Graduate reactive homepage to stable

app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Bring back some 0.16 behavior, when fetching intros we should set the type to be a trailer because the PlaybackController uses that
**Changes**
- Force the type to be trailer as the legacy playback UI uses it to determine if it should show the next up screen
**Issues**
Fixes #3864
=> Fix intros showing next up screen

app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowColors.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt
The info row changes in 0.17 changed the colors of the badges, these new colors make the text harder to read for some users. This PR updates the design to make it more readable by changing the font weight (for all text) and updating the colors for a higher contrast.
Note: these screenshots show all badges for testing purposes, that's not part of the code changes here :)
**Issues**
Fixes #3852
=> Improve InfoRow colors/font readability

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Previously (in 0.16) the video player was its own activity, so when it closed it would automagically reset the display mode. Now that we have it integrated as fragment together with the other screens it would no longer do this.
**Changes**
- Reset display mode when exiting video player
**Issues**
Fixes #3870
=> Reset display mode when exiting video player

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
Excludes Fire TV 1st Gen from requesting HEVC transcodes by device model.
**Changes**
The Fire TV 1st Gen doesn't support HEVC. jellyfin-androidtv detects as such but currently still ends up requesting a transcode to it. This MR offers working video+stereo audio, but despite support for 5.1 EAC3 & AAC only downmixing to stereo works.
**Issues**
Fixes #3842
=> Fix HEVC allowed in transcode profile when not supported

app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt
In some cases the defaultAudioStreamIndex or defaultSubtitleStreamIndex can be `-1` instead of null. Use the `getOrNull` function to avoid an ArrayIndexOutOfBoundsException.
**Changes**
- Fix crash when item doesn't have a default audio/subtitle stream
**Issues**
Fixes #3880
=> Fix crash when item doesn't have a default audio/subtitle stream

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
All other uses of the setFavorite function already did it like this, not sure how this ended up wrong for the ItemListFragmentelper only 🤷 
**Changes**
- Fix toggling favorites in ItemListFragment
**Issues**
Fixes #3905
=> Fix toggling favorites in ItemListFragment

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
The app has some weird error handling code that currently disables direct streaming (remux) once a playback error occurred. Add an additional case that disables direct play when two errors occur. This is a bit of a hack but it's worth trying for now.
**Changes**
- Disable direct play when encountering playback error twice
**Issues**
Might fix a lot of them, could also introduce a bunch of new ones.
=> Disable direct play when encountering playback error twice

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.kt, app/src/test/kotlin/ui/playback/overlay/CustomSeekProviderTests.kt
**Changes**
Attempts to mitigate #3033 somewhat by changing the `SEEK_LENGTH` in `CustomSeekProvider` to a more granular 10 seconds.
Tested on Chromecast running Google TV on Android 12.
**Issues**
#3033 (leaving it open)
=> Set seek parameter for D-Pad to 10 seconds

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
This PR enhances the handling of AVC (H.264) and High 10 profile support. It introduces improvements to how codec profiles are evaluated and managed.
1. Enhanced AVC Profile and level mapping:
-	Mapped AVC levels using `CodecProfileLevel` constants to align with ffprobe reporting format.
3. Added lazy initialization for checks methods:
-  `supportsAVC` `supportsAVCHigh10`
4. Updated  codec profile & level conditions:
- Removed `h264VideoLevelProfileCondition` & `h264VideoProfileCondition`, which had hard-coded data.
- Added `deviceAvcCodecProfile ` &  `deviceAvcLevelCodecProfiles` to manage AVC codec profile and level conditions.
=> Enhance AVC and High 10 Profile Support 

app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
After merging #3932 some videos stopped playing for me with this error:
```
[hevc_nvenc @ 0000023043dc9f40] [Eval @ 00000039cbdfe4b0] Undefined constant or missing '(' in 'Main'
[hevc_nvenc @ 0000023043dc9f40] Unable to parse option value "Main"
[hevc_nvenc @ 0000023043dc9f40] Error setting option profile to value Main.
[vost#0:0/hevc_nvenc @ 000002303caf3700] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libfdk_aac @ 000002303cae4500] 2 frames left in the queue on closing
Conversion failed!
```
Turns out, our server doesn't sanitize shit and de nvenc encoder expects fully lowercase profiles. The server itself compares those strings everywhere ignoring casing though. Ideally this …
=> Fix capitalization in video profiles causing invalid transcodes

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/res/layout/activity_startup.xml
This is a custom implementation of the back stack for our destinations. Previously, we used the back stack from the fragment manager but this didn't really work for us.
The problem was that we had to work around some shortcomings in the fragment manager due to how our destinations work. Specifically the "replace" action, mostly used when going from video player -> next up -> video player.
The way we made the replace action work was to pop the last item from the back stack, and then add a new item. This would result in the fragment before the video player (often the details page) to be resumed to then be replaced with the video player immediately after, because popping cannot be done in a transaction.
By replacing the back stack with our own implementation we have more control over this …
=> Use custom logic for fragment back stack

app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
Device refresh rate would not snap back to default when a video was stopped using a back press. whoops.
**Changes**
- Fix current fragment not removed on back press
**Issues**
Regression from #3958
=> Fix current fragment not removed on back press

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
This PR introduces a new check to verify resolution support, ensuring compatibility with 1080p devices. The update involves changes to `MediaCodecCapabilitiesTest`, `ProfileHelper`, `ExoPlayerProfile`, and `PlaybackController`, allowing playback options to be configured according to the codec's resolution capabilities of the device.
**Changes**
1. MediaCodecCapabilitiesTest:
- Added `getMaxResolution` method to return the maximum supported width and height.
2. ProfileHelper:
- Added `maxResolutionCodecProfile`
- Dynamically use the device’s maximum supported resolution obtained from `MediaTest.getMaxResolution`
- Removed `max1080pProfileConditions`
3. ExoPlayerProfile:
- Updates the `ExoPlayerProfile` to reflect changes in the handling of 1080p profiles and removes the `disable4KVideo …
=> Add resolution codec check

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Register the back press callback in CustomPlaybackOverlayFragment in the onAttach function, according to the androidx documentation
- Additionally add the lifecycle owner (this) so it will be removed automatically
**Issues**
Fixes #3993
=> Fix back press callback in CustomPlaybackOverlayFragment

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentViewsRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/UserViewCardPresenter.kt
**Changes**
- Add new UserViewCardPresenter that can show 2 sizes of user view cards
<details><summary>Comparison with previous size (first row)</summary>
<p>
</p>
</details> 
**Issues**
Fixes #1499
Fixes #2093
Fixes #2721
Fixes #3176
Fixes #3664
Fixes #3749
=> Implement My media (small) home section

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
Don't overwrite the aspect ratio for videos
Change return value of ImageHelper.getImageAspectRatio to not be nullable
Fixes #1192
Possibly a regression from #830
=> Fix aspect ratio specials

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
When the MainActivity resumes we should **not** execute the current navigation action as this will cause the current fragment to reset. Therefor we should use the started lifecycle state instead of resumed.
**Changes**
- Fix incorrectly navigating on resume
**Issues**
Fixes #4026
=> Fix incorrectly navigating on resume

playback/core/src/main/kotlin/element/ElementsContainer.kt, playback/core/src/main/kotlin/element/delegates.kt, playback/core/src/main/kotlin/mediastream/QueueEntryMediaStream.kt, playback/core/src/main/kotlin/mediastream/normalizationGainElement.kt, playback/core/src/main/kotlin/queue/QueueEntryMetadata.kt, playback/jellyfin/src/main/kotlin/queue/baseItemElement.kt, playback/jellyfin/src/main/kotlin/queue/mediaSourceIdElement.kt
Until now all elements were set before they needed to be read. While working on lyrics support this became a limitation. For lyrics we'll fetch them when the song starts playing instead of preloading it. The UI would need to be notified of the lyrics being added, therefor I've added a new API to the ElementsContainer that can return a flow. To avoid caching a bunch of stateflows this implementation uses a single internal flow that emits for each element update, this then prompts the returned flows to update themself.
Unlike the simple getters we do not have a requiredFlow, instead it will always emit either a value or null. I may change this in the future.
**Changes**
- Add flow support for elements
- Add flow getters for all current elements
**Issues**
Part of #1057
=> Add flow support for elements

app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
**Changes**
Updated the code that retrieves the playback position from VLC to use long instead of int. Using long for the position aligns with the data type expected from [VLC](https://wiki.videolan.org/Android_Player_Intents/).
**Issues**
Fixes #4027
=> Fix VLC marked as watched

detekt.yaml
We use 140, Detekt defaults to 120.
**Changes**
- Fix Detekt max line length not matching Editorconfig
**Issues**
=> Fix Detekt max line length not matching Editorconfig

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/res/values/strings.xml
This adds the initial support for media segments with some of the actions I'd like still missing.
**Changes**
- Add new preference category "Media segment actions" in the playback section
- Contains a preference for each supported segment type
- Add "nothing" action - does literally nothing, default for each segment
- Add "skip" action - skips to the end of the segment when the player seeks over the segment start position
The `MediaSegmentRepository` contains a hardcoded list of supported segment types that is always included when requesting segments. This way we can add new segment types on the backend without breaking existing app releases (SDK won't be able to parse an unknown enum). Additionally, I've opted to not support the "unknown" type in the client.
Future additions will …
=> Implement media segments

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
When the video player fragment is closed and then later resumed, it would always reset the position to the timestamp send as argument. This is not desired as some people turn their TV off mid-movie (this should be illegal tbh).
**Changes**
- Always close the video player when the video player fragment stops, this causes the "item details" to pop up with a nice resume button when re-opening the app.
**Issues**
Fixes #4056
=> Fix video player not closing when fragment is stopped

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/MediaSegmentExtensions.kt
I did document it in the MediaSegmentAction enum but I forgot the implementation :-)
**Changes**
- Don't return the `SKIP` action from `MediaSegmentRepository.getMediaSegmentAction` when duration is <1second
- Add extension getters for start/end and duration of a segment
**Issues**
=> Don't skip media segments shorter than 1 second

app/src/main/java/org/jellyfin/androidtv/ui/composable/overscan.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/SkipOverlayView.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt, app/src/main/res/layout/vlc_player_interface.xml, app/src/main/res/values/strings.xml
Addition to #4052. This one adds a new action "ask to skip". When enabled for a segment type, this action will show a message on-screen to suggest skipping the segment. This only shows when the segment is at least 3 seconds long and the message disappears 1 second before the segment ends or 8 seconds after it is shown. Opening/closing the playback overlay also resets that timer as the skipping functionality is **not** working when any other UI is open.
The implementation is a bit of a hack as the player UI is partially leanback, partially custom and now partially compose. When we rewrite the player UI with compose we can make it a bit more integrated with less hacks.
**Changes**
- Add "ask to skip" media segment action
**Issues**
=> Add "ask to skip" media segment action

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
When a media segment skips to the end of the video, the app would misbehave and often just close the player instead of going to the next item. This change adds a fast-path to prevent this from happening.
**Changes**
- Prevent CustomPlaybackOverlayFragment from navigating multiple times
- Add "skipToNext" option to PlaybackController.seek to allow skipping to a next queue item if the position is at the end of the current item (`>= duration - 100ms`)
**Issues**
=> Fix skipping to next episode

app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
**Changes**
- In DestinationFragmentView
- Always call parent onRestoreInstanceState
- Use ParcelableArrayList which is type-safe so we don't need the unsafe cast
**Issues**
Maybe fixes #4073
=> Use parcelable array list in DestinationFragmentView saved state

app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
The 0.18 release of the app will require Jellyfin 10.10 (see #4040). To warn users about this upcoming requirement we'll start warning them to update.
**Changes**
- Change upcomingMinimumServerVersion to 10.10.0
**Issues**
=> Change upcomingMinimumServerVersion to 10.10.0 to warn about upcoming 10.10 requirement

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
(targets release branch)
#4057 introduced an issue where the next episode wouldn't play because of multiple navigations executing at once. This issue didn't happen on master due to other changes so I didn't catch it in time.
**Changes**
- Backport part of #4072
- Prevent CustomPlaybackOverlayFragment from navigating multiple times
**Issues**
Fixes #4089
=> (0.17.z) Fix playing subsequent episode not working

app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java, app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, playback/media3/exoplayer/src/main/kotlin/mapping/audio.kt, playback/media3/exoplayer/src/main/kotlin/mapping/container.kt, playback/media3/exoplayer/src/main/kotlin/mapping/subtitle.kt, playback/media3/exoplayer/src/main/kotlin/mapping/video.kt
In #3825 I made the initial changes to no longer require external subtitles. This came with a few issues; there was no longer support for external subtitles, switching subtitles didn't work a lot of times and the app didn't track which subtitles were playing properly. This pull request aims to fix all the issues by rewriting the subtitle logic.
The new logic relies on the server providing the delivery method for subs. For example, when transcoding the delivery method is set to HLS but on direct-play it is Embedded or External. The client will then decide the appropriate method to loading subtitles based on that information.
In my testing everything appears to work correctly but I'd appreciate some additional testing for:
- Playback starts with the correct subtitles when they are …
=> Rewrite all subtitle behavior

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
`null` means no, just like `-1`.
**Changes**
- Fix PlaybackController not always disabling default track
**Issues**
https://github.com/jellyfin/jellyfin-androidtv/pull/4094#issuecomment-2425131644
=> Fix PlaybackController not always disabling default track

app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/LyricsBox.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/modifier/fadingEdges.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/modifier/overscan.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt, app/src/main/res/layout/fragment_audio_now_playing.xml, playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt, playback/jellyfin/src/main/kotlin/lyrics.kt
After months of ~~procrastinating~~work, we now have 🎤 Lyrics in the app!
Supports both synced (highlight current line) and unsynced (continuous scroll) lyrics. It does introduce a tiny display bug with the seekbar in the screensaver, I'll fix that later.
**Changes**
- Load lyrics for queue items and add them to the new lyrics element
- Add lyric display in screensaver
- Add (small) lyric display in now playing view (on top of album art)
- Move overscan modifier to a new "modifier" subpackage
- Add new "fadingEdges" modifier that adds a fade-out edge
No screenshots for now because we don't have lyrics on the demo server :(
**Issues**
Part of #1057 
Closes #3742
Closes #2988
=> Implement lyrics

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt
This change is aimed to the (non-admin) users to have media segments work by default with sensible defaults. Automatically skipping should never be done, but asking to skip something can't hurt. I opted to enable this for intros/outros only as I expect those to be the segments people want to skip most often.
**Changes**
- Use "Ask to skip" by default for intros and outros
**Issues**
=> Use "Ask to skip" by default for intros and outros

app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
When subtitles are requested for baking but the bakery is not at home, the player would freeze and disabling subtitles did nothing. Now, when this happens the app will automatically turn off subtitles and retry. This fixes the scenario where the user does not have transcoding permissions and plays media with ass as default.
_Also the app can handle null as media url fine already._
**Issues**
=> Automatically disable subtitles when baking fails

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java, app/src/main/res/layout/vlc_player_interface.xml
So we have an unmaintained library that implements like 60% of the player user interface, but on top of that we have a bunch of hacky code. Simply said, the player UI has a bottom-region with the buttons etc. which is implemented by leanback and a top-region that is implemented by us.
Whenever the controls are shown or hidden these would **never** be in sync, sometimes the title would randomly appear during seeking etc. This is super annoying and especially with the "ask to skip" media segment action it was just painful.
So I synced them. _and probably introduced new bugs_
**Changes**
- Show "topPanel" by default, just like the leanback overlay
- Hide/show "topPanel" when leanback overlay is shown/hidden
- Added checks to "topPanel" to not show when already shown or hide when already …
=> Sync custom controls with built-in controls in leanback overlay

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java, app/src/main/res/layout/vlc_player_interface.xml
When the video player opens, you probably know what is gonna play already.. because you just opened it yourself. No reason to show the controls/title by default. So let's hide it!
**Changes**
- Hide video player controls by default
- Don't automatically show video controls when playback starts
- Fix "ask to skip" button showing on overlay on start
**Issues**
=> Hide video player controls by default

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
In some cases there is no preferred subtitle track client side, but the server does have one. When this track needs baking (SSA/ASS) there was a tiny bug in the client where it would restart playback because it thought it had to switch subtitle tracks.
**Changes**
- Fix video restarting immediately when baking subtitles
- Remove log spam from MediaCodecCapabilitiesTest
**Issues**
=> Fix video restarting immediately when baking subtitles

playback/jellyfin/src/main/kotlin/mediastream/AudioMediaStreamResolver.kt
Starting with 10.10 the transcode for music started to fail. After investigating (jellyfin/jellyfin#12926) we found various issues, and this code shouldn't have worked with 10.9 as well (unable to test as I don't have a 10.9 server anymore).
Adding the audio codec to the HLS playlist request fixes transcoding for the sample file I received.
**Changes**
- Add missing audio codec to audio/music transcode request
- Use mp4+aac instead of mp3
**Issues**
=> Add missing audioCodec to music transcode

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
When you shut down your device with the video player open, then start it up again. The OS will resume the app. When this happens the app state is also reset so we don't have anything to play. Closing the player is the way to go! You can't however create a fragment transaction during a fragment transaction, this is what happened because the fragment is being initialized when oCcreate is called. Delay the closing a bit to avoid crashing.
**Changes**
- Move player closing when there are no items to the onViewCreated method instead of invoking it in onCreate
**Issues**
Fixes #4099
=> Don't close player with invalid state in onCreate

app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
We already have the media info when we call the reportStart function so why not let the server know our play method?
**Changes**
- Add additional information to PlaybackStartInfo
**Issues**
=> Add additional information to PlaybackStartInfo

app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
When the default subtitle track is manually set to -1 (during playback and then restarting playback) the subtitles would still show up, but rendered via exo. This happened because read branchname.
**Changes**
- Fix getSubtitleDeliveryMethod in StreamInfo always returning "Encoding"
**Issues**
=> Fix getSubtitleDeliveryMethod in StreamInfo always returning "Encoding"

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Hopefully this doesn't introduce a bunch of other issues again, didn't really have the time to test all cases.
**Changes**
- Fix current audio track selection not set when baking subtitles
**Issues**
=> Fix audio track selection when baking subtitles

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Without this changing to other audio tracks fails, it just keeps playing the first one in the file. I was tipped off to the source of the problem by lines like this in logcat:
11-04 19:26:01.244 11669 11669 D VideoManager: failed to parse track ID [0:2]
It appears exoplayer changed from a simple number for trackid to two numbers separated by a colon. Haven't had any luck tracking down why, but the latter of the two appears to match the old single number so, just pull that out and use it.
=> Fix exo track id parsing for format change.

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
Sometimes we need to be a bit special.
**Changes**
- Use `ItemSortBy.SERIES_DATE_PLAYED` when collection type is `CollectionType.TVSHOWS`
**Issues**
Fixes #4160
=> Fix sorting TV shows by last played

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
We have a special case in the PlaybackController.seek() method that stops playback if the requested seek is higher then the video duration. When this happens we should make sure the duration is set as progress so the reporting helper correctly reports the end time, otherwise it would report the time before seeking/skipping a segment.
**Changes**
- Fix position on playback stop reporting when skipping to playback end
**Issues**
Fixes #4165
=> Fix position on playback stop reporting when skipping to playback end

app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Ideally the stop event should notify the user too but that can be done later ©️ 
**Changes**
- Catch errors when reporting playback state
**Issues**
=> Catch errors when reporting playback state

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Part 2 of #4167
**Changes**
- Fix skipping to end of video reports wrong end time
**Issues**
Fixes #4165 (for real this time!)
=> Fix skipping to end of video reports wrong end time

app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
Kotlin stdlib `error()` throws an `IllegalStateException`. Coil `ImageRequest.error()` sets the error resource. Guess what happens if the latter is not imported correctly.
**Changes**
- Fix a missing import from #4190
**Issues**
=> Fix ImageProvider always throwing

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
When I rewrote the subtitle behavior I did test with media that had both embedded and external subtitles, and in those tests the server would **always** put all embedded tracks (including audio/video) before external tracks, keeping their indexes the same as you would find them sorted in when inspecting with ffprobe, mkvtoolnix and other tools.
However, this piece of shit API does not always do that. In fact, it can put the external tracks before internal tracks just for funs. This leaves a client literally unable to reliably map a media stream to tracks in their video engine. The hack I've implemented will take all the embedded/hls subtitle streams, filtering out everything else, and then calculate the index. Then does the same when selecting the ExoPlayer track. This _should_ fix all …
=> Use relative index matching for subtitle selection

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Not sure why, everything seems correct, but media3 won't render PGS when loaded externally.
**Changes**
- Never load PGS externally
**Issues**
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/4183
Maybe fixes https://github.com/jellyfin/jellyfin-androidtv/issues/4182
=> Never load PGS externally

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
- Log all external subtitle tracks that get added
- Refactor subtitleProfile utility function to be easier to work with
- Fix non-webvtt subtitles allowed in HLS, causing the server to convert SRT->WebVTT (#4191)
- Fix PGSSUB still added as external supported (oops) - also fixed with #4206
- Add TTML as supported
- Fix DVBSUB, IDX allowed as external (media3 does not support that)
- **Document the edge-cases in-code**
**Issues**
Fixes #4191
=> Refactor subtitle profiles to be more readable

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
currentAudioQueuePosition is always either 1 or 0
**Changes**
- Fix audio now playing screen always showing "1 of x" instead of the actual queue position
**Issues**
Fixes #4213
=> Fix audio now playing screen always showing "1 of x" instead of the actual queue position

playback/core/src/main/kotlin/queue/QueueService.kt
should've implemented this earlier
**Changes**
With this change the queue index will always reset to -1 (INDEX_NONE) once the last item in the queue ends instead of leaving the last queue item active. This solves various issues in the UI (like the screensaver) where it keeps showing the last item when nothing is playing
- Allow `INDEX_NONE` in `Queue.setIndex`
- Fix crash when `getOrSupplyItem` is invoked with a lower then 0 index (couldn't happen before this PR though)
- Set queue index to `INDEX_NONE` once last queue item finishes
**Issues**
Fixes #4214
Part of #1057
=> Unset playing item once the playback queue ends

app/src/main/res/drawable/audio_now_playing_album_background.xml
The emerald theme changes the defaultBackground to a drawable (is a color by default). Obviously can't use a drawable as color.
**Changes**
- Hardcode the not_quite_black color in audio_now_playing_album_background instead of using the defaultBackground attribute
**Issues**
Fixes #4266
=> Fix crash when viewing audio now playing while using Emerald theme

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
When the stream needs to be recreated to change audio streams (e.g. transcoding/external stream etc.) the app sets the current stream to null and once the new stream info is ready it will be set again. It does stop all progress reporting for that (normally short) duration.
However, if you try to seek during that time period it will try to report progress which will fail and crash the app.
**Changes**
- Add a check for null before trying to start a report loop
**Issues**
Should fix #4254
=> Fix crash when trying to report playback progress when there is no current stream

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
UI must always use main thread
**Changes**
- Fix ItemRowAdapterHelper.refreshItem using wrong thread when invoking callback
**Issues**
Fixes #4273
=> Fix ItemRowAdapterHelper.refreshItem using wrong thread when invoking callback

app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
Going over the very few changes made that could affect the external video player my best guess right now is that the `playbackControllerContainer` is empty (null) causing an NPE when the app tries to start a video. Untested.
**Changes**
- Make playbackController reference optional in ReportingHelper
**Issues**
Maybe fixes #4274
=> Make playbackController reference optional in ReportingHelper

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Navigating does not cancel the screensaver when using remote control. This is not the intended behavior, it should always cancel the screensaver.
**Changes**
- Always call notifyInteraction on navigation
**Issues**
Fixes #4262
=> Always call notifyInteraction on navigation

app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
The delivery URL was not copied over (using API URL builder) to the stream info anymore, so it would later be filtered out because we can't link without an URL.
**Changes**
- Fix external subtitles not added to external player
- Simplify getSubtitleProfiles function a bit (remove unused code)
**Issues**
Fixes #4310
=> Fix external subtitles not added to external player

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
When shuffling the queue stays the same data structure and the playback order is used to return items based on the shuffled indices. The updateAdapter function used the internal list of the queue supplier so playback ordering was never used, causing the wrong items to display during shuffle.
**Changes**
- Use the actual queue to provide items instead, limited to the next 100 items (including current)
- Refresh adapter when playback order changes
- Compare items by id (performance gain)
**Issues**
=> Fix UI audio queue order when shuffling

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
The fragment already closed itself when a queue ended. However, it is possible to start the fragment after a queue has ended by switching between apps or having the system screensaver active during playback and then closing it after playback ended.
**Changes**
- Move check to self-close `AudioNowPlayingFragment` to `loadItem()` to prevent `AudioNowPlayingFragment` from showing without active queue
**Issues**
=> Prevent AudioNowPlayingFragment from showing without active queue

playback/core/src/main/kotlin/queue/QueueService.kt
I don't think we even use this repeat mode anywhere yet.
**Changes**
- Fix QueueService.getNextIndices returning one item too many when using REPEAT_ENTRY_ONCE
**Issues**
=> Fix QueueService.getNextIndices returning one item too many when using REPEAT_ENTRY_ONCE

app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
- Fix music play action not working after queue has ended
**Issues**
Fixes secondary issue of #4328
=> Fix music play action not working after queue has ended

playback/core/src/main/kotlin/PlayerState.kt, playback/core/src/main/kotlin/queue/QueueService.kt
**Changes**
- Add behavior to PlayerState to repeat media stream when it ends
- Use private (mutable)flow when accessing entry index in queueservice per code style
**Issues**
Depends on #4329 to work correctly
Fixes #4328
=> Fix repeat mode not working

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Fix crash when starting progress report loop without active stream in video player
**Issues**
Fixes #4331
=> Fix crash when starting progress report loop without active stream in video player

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManagerHelper.kt, playback/media3/exoplayer/src/main/kotlin/mapping/audio.kt, playback/media3/exoplayer/src/main/kotlin/mapping/container.kt, playback/media3/exoplayer/src/main/kotlin/mapping/subtitle.kt, playback/media3/exoplayer/src/main/kotlin/mapping/video.kt
This fix is a bit of a hack because I'm parsing the URL client side which I shouldn't need to do.
**Changes**
- Try to infer external subtitle media type from URL first before falling back to using the original codec type (which is the previous behavior)
**Issues**
Fixes #4326
=> Infer subtitle codec from delivery URL if unknown

app/src/main/java/org/jellyfin/androidtv/data/repository/ItemRepository.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt, app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
We currently have API requests all over the app but they all request a different set of item fields. This can cause issues if baseitemdto's are passed between various parts of the app. 
**Changes**
- Add ItemRepository, which for now holds a set of fields used by the app only
- Update all API calls that currently request fields to use the new ItemRepository.itemFields
**Issues**
=> Centralize requested item fields

playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
In Android multiple apps can be playing media at once, even with multiple media sessions. To avoid  this an app should claim "audio focus". This way only the last app requesting audio focus can actually play audio. This helps when a user switches between media apps and is a best practice according to [Android documentation](https://developer.android.com/media/optimize/audio-focus).
**Changes**
- Enable audio focus and set usage audio attribute
**Issues**
Part of #1057
=> Enable audio focus for music playback

app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt, app/src/main/res/drawable/ic_check.xml
We should avoid using anything in `androidx.compose.material.icons` as that dependency will be dropped once we remove `androidx.tv`.
**Changes**
- Replace Icons.Default.Done with ic_check in ConnectHelpAlertFragment
**Issues**
=> Replace Icons.Default.Done with ic_check in ConnectHelpAlertFragment

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
When video playback fails it should always fallback to remuxing. This behavior didn't work anymore for reasons.
**Changes**
- Fix Live TV fail-over not working
**Issues**
Fixes #4178
=> Fix Live TV remux fail-over not working

playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
We should always try-catch network requests as network issues are quite common, especially with people hosting on low power devices. The new playback code (currently used for music) did not catch those when reporting playback state, causing the app to crash as the exception bubbled up to the application.
**Changes**
- Fix app crashing when playback reporting fails
**Issues**
Part of #1057
=> Fix app crashing when playback reporting fails

app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt, app/src/main/res/layout/fragment_select_server.xml
Mixing compose with legacy views keeps challenging us :-)
**Changes**
- Fix focusing the "home" button in the toolbar in the item details screen
- Caused by the "now playing" music composable
- Fix focusing the "get help" button in the toolbar in the server selection screen
- Caused by the "notifications" composable
**Issues**
Fixes #4363
=> Fix focus issues on older Android versions

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/PlaybackSpeedAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectQualityAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.kt, app/src/main/res/values-ca/strings.xml
**Changes**
Dismiss popups from playback actions (ex: closed captions, audio track, etc...) when the video player fragment is detached.
An open popup could hold an invalid reference to a `videoPlayerAdapter` when the app was exited and re-opened.
**Issues**
Fixes #4163 
**Other comments**
I noticed that the actions have slightly different code styles for handling popups. I tried to not move stuff around too much, but I would not mind streamlining stuff a bit :)
=> Dismiss playback actions popups on fragment detach

.github/ISSUE_TEMPLATE/bug-report-playback.yaml, .github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml
**Changes**
- Added `Other Sources` - an optional field to link to existing discussions on the forum or simmilar
- Reworked the `feature request` template to get more detailed requests from users
Additionaly theese minor changes have been made:
- Updated Soft-/ Hardware Versions in the Placeholders
- Added _some_ `before-posting` checks
- Added F-Droid to the Source Dropdown
- Added Sources to `media playback` issue form
- Added `headlines` to `media playback` and `bug` forms
**Issues**
=> update issue forms

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
**Changes**
Run LeanbackHelper onPause() to refresh home screen. When the app is paused, it is probably because the user navigated to the home screen.
**Issues**
#3139
=> Run LeanbackHelper onStop() to refresh home screen

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
Oddly specific title
**Changes**
- Fix crash when favoriting Live TV program while loading additional channels in the guide
**Issues**
Fixes #4384
=> Fix crash when favoriting Live TV program while loading additional channels in the guide

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
All of our official clients I checked start their client name with Jellyfin, e.g. `Jellyfin Android` or `Jellyfin Web`. ATV was the only one that did not. So I fixed it.
**Changes**
- Update reported client name
**Issues**
=> Update reported client name

app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
The AV1 constant in MediaFormat is not available in older API levels, use the media3 constants instead
**Changes**
- Use media3 MimeTypes in deviceProfile
**Issues**
=> Use media3 MimeTypes in deviceProfile

app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Hello there! This is my first Jellyfin PR – Feedback Welcome!
**Changes**
- Corrected condition to properly check if the current time is within the program's duration.
- Fixed progress percentage calculation using double division for accuracy.
- Replaced getPremiereDate() with getStartDate() for correct program start time.
- Refactored getRealTimeProgress() to ensure proper duration calculation.
**Issues**
Both Live TV progress bars are not working properly.
Couldn't find a matching issue, but this likely affects many. If one exists, please link it. Thanks!
=> Fix progress bar calculation

app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/MarkdownBuilder.kt, app/src/main/java/org/jellyfin/androidtv/util/Utils.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt, app/src/main/res/values/strings.xml
Troubleshooting playback issues is extremely difficult because the app doesn't give much insight into what is happening. Even with logging enabled, it can be difficult to figure out why something transcodes or produces a black screen.
This change should somewhat improve that situation by adding a new troubleshooting feature directly inside of the app. At the very least it will be extremely useful to test improvements to the device profile.
**Changes**
- Add new "createDeviceProfileReport" function that creates a (markdown) report about the device profile and the data used to construct it
- Includes the full device profile as JSON, the same one that would be reported on playback
- Includes information about the device capabilities (MediaCodecList)
- Could be extended some more in the …
=> Add button to report device profile to server for troubleshooting

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
Bit of old code that was migrated to the SDK with exact same behavior. We shouldn't need to apply additional constrictions when requesting collections, API request now matches more similarly with jellyfin-web.
**Changes**
- Fix filtering not working in collections view
**Issues**
Fixes #4475
=> Fix filtering not working in collections view

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
The `.first` call throws when there is no match to the predicate, it should've been a `.firstOrNull` call from the start.
**Changes**
- Fix crash when switching subtitle track to non existent index
**Issues**
Fixes #4458
=> Fix crash when switching subtitle track to non existent index

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
Alternative to #4496. That one would accidentally make libraries into folder views, which was not the intended behavior.
**Changes**
- Remove special case when retrieving box sets (collections) from the server. The server does not support filters on these. The query is now more similar to jellyfin-web.
**Issues**
Fixes #4475
=> Fix filtering not working in collections view (v2)

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentLibraryShowcase.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/Icon.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/JellyfinTheme.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/Text.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonBase.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/shapes.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/typography.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/LyricsBox.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/SkipOverlayView.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, gradle/libs.versions.toml
Jetpack Compose (library used for new UI) is build in layers. The top layer is the "theme" package, of which we currently use `androidx.tv`. Unfortunately this library is lacking and IMO not suited for a lot of our uses (like not supporting touch), in addition to already being somewhat unmaintained by Google similar to how they did with the `androidx.leanback` library.
This PR marks the start of our own "Jellyfin" theme. Eventually it will adhere to our design guidelines made by @erikbucik. Right now most of it is close to the previous (material based) theme, as our Figma does not have foundations like typography or shapes ready yet.
The new design composables will eventually be moved to their own Gradle module and be used in both our mobile and TV apps where possible. Some composables …
=> Replace androidx.tv with own theme implementation

app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
Fix regression of #4531
**Changes**
- Make sure logo cannot exceed height of 75dp (same value as screensaver)
- Fix AsyncImage not adjusting view bounds to image aspect ratio
**Issues**
=> Fix logo in next up too large

playback/jellyfin/build.gradle.kts
Honestly no idea how compilation was working without this.
**Changes**
- Fix missing coroutines dependency in playback:jellyfin module
**Issues**
=> Fix missing coroutines dependency in playback:jellyfin module

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
The ItemRowAdapter is used in a lot of old UI (home/browsing/search). It didn't log any API errors, making debugging very hard, the exceptions were just swallowed in most cases.
**Changes**
- Fix ItemRowAdapter failures never logged
**Issues**
=> Fix ItemRowAdapter failures never logged

app/src/main/java/org/jellyfin/androidtv/SessionInitializer.kt, app/src/main/java/org/jellyfin/androidtv/data/repository/ItemMutationRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt, app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopupHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopupHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncherHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManagerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/segment/MediaSegmentRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchRepository.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Right now our Kotlin SDK uses Ktor for networking. Ktor will automatically switch coroutine contexts whenever we call the API. The next version of the SDK will use OkHttp and the SDK will stop switching contexts by itself, instead it relies on the library user to switch contexts.
Before this PR the app barely worked because my quick SDK migrations didn't switch contexts and thus networking would run on the main thread with the OkHttp implementation... oops.
Review best enjoyed with whitespace changes disabled.
**Changes**
- Switch contexts when calling API
- Switch contexts in some other places that make sense
**Issues**
=> Fix a lot of networking on main thread issues

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, gradle/libs.versions.toml, playback/media3/exoplayer/build.gradle.kts, playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt, playback/media3/exoplayer/src/main/kotlin/ExoPlayerOptions.kt
The next version of our SDK will use OkHttp as default networking library and allows us to supply the base OkHttp client. That way the connection pool and cache can be easily shared to slightly speed up networking and allow for easy network configuration (like proxy authentication) in the future.
This PR prepares our media playback to also use OkHttp, with a follow up to share the same base with the SDK/Coil coming once we've updated the SDK.
**Changes**
- Use OkHttp for networking in media3
**Issues**
Part of #1057
=> Use OkHttp for networking in media3

app/src/main/java/org/jellyfin/androidtv/ui/base/JellyfinTheme.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/Button.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonBase.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonColors.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/IconButton.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/button/ProgressButtonBase.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/colorScheme.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/HomeToolbar.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/Toolbar.kt
Make the background of icon buttons in the toolbar (see #4562) transparent again. But in the most complicated way.
**Changes**
- Add JellyfinTheme fun to easily set theme properties
- Add colorScheme
- Add ButtonColors & ButtonDefaults.colors
- Set transparent button color in ToolbarButtons
**Issues**
=> Add ButtonColors and colorScheme

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
As of media3 1.6 the audio session id is not available on initialization, instead we need to defer to the onAudioSessionIdChanged event before enabling audio night mode.
**Changes**
- Fix experimental audio night mode feature crashing the app
**Issues**
Fixes #4578
=> Fix experimental audio night mode feature crashing the app

playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
Similar to #4582 but this one didn't cause a crash
**Changes**
- Do not set audio session to pipeline on create as it will always be `0` (global)
**Issues**
=> Do not set audio session to pipeline on create

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
We add the "favorites playlist" client-side and then load the other playlists to the same row, if we only check the response list it won't know about that and hide the row.. oops
**Changes**
- Fix "favorites" playlist not showing when the user has no playlists
**Issues**
Fix #4587
=> Fix "favorites" playlist not showing when the user has no playlists

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/navigation/ActivityDestinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destination.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationAction.kt, app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Thee are the initial changes to improvements on our navigation code to fix some long standing fragment transaction issues on resume and to better support compose (without fragments wrapping the screen composable).
**Changes**
- Remove activityDestination
- Add ActivityDestinations object to create intents for launching our previous activity destinations: preferences & external player
- Rewrite PlaybackLauncher to actually launch (set media queue & navigate) instead of just returning a destination
**Issues**
=> Move activity opening out of navigation code

app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt, app/src/main/res/values/strings.xml
Would it be better to show CC when there is _any_ non-sdh subtitle stream and SDH when there is _any_ SDH stream? Let me know in the comments (don't forget to like and subscribe).
**Changes**
- Add "SDH" instead of "CC" as indicator to the info row when subtitles are marked as hearing impaired
**Issues**
Fixes #3463
=> Add hearing impaired indicator for subtitles (SDH)

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt, app/src/main/java/org/jellyfin/androidtv/ui/composable/AsyncImage.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpItemData.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/JellyfinImage.kt
Add a new "JellyfinImage" model that contains all image information retrievable from API responses. This is accessible via the next ".images" extension getters like `BaseItemDto.itemImages`, `BaseItemDto.parentBackgroundImages` etc.
The goal is to make it much easier to use images from the API by grouping information like the item id, blurhash, tag etc in a single model. That model can then be passed through the application and resolved to a URL easily.
Current implementation does not use it everywhere yet but it does in the background/screensaver/nowplaying code and fixes at least one bug that has been here for a long time and we only recently became aware of 👀.
**Changes**
- Add intermediate model for image information
**Issues**
Fixes #4628
=> Add intermediate model for image information

app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/UserViewCardPresenter.kt, app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/ModelExtensions.kt
**Changes**
Somewhat finishes the work of #4635 by migrating most code to use the new JellyfinImage intermediate. There's still a few places that use the ImageApi directly:
- AuthenticationRepository (only tag is stored in our local data)
- BaseItemExtensions.buildChapterItems (the "ChapterInfo" API model does NOT have enough information to construct the JellyfinImage)
- createBaseItemQueueEntry (not in the "app" module so no access to JellyfinImage)
**Behavior changes**
We did some dirty "just try and see if it works" requests for images in some fallback scenarios. The API doesn't give us enough information to know whether these images exist or not. I've chosen to remove those fallbacks now to avoid useless network requests. This impacts:
- Artist image fallback for audio items
- Logo …
=> Use new intermediate model in most places

app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
**Changes**
A boxset (collection) has its own sorting that should be preferred over individual sorting names of its contents. Those sorting names are meant for the parent (e.g. episode sorting name for ordering in a season) not for in a collection.
**Issues**
Fixes #4649
=> Always create boxset queues with default sorting instead of using sort names of individual items

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
if use on a tablet, things like pull down quick tiles could bring out system bars, and it stays. 
so I make the hide effect sticky.
=> Improve status bar hiding behavior

app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
**Changes**
I was watching my Jellyfin screensaver and noticed that there were some media that were displayed repeatedly, and found that this was because the screensaver has no memory of the media it recently cycled through. This is a rough draft of an alternative model; instead of requesting a new random library item to display each time, request many distinct random library items from the outset, and then play them in (the provided random) order. This ensures better coverage of the media library and reduces repetition.
=> Change screensaver to cycle through random selection and avoid repeats

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, playback/media3/session/src/main/AndroidManifest.xml
**Changes**
- Add missing action for AndroidMediaService
- This now enables the remote control notification on phones with gplay services when playing music
- Disable channel badge for media notification channel
**Issues**
=> Add missing action for AndroidMediaService to manifest

app/src/main/java/org/jellyfin/androidtv/ui/base/modifier/childFocusRestorer.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
I think onExit isn't called when focus changes to a (non-compose) view. Not sure if bug or intended behavior in compose... issue was there before this PR though.
**Changes**
- Fix compose focus deprecations
**Issues**
=> Fix compose focus deprecations

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
If the capabilities of a device change, Exoplayer can invalidate the current selection to adhere to the new list of capabilities.
This helps the Nvidia Shield and its content matching refresh rate option because, during the refresh rate switching period, the reported capabilities change. Without this flag, the device could reproduce audio as PCM instead of the expected passthrough.
**Issues**
Addresses https://github.com/jellyfin/jellyfin-androidtv/issues/4067, additional context https://github.com/androidx/media/issues/2258
I'm using "addresses" because I don't want to automatically close https://github.com/jellyfin/jellyfin-androidtv/issues/4067. To fully fix it, we also need to bump media3 to the upcoming release (1.6.1+) because we need …
=> Allow Exoplayer to invalidate the track selection on capabilities change

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
This PR fixes an issue where the skip overlay persists when switching episodes
**Changes**
- Clear the skip overlay target before applying any segments
- Extract the clear overlay logic to a helper function since it was being used in 3 places 
**Issues**
Fixes #4721
=> Clear skip overlay before applying media segments

app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Basically made the value overflow all the time causing the value to be reset 0 and play videos from the start instead of resuming.
**Changes**
- Fix retrieveAndPlay incorrectly using ticks instead of milliseconds as start position
**Issues**
Fixes #4405
=> Fix retrieveAndPlay incorrectly using ticks instead of milliseconds as start position

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/AudioQueueBaseRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioQueueBaseRowAdapter.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackRewriteFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, playback/core/src/main/kotlin/queue/Queue.kt, playback/core/src/main/kotlin/queue/QueueService.kt, playback/core/src/main/kotlin/queue/order/OrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt, playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
To integrate the new fancy playback code with old UI I moved the old MediaManager to an interface and implemented it on a best-effort basis. We still don't use the queue system in its intended way and have a dirty supplier implementation that is just a list of baseitems. However, the queue system is only made for those suppliers to grow in size while fetching and never shrink or grow after they stopped supplying. This did happen with the queue removal function causing very weird states in the app.
Those issues are now fixed, just took me a few hours 🫠.
**Changes**
- Add new AudioQueueBaseRowAdapter
- Replacement for the ItemAdapter that was maintained by MediaManager
- Works stand-alone (e.g. it manages its own items)
- Use queue entries instead of just base items in AudioQueueBaseRowItem …
=> Support removing items from playback queue

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
Fixes a crash that sometimes occurs with 10.11 on unwatched multi-season series.
**Changes**
- Query based on seriesId in FullDetailsFragmentHelper.getNextUpEpisode
**Issues**
=> Query based on seriesId in FullDetailsFragmentHelper.getNextUpEpisode

app/src/main/java/org/jellyfin/androidtv/ui/ServerButtonView.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/BaseItemInfoRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/InfoRowItem.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/composable/inforow/rating.kt, app/src/main/java/org/jellyfin/androidtv/ui/card/UserCardView.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/SkipOverlayView.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchTextInput.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/composable/SearchVoiceInput.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/MainToolbar.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/StartupToolbar.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt
**Changes**
- Use Icon composable instead of Image composable where possible
- Use vectorResource instead of painterResource where possible
- Change InfoRowItem to allow for tinting (or disabling tinting using Color.Unspecified)
- Update community rating / critic rating to use their colors as tint
**Issues**
=> Prefer imageVector painting for icon drawables

app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Still doesn't fix the issue I'm encountering but this makes for a nice feature to see whether the debug version of the app is used or not from the jellyfin dashboard.
**Changes**
- Differentiate client name for debug version in API authorization
**Issues**
=> Differentiate client name for debug version in API authorization

build.gradle.kts
Unfortunately GitHub made a breaking change in how they process SARIF files without properly communicating it (I follow the release blog RSS feed and I didn't know about this until they made the actual change). This PR updates the way we lint using Detekt so all results are in a single run so GitHub is happy again.
This change must be backported if we do another 0.18 release.
**Changes**
- Run Detekt from root module only
**Issues**
=> Run Detekt from root module only

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
Remove Jellyfin branding just like in the new toolbar. The logo still shows for 2 seconds when the screensaver initializes but it will no longer show on the now playing / library showcase elements.
**Changes**
- Remove logo from screensaver library showcase
**Issues**
Supersedes #4763
Closes #1888
=> Remove logo from screensaver

app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt, app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt, app/src/main/java/org/jellyfin/androidtv/ui/base/Seekbar.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerSeekbar.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/Toolbar.kt, app/src/main/res/layout/fragment_audio_now_playing.xml
This change backports the new seekbar composable from the new video player user interface and uses it for music playback. It uses the scrubber API from #4843 which results in seeking being extremely smooth (in my testing).
**Changes**
- Use the ToolbarClock composable in the screensaver to avoid duplicate code
- Add a new seekbar composable
- Use new seekbar composable in (audio) now playing screen
- Use new seekbar composable in screensaver
**Issues**
=> Add seekbar to music playback

app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
**Changes**
- Add display information to playback report
Looks like this
<details>
<summary>Display information</summary>
***Id***: `0`  
***Name***: `Built-in Screen`  
***Display product id***: `1`  
***Display bame***: `EMU_display_0`  
***Display manufacture year***: `2006`  
***Display manufacture week***: `27`  
***Display manufacturer pnp id***: `GGL`  
***Display model year***: `-1`  
***Rotation***: 0  
***Refresh rate***: `60.000004`  
***VSYNC offset***: `1ms`  
***Presentation deadline***: `16.666666ms`  
***Minimal post processing***: `false`  
***Any HDR***: `false`  
***Wide color gamut***: `false`  
***Preferred wide color space***: `null`  
***HDR capabilities***: 
- Dolby Vision: false
- HDR10: false
- HDR10+: false
- HLG: false
***HDR/SDR ratio***: 
***Available***: …
=> Add display information to playback report

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
I have not been able to test this on an actual HDR10+ capable device. I only know it correctly detects there is NO support on my shield and emulators.
**Changes**
- Add codec profile rules for Dolby Vision, HDR10 and HDR10+
**Issues**
Fixes #4860
=> Add display HDR capabilities to device profile

app/src/main/java/org/jellyfin/androidtv/ui/navigation/Destinations.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerHeader.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerOverlayLayout.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerSubtitles.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerSurface.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/base/visibilityTimer.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerControls.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerHeader.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerOverlay.kt, app/src/main/java/org/jellyfin/androidtv/ui/player/video/VideoPlayerScreen.kt
This PR adds the first (of many) changes for the new (video-)player user interface. It's built in two layers so everything is reusable for different player types. This will eventually be used for music, audiobooks, photos, live tv etc. as well. With this base it will be easier to add features as the UI can be developed at the same time.
This is not the final design. Things will change.
Currently the UI implements the following features:
- Display video with correct aspect ratio
- Display subtitles with correct aspect ratio
- They are currently rendered on top of the controls, this may change in the future
- Display controls on any key press
- Auto-hide after 5 seconds or on back press
- Play/pause control
- Rewind and fast forward controls
- Seekbar (already backported in #4844) …
=> Add new video player UI

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
I believe this was a workaround for bad code.
**Changes**
- Fix focus always forced to first queue item in AudioNowPlayingFragment
**Issues**
=> Fix focus always forced to first queue item in AudioNowPlayingFragment

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java, app/src/main/res/layout/fragment_audio_now_playing.xml
Some focus issue makes the "home" button inacessible. Tried multiple ways of solving it but I'm quite sure compose interop is just not having fun with it, probably because of the scroll view. So disable the home button for now.
Might have enough time to redesign this entire screen with compose before 0.19. Not sure.
**Changes**
- Disable home button
- Move from ScrollView -> NestedScrollView and update the scrollTo handling
- This fixes an old issue where smooth scroll would just happen instantly
- Also fixes some regression where we never scrolled anymore
**Issues**
=> Fix navigation issues in AudioNowPlayingFragment

app/src/main/java/org/jellyfin/androidtv/ui/search/SearchFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/search/SearchViewModel.kt
**Changes**
Trim any leading/trailing whitespace from the user's input before performing the search - my phone adds a trailing space when using autocomplete, e.g. `"movie "` which does not match anything in my library.
NOTE: I didnt bother `.trim()`-ing the `SearchVoiceInput` query text as I assume that wouldn't have any leading/trailling whitespace, but I can update the PR if it makes sense.
**Issues**
[This](https://github.com/jellyfin/jellyfin/pull/11896) is an unmerged/unfinished PR for performing the trim server-side where it was suggested that the trim be performed client-side.
=> Trim whitespace from search query

app/src/main/java/org/jellyfin/androidtv/ui/player/base/PlayerOverlayLayout.kt
Applies to both video and photo players.
**Changes**
- Use transparent buttons in player controls
(see before at #4865)
**Issues**
=> Use transparent buttons in player controls

app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
Add a check for low memory devices to disable blurhash while loading images with AsyncImageView (the majority of images currently). This should improve performance slightly on underpowered devices.
Note that it is up to a device manufacturer to consider a device low memory or not.
**Changes**
- Disable BlurHash on low memory devices
**Issues**
=> Disable BlurHash on low memory devices

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerHelper.kt
2 issues actually!
**Changes**
- Fix ExoPlayer selecting embedded/external subtitle file when we're already baking
- Fix state not set properly when switching from baked to non-baked subtitle, causing none to show up
**Issues**
Fixes #4914
=> Fix switching between baked and non-baked subtitles

app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt
Copy the client name used by the SDK to the crash reporting so it is consistent. The name is used for the log files written by the server.
**Changes**
- Update client name for crash reports
**Issues**
=> Update client name for crash reports

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
We already communicate whether direct play is allowed or disallowed using the `enableDirectStream` and `enableDirectPlay` options in `(Legacy)PlaybackManager.getVideoStreamInfoInternal()`. No need to change the device profile dynamic for that.
**Changes**
- Remove disableDirectPlay option from device profile
**Issues**
=> Remove disableDirectPlay option from device profile
