jellyfin/jellyfin-androidtv

- AdbConnect - Fire 4k.bat
- AdbConnect - Fire Stick.bat
- AdbConnect - Fire.bat
- AdbConnect NP.bat
- AdbConnect Shield.bat
- AdbConnect.bat
- AdbInit 2.bat
- AdbInit.bat
These batch files where specific to "Eric"'s environment and useless to any of us, should never have been in the repo anyway
> Remove completely useless adb batch files to clean up repo

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/activity_search_no_speech.xml
- app/src/main/res/layout/fragment_settings.xml
Addresses a build error caused by linting issues in a few XML files.
> Fix linting issues in xml files

- app/src/main/AndroidManifest.xml
Use the banner logo for the app icon.
Fixes #27
> Change app icon to use banner

- CONTRIBUTORS.md
- app/build.gradle
- app/src/main/res/xml/preferences.xml
- build.gradle
@thornbill you can test this to see if the build is fixed.
Closes #32
> update build gradle files

- app/build.gradle
- app/src/main/res/layout/activity_search_no_speech.xml
Updates the Android support libraries to match the new SDK version.
Updates search icon for new support library version.
> Update support lib to sdk version

- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
This should fix #22 :crossed_fingers:. I don't have live TV setup to verify though.
> Add null check for channel name

- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
Removes the app store url and icon url that reference Emby resources.
> Remove additional Emby references

- .gitignore
Ignore build artifacts in `app/build/` from git.
> Add build directories to gitignore

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.java
- app/src/main/java/org/jellyfin/androidtv/ui/GenreButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/ImageButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/TextButton.java
Fixes lint errors when building.
> Fix linting errors

- app/src/main/java/org/jellyfin/androidtv/base/BaseActivity.java
Hopefully this will fix an issue where Jellyfin will sometimes display multiple toast notifications that the user is being logged off. It has been difficult to reproduce on demand.
> Fix multiple logoff messages

- build.yaml
Just a quick one for my wrapping infra.
> Don't try to build unminified

- app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
- app/src/main/res/layout/guide_filter_popup.xml
- app/src/main/res/layout/guide_options_popup.xml
- app/src/main/res/layout/live_tv_guide.xml
- app/src/main/res/layout/new_program_record_popup.xml
- app/src/main/res/layout/program_detail_popup.xml
* Fixes theming issues with Live TV
* Updates device name to "Android TV"
* Minor refactoring to remove unnecessary type casting and inline if statements
Fixes #99
> Fix theming issues for Live TV

- app/build.gradle
- app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
- build.gradle
* Pulls official build of libvlc from gradle
* Updates libvlc usage for 3.1.x compatibility
> Use official libvlc build

- app/src/main/AndroidManifest.xml
Allows http traffic on devices using a newer API version.
> Allow http traffic

- app/src/main/java/org/jellyfin/androidtv/constants/CodecTypes.java
- app/src/main/java/org/jellyfin/androidtv/constants/ContainerTypes.java
- app/src/main/java/org/jellyfin/androidtv/constants/MediaTypes.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/AndroidProfile.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/Api16Builder.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/Api21Builder.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/StreamBuilder.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/StreamInfo.java
- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
* Fixes uses of methods that have been removed from the apiclient.
* Refactors String values to contstants
* Changes `Utils.join` to accept varargs
> Fix removed methods

- app/build.gradle
- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
- app/src/test/java/org/jellyfin/androidtv/util/TimeUtilsTest.java
Adds utilities for converting times to milliseconds (with tests!) and updates the next up duration to 30s for short content
> Update next up duration

- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
Removes the error reporting dialog since we don't currently have this functionality.
> Remove report error dialog

- app/src/main/java/org/jellyfin/androidtv/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
Update method names to match changes in https://github.com/jellyfin/jellyfin-apiclient-java/pull/23
> Update apiclient getAddress method name

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
* Fixes an issue where Exceptions thrown when initializing an Activity causes the app to hang in an infinite loop
* Fixes an exception when loading an image resource by URL in a debug build of the app
* Fixes a crash on the SeriesTimer screen due to a null user object
> Fix various exceptions

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/model/LogonCredentials.java
- app/src/main/java/org/jellyfin/androidtv/settings/SettingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/startup/SelectServerFragment.java
- app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
- app/src/main/res/values/strings.xml
- app/src/test/java/org/jellyfin/androidtv/util/UtilsTest.java
* Updates location of `GsonJsonSerializer`
* Refactors server sign in code to remove duplication and consolidate code in `AuthenticationHelper`
* Adds minimum server version check since the apiclient no longer supports servers earlier than 10.3.0.
**Depends on: https://github.com/jellyfin/jellyfin-apiclient-java/pull/27**
> Server sign in updates

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es-rMX/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-kk/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt-rPT/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Removes the poorly implemented logic to default the server port to 8096 if not specified.
> Remove default port

- app/src/main/res/values-mn/strings.xml
Fixes an issue with string formatting that is causing a build error
> Fix string formatting

- app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java
- app/src/main/res/values/strings.xml
Hi there,
I took a quick stab at #81. I was a bit unsure at which position to insert the row in the different modes, but hope this is fine.
Cheers
> Added Latest TV Shows to Home Fragment

- app/src/main/res/values/array.xml
This is in response to #115, which asked for bitrate options up to 120 Mbit/s.
> Added more bitrate options

- app/src/main/res/layout/audio_delay_popup.xml
- app/src/main/res/layout/channel_header.xml
- app/src/main/res/layout/display_prefs.xml
- app/src/main/res/layout/guide_filter_popup.xml
- app/src/main/res/layout/guide_options_popup.xml
- app/src/main/res/layout/live_tv_guide.xml
- app/src/main/res/layout/new_program_record_popup.xml
- app/src/main/res/layout/program_detail_popup.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
* Fixes transparent popup backgrounds and grey text color as reported in #197
* Adds support for translating additional strings
> Fix style issues and untranslatable text

- CONTRIBUTORS.md
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Also adding myself to CONTRIBUTORS.md now, as this ate way too much time :D
> Upgrading Gradle Version to 5.4.1

- app/src/main/java/org/jellyfin/androidtv/base/BaseActivity.java
- app/src/main/java/org/jellyfin/androidtv/browsing/CustomBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/details/ExpandedTextActivity.java
- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/details/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/integration/RecommendationBuilder.java
- app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/presentation/HorizontalGridPresenter.java
- app/src/main/java/org/jellyfin/androidtv/search/MySearchFragment.java
- app/src/main/java/org/jellyfin/androidtv/search/MySearchFragmentNoSpeech.java
- app/src/main/java/org/jellyfin/androidtv/startup/DpadPwActivity.java
- app/src/main/java/org/jellyfin/androidtv/startup/SelectUserActivity.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/AudioDelayPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/DisplayPrefsPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/HorizontalGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
Fixes most deprecations warnings from android/androidx. Each change was tested and the behavior is still the same in my atv emulator.
> Deprecation fixes

- app/build.gradle
- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
> Add ACRA for crash reporting

- README.md
Also adds additional links and some text about translations (copied from web repo)
Ideally the two download badges should be aligned horizontally but the play store image contains margins so it doesn't look good.
> Add downloads to README

- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/search/SearchRunnable.java
make categories in search always show in the same order and split Series + Episodes
The order is just my personal preference so if someone wants to change that it would be fine :)
> Search enhancements

- app/src/main/java/org/jellyfin/androidtv/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentFooterRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentRow.java
- app/src/main/res/layout/activity_home.xml
This restores some missing buttons for Live TV that were removed by the home section changes. I moved those buttons and the guide button to a separate row to reflect the web ui.
> Add HomeFragmentRow for live tv buttons

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/DetailsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/details/DetailsDescriptionPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/EpisodeDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/Episode.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemDtoExtensions.kt
Basically a very rough draft of an idea on how to structure this. Sorry for my bad Kotlin :D
Basically only works when selecting an Episode of a Show in Up Next
> Initial structure idea for the redesign of the FullDetailsActivity

- app/src/main/java/org/jellyfin/androidtv/details/EpisodeDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/details/actions/ActionID.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/BaseAction.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/PlayFromBeginningAction.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/PlaybackAction.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/ResumeAction.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/Episode.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemDtoExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelperExtensions.kt
- app/src/main/res/values/strings.xml
Basically we now have Play and Resume buttons that work, but the way they work is ugly.
I think we may need to re-think the item types and model them into a class structure as on the server where they have a common inheritance root, before this can become prettier
> Added play and resume actions

- app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/DetailsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/details/DetailsDescriptionPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/EpisodeDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/MovieDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/ImageCollection.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/MediaInfo.kt
- app/src/main/java/org/jellyfin/androidtv/util/CollectionUtils.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemDtoExtensions.kt
Goal is to create a reference implementation for details by creating the movie details page.
Also changes some other things
> Movies details

- app/build.gradle
I don't know why Jitpack is having trouble with building but it seems like it finally worked!
edit: Jitpack is still failing and continuously removing the build and building it again...
> Set apiclient version to 0.5.0

- .gitattributes
I don't know of a good way to test this, so hopefully it will work! :crossed_fingers:
> Add merge rule to (hopefully) avoid conflicts in weblate

- app/src/main/java/org/jellyfin/androidtv/constants/HomeSectionType.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.java
> Fix default home sections not used when the user partially changed them

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
> Fix crash on empty server address

- app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
Cherrypicked from #251 from @Florianisme 
Fixes #297
> Fix wrong last position when media player is closed and progress still reported

- app/src/main/java/org/jellyfin/androidtv/base/IItemClickListener.kt
- app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/ChapterInfoPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/MovieDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/PersonPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/PlaybackAction.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/ChapterInfo.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/ImageCollection.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt
- app/src/main/java/org/jellyfin/androidtv/util/PlaybackUtil.kt
Basically very similar to the Persons
> Chapter cards

- app/src/main/java/org/jellyfin/androidtv/details/ChapterInfoPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/ItemPosterPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/MovieDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
We probably need new Images as fallback though, the current ones I'm referencing here are super ugly :D
> Implementation of Similar Items row

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.java
- app/src/main/java/org/jellyfin/androidtv/ui/GenreButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/ImageButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/TextButton.java
> Revert "Remove androidx.appcompat dependency"

- .gitignore
- app/src/main/java/org/jellyfin/androidtv/details/ChapterInfoPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/ItemPosterPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/PersonPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/presentation/MultiBadgeImageCardView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/MultiBadgeImageCardView.kt
- app/src/main/java/org/jellyfin/androidtv/util/NumberExtensions.kt
- app/src/main/res/layout/multi_badge_image_card_view.xml
This introduces a new CardView that can have badges in six locations.
> Add MultiBadgeCardView

- app/src/main/java/org/jellyfin/androidtv/details/ItemPosterPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/ui/FavoriteBadge.kt
- app/src/main/java/org/jellyfin/androidtv/ui/MultiBadgeImageCardView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/WatchedBadge.kt
- app/src/main/res/layout/badge_watched.xml
When displaying an unwatched count, it currently is off-center to the left :/
> Implement basic badges

- app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java
- app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
Tells the server it allows messages and shows them to the user when an admin decides to annoy the user.
> Add ability to annoy users from server

- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/playback/nextup/NextUpActivity.kt
- app/src/main/java/org/jellyfin/androidtv/playback/nextup/NextUpFragment.kt
- app/src/main/java/org/jellyfin/androidtv/playback/nextup/NextUpItemData.kt
- app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt
- app/src/main/res/layout/fragment_next_up.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
**Added**
- Ability to disable "Up Next" screen
- Now shows the logo in "Up Next" screen
**Preview**
Closes #350
> Disable Up Next and show logo

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
Upgrades ExoPlayer to the latest version (as Amazon finally updated it).
> Upgrade Exoplayer to version 2.11.3

- app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java
- app/src/main/res/layout/vlc_player_interface.xml
* Fix whitespace rendering issues in subtitles
* Remove position calculation
* Improve styling of subtitles
* Normal weight font instead of bold
* Use a less huge font size
* Use background color instead of shadow
* Left align multiple lines
> Improve subtitle rendering

- app/src/main/java/org/jellyfin/androidtv/playback/overlay/LeanbackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/playback/overlay/VideoPlayerAdapter.java
> New overlay: code cleanup, fixes and general enhancements

- app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.java
My first time doing this in the few months of programming experience I have, sorry in advance if I did it incorrectly.
Added the enter_manually button to the end of the user list regardless of the amount of users it retrieves. I was able to test it on my Android TV emulator but its really laggy and wouldn't do much once I got past the manually entered user. I'd appreciate any advice on this and am willing to improve the code.
> Add enter_manually button to users list

- app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.java
Fixes a NPE when clicking on user login buttons because `getGridButton()` returns null
> Fix user login buttons

- app/src/main/java/org/jellyfin/androidtv/details/fragments/BaseDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/EpisodeDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/MovieDetailsFragment.kt
Fixes the linter issues introduced by #434 after rebasing the details branch.
> Use `requireContext()` instead of `context!!`

- app/src/main/java/org/jellyfin/androidtv/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/HorizontalGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- Allow HTML in the descriptions while browsing
- Change all places that use HTML to use our utility function for better compatibility
- Update the sorting options in the grid view to match [jellyfin-web](https://github.com/jellyfin/jellyfin-web/blob/e58ce96df120123004c96404daa8936414f75608/src/controllers/shows/tvshows.js#L242-L268)
> Misc fixes in grid browsing view

- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
I guess this is pretty self explanatory
> Focus resume button when returning from playback and it's visible

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/media_playback.md
- .github/PULL_REQUEST_TEMPLATE/default.md
**Changes**
- Add 3 issue templates: bug, feature & playback issue
- Add 1 pull request template (this PR uses it!)
- Add issue template config to provide link to our documentation
**Issues**
- Fixes #436 
Note:
- Added a new label "playback" to the repository for the playback template, this label should be used for issues related to playback
> Add issue and pull request templates

- app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
**Changes**
Change the max static bitrate from 30 Mbit/s to 100 Mbit/s (same as the android app). We could also put it higher like the main project (140 Mbit/s) but I don't have media that have more than 100 Mbit/s to test.
**Issues**
Fix #414
> Set higher max static bitrate

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/base/BaseActivity.java
- app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/presentation/ChannelCardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/presentation/GridButtonPresenter.java
- app/src/main/java/org/jellyfin/androidtv/presentation/InfoCardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
**Changes**
- Remove more usages of the currentActivity property in Tvapp
- Replaced the "showMessage" calls with toasts (I don't think I ever saw one of these messages lol)
- Some miscellaneous cleaning (formatting/removing unused functions) in the smaller files I touched
**Issues**
**Notes**
- Unfortunately the usages now left are a lot harder to fix (needing activity instance in views for example)
- I did not touch the usages inside the playback code
- Most changes have their own commits
> Remove some currentActivity usages

- app/build.gradle.kts
**Changes**
- Pin the version of the apiclient to 0.6.0 (latest) so changes in the master branch won't break the builds
**Issues**
- None
> Pin the apiclient version to 0.6.0

- .editorconfig
**Changes**
- Added the "root" property to the editorconfig file as it was missing
**Issues**
> Add "root" property to editorconfig

- app/build.gradle.kts
Should fix the Azure errors
**Changes**
- Remove hardcoded NDK version
**Issues**
> Remove hardcoded NDK version

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/querying/DataRefreshService.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Even more cleaning in `TvApp.java`!
**Changes**
Moved:
- lastDeletedItemId
- lastPlayback
- lastMoviePlayback
- lastTvPlayback
- lastLibraryChange
- lastVideoQueueChange
- lastFavoriteUpdate
- lastMusicPlayback
to a new class that just holds those values called "DataRefreshService". I also changed all types to long (although an Instant would've been better)
Removed:
- isPlayingVideo()
- stopPlayback()
- pausePlayback()
- unPausePlayback()
- playbackNext()
- playbackPrev()
- playbackSeek()
- playbackJump()
- playbackJumpBack()
And added their implementation to their only callside; the TvApiEventListener
**Issues**
> Tvapp can get even more cleaner

- app/src/main/java/org/jellyfin/androidtv/details/DetailsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/details/actions/PlaybackAction.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/AlbumDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/ArtistDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/BaseDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/EpisodeDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/fragments/MovieDetailsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/details/presenters/DetailsOverviewPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/presenters/SongPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/presenters/VerticalListRowPresenter.kt
- app/src/main/java/org/jellyfin/androidtv/details/rows/DetailsOverviewRow.kt
- app/src/main/java/org/jellyfin/androidtv/details/rows/VerticalListRow.kt
- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt
- app/src/main/java/org/jellyfin/androidtv/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/FullHeightView.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemDtoExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
- app/src/main/res/drawable/list_item_background.xml
- app/src/main/res/layout/list_item_song.xml
- app/src/main/res/layout/row_vertical_list.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
> Music album details

- app/src/main/java/org/jellyfin/androidtv/preferences/ui/UserPreferencesFragment.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
**Changes**
Adds the device model to the "About" section of app settings under the app version. This can be useful information for debugging.
**Issues**
N/A
> Add device model to app settings about section

- app/src/main/java/org/jellyfin/androidtv/browsing/StdBrowseFragment.java
**Changes**
Fixed a crash when changing theme. This was probably introduced in my previous PR that changed some backgroundManager logic
**Issues**
> Fix crash when changing theme

- app/src/main/java/org/jellyfin/androidtv/details/PhotoPlayerActivity.java
**Changes**
- Fixed images not loading (introduced in #490)
- Fixed back button not working (introduced in #458)
- Extend FragmentActivity instead of BaseActivity
- Small cleanup in the PhotoPlayerActivity
> Fix photo viewer not working

- app/src/main/java/org/jellyfin/androidtv/playback/overlay/CustomPlaybackTransportControlGlue.java
- app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/preferences/ui/ButtonRemapDialogFragment.kt
- app/src/main/java/org/jellyfin/androidtv/preferences/ui/ButtonRemapPreference.kt
- app/src/main/java/org/jellyfin/androidtv/preferences/ui/UserPreferencesFragment.kt
- app/src/main/res/layout/button_remap_preference.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
The settings show the keyCode right now, that is not very descriptive but I did not find anything that would make it clearer which button is assigned. Also I'm not sure about the naming and texts of the preferences since english is not my native language.
I'm not an expert in android development so any feedback and criticism is welcome!
> add settings to remap tv remote buttons

- app/build.gradle.kts
> Update apiclient to version 0.6.2

- app/src/main/java/org/jellyfin/androidtv/search/SearchProvider.java
- app/src/main/java/org/jellyfin/androidtv/search/SearchRunnable.java
**Changes**
- Search timeout from 1.5 seconds to 600 milliseconds
- Don't query the server for the same input twice
- Always show search results, even if one or multiple requests failed
**Issues**
Fixes #461
> Search improvements

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/Api16Builder.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/ImageSize.java
- app/src/main/java/org/jellyfin/androidtv/model/compat/StreamBuilder.java
- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/preferences/ui/EditLongPreference.kt
- app/src/main/java/org/jellyfin/androidtv/util/MediaCodecCapabilitiesTest.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
Some try-catch statements silently fail. I added logging statements to those. We can never have enough logs.
**Changes**
- Add a logging statement `Timber.e()` for all catch statements
**Issues**
> Make sure all catch statements in the code log their exception

- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
**Changes**
Fixed a bug introduced in #480 that caused rows to never refresh. The "next up" section on the home screen would never update because of it.
**Issues**
> Fix rows not refreshing after playback

- app/build.gradle.kts
Quick PR to fix the build issues
> Set NDK version to 21.3.6528147

- app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.kt
**Changes**
Fixes position of the "Enter manually" button on the user selection screen.
Minor refactoring of the `ItemRowAdapter`.
**Preview**
**Issues**
Fixes #236
> `Enter manually` button position

- app/build.gradle.kts
> Update apiclient version

- .ci/azure-pipelines.yml
- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/channels/ChannelManager.kt
- app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
- app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
- app/src/test/java/org/jellyfin/androidtv/util/TimeUtilsTest.java
- docker-build.sh
- settings.gradle.kts
**Changes**
This branch includes the following changes for the 0.11.4 release
* #459 
* #349 
* #466 
* #499 
* #539 
* #438 
* #454 
* #525 
* #533 
* #408 
* #407 
**Issues**
N/A
> Release 0.11.4

- app/src/main/java/org/jellyfin/androidtv/playback/nextup/NextUpActivity.kt
**Changes**
This fixes an issue where corrupt images being loaded in the NextUpActivity would cause the app to crash.
**Issues**
N/A
> Fix corrupt images crashing NextUpActivity

- app/src/main/res/values/strings.xml
> Fix weblate bad merge

- app/src/main/java/org/jellyfin/androidtv/ui/shared/AppThemeCallbacks.kt
- app/src/main/java/org/jellyfin/androidtv/ui/shared/ThemeManager.kt
**Changes**
Moves the `ThemeManager` into a more appropriate package
**Issues**
N/A
> Move ThemeManager to proper package

- app/src/main/java/org/jellyfin/androidtv/ui/shared/KeyboardFocusChangeListener.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
**Changes**
This fixes an issue where Android does not close the soft keyboard when the text input view loses focus.
**Issues**
Fixes #167
> Fix keyboard not closing when focus is lost

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
**Changes**
Fixes saving and loading of Live TV settings
> Fix Live TV settings

- app/src/main/res/values/colors.xml
**Changes**
Changes the default card background color to match the grey used throughout the app
**Issues**
N/A
> Update default card background color

- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/ILiveTvGuide.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/res/layout/channel_header.xml
- app/src/main/res/layout/live_tv_guide.xml
**Changes**
Lets the user favorite live tv channels.
- Adds a heart in the channel header for channels marked as favorite
- Adds favorite button in `showProgramOptions` popup
- Long press on channel headers to quick toggle favorite
**Issues**
None
> Adds the ability to favorite live tv channels

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
**Changes**
Fix Live TV tile aspect ratio.
**Issues**
#575 
...you be the judge 😅
> Fix Live TV tiles aspect ratio in CardPresenter.java

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/integration/ChannelManager.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/CustomAction.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/RecordAction.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
**Changes**
* Removes method in TvApp for getting drawables
* Fixes all instances that directly retrieved drawables without using the Compat utilities
**Issues**
N/A
> Use ContextCompat and ResourcesCompat for retrieving drawables

- .ci/azure-pipelines.yml
- app/src/main/res/layout/live_tv_guide.xml
- app/src/main/res/values-zh-rTW/strings.xml
**Changes**
* Adds CI job to run the lint gradle task
* Fixes current lint errors
**Issues**
N/A
> Add Lint CI job

- build.gradle.kts
- gradle.properties
**Changes**
Updates the Kotlin version to current. No migrations were needed.
**Issues**
N/A
> Bump kotlin version

- gradle.properties
**Changes**
Fixes the invalid formatting of the kotlinVersion in gradle.properties
**Issues**
N/A
> Fix invalid formatting of kotlin version

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/di/ActivityLifecycleCallbacksModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
Added new "JellyfinApplication" class that should replace the TvApp class. It extends the old one for now because it's used literally everywhere. We should (slowly) remove functions/properties from the TvApp class and when that's finished remove it.
The JellyfinApplication class contains the minimum code to start the app and shouldn't need much changes in the foreseeable future.
**Issues**
> Add JellyfinApplication class

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
Just updating libvlc :rocket: 
**Issues**
N/A
> Update to latest libvlc release

- app/src/main/res/values-zh-rCN/strings.xml
**Changes**
Fixes a formatting issue recently introduced in the Chinese translations that causes lint to fail
**Issues**
N/A
> Fix formatting issue in Chinese translations

- app/lint.xml
**Changes**
Set "ExtraTranslation" linting rule to warning so we can more generously remove strings.
**Issues**
> Set "ExtraTranslation" linting rule to warning

- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
Quick fix to how we inject the apiclient in the StartupActivity to use the Kotlin method
**Issues**
N/A
> Fix apiclient injection using Java method

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
**Changes**
I broke it in #458 and I just found out.
**Issues**
> Fix back action not working in ItemListActivity

- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupToolbarFragment.kt
- app/src/main/res/layout/fragment_alert_dialog.xml
- app/src/main/res/layout/fragment_toolbar.xml
- app/src/main/res/values-w820dp/dimens.xml
**Changes**
- Use the button from the next_up fragment
- toolbar
- dialogs
- Slightly change positioning in toolbar
**Issues**
> Small UI tweaks in login redesign

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
**Changes**
- Fix crash when using the "Play all" button
- Fix crash when using the "Play Next Up" button
Both are "patches" to make it work, I suspect the underlying issue is a race condition or some other weird spaghetti monster. I've experienced both crashes quite a lot but only now found a way to fix it.
**Issues**
> Fix some crashes when trying to play series

- app/src/main/res/values/colors.xml
- app/src/main/res/values/theme_emerald.xml
- app/src/main/res/values/theme_hotdogstand.xml
**Changes**
- always use `@color/` resources in emerald/hotdog themes
- changed a few colors
- added yellow buttons in hotdog
At some point the default theme should be updated too so everything is consistent.
**Issues**
Closes #629
> Fix theme colors

- app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupToolbarFragment.kt
- app/src/main/res/layout/fragment_toolbar_startup.xml
- app/src/main/res/layout/view_toolbar.xml
**Changes**
- ToolbarFragment is now ToolbarView
- Supports childs in a horizontal linear layout
- StartupToolbarFragment now uses the ToolbarView
- Layout is now XML
**Issues**
Part of #612
> Convert toolbar base to a view

- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
**Changes**
Fixes a crash when playing a series and the end of a season is reached.
**Issues**
N/A
> Fix crash when the end of a season is reached

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/res/layout/new_details_overview_row.xml
**Changes**
Updates the progress bar in the FullDetailsActivity to the new design
**Issues**
I had to play around with padding to push the imageview back down to be close to where it originally was so it may not have exact 1:1 placement compared to before.
> Update the progress bar in FullDetailsActivity to the new design

- .gitignore
**Changes**
- Ignore captures from Layout Inspector
**Issues**
> Ignore captures from Layout Inspector

- app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/preference/constant/RatingType.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/category/general.kt
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java
- app/src/main/res/layout/image_card_view.xml
- app/src/main/res/values/strings.xml
**Changes**
- Adds an option under settings to toggle between Rotten Tomatoes or IMDb for what is shown on the ImageCards.
**Issues**
#584
> Add the ability to change the rating type shown on cards

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/category/authentication.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
**Changes**
- Nullability annotations for functions in TvApp.java
- Moved DataRefreshService to dependency injection
**Issues**
> Move DataRefreshService to dependency injection

- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpState.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/ListServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupToolbarFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginFragment.kt
Depends on #669
**Changes**
- Removed constructor from NextUpFragment
- Refactored the code to use a view model
- Remove constructor from StartupToolbarFragment
- Simple approach by calling a function in the activity
**Todo**
**Issues**
> Remove constructors from fragments

- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
**Changes**
Don't display the "ends at" time when the duration is unknown.
**Issues**
N/A
> Hide end time when duration is unknown

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
Star ratings are showing on UserView cards(My Media cards) if star rating is set in settings. This should not happen.
**Issues**
> Take stars off UserView cards on home screen

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.java
**Changes**
This PR removes all cases where TvApp was stored as class variable. This makes it easier to find all usages and slowly replace them with better options. Using TvApp as singleton is bad practice, we should use dependency injection instead.
**Issues**
> Don't store instances of TvApp

- app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/LegacyAccountMigration.kt
- app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreUser.kt
- app/src/main/java/org/jellyfin/androidtv/auth/model/User.kt
- app/src/main/java/org/jellyfin/androidtv/ui/GridButton.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/startup/ListServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ModelExtensions.kt
- app/src/test/java/org/jellyfin/androidtv/util/apiclient/ModelExtensionsTest.kt
**Changes**
Adds support for user images to the login screen
**Issues**
N/A
> Add user images to login screen

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
**Changes**
Fixes the next up bug, also a NPE with the ends at text
**Issues**
> Fix next up bug

- app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginFragment.kt
**Changes**
Sign in instead of focusing on the ok button in UserLoginFragment
Handle cancel button in UserLoginFragment
**Issues**
> Sign in instead of focusing on the OK button

- app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginFragment.kt
**Changes**
Add editor action listener in AddServerFragment.kt
**Issues**
> Connect to server instead of focusing on OK button

- .github/workflows/merge-conflicts.yml
**Changes**
Adds Github action to label PRs with merge conflicts
**Issues**
N/A
> Add github action to label PRs with merge conflicts

- .github/workflows/merge-conflicts.yml
> Fix merge conflict labeler version

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java
- app/src/main/res/layout/image_card_view.xml
Was experimenting with design changes in the card but I didn't like them. Did some refactoring while I was at it though.
Design/behavior is exactly the same as before.
**Changes**
- Format XML/Java code
- Switch to view binding
- Remove unused branches
- Make it slightly easier to work with the Android Studio designer
**Issues**
> Cardview refactoring

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java
**Changes**
Lines were expecting checkMark
> Check mark name fix

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/di/ActivityLifecycleCallbacksModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsePersonsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericGridActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/UserViewActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/shared/BaseActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/shared/CurrentActivityCallbacks.kt
BaseActivity bad
**Changes**
- Migrate more activities to use FragmentActivity instead of BaseActivity
- Remove a bunch of code from BaseActivity
- Moved the "currentActivity" trash to a callback, still deprecated and should not be used though
- Removed the "onSearchRequested" function
- Not sure if it was even used anywhere, replaced with a search intent filter for now
- Fixed a few small issues with refreshing rows after I changed all of the above
**Issues**
> Remove more code from BaseActivity

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
**Changes**
Adds a null check to fix a crash after closing Display Preferences in the grid view.
> Null check for StdGridFragment

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/search/SearchProvider.java
- app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.java
**Changes**
Requires #703 
**Issues**
#702
> Improve search activity

- app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListDialogFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListPreference.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemEnum.kt
- app/src/main/res/layout/preference_rich_list.xml
- app/src/main/res/layout/preference_rich_list_category.xml
- app/src/main/res/layout/preference_rich_list_option.xml
**Changes**
- Add RichListPreference
- Similar to ListPreference but items can be grouped and use summaries
- Add RichListDialogFragment
- Used to show RichListPreference and ListPreference items
- Use RichListPreference for OptionsItemEnum
- No behavior changes, used to show the changes
Required for auto-login preferences (future PR).
**Issues**
> Rich list preference

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/res/layout/enhanced_detail_browse.xml
- app/src/main/res/layout/horizontal_grid_browse.xml
**Changes**
Removes randomly applied text shadows
**Issues**
N/A
> Remove random text shadows

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomListRowPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomRowHeaderPresenter.kt
**Changes**
Removes the 50% transparency from row headers
**Issues**
N/A
> Fix semitransparent row headers

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/res/drawable/tile_land_folder.xml
- app/src/main/res/values/attrs_tiles.xml
- app/src/main/res/values/theme_emerald.xml
- app/src/main/res/values/theme_hotdogstand.xml
- app/src/main/res/values/theme_jellyfin.xml
**Changes**
Fix the default size of the library image for live tv and playlists and adds a default image with the right ratio
**Issues**
Fixes #530
> Fix live tv library image size

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
**Changes**
- Removed the semi-transparent background that was shown when scrolling down in the FullDetailsActivity.
- Removed junk code
**Issues**
> Remove background from overview row in FullDetailsActivity

- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/ChannelCardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/HorizontalGridPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/InfoCardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/RemoteControlReceiver.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
This is what happens when I'm waiting for other PR's to be merged
**Changes**
**Issues**
> Remove a bunch of static

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
**Changes**
I can't reproduce the bug but i think this will fix #752 
**Issues**
> Fix crash in background service

- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
**Changes**
- Add Next Up channel
- Use the series thumbnail when preferred by the user
- Fix for every episode showing the "Resume watching" message in the Play Next channel
> Leanback channel changes

- app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerFragment.kt
**Changes**
Button was not added when there were no users, fixed that.
**Issues**
Fixes #795
> Fix missing add user button when no users found for server

- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
**Changes**
- Rebuild AuthPreferencesScreen when server is removed
**Issues**
yes
> Rebuild AuthPreferencesScreen when server is removed

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentFooterRow.kt
- app/src/main/res/drawable/tile_switch_user.xml
- app/src/main/res/values/attrs_tiles.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/theme_emerald.xml
- app/src/main/res/values/theme_hotdogstand.xml
- app/src/main/res/values/theme_jellyfin.xml
**Changes**
changed the color too because the green was ugly, it's still ugly now but slightly less ugly.
**Issues**
> Replace logout button with switch user button

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
Fixes episodes displaying as a portrait card if there is no image for the episode
> Display episode cards as 16x9 when no image is present

- app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
- Switch to android DateFormat in addDate function in InfoLayoutHelper
**Issues**
> Switch to android DateFormat in addDate function in InfoLayoutHelper

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.java
- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
**Changes**
Use DiskCacheStrategy.RESOURCE instead of the default AUTOMATIC. Should help to keep more images in cache longer
> Use DiskCacheStrategy.RESOURCE

- app/build.gradle.kts
- build.gradle.kts
- buildSrc/build.gradle.kts
**Changes**
- Use Koin version published on Maven Central
- Prefer Maven Central repository
**Issues**
Part of #839
> Use Koin version published on Maven Central

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
// give some audible feedback
Have you ever heard any of those beep boops?
**Changes**
- Remove the tone generator and beep boops from the code
- 
**Issues**
> Remove the hidden robots from the deep depths of the code

- app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditUserScreen.kt
**Changes**
Wanted to fix the issue where removing a server doesn't update the viewpager but instead just cleaned some code. Behavior doesn't change at all. Just some prettier code.
**Issues**
> Use viewmodel in startup preferences

- app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
- detekt.yml
**Changes**
Adds a workaround for an issue with Koin and Kotlin 1.5
**Issues**
https://github.com/InsertKoinIO/koin/issues/1076
> Add workaround for koin logging issue

- app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt
- app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
- detekt.yml
**Changes**
This is the branch from #847 but now doesn't depend on #853 and doesn't fix the issue at all. It does add more logging which should help find issues in the login flow.
**Issues**
> Add additional logging to ApiBinder and redo asynchronous functionality

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt
**Changes**
Fixes the default state of the DefaultView preference checkbox to be checked when the preference is null
**Issues**
N/A
> Fix default value for DefaultView preference

- app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
**Changes**
Fixes dvdsub support in the exoplayer profile
**Issues**
N/A
> Change subtitle delivery method for dvdsubs in exoplayer

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java
- app/src/main/res/layout/image_card_view.xml
- app/src/main/res/values/colors.xml
**Changes**
Removes the dimming on card text when not focused.
**Issues**
#732
> Remove text dimming on inactive cards

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
Fixes a crash caused by subtitles going out of bounds... whoops :man_facepalming: 
**Issues**
N/A
> Fix subtitles out of bounds crash

- app/src/main/java/org/jellyfin/androidtv/auth/LegacyAccountMigration.kt
**Changes**
Avoid instantiating a json object at each startup if not actually needed
> FIX: unnecessary object at each startup

- detekt.yml
**Changes**
Updates detekt configuration to allow wildcard imports
**Issues**
N/A
> Allow wildcard imports in detekt

- app/src/main/java/org/jellyfin/androidtv/preference/PreferenceStore.kt
- app/src/main/java/org/jellyfin/androidtv/preference/SharedPreferenceStore.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemEnum.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemMutable.kt
**Changes**
Added a new interface that is (right now) only implemented by the SharedPreferencesStore. I want to explore using this for display preferences (stored server side) and possibly others. This PR creates the basis for that.
**Issues**
> Add PreferenceStore interface

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Currently, the switch resolution logic is a tad dumb.
By instance, it ignores resolution, which lead to, e.g. a 4K movie being played in 720p because it happens to be the first reso matching the refresh rate.
This:
- Takes fractional rates into account (e.g. 23.97)
- Ignores resolution lower than the media one
- Takes into account 2:3 rates
- Prefers higher rates
- Rates being equal, prefers resolution closest to the media
> CHG: Be smarter when switching reso

- app/build.gradle.kts
- build.gradle.kts
**Changes**
- Update SDK snapshot version to master-SNAPSHOT
- See jellyfin/jellyfin-sdk-kotlin#264
**Issues**
> Update SDK snapshot version to master-SNAPSHOT

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
- Include specials when queuing subsequent episodes if the server is set to display specials within the seasons they aired in
- Continues playing the next season after finishing the last episode of a season
> Include specials when queuing subsequent episodes

- app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
**Changes**
- Return a boolean from SessionRepository::switchCurrentSession to indicate success
- Same for AuthenticationRepository::setActiveSession
- Check for success in AuthenticationRepository::authenticateUser
- If failed -> require new login or auto-login for users without password
This change fixes the issue where logins would fail when the access token was invalidated by the server.
**Issues**
> Show login dialog when token is invalid

- app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/model/ServerAdditionState.kt
**Changes**
- Add the id of the newly added server to the ConnectedState (ServerAdditionState)
- Required for new UI, backporting now to decrease the UI PR size
**Issues**
> Emit server information after adding it in the ServerRepository

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
Extends the null user handling in PlaybackHelper.getItemsToPlay to cover all queries
**Issues**
N/A
> Improve null handling in PlaybackHelper.getItemsToPlay

- README.md
**Changes**
Moved to a separate Weblate project so had to update the links
**Issues**
> Update weblate links

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
Now properly checks changes and updates only when necessary
**Changes**
- Fix StdGridFragment always refreshing on resume
**Issues**
Fixes #805 (first point, second one already fixed)
> Fix StdGridFragment always refreshing on resume

- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
- Add additional check to prevent an NPE I got while testing something else.
This doesn't really fix the issue but it prevents a crash when playback fails and the app tries it again.
**Issues**
> Close activity instead of crashing when playback fails

- app/src/main/res/layout/view_card_default.xml
**Changes**
- Uses the theme cardRounding value for DefaultCardView
> Use theme rounding value in DefaultCardView

- app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java
- app/src/main/res/layout/clock_user_bug.xml
**Changes**
Changes the clock bug to match the appearance of the toolbar. I think this looks nice, but maybe it's weird to only be able to select the user icon on the home screen? :man_shrugging: 
**Issues**
N/A
> Update clock bug to match toolbar

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
- app/src/main/java/org/jellyfin/androidtv/util/sdk/ApiClientExtensions.kt
**Changes**
- Update SDK version to 1.0.0-beta.8
- Set userId in ApiClient
- Use userId from ApiClient
- Use userId autofill where possible (just one function for now)
**Issues**
> Update SDK to beta 8

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
This is consistent with other apps like YouTube
**Changes**
Fixes a crash when the next up screen would show.
**Issues**
> Don't pause video on activity pause

- .github/ISSUE_TEMPLATE/config.yml
**Changes**
Adds a link to the contact page.
**Issues**
> Add link to contact page in issue template config

- app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
**Changes**
- Build a stream url when direct play url is not http/https
- This fixes the player showing a "format not supported" toast
- For me, in the emulator, this plays audio but video is black because the codec is not supported
- The code is pretty much a copy from direct stream but with the play method changed to direct play
**Issues**
> Fix direct play

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/ui/AudioDelayPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
- app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeToolbarFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.java
- app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
- app/src/main/java/org/jellyfin/androidtv/util/NumberExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.java
**Changes**
* Fixes nullability issues resulting in app crashes
* Marks `TvApp.getApplication()` as nullable as that seems to be a big cause of crashes
**Issues**
N/A
> Fix nullability issues

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/JellyfinGlideModule.kt
- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java
**Changes**
Adds an app module for Glide to manage common configuration options and manage log level
**Issues**
N/A
> Add glide app module for configuration

- app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java
**Changes**
Reverts a breaking change in the nullability changes. I will fix it properly later.
**Issues**
N/A
> Fix crash due to missing context on grid

- app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt
- app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
Catched this issue when my emulator didn't have a network connection
**Changes**
- Catch issues in ApiBinder
- This will fix a crash on startup when auto-login is turned on but the connection fails
- Catch issues in ServerRepository
- This wil fix multiple crashes when a server is unreachable (DNS/Timeouts/etc)
- For this change to be fully effective a newer version (beta10/stable) is required (https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/284). Tested with #985
**Issues**
> Fix app crash on startup when network is unstable

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
- app/src/main/res/layout/vlc_player_interface.xml
**Changes**
* Cleanup CustomPlaybackOverlayFragment
* Update title display
* Moves title and subtitle to the upper left corner where the logo is
* Hides the title if a logo is available
**Movie:**
**Movie with Logo:**
**TV Show:**
**Issues**
N/A
> Update playback overlay layout

- app/src/main/java/org/jellyfin/androidtv/ui/AudioDelayPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/AdjustAudioDelayAction.java
**Changes**
Fixes the position of the audio delay popup so it doesn't show up randomly on the right side of the screen somewhere.
**Issues**
N/A
> Fix audio delay popup positioning

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ZoomAction.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
**Changes**
This seems unnecessary
**Issues**
N/A
> Remove unnecessary createPopupMenu util

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Falls back to the itemTitle text if the logo fails to load in the playback overlay
> Fall back to item title if loading logo fails in playback overlay

- app/build.gradle.kts
> Update SDK to 1.0.0 release

- app/src/main/java/org/jellyfin/androidtv/data/compat/ImageSize.java
This improves memory performance according to the Android linter rule
**Changes**
- Use Double.valueOf
**Issues**
> Use Double.valueOf

- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
- app/src/main/java/org/jellyfin/androidtv/ui/NumberSpinner.java
**Changes**
- Add root when inflating layout
- use `attachToRoot=true` instead of `addView()`
**Issues**
> Add root to NowPlayingBug and NumberSpinner layout inflation

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
**Changes**
* Disables the "smart" screen by default in favor of the grid view
* Fixes some style issues in the DisplayPreferencesScreen
**Issues**
N/A
> Change default screen

- app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationDevice.kt
- app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt
**Changes**
Fixes user information not showing updates on the login screen
**Issues**
N/A
> Fix user information not reflecting updates

- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
- StartupActivity now checks if the action in the launch intent is ACTION_MAIN (opened from launcher)
**Issues**
Fixes #1065
> Fix being unable to switch users

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Reverts my ill-received ff and rw changes. Pulls the FF and RW interval from web settings to make up for it though.
**Issues**
Close #1024
Close #863 
PR #1011 will need to be adjusted to accommodate these changes.
> Revert FF and RW

- app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
**Changes**
Reverts the changes made in #604 since a proper fix for the scaling issue was added in #1096.
**Issues**
N/A
> Restore direct play support for avi with libvlc

- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
This PR does not change behavior of the app unless the new playback module is enabled in preferences.
**Changes**
-  Extend the PlaybackLauncher to now also intercept requests for audio playback.
**Issues**
> Forward audio play requests to playback module

- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
I guess this is something left over from some sort of offline mode? no idea
**Changes**
- Remove isOffline from PlaybackManager (always false)
**Issues**
> Remove isOffline from PlaybackManager (always false)

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
**Changes**
- Update Android Gradle Plugin to 7.0.0
- Changes: https://developer.android.com/studio/releases/gradle-plugin#7-0-0
**Issues**
> Update Android Gradle Plugin to 7.0.2

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Sometimes the PlaybackController would do stuff and then the app crashes because mFragment is null. There's a lot of race conditions in the old playback code so now we're checking for nullability.
**Changes**
- Check nullability for mFragment in PlaybackController
**Issues**
Maybe fixes (partially) #989 🤷‍♂️
> Check nullability for mFragment in PlaybackController

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> Fix wrong key used for "skip back length"

- app/src/main/java/org/jellyfin/androidtv/constant/HomeSectionType.kt
- app/src/main/java/org/jellyfin/androidtv/preference/DisplayPreferencesStore.kt
- app/src/main/java/org/jellyfin/androidtv/preference/SharedPreferenceStore.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/HomePreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/UserPreferencesScreen.kt
- app/src/main/res/values/strings.xml
**Changes**
Add a new preference category "Home" allowing the user to change home sections - no need to do it in jf-web anymore!
**Issues**
> Add preferences UI for home sections

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/searchable.xml
**Changes**
This adds leanback global search support
> Implement global search

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentNowPlayingRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
when queue is changed, remove the nowplaying row and re-add it
**Issues**
now-playing row would only generate once and never update unless audio playback stopped
> Fix now-playing row not updating when queue changes

- .github/ISSUE_TEMPLATE/bug-report-playback.yaml
**Changes**
* corrected typo in playback issue template "reprot" -> "report"
> corrected typo in playback issue template

- app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/model/ServerAdditionState.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/AddServerAlertFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/util/RecommendedServerIssueExtensions.kt
- app/src/main/res/values/strings.xml
This is one of my items I wanted to implement for 0.13. This feature was introduced in the v1.1 version of the SDK. It communicates the issues it found while connecting to a server. See https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/master/docs/migration/v1.1.md#error-reporting-in-recommendedserverdiscovery. I've also made a feature request to the awesome developers of the SDK requesting a new issue type for SSL issues so we don't need the current workaround for it (https://github.com/jellyfin/jellyfin-sdk-kotlin/issues/351).
The UI doesn't look amazing but it works fine, if anyone with UI knowledge wants to improve it; go ahead!
**Changes**
- Communicate "issues" from ServerRepository to UI
- Add helper functions to stringify server issues
- Show issues in login UI
**Issues**
> Implement server connection feedback

- app/src/main/res/values/strings.xml
**Changes**
**Issues**
Fixes #1358
> Fix typo "neccesary" > "necessary"

- app/src/main/java/org/jellyfin/androidtv/constant/CustomMessage.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
- Remove unused RemoveCurrentItem CustomMessage type
- Never send or received
- Remove unused RefreshRows CustomMessage type
- Never received
**Issues**
> Remove unused RemoveCurrentItem and RefreshRows CustomMessage types

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
* else -> sets menu item to hidden
> removed a condition that shouldn't have been added in the buttons row PR

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
Found this one while working on some other stuff. The studio image is loaded but never used. Removing it for a small performance boost.
**Changes**
- Remove unused stuff from MyDetailsOverviewRow
- Remove studio image loading
- Remove getPrimaryImageUrl for StudioDto in ImageUtils
**Issues**
> Remove unused stuff from MyDetailsOverviewRow

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
- gradle/libs.versions.toml
- playback/build.gradle.kts
Nothing special actually
**Changes**
- Upgrade Android Gradle Plugin to 7.1.0
- https://developer.android.com/studio/releases/gradle-plugin#settings-gradle
- Suppress RestrictedApi issues for Leanback library in LeanbackChannelWorker
- Google marked pretty much all of the tvprovider/leanback functions as restricted but theres no other way to use them lol
**Issues**
> Upgrade Android Gradle Plugin to 7.1.0

- .github/ISSUE_TEMPLATE/bug-report-playback.yaml
**Changes**
* added some details to the template
> playback bug report template - changed examples to encourage providing more specific info

- .github/ISSUE_TEMPLATE/bug-report.yaml
**Changes**
* added some details to the template
> bug report template - changed examples to encourage providing more specific info

- gradle/libs.versions.toml
**Changes**
- Update AGP to 7.1.1
**Issues**
> Update AGP to 7.1.1

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/res/values/strings.xml
The `X-Application-Error-Code` header is never sent from the server. Not sure when it was removed though (probably quite some time ago).
**Changes**
- Remove some dead code from itemrowdapdter
**Issues**
> Remove some dead code in error handler from ItemRowAdapter

- app/src/main/java/org/jellyfin/androidtv/ui/AudioDelayPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/DetailRowView.java
- app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
- app/src/main/java/org/jellyfin/androidtv/ui/NumberSpinner.java
- app/src/main/java/org/jellyfin/androidtv/ui/TextUnderButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpButtons.kt
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/HorizontalGridPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.java
Rewrite layout inflation to use view binding in custom views / fragments / activities where possible. Some places I did not convert are live tv related and/or hacks.
findViewById usages went from 169 to 85
**Changes**
- Move to view binding
- Remove a bunch of unused code from changed files
**Issues**
> Move to view binding in most views

- app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GroupedItemsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapPreference.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListPreference.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemUserPicker.kt
- app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Mostly removes experimentalxxx annotations
**Changes**
- Fix various Kotlin warnings
**Issues**
> Fix various Kotlin warnings

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Fixes a bunch of issues caused by #1453.
**Changes**
- Always check if mFragment is null before using it to get a context in PlaybackController
**Issues**
> Check mFragment for null value in PlaybackController

- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
**Changes**
- Lower minimum subtitle size to 10
**Issues**
Fixes #1492
> Lower minimum subtitle size to 10

- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Although exceptions in the worker don't matter too much (it will retry automatically) it's good to write safe code.
**Changes**
- Catch SDK errors in the LeanbackChannelWorker
**Issues**
> Catch SDK exceptions in LeanbackChannelWorker

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* updated changes from #1508 so tvapp getapplication isn't used
> remove tvapp getapplication

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* re initialize `mCurrentPosition` when playback starts from idle so there isn't a chance for the position from the prior session to be reported to the server as belonging to the new session.
* refresh `mCurrentPosition` when stopping so the position is accurate
* reset `mSeekPosition` in `clearPlaybackSessionOptions()` - this is called by `stop()` so it happens when there's a playback error, when going to the next/prev item, or when ending playback
* refactored the subtitle logic in `onPrepared` so that `switchSubtitleStream()` will also be called when subtitles should be disabled (by its parameter == -1). This way "disabling subtitles by default" actually disables subs instead of just not enabling them.
**Issues**
* using the "next" button to skip to the next item during …
> fixed position and subtitle values not being cleared when next item is played

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpItemData.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
- app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
**Changes**
- Fully migrate NextUpActivity to SDK
- Remove unused ApiClientExtensions
- Move BaseItemUtils.getDisplayName to BaseItemExtensions for SDK
- Prefer SDK BaseItem in BackgroundService
**Issues**
> Fully migrate NextUp to SDK

- app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationSortBy.kt
- app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt
🤷 
**Changes**
- Move AuthenticationSortBy to model package
**Issues**
> Move AuthenticationSortBy to model package

- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
**Changes**
- Use more strict sizing in getPosterArtImageUrl and return different size for movie posters
- Values from https://developer.android.com/training/tv/discovery/video-programs#preview_images
- Optimize getResumeItems API call by filtering serverside
- Get resumable movies in getResumeItems call
- Show resumable movies in next up section
**Issues**
> Support resume movies in "next up" integration

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/backup_content.xml
- app/src/main/res/xml/backup_rules.xml
**Changes**
- Add Android 12 backup configuration (backup_rules)
- Add authentication preferences to backups (backup_content)
**Issues**
> Add Android 12 backup configuration

- app/src/main/res/layout/vlc_player_interface.xml
**Changes**
* center align subtitles via XML
**Issues**
* fixes #1565
> center align subtitles

- app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.kt
**Changes**
- Fix ExpandableTextView focusable when text is not ellipsized
**Issues**
> Fix ExpandableTextView focusable when text is not ellipsized

- app/src/test/kotlin/preference/PreferenceStoreTests.kt
**Changes**
- Fix PreferenceStoreTests location (was in java dir with package name dirs)
- Rename PreferenceStoreTest -> PreferenceStoreTest**s** 
- Remove empty line, optimize imports
**Issues**
> Fix PreferenceStoreTests location

- app/src/main/AndroidManifest.xml
See https://developer.android.com/reference/android/R.attr.html#appCategory
**Changes**
- Add appCategory attribute to manifest
**Issues**
Fixes #1578
> Add appCategory attribute to manifest

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.java
TvApp is almost empty... almost
**Changes**
- Move TvApp.canManageRecordings to Utils
**Issues**
> Move TvApp.canManageRecordings to Utils

- app/src/main/java/org/jellyfin/androidtv/data/model/GotFocusEvent.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
🤷 
**Changes**
- Remove unnecessary GotFocusEvent
**Issues**
> Remove unnecessary GotFocusEvent

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerContainer.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
No longer relying on TvApp to remember it, using DI instead.
**Changes**
- Add PlaybackControllerContainer to store PlaybackController instance
**Issues**
> Add PlaybackControllerContainer to store PlaybackController instance

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/constant/LiveTvOption.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
**Changes**
- Move LIVE_TV constants to separate file
**Issues**
> Move LIVE_TV constants to separate file

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/data/querying/StdItemQuery.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Replaced TvApp.getCurrentUser() calls with direct calls to UserRepository.currentUser.
**Changes**
- Remove TvApp.getCurrentUser()
**Issues**
> Remove TvApp.getCurrentUser()

- app/src/main/java/org/jellyfin/androidtv/TvApp.java
- app/src/main/java/org/jellyfin/androidtv/data/model/DataRefreshService.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Move lastPlayedItem to DataRefreshService
- Also uses SDK BaseItemDto now
**Issues**
> Move lastPlayedItem to DataRefreshService

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
**Changes**
- Use BaseItemDto from SDK (converted with ModelCompat)
- Reformat the code a bit
**Issues**
> Use SDK models in PhotoPlayerActivity

- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- app/src/main/res/drawable/btn_focus.xml
- app/src/main/res/drawable/btn_non_focus.xml
- app/src/main/res/drawable/button_default_back.xml
- app/src/main/res/drawable/button_default_disabled.xml
- app/src/main/res/drawable/button_default_highlight.xml
- app/src/main/res/drawable/button_default_normal.xml
- app/src/main/res/drawable/button_icon_back.xml
- app/src/main/res/drawable/button_icon_highlight.xml
- app/src/main/res/drawable/button_minimal_highlight.xml
- app/src/main/res/drawable/button_minimal_normal.xml
- app/src/main/res/drawable/expanded_text.xml
- app/src/main/res/drawable/jellyfin_button.xml
- app/src/main/res/drawable/jellyfin_button_minimal.xml
- app/src/main/res/drawable/txt_focus.xml
Instead of using 20 xml files for each drawable, inline them so it's easier to maintain.
**Changes**
- inline drawable resources
**Issues**
> Inline drawable resources

- app/src/main/res/drawable/popup_menu_back.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/theme_emerald.xml
- app/src/main/res/values/theme_jellyfin.xml
- app/src/main/res/values/theme_mutedpurple.xml
Related to #1696
**Changes**
- Add a custom popup menu style
- Changes based on selected app theme
Muted Purple
Dark
**Issues**
> Update popup menu theme

- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
Removes a local variable only used to access static class members
**Issues**
N/A
> Remove a useless local variable

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginFragment.kt
- app/src/main/res/layout/fragment_toolbar_startup.xml
- app/src/main/res/layout/fragment_user_login.xml
**Changes**
- Add the new splashscreen generated in Jellyfin 10.8 as the background in the login screen
- Use transparent toolbar in startup
No screenshot this time because the unstable server doesn't have a splash screen.
**Issues**
> Add splashscreen to login

- app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java
**Changes**
- Hide channel number from ChannelCardView when null
**Issues**
Fixes #1721
> Hide channel number from ChannelCardView when null

- app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Tested with autologin enabled and disabled and tried switching sessions, everything seemed to work fine.
**Changes**
- Added "state" to SessionRepository indicating what is currently happening
- Watch the state instead of the session in StartupActivity to avoid the splashscreen flickering
**Issues**
> Fix flickering of splash screen when using auto login

- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
**Changes**
* fix playNext start position for ExternaPlayerActivity
* fix some missing null checks and finish() calls
> fix playNext start position for ExternaPlayerActivity

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
- app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.java
- app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
- add AVC "high 10" profile test
- enable AllowVideoStreamCopy, AllowAudioStreamCopy
**Issues**
Allows the server to copy streams and also enables "Hi10" profile playback.
> add AVC "high 10" profile test

- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
**Changes**
loadDiscoveryServers() was never called
fix binding.discoveryServers in wrong scope
**Issues**
Fixes #1789
> Fix server Startup discovery

- app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreServer.kt
- app/src/main/java/org/jellyfin/androidtv/auth/model/Server.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
- app/src/main/res/values/strings.xml
**Changes**
- Save setupCompleted boolean for servers
- Show notification when setupCompleted is false
**Issues**
> Show notification on server screen when server setup is incomplete

- .github/ISSUE_TEMPLATE/bug-report-playback.yaml
- .github/ISSUE_TEMPLATE/bug-report.yaml
**Changes**
- Update server version in placeholder to 10.8.1
- Update client version in placeholder to 0.14.0
- Update instructions for logs
- Remove "render: shell" from logs, the logs are markdown so we can just display as-is
**Issues**
> Update issue template for 0.14

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/GuideOptionsScreen.kt
**Changes**
Persists live tv guide options
**Issues**
None that I could find...
> Fix live tv guide options not persisting

- app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java
- app/src/test/kotlin/util/DeviceUtilsTests.kt
**Changes**
Adds support for the Fire Stick 4k Max
**Issues**
N/A
> Add support for the Fire Stick 4k Max

- app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
**Changes**
- Use clientLogApi.logFileUrl to generate crash report URL
**Issues**
> Use clientLogApi.logFileUrl to generate crash report URL

- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
**Changes**
- Set minimum server version in SDK from ServerRepository constant
**Issues**
> Set minimum server version in SDK from ServerRepository constant

- app/src/main/res/values/strings.xml
Thanks wife
I tried to edit on weblate but looks like editing the source string is disabled?
> Fix typo in source string

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
Fixes the heights of the load more channels buttons in the popup guide while viewing TV
**Issues**
Fixes #1543
> Fix channel load more button size in popup guide

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
> Fix 'Shuffle All' for video playlist

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> Fix 'Play from Here' in video playlists

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
This allows the playback rewrite to play audio
**Changes**
- Forward music play requests to PlaybackLauncher
**Issues**
Part of #1057
> Forward music play requests to PlaybackLauncher

- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Likely fix for https://github.com/jellyfin/jellyfin-androidtv/pull/1939#issuecomment-1208485753
> Handle uninitialized current media position

- app/src/main/AndroidManifest.xml
Not thoroughly tested but I believe this should work without any problems.
**Changes**
- Allow app installation on external storage
**Issues**
Fixes #1955
> Allow app installation on external storage

- app/src/main/java/org/jellyfin/androidtv/ui/shared/AppThemeCallbacks.kt
- app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
Regression of #1607
**Changes**
- Fix ActivityLifecycleCallback calls on Android 9 and lower by checking the Android version
**Issues**
Fixes #1907
> Fix themes on Android 9 and lower

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
**Changes**
- Replace GSON usages in ItemLauncher with kotlinx.serialization
- Replace GSON encoding usages in EnhancedBrowseFragment with kotlinx.serialization
**Issues**
> Replace GSON encoding usages with kotlinx.serialization

- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
- app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
- app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/StreamHelper.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/ModelExtensions.kt
Picked a random file and started migrating it to use SDK models. Ended up quite big because everything is connected.
**Changes**
- Migrate InfoLayoutHelper to use SDK models
- Also a bunch of other files
**Issues**
> Migrate InfoLayoutHelper to use SDK models

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
Migrating code to the SDK can cause some issues
**Changes**
- Fix Live TV guide crashing
- Fix movie items crashing
**Issues**
> Misc crash fixes

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
Slowly but surely we're migrating to the SDK...
**Changes**
- Always use SDK BaseItemPerson and PersonType
**Issues**
> Always use SDK BaseItemPerson and PersonType

- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
**Changes**
- Remove unused ApiEventListener from legacy apiclient
**Issues**
> Remove unused ApiEventListener from legacy apiclient

- app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
**Changes**
- Use SDK SortOrder enum in LibraryPreferences
**Issues**
> Use SDK SortOrder enum in LibraryPreferences

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
- Use SDK in StartupActivity
**Issues**
> Use SDK in StartupActivity

- app/src/main/java/org/jellyfin/androidtv/ui/card/MediaInfoCardView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/InfoCardPresenter.java
**Changes**
- Use MediaStream from SDK in MediaInfoCardView and InfoCardPresenter
**Issues**
> Use MediaStream from SDK in MediaInfoCardView and InfoCardPresenter

- app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
**Changes**
- Remove USE_DOWNLOAD_API from picture viewer
**Issues**
> Remove USE_DOWNLOAD_API from picture viewer

- app/src/main/java/org/jellyfin/androidtv/data/repository/ItemMutationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
It's getting harder to find easy-to-migrate code
**Changes**
- Migrate favorite and played toggles in KeyProcessor to SDK
**Issues**
> Migrate favorite and played toggles in KeyProcessor to SDK

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Fixes some crashes
**Changes**
- Always set base item type on custom base item dto instances
**Issues**
> Always set base item type on custom base item dto instances

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
🤷 
**Changes**
- Fix missing imports causing a build issue
**Issues**
> Fix missing imports causing a build issue

- app/build.gradle.kts
- playback/core/build.gradle.kts
- playback/exoplayer/build.gradle.kts
- playback/jellyfin/build.gradle.kts
- playback/ui/build.gradle.kts
- preference/build.gradle.kts
Required for #2044
**Changes**
- Bump Android compile & target version to 33 (Android 13)
- Sneak in some build.gradle.kts changes for a playback module
**Issues**
> Bump Android compile & target version to 33 (Android 13)

- app/src/main/res/values/theme_jellyfin.xml
There are a few visual issues when focusing certain items, will try to fix those in separate PR's at some point.
**Changes**
- Use appcompat theme as base
**Issues**
> Use appcompat theme as base

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeClickedListener.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/CompositeSelectedListener.kt
Fix a regression of #2078 
**Changes**
- Add proper nullability notation
**Issues**
> Fix crash when selecting or clicking items in grid view

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
> Fix NPE when live tv program is null

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
- app/src/main/res/layout/live_tv_guide.xml
**Changes**
- Use AsyncImageView for Live TV program image
**Issues**
> Use AsyncImageView for Live TV program image

- .github/workflows/app-build.yaml
- .github/workflows/app-lint.yaml
- .github/workflows/app-publish.yaml
- .github/workflows/app-test.yaml
- .github/workflows/gradlew-update.yaml
- .github/workflows/gradlew-validate.yaml
- .github/workflows/repo-merge-conflict.yaml
- .github/workflows/repo-stale.yaml
**Changes**
- Use Ubuntu 22.04
- Use Java 17
- Use Java Temurin distribution
- Use official Gradle setup action
- Use consistent naming scheme
- Use organization check instead of repository check
**Issues**
> Update GitHub actions workflows

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
oops
**Changes**
- Fix blurhash not showing in CardPresenter
**Issues**
> Fix blurhash not showing in CardPresenter

- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
oops 2. Accidentally compared a string with uuid which doesn't work so we never created any episode queues.
**Changes**
- Fix series queueing not working
**Issues**
> Fix series queueing not working

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
**Changes**
- Refactor FullDetailsActivity to fragment
**Issues**
> Refactor FullDetailsActivity to fragment

- app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java
- app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Refactor LiveTvGuideActivity to fragment
- Also migrate to view binding
**Issues**
> Refactor LiveTvGuideActivity to fragment

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
oops 3
**Changes**
- Fix audio player screensaver starting too soon
**Issues**
> Fix audio player screensaver starting too soon

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
Just like #2148 this fixes race condition stuff in java code.
**Changes**
- Check lifecycle state when runnable executes
**Issues**
> Check lifecycle state when runnable executes

- app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
- app/src/main/res/layout/fragment_picture_viewer.xml
**Changes**
- Show picture viewer controls by default
**Issues**
> Show picture viewer controls by default

- app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
Depends on #2169 
The controls in the current video player hide after 3 seconds, I chose 4 seconds for the picture viewer because it felt slightly better. The controls only hide when slideshow is active.
**Changes**
- Automatically hide picture viewer actions after 4 seconds
**Issues**
> Automatically hide picture viewer actions after 4 seconds

- app/src/main/java/org/jellyfin/androidtv/ui/FadeViewSwitcherLayout.kt
**Changes**
- Don't use LibraryDreamService.TRANSITION_DURATION in FadeViewSwitcherLayout
Hardcoding the value for now
**Issues**
> Don't use LibraryDreamService.TRANSITION_DURATION in FadeViewSwitcherLayout

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
**Changes**
- Use fade animation when navigating
**Issues**
> Use fade animation when navigating

- app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
- app/src/main/res/drawable/placeholder_icon.xml
**Changes**
- Add placeholder drawable for ImageProvider
Used when the image cannot be loaded (server offline, no network etc.)
**Issues**
> Add placeholder drawable for ImageProvider

- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
**Changes**
- Add missing displaypreferencesid to JavaCompat FakeBaseItem
**Issues**
Partially fixes #2281
> Fix opening Live TV series timers

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
**Changes**
- Fix not always using SERIES_TIMERS FakeBaseItem
- Fix not using correct destination when opening series timers
**Issues**
Fixes #2281
> Fix crash when opening Live TV series

- gradle/libs.versions.toml
**Changes**
- Use separate version tags for compose compiler,foundation,material and ui.
**Issues**
Fixes build in #2323
> Split compose versions in catalog

- app/src/main/java/org/jellyfin/androidtv/auth/ui/ActivityAuthenticationExtensions.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
**Changes**
- Validate current user from UserRepository in validateAuthentication()
**Issues**
Should fix #2343
> Validate current user from UserRepository in validateAuthentication()

- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
isFolder() returned null which caused a NPE
**Changes**
- Fix crash when opening menu for AlbumArtist
**Issues**
> Fix crash when opening menu for AlbumArtist

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
Fixes #2379
I don't know the semantics of `KEYCODE_DPAD_RIGHT` and `KEYCODE_DPAD_LEFT` so I didn't change them.
> Support fast forward and rewind in audio player

- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
- Fix IndexOutOfBoundsException in setExoPlayerTrack
**Issues**
Fixes #2382
> Fix IndexOutOfBoundsException in setExoPlayerTrack

- playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
- playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
- playback/jellyfin/src/main/kotlin/playsession/PlaySessionSocketService.kt
- playback/jellyfin/src/main/kotlin/queue/item/BaseItemDtoUserQueueEntry.kt
**Changes**
- Use Duration ticks extensions from SDK
**Issues**
> Update playback module with SDK 1.4.1 changes

- app/src/main/res/values/strings.xml
https://github.com/jellyfin/jellyfin-androidtv/pull/2415#discussion_r1096817167
**Changes**
**Issues**
> Update item delete confirm message string

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
When a filter is applied all current items are removed first. Before updating them.
**Issues**
Fixes #2470, #2180
> Fix old items are shown when new filter is applied.

- gradle/libs.versions.toml
This should trigger Renovate to update the version for us
**Changes**
- Add androidx.compose.compiler to libraries section in version catalog
**Issues**
> Add androidx.compose.compiler to libraries section in version catalog

- gradle/libs.versions.toml
Reverts jellyfin/jellyfin-androidtv#2509
> Revert "Update aboutlibraries to v10.6.0"

- app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditUserScreen.kt
- app/src/main/java/org/jellyfin/androidtv/util/BundleExtensions.kt
**Changes**
- Replace deprecated Bundle.get with Bundle.getParcelable
**Issues**
> Replace deprecated Bundle.get with Bundle.getParcelable

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
**Changes**
- Only use BackgroundService.attach() in activites - not in fragments
**Issues**
> Only attach background service in activities

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/res/values/strings.xml
**Changes**
Related web PR https://github.com/jellyfin/jellyfin-web/pull/4344
**Issues**
N/A
> Update "Latest" media labels to be "Recently Added"

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
**Changes**
- Fix app closing when music queue ends
**Issues**
Fixes #2617
> Fix app closing when music queue ends

- app/src/main/AndroidManifest.xml
**Changes**
- Set screenOrientation for PreferencesActivity
**Issues**
This might fix #2626 but I can't reproduce the issue.
> Fix screenOrientation not set for PreferencesActivity

- README.md
**Changes**
- Add F-Droid badge to README
**Issues**
> Add F-Droid badge to README

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
- Use ItemRowAdapterHelperKt.setItems for NextUpQuery in ItemRowAdapter
This will prevent the selected item to reset when you go back to the home screen after watching an item.
**Issues**
> Use ItemRowAdapterHelperKt.setItems for NextUpQuery in ItemRowAdapter

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Fix app crash when playback stop is requested without an active player
**Issues**
Fixes #2653
> Fix app crash when playback stop is requested without an active player

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/res/layout/fragment_picture_viewer.xml
The "keepScreenOn" option is superseded by our custom screensaver implementation.
**Changes**
- Remove old screen locks
**Issues**
> Remove old screen locks

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/search/LeanbackSearchFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/search/TextSearchFragment.kt
**Changes**
- Use context in ItemLauncher
**Issues**
> Use context in ItemLauncher

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/StartupToolbarFragment.kt
**Changes**
- Migrate some activity usages to context
**Issues**
> Migrate some activity usages to context

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
- Use view binding in MainActivity
- Use view binding in StartupActivity
**Issues**
> Use view binding in MainActivity & StartupActivity

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
**Changes**
- Fix PictureViewerFragment using activityViewModel
**Issues**
May fix #2767
> Fix PictureViewerFragment using activityViewModel

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowType.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
**Changes**
- Remove left over search hint code
- Fix some warnings in the changed files
**Issues**
> Remove left over search hint code

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt
**Changes**
- Add the SEASON type to the list of base item types that can use external players
**Issues**
Fixes #2785
> Fix playback of seasons with external player

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
**Changes**
Focus back on versions button when selecting a version, instead of focusing on the summary.
> focus back on versions button when selecting a version

- app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt
- app/src/main/java/org/jellyfin/androidtv/di/PreferenceModule.kt
- app/src/main/java/org/jellyfin/androidtv/preference/PlaybackPreferenceBridge.kt
- app/src/main/java/org/jellyfin/androidtv/preference/PreferencesRepository.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
- playback/core/src/main/kotlin/PlaybackManagerBuilder.kt
- playback/core/src/main/kotlin/PlaybackManagerOptions.kt
- playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
- playback/core/src/main/kotlin/mediasession/MediaSessionService.kt
**Changes**
- Use fast forward & rewind durations from preferences
- Set on login/user change
- Uses a bridge from our preferences options to stateflows
- Expose fast forward/rewind timings to media session
**Issues**
#1057
> Use fast forward & rewind durations from preferences

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
- Fix crash when player controls are auto-hiding while closing the player
**Issues**
> Fix crash when player controls are auto-hiding while closing the player

- app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
**Changes**
- Add more logging to authentication code
- Raise severity level of some authentication logging
**Issues**
Should help debug issues like #2503.
> Add more logging to authentication code

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java
**Changes**
Backports a small bit from #2458 to the release branch.
**Issues**
Fixes #2414, which was accidentally fixed on master by #2458 making it really hard to reproduce.
> Fix horizontal grid position resetting on resume

- app/src/main/AndroidManifest.xml
Regression from #2880, thanks build cache.
**Changes**
- Fix application crash on startup by removing an invalid initializer entry from the manifest
**Issues**
> Fix application crash on startup

- app/src/main/java/org/jellyfin/androidtv/constant/CustomMessage.kt
- app/src/main/java/org/jellyfin/androidtv/integration/dream/model/DreamContent.kt
- app/src/main/java/org/jellyfin/androidtv/ui/navigation/NavigationAction.kt
Kotlin 1.7 feature
**Changes**
- Use data object in sealed interfaces
**Issues**
> Use data object in sealed interfaces

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
**Changes**
- Add music progress to screensaver
**Issues**
> Add music progress to screensaver

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/NotificationsHomeFragmentRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerAddViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerAddFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginCredentialsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt
- app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt
Reviewing without whitespace changes recommended
**Changes**
- Replace flow.collect usages with onEach & launchIn
This is functionally the same but slightly more readable due to less indent
**Issues**
> Replace flow.collect usages with onEach & launchIn

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
- app/src/main/java/org/jellyfin/androidtv/ui/composable/ZoomBox.kt
**Changes**
- Add animation labels for Compose
This hides the warnings that labels are missing and improves support for using the animation editor in Android Studio. Labels don't do anything in runtime.
**Issues**
> Add animation labels for Compose

- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
- Fix crash when location type is null in CardPresenter
**Issues**
Should fix #2930
> Fix crash when location type is null in CardPresenter

- app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt
**Changes**
Fix regression from #2925 using the wrong lifecycle state in NextUpFragment.. doesn't actually cause issues though.
**Issues**
> Fix wrong lifecycle state in NextUpFragment

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
**Changes**
- Always use child fragment manager instead of activity fragment manager
**Issues**
Fixes #2931
> Always use child fragment manager instead of activity fragment manager

- playback/core/src/main/kotlin/mediasession/MediaSessionPlayer.kt
**Changes**
- Fix crash when same item appears in queue multiple times
**Issues**
> Fix crash when same item appears in queue multiple times

- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Always use user provided fast forward and rewind values
**Issues**
Fixes #2529
Fixes #460
> Always use user provided fast forward and rewind values

- app/src/main/res/layout/fragment_audio_now_playing.xml
**Changes**
The progress bar item is now aligned with the buttons,
There is now a lot more space for the song title
> Alignment changes to audio player

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
- app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
- app/src/main/java/org/jellyfin/androidtv/ui/composable/time.kt
**Changes**
- Fix compose deprecations
- with -> togetherWith
- get -> rememberKoinInject
- Use new mutableXStateOf functions to prevent boxing
**Issues**
> Fix compose deprecations

- app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
**Changes**
- Remove old user preference migrations (before 0.15)
**Issues**
> Remove old user preference migrations (before 0.15)

- app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemListViewHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
SDK migrations yay
**Changes**
- Migrate ItemListView to SDK
**Issues**
> Migrate ItemListView to SDK

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncherHelper.kt
**Changes**
- Migrate the left over legacy api usages to helper function using the SDK
- Remove import for legacy BaseItemDto model, add SDK one
**Issues**
> Fully migrate ItemLauncher to SDK

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
- Use series poster in latest row when "prefer series thumbnails" is enabled
**Issues**
Fixes angry Redditors
> Use series poster in latest row when "prefer series thumbnails" is enabled

- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivityHelper.kt
Ok one more
**Changes**
- Migrate ExternalPlayerActivity (mostly) to SDK
- Doesn't cover the playback info stuff because legacy code garbage etc
**Issues**
> Migrate ExternalPlayerActivity (mostly) to SDK

- app/src/main/res/layout/view_row_details.xml
Regression from #2929
**Changes**
- Fix progress bar positioning in view_row_details
**Issues**
Supersedes #3057
> Fix progress bar positioning in view_row_details

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
Used animation API's are no longer experimental!
**Changes**
- Remove unnecessary OptIn annotations
**Issues**
> Remove unnecessary OptIn annotations

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
This issue happened mostly when disabling auto login. If Android re-opens the app from the launcher the app will asynchronously re-authenticate (or not when disabled) and if the home fragment initialization was happening before authentication succeeded it would get `null` as currentUser.
This would cause a crash in one of the helper functions. With this fix applied it will nicely close the home fragment and show the login screen when required.
Unfortunately this doesn't fix all other fragments, but the crash happened most often from the home screen because using the "back" button from that one will "close" the app.
**Changes**
- Wait for the first (not-null) user information in HomeRowsFragment (or timeout of 30 seconds)
**Issues**
Fixes #2947
Fixes #3063
Fixes #3172
Fixes #3161
Fixes …
> Defer home initialization until user info is available

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
Like #3292 but for series and way simpler to implement. Just had to copy some code from the movies section in this giant switch statement over to the series section in this enormous switch statement.
**Changes**
- Show specials for series
**Issues**
https://github.com/jellyfin/jellyfin-androidtv/issues/3009#issuecomment-1881395185
> Show specials for series

- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
**Changes**
Implemented SET_AUDIO_STREAM_INDEX and SET_SUBTITLE_STREAM_INDEX commands by calling associated method on PlaybackController.
> Support setting audio and subtitle streams via remote control

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Removes some stuff from the MediaManager interface now that we only have one implementation.
**Changes**
- Refactor some things
**Issues**
> Simplify MediaManager interface

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamContentNowPlaying.kt
- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHost.kt
- app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
- app/src/main/java/org/jellyfin/androidtv/ui/composable/mediaItem.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt
deprecated things being deprecated
**Changes**
- Replace deprecated rememberKoinInject with koinInject
**Issues**
> Replace deprecated rememberKoinInject with koinInject

- .github/workflows/app-publish.yaml
**Changes**
Updates the secrets and locations to match other projects going forward.
**Issues**
N/A
> Update CI to new repository secrets and layout

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/JavaCompat.kt
**Changes**
- Remove "SeriesTimers" value for collection type as it does not exist and collection type is an enum in 10.9
- Remove some unused clutter
- Use UUID in a place
**Issues**
Backports a few things from #3472
> Remove non existent "SeriesTimers" collection type

- app/src/main/java/org/jellyfin/androidtv/data/compat/AudioOptions.kt
- app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
- app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java
- app/src/main/java/org/jellyfin/androidtv/ui/ItemRowView.java
- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuide.kt
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
- app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
- app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
- app/src/main/java/org/jellyfin/androidtv/util/Utils.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
- Convert a bunch of string usages to uuid
**Issues**
> Use UUID for "itemId" parameters

- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
- app/src/main/res/values/strings.xml
**Changes**
- Split the playback preferences page in two with the first one linking to the second one
- Slightly re-order preferences
**Issues**
> Split playback preferences into normal and advanced screens

- app/src/main/res/layout/fragment_user_login_quick_connect.xml
**Changes**
- Force Quick Connect code to use LTR text direction
**Issues**
Fixes #3552
> Force Quick Connect code to use LTR text direction

- playback/core/src/main/kotlin/mediastream/MediaStream.kt
- playback/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
- playback/exoplayer/src/main/kotlin/mapping/container.kt
- playback/exoplayer/src/main/kotlin/mapping/video.kt
- playback/exoplayer/src/main/kotlin/support/ExoPlayerPlaySupportReport.kt
- playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
- playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
- playback/jellyfin/src/main/kotlin/mediastream/VideoMediaStreamResolver.kt
- playback/jellyfin/src/main/kotlin/mediastream/tracks.kt
**Changes**
- Split ExoPlayer format testing to separate tests for audio and video streams
- Add testing for video streams
**Issues**
Part of #1057
> Add initial video codec testing

- app/src/main/java/org/jellyfin/androidtv/util/sdk/compat/ModelCompat.kt
**Changes**
- Fix ModelCompat crash for media type
**Issues**
> Fix ModelCompat crash for media type

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
Used on homepage and movie/series/music smart screens.
**Changes**
- Migrate "Recently added" to SDK
**Issues**
> Migrate "Recently added" to SDK

- app/src/main/java/org/jellyfin/androidtv/data/querying/GetSeriesTimersRequest.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapterHelper.kt
**Changes**
- Migrate Live TV rows to SDK
Only ones left now are the annoying ones that use paging, setFilters, setSortBy and setStartLetter.
**Issues**
> Migrate Live TV rows to SDK

- app/src/main/java/org/jellyfin/androidtv/data/querying/AlbumArtistsQuery.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcesorHelper.kt
- app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Companion to #3654, this migrates the final usage of ItemQuery to the SDK.
**Changes**
- Migrate "Play first unwatched" to SDK
- Remove unused AlbumArtistsQuery
**Issues**
> Migrate "Play first unwatched" to SDK

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
- app/src/main/res/layout/fragment_picture_viewer.xml
Really just a variety of fixes for bugs found while doing some regular testing.
**Changes**
- Fix NPE in FullDetailsFragment when opening (album) artists
- Fix "shuffle all" not working for albums
- Fix usage of removed androidx.legacy.widget.Space class in picture viewer
**Issues**
> Various small bug fixes

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
wow this playback code sucks to work with
**Changes**
- Fix version menu not showing current version as selected
- Fix PlaybackController not respecting selected media source
**Issues**
Fixes #3675
Fixes #1521
> Fix version selection

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/res/values/strings.xml
**Changes**
- Use a new string "Continue listening" instead of "Continue watching" for the continue listening row
- Remove user id from resume query (not needed)
- Exclude audio books from continue listening row (not supported)
**Issues**
> Improve "continue listening" row

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
idk why it fails, just managed to fix it by not setting the media source. I believe the server is just mocking me.
**Changes**
- Fix Live TV not playing video streams
**Issues**
> Fix Live TV not playing video streams

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
I screwed something up in #3677
**Changes**
- Fix skip to previous/next playback actions
**Issues**
> Fix skip to previous/next playback actions

- app/src/main/res/layout/view_lb_browse_title.xml
**Changes**
- Fix header position in BrowseFolderFragment
**Issues**
> Fix header position in BrowseFolderFragment

- playback/jellyfin/src/main/kotlin/playsession/PlaySessionService.kt
I knew about this bug but forgot to fix it before tagging the 0.17.0-beta.1 release... oh well.
**Changes**
- Fix PlaySessionService no longer reporting to server
**Issues**
> Fix PlaySessionService no longer reporting to server

- playback/exoplayer/src/main/kotlin/support/mediaStreamToFormat.kt
**Changes**
- Add direct play support for WAV audio
**Issues**
Fixes #3734
> Add direct play support for WAV audio

- app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java
- app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
- app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
I might find more later, but here is my initial set of Live TV fixes.
**Changes**
- Fix program card sizes
- Fix NPE in EnhancedBrowseFragment
- Fix NPE in FullDetailsFragment
- Fix NPE in ProgramGridCell
- Fix cast exception in ChannelCardView
- Fix PlaybackController spam refreshing Live TV channels
**Issues**
> Fix various Live TV issues

- app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java
- app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java
I believe these are left overs from the old audio player
**Changes**
- Remove a bunch of unused code from StreamInfo
**Issues**
> Remove unused compat streaminfo code

- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
- playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
Forwardport #3296 from 0.16 to master & 0.17. Causes playback issues.
**Issues**
Fixes #3782
Fixes #3726
> Disable tunneling

- app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackAdvancedPreferencesScreen.kt
- app/src/main/res/values/strings.xml
🤷 
**Changes**
- Remove unused dtsEnabled preference
**Issues**
> Remove unused dtsEnabled preference

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
**Changes**
- Fix NPE when opening Live TV guide for the first time
**Issues**
Fixes #3789
Fixes #3748
> Fix NPE when opening Live TV guide for the first time

- app/src/main/java/org/jellyfin/androidtv/ui/LiveProgramDetailPopup.java
some idiot swapped the function called from the buttons
**Changes**
- Use correct record function in LiveProgramDetailPopup 
**Issues**
Fixes #3805
> Fix record buttons in LiveProgramDetailPopup swapped

- app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt
- preference/src/main/kotlin/Preference.kt
- preference/src/main/kotlin/store/PreferenceStore.kt
- preference/src/main/kotlin/store/SharedPreferenceStore.kt
- preference/src/test/kotlin/PreferenceStoreTests.kt
Needed for an upcoming PR.
**Changes**
- Support float preferences
**Issues**
> Support float preferences

- app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
- app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt
**Changes**
- Strip HTML from descriptions in leanback integration
**Issues**
> Strip HTML from descriptions in leanback integration

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
When the AudioNowPlayingFragment is started it will asynchronously ask the player to play an item. Previously this would almost always finish before the UI was started and thus the correct item would display.
I'm working on some changes related to the queue, in which it would often (50% of the time or so) not finish in time, because the actual item information is not retrieved from the server yet.
**Changes**
- load current item after registering event listener
- Always update item when it changed, even when paused
- Remove "playing" parameter from updateButtons() and read it from media manager directly in implementation
- Misc code cleanup fixes
**Issues**
> Fix AudioNowPlayingFragment showing wrong item in extremely rare cases

- app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/RewriteMediaManager.kt
…
**Changes**
- Fix regression from #3833
**Issues**
> Fix RewriteMediaManager emitting onQueueStatusChanged with a queue when there is no audio items available

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListFragmentHelper.kt
Race condition, especially notable on slow servers
**Changes**
- Check cancellation in loadItem helper to avoid updating non-existent layout
**Issues**
Fixes #3867
> Fix crash when starting next episode

- app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
- playback/media3/exoplayer/src/main/kotlin/ExoPlayerBackend.kt
**Changes**
- Enable constant bitrate seeking
- https://developer.android.com/media/media3/exoplayer/customization#enabling-constant-bitrate-seeking
**Issues**
> Enable constant bitrate seeking

- playback/jellyfin/src/main/kotlin/JellyfinPlugin.kt
**Changes**
- Use device profile builder in jellyfinPlugin
**Issues**
> Use device profile builder in jellyfinPlugin

- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
**Changes**
- Fix channels interpreted as Live TV channels
**Issues**
Fixes #3886
> Fix channels interpreted as Live TV channels

- app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
This updates `DeviceUtils` to include the Xiaomi TV Stick and adds it to the `has4kVideoSupport` function. 
**Issues**
Fixes #2516
>  Update DeviceUtils with Xiaomi TV Stick

- app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/HomePreferencesScreen.kt
We've added some new sections in the last few years so it makes sense to increase the limit.
**Changes**
- Increase amount of home sections from 7 to 10
**Issues**
> Increase amount of home sections from 7 to 10

- app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
Profile related fixes in 10.9.10 improve playback, however users may not be aware of that. Use the upcoming minimum server function to notify users about this version. We'll still support 10.9.0>=.
**Changes**
-Change upcomingMinimumServerVersion to 10.9.11
**Issues**
> Change upcomingMinimumServerVersion to 10.9.11 to encourage updating

- playback/core/src/main/kotlin/queue/QueueService.kt
I forgot to re-introduce queue advancing in #3833. So music would just stop and never advance to the next item. Whoooops.
**Changes**
- Fix queue not advancing
**Issues**
Part of #1057
> Fix queue not advancing

- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
Old one is deprecated
**Changes**
- Update package for Koin viewModel import
**Issues**
> Update package for Koin viewModel import

- app/src/main/java/org/jellyfin/androidtv/ui/composable/LyricsBox.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragmentHelper.kt
- app/src/main/res/layout/fragment_audio_now_playing.xml
**Changes**
- Fix moving focus down from home button in AudioNowPlayingFragment
- Decrease scaling size of active lyric line
- Fix synced lyrics not working in AudioNowPlayingFragment
**Issues**
Fixes #4130 (commit 3)
Fixes #4131 (commit 2)
Fixes #4132 (commit 1)
> Fix some issues with lyrics

- app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
**Changes**
- When getting the image for an audio item, prefer an artist image before album artist images when there is no album image.
**Issues**
> Consider artist images before album artist images

- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseItemDtoBaseRowItem.kt
- app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
Same as #4142 but for names.
**Changes**
- When getting the name for an audio item, prefer an artist name before album artist names.
**Issues**
Fixes #4139
> Consider artist names before album artist names

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Unable to reproduce the issue but this should fix it.
**Changes**
- Fix player crashing when playback failed
**Issues**
hopefully fixes #4149
> Fix player crashing when playback failed

- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.kt
- app/src/main/java/org/jellyfin/androidtv/ui/home/HomeRowsFragment.kt
**Changes**
- Remove runBlocking usage in HomeRowsFragment
**Issues**
> Remove runBlocking usage in HomeRowsFragment

- playback/media3/session/src/main/kotlin/MediaSessionService.kt
Sometimes the network will be unavailable or the artwork URL is invalid, make sure we don't crash when that happens!
**Changes**
- Catch errors when loading MediaSessionService artwork
- Use coroutine instead of a future with a blocking `.get()` call
**Issues**
Fixes #4157
> Catch errors when loading MediaSessionService artwork

- app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemSeekbar.kt
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt
- app/src/main/res/values/strings.xml
**Changes**
- Use percentage seekbar for subtitle text size
**Issues**
Fixes #4173
> Use percentage seekbar for subtitle text size

- app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
- app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt
- app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/integration/provider/ImageProvider.kt
- app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.kt
- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
- app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt
- app/src/main/java/org/jellyfin/androidtv/util/coil/SubsetTransformation.kt
- gradle/libs.versions.toml
**Changes**
- Upgrade to [Coil 3](https://github.com/coil-kt/coil/releases/tag/3.0.0)
**Issues**
> Upgrade to Coil 3

- app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.kt
**Changes**
- Fix subtitle menu not always showing "None" as first item by adding a manual counter instead of relying on the subtitle index (which may be 0)
**Issues**
> Fix subtitle menu not always showing "None" as first item

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Somewhat surprised nobody complained about this, this was the only known issue to me since the first beta 😄 
**Changes**
- Fix player UI not hiding automatically
**Issues**
Fix regression from #4119
> Fix player UI not hiding automatically

- app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Set type `PGSSUB` to transcode when loaded externally.
**Issues**
Fixes #4202
> Really never load PGS externally

- app/src/main/res/drawable/audio_now_playing_album_background.xml
- app/src/main/res/layout/fragment_audio_now_playing.xml
bit of a hack but it's legacy views
**Changes**
- Fix background of album in now playing screen when lyrics are displaying
**Issues**
Fixes #4207
> Fix background of album in now playing screen when lyrics are displaying

- app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsFragmentHelper.kt
**Changes**
- Specify fields in resumePlayback() API request
**Issues**
Maybe fixes #4240
> Specify fields in resumePlayback() API request

- gradle/libs.versions.toml
- playback/core/src/main/kotlin/queue/order/RandomOrderIndexProvider.kt
- playback/core/src/main/kotlin/queue/order/ShuffleOrderIndexProvider.kt
Some androidx packages now require the newer SDK and Google Play will probably require in a bit too.
**Changes**
- Use Android SDK 35 (Android 15)
**Issues**
> Use Android SDK 35 (Android 15)

- app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
- Prevent seeking from crashing app if video info is not initialized yet
**Issues**
Fixes #4344 (for real this time)
> Prevent seeking from crashing app if video info is not initialized yet

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsingUtils.kt
Reverts jellyfin/jellyfin-androidtv#4492
> Revert "Fix filtering not working in collections view"

- app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt
- app/src/main/java/org/jellyfin/androidtv/ui/base/button/Button.kt
- app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonBase.kt
- app/src/main/java/org/jellyfin/androidtv/ui/base/button/ButtonDefaults.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ConnectHelpAlertFragment.kt
Cherry picking some changes from an upcoming branch.
**Changes**
- Add new Button composable
- Move Row from ButtonBase to Button
- ButtonBase is now purely for the "surface" (background color/interaction)
- Add ButtonDefaults, which are the default padding & shape values for buttons
No visual differences.
**Issues**
> Add Button composable

- app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingFragment.java
**Changes**
- Fix crash when trying to update detached AudioNowPlayingFragment
**Issues**
Fixes #4526
> Fix crash when trying to update detached AudioNowPlayingFragment

- app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerUserRepository.kt
- app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
- app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
- app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt
- app/src/main/java/org/jellyfin/androidtv/integration/MediaContentProvider.kt
- app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt
- app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
- app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginViewModel.kt
- app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.kt
- app/src/main/java/org/jellyfin/androidtv/util/sdk/SdkPlaybackHelper.kt
Same as #4548
**Changes**
**Issues**
> Fix some more API calls being made on main thread

- app/src/main/java/org/jellyfin/androidtv/util/sdk/BaseItemExtensions.kt
**Changes**
Adjusted the string building for live TV to include season and episode numbers when available.
**Issues**
Fixes #4337
> Add season and episode numbers for Live TV programs

- app/src/main/java/org/jellyfin/androidtv/integration/dream/composable/DreamHeader.kt
- app/src/main/java/org/jellyfin/androidtv/ui/composable/time.kt
- app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/HomeToolbar.kt
- app/src/main/java/org/jellyfin/androidtv/ui/shared/toolbar/Toolbar.kt
**Changes**
- Fix non-square profile picture in toolbar
- Fix time formatting in toolbar
- Merge duplicate rememberCurrentTime implementations
- Optimize it a bit :)
**Issues**
> Fix toolbar profile picture & time formatting

- app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
- app/src/main/res/anim/slide_bottom_in.xml
- app/src/main/res/anim/slide_top_in.xml
**Changes**
- Replace leanback animations with our own definitions in CustomPlaybackOverlayFragment
Compared to the leanback animation this also adds a fade effect to the slide animations.
**Issues**
Fixes compilation of #6841
> Replace leanback animations with our own definitions in CustomPlaybackOverlayFragment

- app/src/main/java/org/jellyfin/androidtv/ui/browsing/DestinationFragmentView.kt
**Changes**
Handles already running transactions. Not an android expert, but judging from the stack trace this could fix the issue.
**Issues**
#4572
#4441
> Fix crash on startup

- app/src/main/java/org/jellyfin/androidtv/integration/dream/DreamViewModel.kt
**Changes**
- Fix screensaver request loop when there are no items to showcase
**Issues**
> Fix screensaver request loop when there are no items to showcase

- build.gradle.kts
**Changes**
- Replace the Kotlin Gradle Plugin deprecated `kotlinOptions` function with `compilerOptions`
**Issues**
> KGP: replace kotlinOptions with compilerOptions

- app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt
**Changes**
- Fix AsyncImageView.load showing incorrect images on rapid changes
**Issues**
> Fix AsyncImageView.load showing incorrect images on rapid changes

- app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java
Enhance LiveTVGuide Issue #4114
**Changes**
Clicking on the channel name now tunes to the LiveTV channel.
**Issues**
Enhancement #4114
> Start Live TV player when activating channel header

- app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
- Catch API issues in StartupActivity when opening a library
**Issues**
Related #4794
> Catch API issues in StartupActivity when opening a library

- app/src/main/java/org/jellyfin/androidtv/util/speech/speechRecognizer.kt
Voice search would always show the unknown error toast when manually stopped because we used cancel instead of stopListening.
**Changes**
- Fix voice search cancellation showing error toast
- Add more logging
**Issues**
> Fix voice search cancellation showing error toast

- app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt
- app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfile.kt
- app/src/main/java/org/jellyfin/androidtv/util/profile/deviceProfileReport.kt
This PR fixes playback problems (like black screens with Dolby Vision) by making sure unsupported HDR formats are remuxed or transcoded.
**Changes**
- Added codec decoder checks in the device profile for Dolby Vision, HDR10, and HDR10+ support.
**Issues**
~~Fixes #4021~~ See #4892
Fixes #4860
Fixes #4933
**Notes**
- VP9 and HLG checks aren’t included in this PR.
- Tested on several physical devices (HDR emulation hasn’t been reliable). Extra testing and feedback from the community would be super helpful.
> Add HDR capability checks for codecs in device profile

- app/src/main/java/org/jellyfin/androidtv/util/profile/KnownDefects.kt
https://github.com/jellyfin/jellyfin-androidtv/pull/4995#issuecomment-3378375527
**Changes**
- This reverts commit e340b7267abb0875d54c3fa6c743d4a7bb5361ef.
**Issues**
> Revert "Add Google TV Streamer to modelsWithDoViHdr10PlusBug"
