jellyfin/jellyfin-androidtv

app/src/main/java/org/jellyfin/androidtv/model/FilterOptions.java
Fixes the following build time warning due to a missing generic type definition.
```
Note: /home/bill/Projects/jellyfin-androidtv/app/src/main/java/org/jellyfin/androidtv/model/FilterOptions.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
=> Fix missing generic type

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java, app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.java
Resolves #45 
Remove "send log" buttons that no longer work. Tested on Fire TV Gen 2. Removes buttons from both the login and the home screens.
=> Remove send log buttons

build, build.yaml
**Changes**
Makes some minor modifications to better support the wrapping `jellyfin-build` infrastructure. Specifically:
1. Put the output in `../bin` rather than `../`, which is cleaner, and easier to grab from.
1. Add a `build.yaml` configuration listing the available package types. `build` within the repo doesn't use this (yet).
=>  Build improvements for wrapping infrastructure

app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java
The credentials path was updated and moved to a constant but one location was missed. (This is exactly why you should use variables instead of hard coding strings everywhere :man_facepalming:)
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/95
=> Fix credentials path for autologin

app/src/main/java/org/jellyfin/androidtv/browsing/BrowsePersonsFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/ByGenreFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/ByLetterFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/CollectionFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
This should fix an issue reported on [reddit](https://www.reddit.com/r/jellyfin/comments/bdznxn/beta5_androidtv_gray_screen/) where the app would crash if `getChildCount` returned `null` in cases where it is unboxed to an `int`.
=> Fix NPE when getChildCount returns null Integer

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.java, app/src/main/res/xml/preferences.xml
* Fixes NPE caused by `getIsFolder()` returning null value. `getIsFolderItem` coerces null to a boolean value.
* Changes default settings for Live TV to direct play by default
:warning:  This does not fix issues with playing a transcoded live tv stream.
=> Fix Live TV playback

app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
For some reason, having a space in the application name is causing issues with displaying seasons in the app. I'm removing it temporarily until a proper solution can be found.
=> Remove space from application name

app/src/main/java/org/jellyfin/androidtv/itemhandling/BaseRowItem.java
Should fix the crash on startup as reported [on Reddit](https://old.reddit.com/r/jellyfin/comments/c4femc/androidtv_client_does_not_load_after_leaving/).
=> Fix NPE on startup when local address is null

app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
Addresses the following error with libvlc objects not being released. I have not noticed if this actually causes any errors in the client though.
```
org.jellyfin.androidtv.debug E/System: java.lang.AssertionError: VLCObject (org.videolan.libvlc.LibVLC) finalized but not natively released (1 refs)
at org.videolan.libvlc.VLCObject.finalize(VLCObject.java:97)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
at java.lang.Daemons$Daemon.run(Daemons.java:103)
at java.lang.Thread.run(Thread.java:764)
```
=> Fix error when libvlc is not properly released

app/src/main/java/org/jellyfin/androidtv/integration/RecommendationBuilder.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java
Fixes a crash in `RecommendationBuilder` when Jellyfin is in the background. Seems like this may be the cause of #122.
=> Fix crash due to null context in RecommendationBuilder

app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/playback/IPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
This forces the color of subtitles to be white. Without this change subtitles would be rendered black.
=> Fix color of subtitles

app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
This wraps `Arrays.toList()` calls in an `ArrayList` if elements are later added to the `List`. This was causing an exception due to `Arrays.toList()` creating a fixed length `List`.
=> Fix exception due to adding elements to fixed length arrays

.ci/azure-pipelines.yml
* Adds an Azure Pipelines config for building the app and running unit tests
See: https://github.com/thornbill/jellyfin-androidtv/pull/1/checks
@jellyfin/core someone with access will need to set this up on the Azure side.
=> Add Azure Pipelines config

gradlew
Will cause failing builds to abort properly.
=> Set errexit in gradlew

app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
=> Disable DelayedMessage to prevent crash on login

app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
Fixes a regression in the transcode profile causing the app to request an invalid video codec.
See https://github.com/jellyfin/jellyfin-androidtv/commit/5565cbc475412bae4607b3b2c8fd763dddb99f4a#diff-4143bb1939f6bb0e2bc74743e0eae2f5R51
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/180
=> Fix video codec in transcode profile

app/src/main/java/org/jellyfin/androidtv/util/DelayedMessage.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
Follow up on #182 with a proper fix.
Passing `activity.getMainLooper()` to the `Handler` constructor ensures that it has the proper reference to the main UI thread.
=> Fix using DelayedMessage on not the main ui thread

app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
Fixes a crash when the response does not include a server for some reason (invalid url, server offline, etc.).
Refs: #177
=> Fix version check when no servers in response

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/base/BaseActivity.java, app/src/main/java/org/jellyfin/androidtv/search/SearchActivity.java
Fixes an issue where the `onRequestPermissionsResult` callback is never called and the search activity was never displayed if the `RECORD_AUDIO` permission was denied.
cc @joshuaboniface
=> Fix search with denied permissions

app/src/main/AndroidManifest.xml
When I tried running my locally clones version of the Jellyfin Android TV app I wan't able to because I have the stable version installed from the Play Store and this caused a conflict with the recommendation provider. By using the `${applicationId}` variable the key is automatically applied for the current build type (release / debug) of the app.
=> Use ${applicationId} in authorities so the ".debug" prefix is applied while developing

app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
The .switchSubtitleStream() function calls the stop & play functions which will then call the switch function and this ends up looping.
Adding an additional check if the stream we want to switch to isn't the currently used stream prevents this.
=> Fix switching to encoded subtitles causing the video player to hang.

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java
Issue: 
Playlists in music library are missing, only the playlist with the favorites was present.
Fix: 
The playlist query with MediaTypes=Audio dosent return any elements. Removing this argument solves it. This argument also does not exist in the jellyfin-web playlist query.
=> Fixed playlist query

app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
TCL EP66x Android TVs (BeyondTV) are HEVC HDR compatible.
This PR add it on Jellyfin Android TV application.
=> Add HEVC support for BeyondTV

app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Issue: 
Play button on a MusicArtist does not work as intended: Instead of adding all songs into the queue, the queue stays empty.
Fix: 
The get all songs query with ParentId parameter dosent return any elements. Replacing this parameter with ArtistIds solves the issue. I also replaced setIncludeItemTypes parameter with MediaTypes as it is in the query from jellyfin-web.
=> Fixed Play on MusicArtists

app/src/main/java/org/jellyfin/androidtv/playback/AudioEventListener.java, app/src/main/java/org/jellyfin/androidtv/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
'MediaManager.shuffleAudioQueue()' returns while the dialog to replace or
add the queue is showing. This causes the reload of the current queue to
fire before the queue has changed.
I implemented a 'onQueueReplaced' event to fix this.
=> Fix audio queue reload

app/src/main/java/org/jellyfin/androidtv/presentation/MyDetailsOverviewRowPresenter.java
The web version allows HTML in the overview field of movies/tv series/seasons/people etc. but in the app it showed the HTML elements. Changed it to parse the HTML (using Android's built-in html to text spanned parser).
=> Support simple HTML elements in descriptions

app/src/main/res/layout/image_card_view.xml
- Make title and subtitle scroll instead so it's actually readable
- Move the badge down so the title is wider
Best explained with an example:
=> Make title in cards readable

app/src/main/res/layout/image_card_view.xml
This fixes a small display issue where a 1px bar would be shown above the title when it has the marque effect active. See the bar above the "ne" in the following image.
=> Fix top margin on card title

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragmentBrowseRowDefRow.java, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragmentFooterRow.java, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragmentLatestRow.java, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragmentNowPlayingRow.java, app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragmentRow.java, app/src/main/java/org/jellyfin/androidtv/constants/HomeSectionType.java, app/src/main/res/values/strings.xml
I'm currently working on moving my personal library from Plex to Jellyfin and one of the things that annoyed me is that the sections I made in the web version weren't available in the TV app. So I implemented it!
I tried to make it look exactly the same as the web version but some things are still different:
- The library buttons are not implemented as I tried but couldn't find a nice way to implement it
- The "Latest Additions" section is split in the web version with one row for each media type, my implementation shows everything in a single row
- Editing the sections is not supported (I might add it another time in a separate pull request)
It took quite some time to get familiar with this part of the code because I haven't used Java in a few years (I use Kotlin primarily) and the …
=> Add home sections

app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java
Request the focus on the resume button if it is visible, otherwise the play button is focused by default.
Fixes #126
=> Focus resume or otherwise play button by default

app/build.gradle, app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java, app/src/main/res/layout/vlc_player_interface.xml
The goal of this PR is to upgrade ExoPlayer to the latest revision supported by the Amazon port, which is currently [2.10.6](https://github.com/amzn/exoplayer-amazon-port/tree/amazon/r2.10.6). In addition ExoMedia will be removed.
The goal is **not** to refactor the player code. Everything should work as it did before with minimal changes. In the future we should consider rebuilding all player code however.
Current progress:
- Audio playback kinda works, progression is not tracked properly
- Video playback works quite well with some minor issues
=> Upgrade to ExoPlayer 2

.editorconfig, app/src/main/java/org/jellyfin/androidtv/channels/ChannelManager.kt
This method for recommendations is only supported on API level 26 or later, so it was causing a crash on older OS versions.
https://developer.android.com/training/tv/discovery/recommendations-channel
=> Fix ChannelManager crash on older API levels

app/src/main/res/layout/overlay_tv_guide.xml
The `programImage` id did not exist in this layout which caused the release build to fail linting when running `assembleRelease`, but not when running `build`.
=> Fix invalid id reference causing lintVitalRelease to fail

app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es-rDO/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rPT/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sr/strings.xml
Since we can't seem to do this with Weblate. I think the only way forward is to remove these strings and hope the changes get pulled into Weblate before any further edits are made.
=> Remove removed strings

app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.java
Depends on jellyfin/jellyfin-apiclient-java#33
=> Refactor PersonType into a proper enum

app/src/main/res/values-sk/strings.xml
A resource tag appeared in the middle of the resource file after a weblate update which resulted in the build failing.
=> Fix weblate merge error

app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java
Fixes #290 
This PR will stop exoplayer from choosing subtitles on it's own. This fixes the double subtitles or subtitles when none are requested when starting a video.
Changing the subtitle track will still cause issues.
=> Partial fix for subtitles

app/src/main/java/org/jellyfin/androidtv/base/ClickablePresenter.kt, app/src/main/java/org/jellyfin/androidtv/base/IItemClickListener.kt, app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/MovieDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/PersonPresenter.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/BriefPersonData.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt, app/src/main/res/values/styles.xml
Basically this is very much not yet done, but more to verify whether this is an acceptable path to handling item selection, or whether we want to go with a more complex scheme like a custom row that handles its own clicks or each item on its own.
Also, I experimented with square cards and it already did not look good as some actor pictures are off-center, so circle crop would definitely ruin them. Will need to stay in portrait mode.
Another question is whether we would want to use our own layout or not, because to me the default `ImageCardView` seems fine for now.
This is what it looks like currently
=> Implement Cast display for Movies

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/browsing/CustomViewFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/details/PhotoPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/playback/SubtitleHelper.java, app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/presentation/PositionableListRowPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/MediaCodecCapabilitiesTest.java, app/src/main/java/org/jellyfin/androidtv/util/MediaUtils.java, app/src/main/java/org/jellyfin/androidtv/util/RemoteControlReceiver.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
So, turns out that there were a *lot* of incorrect usages of the `ILogger` interface that may lead to crashes due to format string injections via them.
=> Fix broken logger calls

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/playback/PlaybackOverlayActivity.java, app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Applications shouldn't change the device audio except when it's caused by user interaction. The app does not contain any UI elements to do this but we still have code to mute/unmute the device.
This PR removes the `setAudioMuted` method from the `TvApp` class and all references to it.
There is at least one issue in Tracepot that will be solved with this PR.
Maybe fix #309
=> Remove audio mute features

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
This _might_ fix that issue in the `ClockUserView` because I added some missing `finish()` calls.
Was not able to test that properly because I couldn't crash the app (_lol_)
=> Startup activity mess

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
This updates the video player preferences for live tv to use the same method as for regular videos.
=> Use PreferredVideoPlayer enum for live tv preference

app/build.gradle.kts
Cherrypicked from the details branch (needed to fix compile errors).
This configures the Kotlin compiler to use Java 1.8 instead of the default, 1.6, when compiling. This is needed for certain features like inline functions.
=> Set Kotlin JVM target to Java 1.8 (from 1.6) to support inline functions

app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java
Selecting "Shuffle All" when viewing an album would open an `AudioNowPlayingActivity` with no items in the queue.
=> Fix shuffle all option for albums

app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/presentation/HorizontalGridPresenter.java
For some reason selecting a music artist in search results would attempt to open the wrong activity and cause the app to crash. Removing this check for MusicArtist causes it to open the detail activity as expected.
=> Fix crash when selecting a music artist in search results

app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/ImageCollection.kt
The `setItem` was blocking while loading images. With this change the images are loaded in separate threads so content will be shown earlier. It should still get some improvements later on though.
=> Improve image loading

app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/preferences/SharedPreferenceStore.kt, app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preferences/ui/EditLongPreference.kt, app/src/main/java/org/jellyfin/androidtv/preferences/ui/UserPreferencesFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/AudioDelayPopup.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
libVLC audio always seems to be 300ms out of sync from the video. This adds a user preference to adjust that and sets `-300` as the default.
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/144
=> Add default audio delay for libVLC

app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/DetailsDescriptionPresenter.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt
- Poster now stays in the same place (there was no animation when switching position and this was really annoying IMO)
- Removed the properties for `Episode` as they are not used at this moment
- Fixed crashes when properties were set to null
- This can be tested by creating a "garbage" file like `sldfjlksjfkl.mkv`
=> Detail misc

app/src/main/java/org/jellyfin/androidtv/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/querying/StdItemQuery.java, app/src/main/java/org/jellyfin/androidtv/ui/ItemListView.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
Jellyfin adds `ChildCount` to the list of requested fields for particular app names. That is dumb, we should just request the fields we need. I added `ChildCount` to all queries since that seems to be what what was happening server side although it's probably not strictly needed for all of them.
https://github.com/jellyfin/jellyfin/blob/a6f883345f1941bf99db1667e84c1caf0b370479/MediaBrowser.Api/BaseApiService.cs#L157-L171
This will allow us to _finally_ add a space to the app name because that has been annoying me for far too long. :laughing:
=> Add child count to requested fields in queries

app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java
Critical fix for issue with app name displayed on Admin dashboard.
Depends on #360
=> Add space to app name

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt, app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-en-rGB/strings.xml, app/src/main/res/values-es-rMX/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-kk/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt-rPT/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, build.gradle.kts
Simple PR that upgrades the build tools version 3.6.0 (released today!). Some interesting changed for us include:
- The new default packaging tool, this might speed up build times for local development and CI
- Simplified R class generation, this might speed up build times for local development and CI
- Remove resources missing from default configuration, this should help with compile errors when Weblate makes a mistake
[Android release notes](https://developer.android.com/studio/releases/gradle-plugin#3-6-0)
**Note:** We should watch CI for the next few commits to master to make sure everything works fine. Local testing is also needed to make sure no weird errors happen. Although I expect everything to work fine.
**Additional note:** Because of new linting checks some issues in the …
=> Upgrade Android Gradle build tools to version 3.6.0 (latest)

app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java
This fixes a small code smell. The getString() function already supports formatting strings
=> Use string formatter via `getString` instead of `String.format`.

.editorconfig, .gitattributes
It caused issues in Android Studio on Windows where it would "detect" changed files but there were none. git will automatically convert line endings on windows so this should not cause any problems.
=> Remove "end_of_line" rule from editorconfig

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Kotlin 1.3.70 was released today 🎉 
Some changed in the stdlib could be useful for our codebase (Mostly the collection builders). And editing Gradle files should work better now as we're using Kotlin based Gradle scripts.
[Release notes](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/)
----
Gradle 6.2 was released not too long ago 🎉 . The wrapper is now updated to version 6.2.1 (the latest) to keep everything up-to-date.
=> Upgrade Kotlin to 1.3.70

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLatestRow.java
The Latest Books row would just display a never ending loading element. I don't think we have any plans to support book libraries on TVs so let's just exclude them for now. :smile:
=> Add books to excluded types in latest row fragment

app/lint.xml
This PR adds some additional checks to the Android linter that are disabled by default. I look at the reports from time to time to find code smells to fix. Most of our Kotlin code doesn't have any issues at this moment so hopefully the amount of issues will keep going down.
Before adding extra options:
```
Ran lint on variant release: 498 issues found
Ran lint on variant debug: 500 issues found
```
With extra options (Excluding `UnknownNullness`):
```
Ran lint on variant release: 787 issues found
Ran lint on variant debug: 790 issues found
```
With extra options (Including `UnknownNullness`):
```
Ran lint on variant release: 2346 issues found
Ran lint on variant debug: 2349 issues found
```
=> Add relevant linter issues disabled by default

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt
This updates libVLC to the latest version available in the maven repository. In testing, this update fixes the 300ms audio delay, so I changed the default for that to be `0` also. A migration should not be needed since this has not made it into a release yet.
Closes #385
=> Update libvlc and reset default audio delay

app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
Leaving the subtitle delivery method as encode caused external players to crash with .ass subtitles.
=> Update ProfileHelper.java to embed .ASS subtitles in external players

app/src/main/java/org/jellyfin/androidtv/details/DetailsOverviewPresenter.kt, app/src/main/res/drawable/progress_bar_poster.xml, app/src/main/res/layout/row_details_description.xml, app/src/main/res/values/styles.xml
In the future I'd like to use this design in other places too but the margins were causing issues on the `MyImageCardView`.
It's partially based on the next up progress bar (shape) and the MyImageCardView progress bar (color)
=> Show progress on poster

app/build.gradle.kts, docker-build.sh
This was being renamed in the build scripts, but it probably makes more sense to have in Gradle.
=> Update output filename to published format

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/presentation/MyDetailsOverviewRowPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/res/layout/new_details_overview_row.xml
From my understanding Linear Layout doesn't allow for the desired behavior, my proposed changes would include a Google library (Flexbox) that allows the dynamically added text views to wrap into multiple lines.
=> Fix issue #204

app/src/main/java/org/jellyfin/androidtv/details/BaseDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/DetailsActivity.kt, app/src/main/java/org/jellyfin/androidtv/details/DetailsOverviewPresenter.kt, app/src/main/java/org/jellyfin/androidtv/details/DetailsOverviewRow.kt, app/src/main/java/org/jellyfin/androidtv/details/EpisodeDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/MovieDetailsFragment.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/Action.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/AddToQueueAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/DeleteAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/GoToItemAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/PlayFromBeginningAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/ResumeAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/SecondariesPopupAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/ToggleFavoriteAction.kt, app/src/main/java/org/jellyfin/androidtv/details/actions/ToggleWatchedAction.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/BriefPersonData.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/ImageCollection.kt, app/src/main/java/org/jellyfin/androidtv/model/itemtypes/LiftedItems.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt, app/src/main/res/layout/row_details_description.xml, app/src/main/res/values/strings.xml
This draft PR is created early to coordinate work on implementing the new details screens to avoid duplication of work.
Features needed for this Fragment:
If any of these are needed for a different Fragment as well, please tell me and I will implement them first.
=> Implementing EpisodeDetailsFragment

app/build.gradle.kts
It turns out Picasso was actually using OkHttp through reflection. It seems that without it, Picasso was setting up some crazy caching to disk behavior on the default HTTP stack. This caused streams played by Exoplayer to be cached to disk when we updated Exoplayer from 2.10.6 to 2.11.3.
Fixes #417
=> Fix Exoplayer Caching

app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
_**10% more cool**_
Uses the noise drawable used in the "play next" thingy as background for the sidebar in the home screen. This will make the backdrop visible and make the app look 10% more cool.
Before:  
After:
=> Add noisy background for "BrowseHeaders" in home screen

app/build.gradle.kts, build.gradle.kts
I noticed we don't depend directly on the androidx.fragment library but we do use it's classes. It's probably exposed by some other androidx library. I now added it so we can be sure it's the latest version. The updated plugins are just patch version so nothing really changed.
Because the androidx.fragment library got bumped to a newer version additional linter checks are automatically enabled. They pass on master but will fail on the details branch, therefore when this PR is merged I will rebase the details branch and submit a PR for fixing the linter.
=> Add androidx.fragment as direct dependency, update androidx.preference & update kotlin/android plugins

app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
should fix
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at org.jellyfin.androidtv.playback.PlaybackController.getCurrentlyPlayingItem(PlaybackController.java:129)
at org.jellyfin.androidtv.playback.PlaybackController$15.run(PlaybackController.java:962)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
=> Fix NPE when finished playing media

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java
Because we can't always get a proper activity inside this function.
(Sort of needed for #443 to fix a bug)
=> Always replace audio queue

app/src/main/java/org/jellyfin/androidtv/playback/overlay/CustomPlaybackTransportControlGlue.java
When a user presses the subtitle button on the tv remote (KEYCODE_CAPTIONS) and there are subtitles for the currently playing media it will popup the subtitle chooser. It will just pop up on the right edge of the screen and won't show other controls, I tried showing controls but it did not feel as good.
=> Add support for TV remote subtitle button

app/src/main/java/org/jellyfin/androidtv/playback/overlay/LeanbackOverlayFragment.java
This is just a small thing but I found the dark background really annoying, especially when continuing playback and not being able to see much until the controls fade out.
=> Change the background of the control overlay from dark to light

app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java
It often happened to me that after stopping playback on the android tv client I found the media still shown with progress where I stopped it in the Dashboard. After debugging it seems that sometimes the report progress loop would run one more time after the stop method was called. I'm not sure if there is a better method of preventing that, but seeing as the loop right above this one also checks the mPlaybackState I thought this might be fine.
=> Stop progress report if playback was already stopped

app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/playback/PlaybackOverlayActivity.kt
**Changes**
- Cleaned the cleaned code
- When creating the view of the fragment it will now **not** attach to the root ([as it should be](https://developer.android.com/guide/components/fragments#UI))
- This caused a new issue
- Moved the code that created the videomanager and pushed it to the playbackcontroller
- It's now created as soon as the view in the fragment is created ([lifecycle](https://developer.android.com/guide/components/fragments#Creating))
- This also cleans the activity a bit (which is nice because it will be easier to switch to less activities in the future)
**Issues**
- none!
🤡
=> Fix playback activity crashing

app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/browsing/BrowseFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/CustomViewFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/constants/Extras.kt, app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/model/repository/ConnectionManagerRepository.kt, app/src/main/java/org/jellyfin/androidtv/model/repository/SerializerRepository.kt, app/src/main/java/org/jellyfin/androidtv/startup/DpadPwActivity.java, app/src/main/java/org/jellyfin/androidtv/startup/SelectServerFragment.java, app/src/main/java/org/jellyfin/androidtv/startup/SelectUserFragment.java, app/src/main/java/org/jellyfin/androidtv/startup/StartupActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
**Changes**
* Adds a `ConnectionManagerRepository` singleton to handle initialization of the `ConnectionManager`
* Adds `SerializerRepository` singleton to handle the `GsonJsonSerializer`
* Moves initialization of `PlaybackManager` to `TvApp`
* Adds constants for common extras values
**Issues**
N/A
=> Refactor ConnectionManager intialization

app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java
**Changes**
This adds in some new logic to intercept the fast forward and rewind
keys presses if the popup panel is not in view.
If the media playing is not live TV, it will skip forwards or backwards
the appropriate amount of seconds. It will show the overlay as expected]
and then initiate the fadeout timer.
There is also a filter that has been added to only intercept the `ACTION_DOWN` of the keypress. Before, this would cause a fast forward/rewind to be done twice, effectively doubling the intended seek time.
**Issues**
Fixes #351 
I would appreciate any testing on other Fire Sticks, this has only been tested on a Fire Stick 4K.
=> Fix fast forward/rewind not working on Fire Stick

app/src/main/java/org/jellyfin/androidtv/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/preferences/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preferences/enums/GridDirection.kt, app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/res/values/array.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
This adds some more poetry and spaghetti to the grid code to allow vertical grids! A user preference is added and will default to the new vertical view.
**Changes**
- Add new preference "grid direction"
- Can be vertical or horizontal
- Add new vertical grid direction
**Issues**
- Closes #317
=> Add support for vertical grids

build.gradle.kts, detekt.yml
Added Detekt as Gradle plugin. Can be executed via `gradlew detekt` or via the lint task.
It will use the default detekt configuration and options can be overwritten using the `detekt.yml` file.
The maximum amount of issues is currently set to `0` which means it will fail if it finds an issue. Depending on how the pipeline will be configured in #492 this number might change.
=> Add Detekt support

.github/workflows/gradle-wrapper-validation.yml
I'd rather add it using the DevOps Pipeline to stay consistent but unfortunately this action is only available on GitHub.
See: https://github.com/gradle/wrapper-validation-action
=> Add GitHub action to validate the Gradle Wrapper blob

README.md
I suddenly noticed this and it annoyed me.
=> Fix spelling of Nvidia in README

app/src/main/java/org/jellyfin/androidtv/channels/ChannelManager.kt
**Changes**
When using STRM media files, and possibly in other contexts, episode files may be replaced, renamed or otherwise changed in a way that causes Jellyfin to delete stored ffprobe/mediainfo output. However, when this happens user resume data still remains for these episodes, and is sent by Jellyfin to clients normally. Therefore, clients must account for the RunTimeTicks field not being present in the JSON returned by `https://jellyfin.sachk.com/Shows/NextUp` even when the `PlaybackPositionTicks` field is present and non-zero. 
To fix this, I added an extra conditional to ensure runTimeTicks is not null before its value is used to call `setDurationMillis`. This avoids the null pointer error, and seems to entirely resolve this crash.
**Crash log from current master**
```
2020-07-25 …
```
=> Fix crash upon loading resumable episodes without runtime field

app/src/main/java/org/jellyfin/androidtv/util/TimeUtils.java, app/src/test/java/org/jellyfin/androidtv/util/TimeUtilsTest.java
**Changes**
Improved current/resume time formatting from milliseconds
**Preview:**
**Issues**
Fixes #505
=> Fix time format for current and resume time

app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/ILiveTvGuide.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.java, app/src/main/res/layout/overlay_tv_guide.xml, app/src/main/res/values/strings.xml
- Added channel name to info bar for programs with no data.
- Ignore programs that fill time slots that have already been filled by a previous program.
- Change live tv guide from 6 hours to 9 hours of programming to be consistent with non live guide.
- Channel surf using channel headers in live guide
- Long/short press in non-live guide and live guide
- Added full back button handling properly
- Split no program data into 30 minute slots for easier side scrolling
- Fixed favorite programs not sorting to the top when the preference is checked
- ~~When watching live TV the live guide is set to force refresh every 30 minutes, it appears when it is supposed to refresh the loading spinner will not disappear.~~
- None
~~1. Look into channel sorting~~ **My guide data is so bad I can't get good …
=> Live TV improvements

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java
**Changes**
Removes the functionality that pulls the background color of cards from the image being displayed in the card for a more uniform appearance.
**Before**
**After**
**Issues**
N/A
=> Remove color vomit card backgrounds

app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/constant/PreferredVideoPlayer.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/res/menu/menu_details_play_with.xml, app/src/main/res/values/strings.xml
Feature to choose player from the menu where we have play button. I created this because some files play fine on vlc and some play fine on external app. It is better to have such button than going to settings and changing there.
**Changes**
Added play with button next to play button. This button will only be visible if preferred player is set external app.
**Issues**
#561
=> Feature play with button

app/src/main/java/org/jellyfin/androidtv/ui/TextUnderButton.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/res/values/strings.xml
**Changes**
- Add `setContentDescription` to the buttons unlabeled: those to sort the movies/musics, those before the play/resume (put to favorite, mark the media viewed…) and those in the playback overlay.
- Add 3 strings to translate, *lbl_pause*, *lbl_audio_track* and *lbl_subtitle_track*, because I didn't find any string that would have matched.
**Issues**
Fixes #418
=> Fix unlabeled image buttons for accessibility

app/src/main/java/org/jellyfin/androidtv/util/MediaCodecCapabilitiesTest.java, app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
**Changes**
Removes direct play support for avi containers from the libvlc profile. This is a workaround for the "tiny video" bug. I'm uncertain if any avi files direct played correctly since any using the xvid video codec were already being transcoded.
**Issues**
#372
=> Remove direct play support for avi with libvlc

app/src/main/java/org/jellyfin/androidtv/ui/browsing/CustomBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
Fixes an application crash
**Changes**
Fixes resuming activities that use the `prepareBackgroundManager` function. Hurray duplicate code everywhere.
Fun fact: I apparently already fixed this crash in #483 for the home screen.
```
java.lang.IllegalStateException: Already attached to DecorView@22feb4[]
at androidx.leanback.app.BackgroundManager.attachToViewInternal(BackgroundManager.java:676)
at androidx.leanback.app.BackgroundManager.attach(BackgroundManager.java:650)
at org.jellyfin.androidtv.ui.browsing.StdGridFragment.prepareBackgroundManager(StdGridFragment.java:350)
at org.jellyfin.androidtv.ui.browsing.StdGridFragment.onActivityCreated(StdGridFragment.java:180)
at org.jellyfin.androidtv.ui.browsing.BrowseGridFragment.onActivityCreated(BrowseGridFragment.java:22)
at …
```
=> Don't attach the background manager when it's already attached

app/src/main/java/org/jellyfin/androidtv/data/querying/StdItemQuery.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
Add `ItemFields.MediaSources` and `ItemFields.MediaStreams` to more queries so this info will be added to the infoRow in browsing fragments/views
**Issues**
#633
I _think_ this info is now grabbed every where it should be. I do not have collections/box sets though and I have never seen a favorites row so I can not test those.
=> Add MediaSources and MediaStreams to additional queries

app/src/main/java/org/jellyfin/androidtv/base/AuthenticatedUserCallbacks.kt
<font color=red><marquee><blink><h1>Targets the release branch</h1></blink></marquee></font>
This backports the crash dialog fix to the 0.11.x release branch.
=> Fix crash dialog (backport)

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/base/KeyboardFocusChangeListener.kt, app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java, app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/AuthenticationHelper.java
<font color=red><marquee><blink><h1>Targets the release branch</h1></blink></marquee></font>
Included:
- #603 
- #524 
- #604 
- #589 
- #576 
Dropped a few from the list because they we're already added in 0.11.4 (whoops!).
=> Freshly picked cherries for 0.11.5

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
I thought images loaded slow and went to find out why, I don't think this PR changes anything about the performance but I want to think it does.
**Changes**
- Loading the image changed:
- Doesn't use unnecessary Glide options like setting the size or requiring bitmaps because Glide infers this from the view
- Remove the unbind functions, they are useless as the only expensive part of a card is the image which is handled by Glide
**Issues**
=> Optimize image loading in card presenter

app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.kt
**Changes**
I think I broke this a while ago, simply said textviews in the details screens are expandable. This should only be allowed when the textview is overflowing though. This PR makes it so it only allows expansion if the text is not-empty.
**Issues**
=> Disable text expansion for empty textview

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.java
The ChannelManager is an asynchronous background job to update information in the OS. The current implementation relied on the app running and calling the `.update()` function (in the home activity). This PR changes it to use the androidx work manager library so we can start updating the channels when the app is not running. This can hopefully be finished after the new auto-sign in code is merged so it actually works with the app in the background. Since we use Koin for dependency injection I used that as backend for the workers.
**References**
- [Koin release notes explaining workmanager in DI](https://medium.com/koin-developers/whats-next-with-koin-2-2-3-0-releases-6c5464ae5e3d)
- [WorkManager class reference](https://developer.android.com/reference/androidx/work/WorkManager)
- [Work …
=> Convert ChannelManager to work manager

app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
**Changes**
This enables support for HEVC universally. According to [this](https://developer.android.com/guide/topics/media/media-formats#video-codecs) it should be supported on anything running Android 5+ which is the minimum version we support in the app. I did notice that some of the first gen Amazon Fire devices do not support it, so we should probably add some specific exclusions for those.
**Issues**
Should help with #49
=> Enable hevc support universally

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ExpandedTextActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpButtons.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapDialogFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/AlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/ToolbarView.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupToolbarFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginFragment.kt
**Changes**
- Remove Kotlin Android Extensions Gradle Plugin
- Replaced all synthetic uses with findViewById
- Added viewbinding for the NextUpFragment
- Other fragments/views/activities etc. won't be done in this PR, this is purely to show how it works.
I'd like to use viewbinding for everything in the future but this PR focuses on replacing the kotlin extension.
**Issues**
Closes #661
=> Remove Kotlin Android Extensions Gradle Plugin

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
Removes the next up activity from showing up after the intro and trailer videos.
This works by setting intro videos manually to the trailer type and immediately playing the next item in the queue if the current item is a trailer.
This is the default behavior of v0.11
**Issues**
=> Remove NextUpActivity from displaying after intro videos or trailers

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
The watched state wasn't reset properly. I thought the unbind function was useless but the restore functionality is not implemented properly so it would re-use the watched state when the view is used in another place.
Some additional context: When a card from the card presenter is offscreen the card element will be re-used in another row to avoid unnecessary allocations. Unfortunately our code doesn't work properly when it restores a state so this is a fix until we rewrite all presenters.
Also removed some unused code.
=> Partially revert #656

app/build.gradle.kts
Although fixing them is difficult with the 100% static MediaManager, this PR adds LeakCanary so we can start investigating memory leaks in the app.
Because our app is for ATV some things are different from the mobile version;
- Leaks are notified using a Toast
- The "Leaks" app doesn't show up, you need to manually open it using adb
When a leak is found the adb command is logged in logcat:
`adb shell am start -n "org.jellyfin.androidtv.debug/leakcanary.internal.activity.LeakLauncherActivity"`
[LeakCanary docs about ATV](https://square.github.io/leakcanary/recipes/#android-tv)
It will only run in debug builds.
=> Add LeakCanary

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
**Changes**
- You can now mark shows as watched without a stupid popup
- You can just unmark it again if it was not intended, but why would you press the button without intention anyway!?
- Shuffle music is now 10% easier (removed a stupid popup)
- Marking played/unplayed in that hidden menu that nobody knows about was improved too
- I removed the popup
TL;DR: Searched for all "AlertDialog.Builder" instances in the code and picked a bunch that I 100% think should be removed.
=> Remove more unnecessary popups

app/src/main/java/org/jellyfin/androidtv/auth/AccountManagerHelper.kt
**Changes**
Adds some null checks to `AccountManagerHelper` to fix an issue where the app was crashing on launch in the `getAccount()` function.
**Issues**
N/A
=> Add null checks to AccountManagerHelper

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/auth/AccountManagerHelper.kt, app/src/main/res/xml/authenticator.xml
When both the debug and release version are installed on the same device, only the first app that tries to use the authentication store can claim the account type because it was hardcoded to "org.jellyfin.v1". This PR changes it to be based on the application id, which means that the debug and release version use a different type to store the accounts.
Sidenote: since the type changed all currently stored accounts won't be used anymore, you can remove them manually from your device settings.
| flavor   | before | after |
| -------- | --- | --- |
| debug  | org.jellyfin.v1 | org.jellyfin.androidtv.debug |
| release | org.jellyfin.v1 | org.jellyfin.androidtv |
I've also removed the versioning part since that's a pain to support anyway.
**Issues**
=> Fix authenticator store account type

app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/ListServerFragment.kt
**Changes**
The default ObjectAdapter's from Leanback are:
1. Not type safe (no generic used, returns "Any" / "Object")
2. Not null-safe
3. Incompatible with Kotlin collections
To fix this I made a new adapter called the "MutableObjectAdapter". It uses a generic to set the element type, this fixes 1 and 2. It then implements Iterable for 3.
To illustrate the abilities of this new adapter I made some changes in the ListServerFragment that uses it, and while I was at it I changes the behavior of the server list to not reset itself but instead only append.
Items in the adapter now have a id, the Row class in leanback likes to use a Long for that so I convert uuid->long now. I might create a custom row class so we can set the id using generics or something later.
**Issues**
=> Add mutable object adapter

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/authentication.kt
Depends on #684
**Changes**
Removed live tv mode. I think we managed to break it in the auth rewrite as it crashed the app after signing in. I think this feature is useless because it wasn't thought out. You couldn't go back to the home view.
**Issues**
=> Remove live tv mode 

app/build.gradle.kts, gradle.properties
Simple change, will disable LeakCanary by default, we should probably enable it by default after the playback rewrite since most of the leaks come from there.
=> Disable LeakCanary by default and add option to gradle properties to enable

app/lint.xml, app/src/main/res/layout/fragment_search_text.xml, app/src/main/res/layout/vlc_player_interface.xml
> FragmentContainerView replaces the <fragment> tag as the preferred way of adding fragments via XML. Unlike the <fragment> tag, FragmentContainerView uses a normal FragmentTransaction under the hood to add the initial fragment, allowing further FragmentTransaction operations on the FragmentContainerView and providing a consistent timing for lifecycle events.  
> 
> More info: https://developer.android.com/reference/androidx/fragment/app/FragmentContainerView.html
=> Use FragmentContainerView instead of fragment in layout XML

app/src/main/res/layout/horizontal_grid_browse.xml
> When setting text sizes, you should normally use sp, or "scale-independent pixels". This is like the dp unit, but it is also scaled by the user's font size preference. It is recommend you use this unit when specifying font sizes, so they will be adjusted for both the screen density and the user's preference.
=> Use sp unit instead of dp for font size in horizontal_grid_browse.xml

app/src/main/AndroidManifest.xml
> Exported services (services which either set exported=true or contain an intent-filter and do not specify exported=false) should define a permission that an entity must have in order to launch the service or bind to it. Without this, any application can use this service.
=> Don't export AuthenticatorService

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java
**Changes**
Adds the "Series Name S1 E1" text as the subtitle while playing a TV episode. Useful for a quick glimpse at what season and episode you are on without having to back out of your video.
**Issues**
=> Add episode full name as subtitle while playing TV episode

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationDevice.kt, app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt
**Changes**
The server only allows a single authenticated user per device id. To fix this we need to create an unique device id for each session. The server still needs this device id in all requests so the id is based on app-device id + username.
See https://github.com/jellyfin/jellyfin-apiclient-java/pull/174
**Issues**
=> Fix automatic sign out when switching users

app/src/main/java/org/jellyfin/androidtv/util/TextUtils.kt
**Changes**
- Use HtmlCompat in TextUtils String.toHtmlSpanned function.
- Added comment
**Issues**
=> Use HtmlCompat in TextUtils String.toHtmlSpanned function

app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
**Changes**
Removed the warning to enable audio downmixing in the home screen. It only appeared once for new installs. In the future we should auto-detect capabilities (with the playback rewrite) so users don't need to do anything, for now going to the preferences and changing the behavior enum is the way to go.
**Issues**
=> Remove audio behavior warning

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
Set the staticHeight option to `true` for the latest & resume rows used in the home screen. This will make all images in the cards use the same height. Old behavior was especially noticeable when a series poster and episode thumbnail were shown next to each other and in image libraries using different sized images.
**Issues**
=> Enable static height on most home rows

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CustomViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
Finally found out why it didn't work before. The StdBrowseFragment used onActivityCreated because it needs to tweak UI in the activity (lol). Changed it to use the onCreate function for most code (except clock initialization) and now we can disable the headers perfectly fine. I decided to not add a preference to enable/disable the headers because it can't show more than 6 anyway.
**Changes**
- Disable headers on all screens
- Enabling them is not possible when extending StdBrowseFragment
**Issues**
=> Disable headers on home screen

app/src/main/java/org/jellyfin/androidtv/ui/preference/category/general.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/UserPreferencesScreen.kt, app/src/main/res/drawable/ic_flask.xml, app/src/main/res/values/strings.xml
_Finishing old branches_
**Changes**
Adds a new preferences screen, linked to from the default preferences screen for "developer options". It contains 2 (moved) preferences for now:
- Debug flag
Used in some cases to enable extra information in views
- Grid direction
I added this a while back for 0.12 but I don't consider it a proper fix as it contains quite some bugs, moving it to the dev options will mark it as "experimental".
**Issues**
=> Add developer preferences screen

app/src/main/java/org/jellyfin/androidtv/preference/constant/RatingType.kt, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/res/values/strings.xml
**Changes**
- Adds an option to hide the Rotten Tomatoes/IMDb ratings on the home screen cards and the item details page.
=> Add an option to hide ratings on cards/item details

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
When a card is re-used by the presenter it might not set the rating, this would cause the old rating to still show up. This PR fixes it by always clearing the rating.
**Changes**
- Fix rating not clearing properly
**Issues**
=> Fix rating not clearing properly

app/src/main/res/layout/image_card_view.xml
**Changes**
Hide the overlay in cardviews by default, this was previously done in MyImageCard.java but accidentally removed in #744. This PR adds the default visibility back but using the XML (how it should be done).
**Issues**
- https://github.com/jellyfin/jellyfin-androidtv/pull/744#issuecomment-787712008
=> Hide cardview overlay by default

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
**Changes**
Fixed a race condition where backgrounds would appear for items with no backgrounds if the previous backgrounds were still loading.
**Issues**
=> Cancel loading backgrounds on clear

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseScheduleActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/UserViewActivity.kt
The fragment uses the messaging trash in BaseActivity.
**Changes**
- Add check in EnhancedBrowseFragment if the parent activity is a BaseActivity
- Use BaseActivity for all activities (indirectly) using the EnhancedBrowseFragment
**Issues**
=> Fix EnhancedBrowseFragment crash

app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java
**Changes**
The handler crashes the app when navigating quickly, this happens because the activity is closed before the handler activates.
I could've added a simple check for it but it made more sense to remove the handler entirely. 
Because this is the second time I had to work in this file today while working on something else I formatted it and fixed the warnings.
**Issues**
=> Show item info instantly instead of delayed in EnhancedBrowseFragment

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
The necessary types for folders are missing in `BaseItemType` in the current apiclient. This causes the app ui to break due to an exception, so best to disable for now.
**Issues**
N/A
=> Disable folders views because types are missing in the apiclient

app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
Regression from #743
**Changes**
- Use BaseActivity as parent in MainActivity
**Issues**
Fixes #776
=> Use BaseActivity as parent class for MainActivity

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
**Changes**
When activating an item in the "now playing" section on the home screen the app crashed because the menu did some unsafe casting.
**Issues**
=> Fix ItemLauncher crashing due to unsafe casting

app/src/main/res/layout/item_discovery_server.xml
**Changes**
Fixes the text color of the discovered server buttons. For some reason I needed to use `AppCompatImageView` for the `app:tint` to actually work. :man_shrugging: 
**Issues**
N/A
=> Fix discovered server button text colors

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundServiceFragment.kt
**Changes**
- The default background didn't restore properly because a bitmap of the backgroundservice background was saved (whoops)
- The fragment could crash because it didn't have an empty constructor (as is required for fragments)
**Issues**
=> Fix BackgroundService fragment crash and default background not restoring

app/src/main/AndroidManifest.xml
**Changes**
I think this might be a Shield-specific issue, so I couldn't reproduce it (I don't have a Shield). This seems to have fixed it, though.
Edit: ~~Agh, this breaks Dolby Vision in mkv. Dolby Vision in mp4 still works.~~ I take that back, the file was transcoding instead of direct playing. HDR behavior seems the same on my Sony TV and Chromecast with Google TV.
**Issues**
Fixes #782
=> Fix for HDR always being activated

app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MutableObjectAdapter.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerFragment.kt
**Changes**
- Emit users in 2 steps from the ServerRepository; once for stored users and once for stored+public users
Stored users now show up instantly on the server fragment, while previously they only showed up after public users were retrieved (which could take a few seconds depending on the network quality).
It does not cause any flickering or focus changes since the MutableObjectAdapter is used.
**Issues**
=> Show stored users instantly and update row when public users are retrieved

app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java
**Changes**
Replaces the "By Name" header for the row of episodes within a season.
=> Use season name for season row header

build.gradle.kts
**Changes**
- Add `mavenCentral()` as repository
- Move `jcenter()` to the bottom of the repository list
**Notes**
I checked which dependencies we use are not available when jcenter is removed:
- **Koin** 2.x branch is not on Maven Central, 3.x is, it's not a drop-in replacement though and requires some work
- **Jellyfin Apiclient** is not on Maven Central, Kotlin SDK is, so it needs migration
- **Amazon ExoPlayer** port is not on Maven Central, developers have been ignoring issues for months now. Not likely to see updates. We might need to remove it and start using the official ExoPlayer again.
- **LibVLC** is not on Maven Central, developers acknowledge this as an "important" issue but have not moved yet
- ~~**Android Flexbox** is not on Maven Central, developers acknowledge this and …
=> Use Maven Central as primary dependency repository

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
I looked into the sourcecode of Koin and found out that calling the `workManagerFactory()` function instantly initializes the androidx.workmanager library, in some cases this would try to start the workers but those weren't defined. Changing the order of function calls fixed it for me.
**Changes**
- Fixed crash on startup due too race conditions
**Issues**
https://github.com/jellyfin/jellyfin-androidtv/pull/784#issuecomment-808769226
=> Initialize workmanager factory after setting the modules

gradle.properties
**Changes**
Running the linter in #784 locally didn't work because it ran out of memory. I think it's time to increase it (again). Copied the values from the Kotlin SDK and it works great now (at least for me).
**Issues**
=> Use the jvmargs from kotlin sdk to increase memory available to Java process

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
**Changes**
I found a movie with a backdrop that always causes the crash, so testing for it became very easy. This seems to have finally fixed it.
**Issues**
#752
Logs for reference:
<details><summary>Before: GlideException</summary>
```
2021-04-06 16:02:56.647 5034-5314/org.jellyfin.androidtv.debug E/ACRA: ACRA caught a ExecutionException for org.jellyfin.androidtv.debug
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
call GlideException#logRootCauses(String) for more detail
at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
at …
```
=> Change exception type for background service crash

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt, app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentFooterRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/ApiClientExtensions.kt
**Changes**
This PR introduces the "SessionRepository" that manages the current session in the app. It contains two methods to restore the session based on the authentication preferences, these methods are called on application start.
When the session changes it uses a new class "ApiBinder" to configure the apiclient instance. I had to implement a hack to set the "currentUser" in the Application class (couldn't think of a better way unfortunatetely).
The StartupActivity now observes the current session, if a session is found it will wait for the currentUser to be assigned too and switch to the next activity. The splash screen is used to indicate something is happening. If the session is restored on start the startup activity will skip showing the user screen.
The sign out button on the …
=> Implement auto-login and introduce SessionRepository for managing sessions

app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt, app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
**Changes**
- Fix infinite loading issue when the apiBinder fails to set the currentUser property in TvApp.
It's kind of a hack until we fully migrate to the Kotlin SDK and remove the currentUser property entirely.
**Issues**
- https://github.com/jellyfin/jellyfin-androidtv/pull/784#issuecomment-813879511
=> Cancel setCurrentSession call if the UserDto cannot be retrieved

app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt
**Changes**
Fixes an issue that slipped through in #808. I think it makes sense to return true here since the value of `currentUser` is updated. :man_shrugging: 
**Issues**
N/A
=> Fix null session causing app to hang

app/src/main/java/org/jellyfin/androidtv/ui/shared/AlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/KeyboardFocusChangeListener.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerScreenFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginAlertFragment.kt, app/src/main/res/layout/fragment_alert_add_server.xml, app/src/main/res/layout/fragment_alert_dialog.xml, app/src/main/res/layout/fragment_alert_user_login.xml
**Changes**
- Alerts don't use the constructor anymore, now Android can correctly resume the fragments
- Alerts now use view binding for type safe layouts
- (child-)Alerts now use XML layouts
- AlertFragment is now easier to extend and work with
- Fixed the "next focus" not going to the confirm button correctly
**Issues**
I think there was one but I can't find it...
=> Rewrite login alerts

app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java, app/src/main/res/layout/image_card_view.xml
**Changes**
- Fixed a crash in the async setupQueries() function by checking for coroutine cancellation.
- Fixed logo position after changing theme
- Also removed the width constraint so it will be displayed slightly more to the right
- Rename `title_text` id in image card view to just `title` because `title_text` is used by the leanback logo and caused crashes (lol)
**Issues**
Fixes #812
=> Fix crash in home when changing theme

app/src/main/AndroidManifest.xml
**Changes**
Removed labels for activities in the manifest. According to the Android documentation the app name will be used if it's not set.
https://developer.android.com/guide/topics/manifest/activity-element#label
**Issues**
=> Remove activity labels

app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
**Changes**
For the vertical grid:
- Adjust column size for thumb and banner views
- Decrease heights of medium posters (175 -> 171 dp) and large posters (210 -> 202 dp) to fit another item in each row
- Setting the image size preference to Default (used to be named Auto) now chooses the correct column size for the image size that gets used
=> Adjust card and column sizes for vertical grid

app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt
**Changes**
The displaypreferencesscreen didn't save anything on the server, now it does
**Issues**
Fixes #822
=> Fix DisplayPreferencesScreen not saving the preferences

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
**Changes**
I couldn't reproduce the issue but I switched the formatting to use android's DateFormat class. This is consistent with other parts of the app (like FullDetailsActivity).
**Issues**
Fixes #819
=> Switch to android DateFormat for "ends at" time in playback overlay

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
Sets the height of the first episode of the next up row of the main item details page to 260 to match the rest of the episodes in the row.
**Issues**
The first episode was 300 while the rest were 260, causing the episode to appear larger and the row height to change as the episode was scrolled off screen.
=> Fix height of first episode of next up row in the main item details page

.github/dependabot.yml
**Changes**
- Add Dependabot for GitHub Actions updates
- Mostly copied from jellyfin-sdk-kotlin (originally added by @h1dden-da3m0n)
**Issues**
=> Add Dependabot for GitHub Actions updates

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
**Changes**
Big brain in this part of the code caused a crash because genres is null but we didn't check for it in the addGenres function.
https://github.com/jellyfin/jellyfin-androidtv/blob/29c671164b036e51da55602b173abcb4bc5377a4/app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java#L336-L367
**Issues**
=> Fix crash when genres in baseitem is null

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
I'm watching a show where each episode is around 1 minute and 50 seconds. The details page said rounded it down to "1 min". It makes more sense to always round up.
**Issues**
=> Always round up in runtime calculation

.ci/azure-pipelines.yml, .github/workflows/app-lint.yaml, .github/workflows/app-test.yaml, .github/workflows/gradlew-update.yaml, .github/workflows/merge-conflict-labeler.yaml, build.gradle.kts
**Changes**
- Add new test action to run `gradlew test`
- Copied from the Kotlin SDK
- Add new lint action to run `gradlew detekt` and upload the sarif file
- Copied from the Kotlin SDK
- This will start showing linter issues in pull requests, we need to finetune the for this linter config later
- Temporarily removed Android linting (SARIF support is added in the next Android Gradle build tools version so we'll wait a bit for that)
- Remove test and lint jobs from Azure CI
- Use `GH_TOKEN` so CI actions run as the bot. ~~**SECRET NEEDS TO BE ADDED TO THE REPOSITORY FOR THIS TO WORK**~~
- Rename .yml to .yaml for merge conflict labeler
- Replace `mschilde/auto-label-merge-conflicts` (unmaintained) with `eps1lon/actions-label-merge-conflict`
**Issues**
=> Move linting and testing to GitHub actions

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/model/ServerAdditionState.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerAlertFragment.kt, app/src/main/res/values/strings.xml
**Changes**
- Add the Kotlin SDK as dependency
- Use the AddressCandidateHelper from the SDK to find candidates for the inputted server address and try them one-by-one. The first one that works is chosen. If none of the candidates work we show the error of the latest attempt.
Function-wise this works great, I can now just input "demo.jellyfin.org/stable" and it will automatically add  the protocol. UI-wise it's terrible right now, error reporting wasn't great before but it's garbage now.
The `// TODO` is not something that can be fixed right now - we don't have a `Jellyfin()` instance of the SDK at this moment.
**Issues**
=> Use the AddressCandidateHelper of the Kotlin SDK to normalize the inputted server address

README.md
**Changes**
Update the README to be more like the jellyfin-android readme.
- Removed `utm_source` parameters from urls
- `alt` before `src`
- Update jellyfin.media to jellyfin.org
- Build process (copied from jf-android)
**Issues**
=> Update README to 2021

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
I can't reproduce the issue that crashes the application anymore after these tweaks
Issue before:
```
java.lang.Error: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'org.jellyfin.androidtv.integration.LeanbackChannelWorker',qualifier:q:'org.jellyfin.androidtv.integration.LeanbackChannelWorker',binds:androidx.work.ListenableWorker]
```
**Changes**
- Always cancel existing workers
- If we add new ones/change existing ones in the future this prevents duplicate or deprecated runners to run
- Await the results of  the cancellation/creation
- It should never fail but this makes sure that if it does the exception it thrown to the main thread
Most of it is inspired from a Koin sample here:
https://github.com/InsertKoinIO/koin/blob/68b2e9eaf3ad465f0ebb8f1e6b7 …
=> Always cancel existing workers before recreating

.github/workflows/app-lint.yaml, app/build.gradle.kts, app/lint.xml, build.gradle.kts, gradle.properties
**Changes**
- Kotlin 1.5
- Android Gradle plugin 4.2
- Enabled SARIF reports for Android linter
- Updated lint workflow to run the Android linter
- Remove Java 8 target options (is now the default)
**Issues**
=> Update Kotlin and Gradle plugin to latest version and add Android linter to linting workflow

.github/ISSUE_TEMPLATE/config.yml
Fix the "Getting help" URL in ISSUE_TEMPLATE/config.yml.
Signed-off-by: Jeff Squyres <jeff@squyres.com>
**Changes**
Trivial URL fix in the `.github/ISSUE_TEMPLATE/config.yml` file so that the "Jellyfin documentation" link on https://github.com/jellyfin/jellyfin-androidtv/issues/new/choose is correct (I'm guessing that the old URL is just stale / has changed...?).
I do not think that this trivial change is worth adding me to CONTRIBUTORS.md.  😄 
**Issues**
NA.
=> ISSUE_TEMPLATE/config.yml: fix URL

app/src/main/java/org/jellyfin/androidtv/preference/constant/AppTheme.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/ThemeManager.kt, app/src/main/res/drawable/btn_focus.xml, app/src/main/res/drawable/btn_non_focus.xml, app/src/main/res/drawable/square_accent.xml, app/src/main/res/layout/image_card_view.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/theme_jellyfin.xml, app/src/main/res/values/theme_mutedpurple.xml
**Changes**
- Allows themes to change the indicator shape and the rounding values for cards/buttons
- Adds a Muted Purple theme that uses an accent color from the inner triangle of the Jellyfin logo, translucent buttons, and a rounded square watched indicator
- Increases the rounding value for btn_focus and btn_non_focus from 2dp to 4dp (default theme)
- Raises the brightness of the non-focus grid items (all themes)
=> Allow themes to change rounding values/indicator shape, add Muted Purple theme

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/shared/PaddedLineBackgroundSpan.kt
**Changes**
Adds horizontal padding to the background for subtitles. Based on this approach: https://medium.com/@tokudu/android-adding-padding-to-backgroundcolorspan-179ab4fae187.
**Issues**
N/A
=> Add horizontal padding to subtitles

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
**Changes**
The app crashed on start because the WorkManager was not initialized in the applications onCreate function. This might have caused the Koin issues before,....
Move worker initialization and auto bitrate test to after session is created.
I also moved the autobitrate thingy, it takes around 250ms for me. But when I look at the references it looks like it isn't even used. the only reference that uses it is here:
https://github.com/jellyfin/jellyfin-androidtv/blob/71e52b1bb25fa3c57daddca9bc73ce817fab2d44/app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java#L566-L567
I'm considering removing the autobitrate stuff for now, it didn't seem to work anyway.
**Issues**
=> Move worker initialization and auto bitrate test to after session is created

app/src/main/java/org/jellyfin/androidtv/ui/shared/KeyboardFocusChangeListener.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/AddServerAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/UserLoginAlertFragment.kt
**Changes**
* Prevents the on-screen keyboard from being activated automatically on Fire OS
* Fixes navigating down on alert fragments
* Ensures focus is cleared when confirm is selected
* Fixes username field receiving focus when disabled
**Issues**
N/A
=> Fix Fire OS focus issues on login

.github/workflows/gradlew-update.yaml, .github/workflows/merge-conflict-labeler.yaml
``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))
*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*
The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``JF_BOT_TOKEN``, which should be pretty generic.
=> Replace GH_TOKEN with JF_BOT_TOKEN

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Fix VLC player passthrough
**Changes**
As per the vlc javadoc, using `setAudioOutput`  "disable the encoding detection", and that seems to intefere with PT.
As  `android_audiotrack` is the default value (and I don't think you can switch the output during a playback), plainly removing the lines fixes the issue.
**Issues**
Fixes #786
=> FIX: [vlc] "setAudioOutput" disables passthrough

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Allow switching audio track from paused state.
Currently, changing track in the UI when paused is silently ignored.
Tested with libVlc
=> FIX: allow switch audio from paused

app/src/main/res/layout/image_card_view.xml
**Changes**
Removes the transparency applied to rating badges on cards.
This was added in the card redesign in https://github.com/jellyfin/jellyfin-androidtv/pull/585, but I think we should revisit some of the transparency changes made there. This one in particular is rather hard to see currently being only 25% opaque.
**Issues**
N/A
=> Remove transparency from card badges

app/build.gradle.kts
**Changes**
Although the library already used desugaring in a previous beta it appears that it doesn't matter unless it is added to the app using it. This PR fixes that by adding the desugaring to the app and allows java.time to be used fixing the crash from @thornbill in #880.
**Issues**
Required for #880 to work on older devices (\<Android 8)
=> Add desugaring to support java.time

app/build.gradle.kts
**Changes**
- Update ExoPlayer to 2.14.0 (was 2.11.3)
- Switch from Amazon fork to official Google version
Amazon doesn't maintain their fork anymore and I'm not a fan of using an outdated version. There's lots of complains on Reddit about it too, some users even manually replace the dependency and build their own version of the app. Moving away from the fork should not impact too many users, afaik the patches in the fork are mostly for older generations of Fire OS devices. Those users should update their device or force LibVLC as videoplayer.
**Issues**
Part of #839
=> Update ExoPlayer to 2.14.0

app/lint.xml
**Changes**
Update notifications are not meant to be linter rules, it's annoying that these show up on PR's too.
**Issues**
=> Disable GradleDependency lint check

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/ProfileHelper.java
**Changes**
* Disables support for AC3 for Fire Stick Gen 1 devices as a follow up to #843
**Issues**
N/A
=> Disable AC3 for Fire Stick Gen 1 devices

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
**Changes**
Add a linear backoff criteria that will retry every 10 minutes. This will retry faster when a user is not signed in when the worker is run and needs to retry. And prevents the worker from not running because the server was offline for a while (default was exponential).
**Issues**
=> Add backoff setting for leanback channel worker

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
New Koin version now supports Kotlin 1.5
**Changes**
Update Koin to 2.2.3 and remove temporary logging change to prevent crashes
**Issues**
=> Update Koin to 2.2.3 and remove temporary logging change to prevent crashes

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
Adds flac direct play support to the ExoPlayer profile. Support is required for API level 27+ but all Amazon Fire devices support it.
**Issues**
Fixes #163
=> Add flac support to exoplayer profile

app/build.gradle.kts, build.gradle.kts, gradle.properties
**Changes**
Adds a new property to `gradle.properties` called `sdk.useSnapshot`. When set to `true` it will use the `latest-SNAPSHOT` version of the SDK (which is the master branch). This is useful when making changes for a next release or testing stuff. 
I've also renamed `kotlinVersion` to `kotlin.version` and updated the gradle build tools.
edit: This PR also updates the SDK version to 1.0.0-beta.7
**Issues**
=> Add Gradle property to use SDK snapshot version

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/ApiClientExtensions.kt
**Changes**
- Add KtorClient instances for user and system and apply sessions in SessionRepository
- This allows the use of the new SDK while keeping the old apiclient working
- Migrate LeanbackChannelWorker to SDK with the system user
Because of an issue in the current SDK beta the `date created` field is not returned from the server. This causes the order of the "next up" row to be incorrect. It's already fixed with jellyfin/jellyfin-sdk-kotlin#262 and confirmed working when using the snapshot release (#913). We can either wait for the SDK developers to release a new beta or just merge this now. The version will definitely be bumped before releasing anyway (SDK will promote to non-beta).
**Issues**
=> Add SDK ApiClient and migrate LeanbackChannelWorker

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt
**Changes**
* Hides the Live TV rows from the home screen when unavailable on a server. This mimics the logic in web although it's kind of crappy.
**Issues**
Kind of fixes the issue for #512 while not adding the requested feature
=> Hide live TV section when unavailable

app/src/main/res/layout/new_details_overview_row.xml
**Changes**
Fixes an issue with titles that were long enough to reach the end of the first line but not long enough to extend onto a second line. The title/main info row/genre row/summary would get pushed up as if it were trying to accommodate a two-line title even though the title is only one line. Examples of titles that caused this issue: 
> Marvel's Agents of S.H.I.E.L.D.
> Revenge, Getting Rich, Aching
- This PR should have no effect on the layout for items with a title that takes up only 1 line (aside from fixing this issue)
- For titles that extend onto a second line, the main info row/genre row/summary are now 5dp higher—these positions now match their respective positions when the title is only one line
Screenshots:
<details>
<summary> Bug </summary>
</details>
<details> …
=> Fix long single-line title pushing item details text up

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
- Separate TV Series and Episodes into their own rows in the item details for a person. TV Series got lost in the row if there were a lot of episodes, and the row height was changing as items entered/exited the screen since the series poster has a different height than episode thumbs
- Sort movies/series by name
- Sort episodes by series name and, within the same series, by season/episode number
=> Separate series and episodes in person item details, sort items by name

LICENSE
Exact same license but formatting changed slightly.
Sourced from https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
We could update it to GPL3.0 since the source code never specified an exact version (license says "If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation.") but I didn't do that (yet).
=> Update LICENSE file to match exact formatting from gnu.org

.ci/azure-pipelines.yml, .github/workflows/app-build.yaml, .github/workflows/app-test.yaml
Azure still used for releases only (not triggered on pull requests anymore)
**Changes**
Based on the work of @h1dden-da3m0n in the mobile app repository this introduces a new "app-build" workflow that builds the app for pull requests and the master branch The apk can be easily downloaded from GitHub instead of going to Azure.
The Azure CI is still used for publishing an building the release APK on master/release branches. I'm planning to replace that one with a GitHub workflow before 0.12 as well.
**Issues**
=> Move build CI to GitHub Actions

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/IPositionablePresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/PositionableListRowPresenter.java
**Changes**
Interface was only used by one class and one usage, simplified it to use the class directly. Additionally added a check before casting and removed an unused constructor.
**Issues**
=> Simplify IPositionablePresenter structure (removed interface)

app/lint.xml
Doesn't work properly with view binding (causing false-positives)
**Changes**
- UnusedIds check changed from warn to ignore
**Issues**
=> Ignore UnusedIds linter check

app/src/main/res/layout/clock_user_bug.xml
**Changes**
Fixes an issue introduced in https://github.com/jellyfin/jellyfin-androidtv/pull/920 where the clock view filled the entire width of the screen causing all the other header content to be drawn offscreen.
**Issues**
N/A
=> Fix broken layout on grid pages

app/build.gradle.kts, build.gradle.kts
In case 0.13 will end up taking over a year this PR makes sure 0.12 will at least be able to support maintenance updates :).
**Changes**
- Removed JCenter repository
- Use apiclient from JitPack (and yes I still don't like JitPack)
- "update" apiclient to 0.7.10
- Update Detekt to 1.17.1 (current version used a JCenter dependency)
**Issues**
Closes #839
=> Use Jellyfin apiclient from JitPack, remove JCenter repository

app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
**Changes**
There is a limitation hardcoded in jellyfin-androidtv that prevents
direct playing a h264 file with libvlc if it has a number of reference
frames == 1.
This limitation was added 5 years ago (da38c02) and causes files to
be transcoded. But since then, libvlc seems to support files with
reference frames < 2.
Thus, this commit removes that limitation, as from my tests
jellyfin-androidtv directs streams and plays those files without any
issue when libvlc is selected.
**Issues**
Fixes #958
=> Remove libvlc RefFrames restriction

app/src/main/res/layout/view_toolbar.xml
**Changes**
- Removes padding from the end of the toolbar content if the clock is hidden
Really liking the toolbar :)
<details open>
<summary>Before (no clock)</summary>
</details>
<details open>
<summary>After (no clock)</summary>
</details>
<details open>
<summary>Before (with clock)</summary>
</details>
<details open>
<summary>After (with clock)</summary>
</details>
(Before/after with the clock are the same)
=> Remove padding from end of toolbar content when clock is hidden

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
Noticed an issue where the video player would close if the activity was paused on my shield. This could happen when you opened system settings (even quick settings that show on top). Apparently this was done because someone assumed a pause means the user hit the home button!?
```java
if (!mActivity.isFinishing()) mActivity.finish(); // user hit "home" we want to back out
```
In my quick testing this change did not cause any issues since the onResume function is properly-ish implemented.
**Issues**
=> Don't close the video player when activity is paused

app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/sdk/ModelExtensions.kt
**Changes**
- Show server not supported error in user login alert 
- Forgot this earlier when adding the new LoginState
- replace ServerVersion.asText() with ServerVersion.toString()
- Copied that function to the SDK in beta8
**Issues**
=> Show server not supported error in user login alert and replace ServerVersion.asText() with ServerVersion.toString()

.github/workflows/app-publish.yaml
**Changes**
- Updated publish workflow to use apksigner instead of Gradle
- This change was originally made in the mobile app repo to fix F-Droid compatibility
- Add unsigned release files to build output
- Add debug files to build output
- Changes originally made by @h1dden-da3m0n 
**Related pull requests**
jellyfin/jellyfin-android#446
jellyfin/jellyfin-android#448
jellyfin/jellyfin-android#449
**Issues**
=> Sign release files using apksigner instead of Gradle and include debug files in release

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/RecordAction.java
**Changes**
Fixes a crash due to an index out of bounds when watching a live tv program that is also being recorded. The `setIndex` call was just unnecessary because calling `setDrawables` calls `setIndex(0)` already.
**Issues**
N/A
=> Fix crash when watching and recording live tv

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
Fixes a crash when selecting the "previous channel" button on live tv when there is no previous channel
**Issues**
N/A
=> Fix crash when previous channel id is empty

app/src/main/res/values/colors.xml
**Changes**
Changes the background filter to match the default background color with an opacity of 80% based on the discussion in: https://github.com/jellyfin/jellyfin-androidtv/discussions/982.
**Issues**
N/A
=> Update background filter transparency

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, build.gradle.kts, gradle.properties
**Changes**
From https://github.com/jellyfin/jellyfin-android/pull/428: This should help with preparing for next server releases, next sdk releases or sdk development.
- Allow using stable/snapshot/unstable-api-snapshot/local versions of SDK
- Bumped SDK to beta 9
- Fixed nullability issue in LeanbackChannelWorker (was not-null before beta9)
**Issues**
=> Support different SDK flavors

app/lint.xml
**Changes**
- Added Typos and DuplicateStrings to ignore list. Both are caused by translations which often are correct. Weblate does a bit of linting on it's own and translators don't look at our issue list.
**Issues**
=> Ignore strings related linter issues

app/src/main/java/org/jellyfin/androidtv/ui/NumberSpinner.java
**Changes**
This class is only used for the audio delay popup and 100ms steps seem too large. In the app settings we allow for 1ms steps, so maybe we should just use 1 here also? Either way 100 was far too large.
**Issues**
N/A
=> Change default step value in NumberSpinner

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
**Changes**
Fixes a crash when fast-forwarding/rewinding in the player
<details>
<summary>Logs from the crash</summary>
```
2021-07-02 01:15:16.412 4283-4283/org.jellyfin.androidtv.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.jellyfin.androidtv.debug, PID: 4283
java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.leanback.widget.Presenter$ViewHolder.view' on a null object reference
at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder.startSeek(PlaybackTransportRowPresenter.java:386)
at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder.onBackward(PlaybackTransportRowPresenter.java:253)
at androidx.leanback.widget.PlaybackTransportRowPresenter$ViewHolder$4.onKey(PlaybackTransportRowPresenter.java:292)
at …
```
=> Fix crash when seeking in video

app/src/main/java/org/jellyfin/androidtv/ui/card/DefaultCardView.kt, app/src/main/res/values/dimens.xml
The leanback based cards previously used 114% scaling and the animation is hardcoded to 150ms. The timing of our own DefaultCardView is now also 150ms and the scaling for the leanback cards is now 115%. This makes our own card and the leanback based cards consistent in their animations.
**Changes**
- some code changed
- xml stuff
**Issues**
=> Use consistent animations for different card views

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
- Hides the end time in the item details and the info row underneath the item title when the 'Show clock' preference is set to 'During playback' or 'Never'
=> Hide end time when clock is hidden while browsing

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/res/layout/view_card_legacy_image.xml
See https://github.com/bumptech/glide/issues/1456 for information about this bug.
**Changes**
- Remove adjustViewBounds from card main image (not used since we set an absolute width/height)
- Use Glide thumbnail instead of placeholder so the images will be properly scaled
**Issues**
Fixes #992
=> Fix incorrect placeholder scaling

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
This change is to permit startPauseReportLoop to run effectively and avoid a web socket timeout when pausing player. 
**Issues**
Fixes #400
=> fix  to check for PAUSED state when running startPauseReportLoop

gradle/libs.versions.toml
Fixes an issue with special characters in device names
**Changes**
- Update jellyfin-sdk-kotlin to 1.0.1 to an issue with special characters in device names
**Issues**
=> Update jellyfin-sdk-kotlin to 1.0.1

app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
* Fixes the supported h264 level for Fire TV devices
* Adds a profile condition for devices that only support 1080p video playback (Requires a server side fix https://github.com/jellyfin/jellyfin/pull/6274 to work in 10.7.x)
Ideally both of these would be covered by properly querying the devices capabilities, but I don't want to dive into that when we want to get a beta release out soon :tm:.
**Issues**
Maybe some playback issues :man_shrugging:
=> Playback fixes for Fire TVs

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
Huawei was inspired by Samsung and wanted to break everything too. They decided that on HarmonyOS TV all apps get a false-positive for the leanback system feature so that all apps crash as soon as they try to integrate with it.
Fortunately this issue wouldn't crash the app starting from 0.12 because leanback integration was moved to a background worker, which uses a separate thread.
**Changes**
- Added an additional check to see if the content provider (android.media.tv) is available on the system
**Issues**
Fixes #1015
=> Check if content provider is available in LeanbackChannelWorker

app/src/main/java/org/jellyfin/androidtv/ui/preference/category/authentication.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
**Changes**
- Update system session when system user is modified
I noticed this while recording the video in my comment in #1012, I switched from my own server to the demo server and the system user didn't update until an app restart.
**Issues**
=> Update system session when system user is modified

app/src/main/java/org/jellyfin/androidtv/auth/LegacyAccountMigration.kt, app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt
The 0.11.5 -> 0.12.0 migration contained a few issues that I noticed when updating my stable version of the app. This PR fixes those issues. I tested it locally in an emulator by removing the app + app data, install 0.11, sign in and then update to this branch.
**Changes**
- Migration
- Read access token from serverinfo (who invented this scheme lol) - fallback to the old approach as I'm not sure why we did it that way
- Add server version
- Only run once (prevents server being re-added if the user manually removes it)
- Curent beta users fix
- Refresh server info when version is null, even if the timer says we shouldn't
**Issues**
Fixes #1030
=> Fix legacy credential migration not working as expected

app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
- Rounds up the runtime calculation -- pretty much the same reasoning as #836
- Matches the resolution text conditions to the values used by the server (added in https://github.com/jellyfin/jellyfin/pull/6256)
- This fixes 4:3 content being displayed a tier lower than the actual resolution (ex. 1440x1080 was displayed as '720')
=> Round up runtime calculation and match server resolution text in InfoLayoutHelper

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, gradle/libs.versions.toml
**Changes**
Noticed some crashes in Tracepot that came from the androidx.window library. Hopefully updating it to a more recent version will fix the problem.
**Issues**
=> Update androidx.window to alpha09

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackOverlayActivity.kt
Although we don't support phones with the ATV app some custom ROM's apparently have system bars. This PR hides them during playback.
**Changes**
- Hide system bars (status bar / navigation) in video player
**Issues**
Closes #1044
=> Hide system bars during video playback

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, gradle/libs.versions.toml
ACRA went Kotlin-first and changed the way it is initialized to use Kotlin DSL.
**Changes**
- Update ACRA to 5.8.x
**Issues**
=> Update ACRA to 5.8.x

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/playback.kt, app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java
The app only supports Android API 21 and up, the check would always return true.
**Changes**
- remove is50 check
- remove hasSubtitlesSurface from VideoManager
**Issues**
=> Remove is50 check (always true)

app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
This fixes an "issue" where closing the app using the back button (a "soft-close") wouldn't restore the default user session on re-opening. This is mostly notable when changing the default user.
**Changes**
- Always restore user session in StartupActivity
**Issues**
https://github.com/jellyfin/jellyfin-androidtv/issues/1058#issuecomment-890512663 (does not close the issue)
=> Restore user session when starting after soft-closing the app

CODEOWNERS, app/build.gradle.kts, buildSrc/src/main/kotlin/VersionUtils.kt, playback/build.gradle.kts, playback/src/main/AndroidManifest.xml, settings.gradle.kts
**Changes**
- Add an empty module for the playback code
- Add CODEOWNERS file
**Issues**
Goes together with #1064
Part of #1057
=> Add (empty) playback module and CODEOWNERS

app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt
When I made the ApiBinder I based the code on the StartupActivity code in the 0.11 branch but I forgot it was already changed a lot. The mute commands were removed.
**Changes**
- Unsupport mute commands
- Support displaymessage command
- Small cleanup
**Issues**
=> Fix wrong supported commands reported

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/TvApp.java, app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java, app/src/main/res/values/strings.xml, buildSrc/src/main/kotlin/VersionUtils.kt
This change is to make sure development for the new playback code can happen in the master branch while still being able to release updates with the old code. It does this by adding a new interface "PlaybackLauncher" that is used when launching the playback activity and a toggle for which implementation to use.
When the initial playback module is added this will launch an activity that reads the data from the current playback code (item to play etc.) and converts it to the new playback module format before launching the new playback module activity. This is a bit hacky but good enough for development.
The implementation toggle only works on debug builds of the app and will never show up on releases.
**Changes**
- Move useExternalPlayer and getPlaybackActivityClass functions to new …
=> Move useExternalPlayer and getPlaybackActivityClass functions to new PlaybackLauncher interface

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
Turns out due too some race conditions the app sometimes started the home screen four times. This PR fixes the cause of that and adds a debug log that could help when similar issues happen in the future.
**Changes**
- Add debug log statement in StartupActivity to log the next activity
- Add intent flags to StartupActivity.openNextActivity that make sure the navigation history is cleared (no going back to startup activity)
- Add some checks in SessionRepository to prevent setting the same user twice
**Issues**
=> Fix going back from home screen

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
**Changes**
Fixes a slight regression from https://github.com/jellyfin/jellyfin-androidtv/pull/1074 that prevented user sessions from being explicitly set to null on startup. This caused the loading screen to never be replaced by the correct activity to enter a server or select a user.
**Issues**
N/A
=> Allow user sessions to be set to null again

app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationSortBy.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/authentication.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/res/values/strings.xml
Adds an option to change the sorting of the users and servers lists. Additionally reload users on resume (to update the sorting if it changes).
**Changes**
- New preference: authentication -> Sort by
- Added a few line breaks to the LoginViewModel
- Not much else
**Issues**
Fixes #1078
=> Add preference to change user sort order in login screen

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt, gradle/libs.versions.toml
So I made quite a few changes in when this single function (restoreDefaultSession) is called in the past few weeks but I'm now confident this is the correct way. The process lifecycle allows us to observe the process and restore the session when the process is started (not created).
The app will now (re)load the session only in this lifecycle event which is called everytime the app is visible. This can happen due too a user launching the app or opening it via a view action (leanback integration) or when reopening after a soft-close.
**Changes**
- Use the process lifecycle to (re)load user sessions
**Issues**
Closes #1081
=> Fix session loading twice on app startup

app/src/main/java/org/jellyfin/androidtv/auth/AuthenticationRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/authentication.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt, app/src/main/res/values/strings.xml
This PR adds a new option at the bottom of the authentication preference screen called "always authenticate". When enabled it changes the behavior of the app:
**Changes**
- Option enabled behavior
- Auto login is disabled
- System users are disabled
- System integrations are disabled (search, leanback, daydreams etc.)
- User is required to enter the password when selecting a user
- Access tokens are still stored in the system
- Option disabled behavior like it always was
- Option is hidden when not currently signed in ~~although a "kid account" could still disable it after signing in~~
**Issues**
Closes #1080
=> Add option to always require authentication

CONTRIBUTORS.md, app/src/main/java/org/jellyfin/androidtv/constant/CodecTypes.java
**Changes**
Remove the unused `vpx` video codec, which is actually ambiguous between VP8 and VP9, as part of a bigger shift to be specific between the codecs in the VPx.
**Issues**
Progress on jellyfin/jellyfin#6455
=> Remove vpx (unused) as a CodecType

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackLauncher.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt
**Changes**
This is a small change that does not modify any behavior in the normal app flow (and thus is safe for 0.12 inclusion). It adds a new activity "PlaybackForwardingActivity" that is used to bridge all playback requests to the new playback module.
Right now it extracts the to-be-played item from the current playback code and retrieves the BaseItemDto from the api using the SDK. It then quits the activity. This code is backported from my playback scratch branch.
With this the app will not crash anymore when playback is started with the new playback module enabled.
**Issues**
Part of #1057
=> Add PlaybackForwardingActivity for bridging to new playback module

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VlcEventHandler.java
**Changes**
- Fix VLC error reporting
No idea why but the errors where ignored, this might help fixing some of our playback issues
- Fix VLC output not using android-display
The onNewVideoLayout function we use to scale the video view does not work on the opengl video output from LibVLC
**Issues**
Possibly a few of them..
=> Fix VLC error reporting and black screens

app/src/main/java/org/jellyfin/androidtv/ui/preference/category/playback.kt, app/src/main/java/org/jellyfin/androidtv/util/Utils.java
**Changes**
Reviewing the codec support for Fire TVs, it seems they all support multichannel audio. This seems to just be a legacy holdover. I tested this on a 2nd Gen Fire Stick and it seems to work as expected.
**Issues**
N/A
=> Enable multichannel audio support for Fire TVs

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
**Changes**
- Uses `parentThumbItemId` instead of `seriesId` when fetching the leanback channel images
- Falls back to the parent thumb if the episode is missing a primary image
- This behavior matches inside the app
=> Use parentThumbItemId in LeanbackChannelWorker

.github/workflows/app-build.yaml, .github/workflows/app-lint.yaml, .github/workflows/app-test.yaml
See https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/
Results in smaller workflow files etc.
=> Use actions/setup-java caching

app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java, app/src/main/res/layout/now_playing_bug.xml
**Changes**
Fixes the layout issue in the now playing bug found in https://github.com/jellyfin/jellyfin-androidtv/pull/1099
**Issues**
None
=> Fix now playing bug layout

app/src/main/res/drawable/tile_land_series_timer.xml, app/src/main/res/values/attrs_tiles.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/theme_emerald.xml, app/src/main/res/values/theme_hotdogstand.xml, app/src/main/res/values/theme_jellyfin.xml
**Changes**
* Removes unused tile attributes
* Updates default theme colors
The "smart screens" were the worst offenders of using completely random colors, but it can also be seen in the red background for user avatars and the various shades of blue or green used for placeholders throughout the app. This reduces the colors used to only those in [this theme](https://coolors.co/031a6b-033860-1e76ba-00a4dc-aa5cc3).
| This PR | Current |
|--|--|
| ![tile colors](https://user-images.githubusercontent.com/3450688/132449653-0435ac1b-675d-4977-ae8f-a2d9b5e76be0.png) | ![current tile colors](https://user-images.githubusercontent.com/3450688/132449625-271325cb-efe1-4ddb-9192-5b95aa5276bd.png) |
**Issues**
N/A
=> Remove unused tile colors and update default theme

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
Please test this thoroughly before approve/merge 
**Changes**
- Use `destroyCurrentSession` instead of `setCurrentSession` with null value
- Change `destroyCurrentSession` to set api etc. to null in a **synchronous** way instead of calling `setCurrentSession`
**Issues**
Supersedes #1144
=> Fix crash when autologin is off

app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/res/values/strings.xml
**Changes**
Added sorting by star rating(called CommunityRating in the jellyfin-api) to the sortOption HashMap
Tested it in the android studio emulator and it worked.
**Issues**
Fixes https://github.com/jellyfin/jellyfin-androidtv/issues/1135
=> add star rating sort to grid view

app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt
This fixes the "server version not supported" toast from showing the build number. 10.7.7.0 now shows as 10.7.7
**Changes**
- Remove build number from internal version reference
**Issues**
Fixes #1162
=> Remove build number from internal version reference

app/src/main/AndroidManifest.xml
**Changes**
Removes the following warning in Android Studio:
> When using intent filters, please specify android:exported as well
It is true per default for activities and receivers that do have intent filters.
=> Explicitly specify android:exported

app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowsePersonsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByGenreFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentLiveTVRow.kt
Someone thought it was a great idea to send JSON blobs between activities. They use Gson for serializing/deserializing. This PR changes most of them to use the BaseItemDto from the SDK and kotlinx.serialization. I tested everything except for the Live TV activities to work.
**Changes**
- Remove GSON usages when (de)serializing for extras
- Use SDK BaseItemDto
- Use kotlinx.serialization
**Issues**
=> Remove GSON usages when (de)serializing activity extras

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
The watch next row is used by Android TV (leanback) and Google TV to display media content. Until now we've only showed "next up" items (unwatched episodes). This PR adds resumable episodes (episodes not fully watched). I specifically filtered out movies because their posters won't be displayed nicely (they would be resized to 16:9).
I've also marked the "my media" row (shows all libraries) as a default row, this means that users upgrading from 0.11 -> 0.12 will automatically see this row on their home screen.
**Issues**
=> Show unfinished episodes in watch next row

app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
H264 level 52 support added for all NVIDIA Shield TV models, to prevent transcoding when video can be decoded directly by the android-tv client.
**Issues**
Fixes #1231
=> Fix H264 52 Level available on NVIDIA Shield but not detected Fixes #1231

app/src/main/java/org/jellyfin/androidtv/ui/ServerButtonView.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeToolbarFragment.kt, app/src/main/res/layout/fragment_toolbar_home.xml, app/src/main/res/layout/view_button_server.xml
Although mobile is not supported the app works reasonably on tablets and it works with VR 😉. Two buttons added in 0.12 didn't work with touch - now they do!
**Changes**
- Fix touch support for "switch user" button
- Also switched from framelayout + 2 image buttons that toggled visibility based on image/icon to a single image button
- Fix touch support for server button
**Issues**
=> Fix touch support in home/auth screens

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
This issue didn't happen all the time but it sometimes caused the home activity to load default home sections because display prefs were still loading.
**Changes**
- Fix race condition in loading async preferences
**Issues**
=> Fix race condition in loading async preferences

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/LogInitializer.kt, app/src/main/java/org/jellyfin/androidtv/SessionInitializer.kt, app/src/main/java/org/jellyfin/androidtv/di/KoinInitializer.kt, gradle/libs.versions.toml
This PR is required to properly initialize ContentProvider's (like in #900) and declutters the JellyfinApplication class.
I did not move ACRA as it unfortunately requires an instance of Application.
**Changes**
- Add androidx.startup
- Move Koin initialization code to a androidx.startup initializer
- Move logging initialization code to a androidx.startup initializer
- Move session initialization code to a androidx.startup initializer
**Issues**
=> Migrate to androidx.startup for app initialization

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
changing the media for exoplayer clears its state and position so it uses the properties of the new media
**Issues**
on seeking transcoded media played with exo, the seekbar would briefly jump back to the start
on `changeVideoPath()` exoplayer either didn't or delayed using the new media's timeline position
**Docs**
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#prepare(com.google.android.exoplayer2.source.MediaSource,boolean,boolean)
=> reset exoplay position and state on media change

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
1) `CustomPlaybackOverlayFragment` will now `playPause()` when it catches a
`DPAD_CENTER` keyEvent instead of just calling `pause()`. If allowing playing in this context isn't desired, 2) will prevent double pausing and this change could be excluded.
2) `pause()` in `playbackController` now checks if already paused and returns if it is to prevent double pausing.
**Issues**
When the seekbar is interacted with `pause()` is always called. 1) stops this from potentially causing issues
When playback is paused and the overlay is hidden `CustomPlaybackOverlayFragment` called `pause()` on d-pad center keyEvent, even if already paused.
=> prevent double pausing, allow d-pad center to unpause with overlay hidden

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
libvlc `getTime()` reports ms from stream start during transcode. Now, that value alone is not used to report position.
In videoManager a new property `mMetaVLCStreamStartPosition` stores the timestamp of the media where playback began.
This value is added to the return from `getTime` to get an accurate timestamp from the player.
The values being added is done in `getCurrentPosition()`
The value of `mMetaVLCStreamStartPosition` is set before `videoManager.start()` is called, and before seeking an mkv transcode.
**Issues**
during transcoded playback, libvlc `getTime()` is used by `videoManager` to get the current player position in `getCurrentPosition()`, which is used to display timestamps in the overlay and report progress to the server. `getTime()` only reports ms since …
=> Fixed libvlc reporting incorrect currentPosition when transcoding

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
use `lastExoPlayerPosition` when `!isPlaying()`. This should finally prevent any seekbar irregularities when seeking.
**Issues**
when seeking trancoded media using exoplayer, the seekbar would jump around before playing because the `playbackController` report loops ask `mExoPlayer` for its position even when it can't report an accurate value.
=> Dont report real exoplayer position when not playing

app/src/main/java/org/jellyfin/androidtv/preference/SharedPreferenceStore.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/migrations/MigrationContext.kt
To fix an issue where new installs would execute all migrations I made some changes to the code.
**Changes**
- Add new MigrationContext
- Implementation unaware, meaning we can add migrations for display preferences at some point
- Works in 2 steps:
1. Define migrations
2. Run migrations
- Skips migrating when current store version is -1 (new install)
- Skips migrations already executed (previous behavior)
- All migration run in their own transaction (previous behavior)
- Remove .migration from SharedPreferencesStore and add .runMigrations instead
- Merge UserPreferences migrations meant for 0.11->0.12 into a single block. (keeps the toVersion for compatibility with current installs)
**Issues**
=> Add MigrationContext for improved preference migration behavior

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* in `prevAudioItem()` adjust `ndx` to accommodate for repeat mode **before** using `ndx` to modify `mManagedAudioQueue` -
to avoid attempting to `add()` at index `-1`
**Issues**
* in `prevAudioItem()`, an item is added to `mManagedAudioQueue` at index `ndx`. This is done prior to compensating for repeat mode, which would result in `ndx` == -1
=> fixed audio repeat mode crash when going from first to last item

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
1) use tmp position value for seeking instead of modifying mCurrentPosition right away
2) new method for updating mCurrentPosition. This is called not only from progressListener, but from the audio and subtitle switching methods to make sure everything is synced
3) queries to playbackController for currentPosition will return seeked position if relevant
4) seekbar will hopefully be **extra** stable now. no more jumping from 0:00 to resume position
5) adjusted directplay seeking to prevent seekbar pos irregularities
6) startReportLoop calls stopReportLoop before starting. I saw a log where it looked like there were two instances running. This should prevent that.
**Issues**
playbackController would report wrong position during seeking and when initializing playback
seekbar …
=> reworked playbackController position tracking and reporting system

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* new shuffle system that saves the original state of the queue
while shuffled the queue can be:
added to, keeping the position of the added items after un-shuffling
have items removed, when unshuffled the order of remaining items is kept
* fixed a crash related to removing items from the queue causing index out of range in the managed queue
* fixed a bug where removing an item would cause mCurrentAudioQueuePosition to be incorrect
**Issues**
* shuffling was destructive (the original state of the queue was lost)
* removing certain items could cause a crash from the managed queue
* removing an item that isnt currently playing could cause the mCurrentAudioQueuePosition to be incorrect
=> new in-place, non-destructive shuffle system

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
**Changes**
* `ItemListActivity`'s `play()` takes a queue index for starting playback (for audio only right now)
* `play()` has an overload that excludes the index
**Issues**
`play from here`, in the dropdown menu, would create an audio queue only containing the selected item and all subsequent items, and discard the preceding ones.
Using an album as an example, it was impossible to have a full album in the queue and start playback from a specific song without using play all -> changing the song in the now playing activity
=> audio play from here doesnt discard the preceding items in its parent

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
* added "add to queue" and "shuffle all" buttons to `fullDetailsActivity` for music artists
* updated `playbackHelper`'s artist query so all song by an artist can be played, arranged by album, and songs keep their order within the album
**Issues**
* `FullDetailsActivity.addItemToQueue()` would pass `mBaseItem` to `mediaManager` even when `mBaseItem` was a "parent" item like an artist or an album
(I added logic for albums just in case even though they arent handled here. There is logic elsewhere in `FullDetailsActivity` for `MusicAlbum` so I added it just to be safe)
=> fixed add artist to queue, added shuffle artist

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
**Changes**
* during playback with the overlay hidden, d-pad left/right should reveal the overlay, typically used to begin scrobbling the seekbar. I removed a check that would disable this behavior on fire tv devices
* `videoPlayerAdapter` would always return false on firetv when `canSeek()` is called (this is used by various objects like the seekbar and control glue to allow/disallow seeking & seekbar interaction)
**Issues**
https://www.reddit.com/r/jellyfin/comments/rfs766/comment/hogi4ih/?utm_source=share&utm_medium=web2x&context=3
=> bring firetv controls in line with the new player controls

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
**Changes**
* gave `itemListActivity` an add to queue button for `MusicAlbum`s
* the add to queue button replaces play/play all only when a queue exists and viewing a `MusicAlbum`, and is otherwise hidden
**Notes**
The reason for swapping the buttons is the limit of 5 buttons to a row. A "show more" button could be used instead, like in fullDetailsActivity
It's debatable whether replacing play with add to queue is a good UX choice.
An album can still easily be played by playing the first song.
Gelli for instance doesn't have a "play/play all" button and you just tap on the song
=> swap play for add to queue when an audio queue is present and viewing an album

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
**Changes**
* made `KeyProcessor.createItemMenu()` public so it can be called directly, and it now returns the created menu so the caller can dismiss it
* if the created item menu is open during various events it's closed (screensaver starting, queue replaced)
* added checks for all interactive objects to account for the screensaver being active
* updated the animation for the screensaver to make the fade in and out look the same
* play/pause button gains focus when the screensaver is stopped for user convenience
**Issues**
* the screensaver being active didn't prevent interactions with objects like the buttons or the queue items
* the dropdown menu opened by clicking on a queue item would stay open if the screensaver starts and after a queue replace (which could result in the clicked …
=> prevent unwanted interactions when music player screensaver active

.github/workflows/app-publish.yaml
Add .aab publishing for releases to the Google Play store. Based on jellyfin/jellyfin-android#509 by @Maxr1998. This results in smaller download sizes for end users.
**Changes**
- Generate and sign .aab files in publish CI
**Issues**
=> Also build app bundle for Google Play in CI

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* fixed a regression I introduced: changed `resetState` to `false` in `exoplayer.prepare(media, resetPosition, resetState)`
**Issues**
*  With `resetState` = `true`, the player doesn't recover from a player error. Instead it will continuously error until the limit is reached.
**Notes**
* `exoplayer.prepare(media, resetPosition, resetState)` is deprecated. The new spec excludes `resetState`. Perhaps it's excluded because it causes problems
* I'm also testing a replacement for `prepare(mediaitem, resetpos, resetstate)` that instead uses `setmediasource(media, resetpos)`, and uses a `mediaItem.Factory()`
=> fixed a regression in player prepare

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
**Changes**
* scroll to the bottom of the `scrollView` when the queue row is focused, fully displaying the queue row and the `1 | 10` "counter" indicator for queue progress.
_This is a dumb but functional hack to get around the weirdness of how the row behaves in this activity. I have tried many other options, and I suspect a proper fix would involve rewriting the layout xml, which I am not qualified to do._
* rearranged the code that defines the buttons so the code for each button is in the same place
* gave the `save queue` button the same on `onFocusChangeListener` as the other buttons since this fix needs the listener to only register `hasFocus == false` when the focus goes to the queue row
**Issues**
* navigating to the queue row would only scroll the view part way down, leaving the …
=> fixed scrolling behavior when queue row gains focus in AudioNowPlayingActivity

app/build.gradle.kts, gradle/libs.versions.toml
**Changes**
This allows Koin to do DI during unit tests and allows us to establish
Junit rules which involve Koin
This is essential for testing some classes as the playback code, where
DI is used heavily.
Prerequisite of #1302
=> Add Koin unit testing deps implementation

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* call `stopAudio` in `playNowInternal`, before replacing the queue, so that the logic in `stopAudio` doesn't index a now non-existent item.
**Issues**
* If music is playing from a queue of `n` size, particularly if playing the last item in the queue (index n - 1), and the user tries to start playback from another album/artist that would create of queue of `< n` size, `stopAudio` calling `updateCurrentAudioItemPlaying` attempts to access an index only valid in the old queue.
**Notes**
This is another example of correcting for edge cases before passing data to a method, which isn't ideal.
=> fix crash in playFrom where queue is replaced but old queue item is referenced

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* send `onPlaybackStateChange` to listeners in `startProgressLoop`, instead of in `playInternal`, so that the initial button update happens once the player is ready and can report accurate info
* replaced runnables with simple queries to `mediaManager`. It works well for me but perhaps situations exist that made the delays necessary. I will do some additional testing before marking this ready for review
**Issues**
When the first instance of music playback starts, the query to `mediaManager` for button states often happens too soon to get accurate info, and the play/pause button usually just shows the default state.
=> fixed nowplaying buttons not updating when playback starts

build.gradle.kts
**Changes**
Tweaks the gradle script to forward on test failures in a way that the
stack trace is preserved.
Previously, the stack pointed to a line after the test suite, e.g. line
101 on an 80 line file.
**To Test**
- Go to a test, e.g. `TimeUtilsTest` and change the expected output
- Run `gradlew test`, check the output points to the line changed
=> Emit JUnit output whilst running Gradle through CLI

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/playback.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/OutlineSpan.kt, app/src/main/res/values/strings.xml
**Changes**
Added seekbar for choosing subtitles font size (18-38 range, keeping 28 by default)
Added text outlining for better legibility and an option to disable the subtitles black background.
[Few screenshots and debug apk for who wants to test](https://drive.google.com/drive/folders/1Lk0FQIEC1klFdcbZ5DarzyCXobGYHjcc?usp=sharing)
**Issues**
Fixes: #1055
Fixes: #437
=> Add subtitles font size and background configurations

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
* moved the condition that checks whether to refresh buttons inside the runnable so it also has time to get new data
* added a condition that accounts for `mLastUpdated` updating right as playback ends (I'm not totally sure this is needed but I left it in for feedback)
**Issues**
* buttons like resume often failed to update after playback
=> made fullDetails button refresh after playback more reliable

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* `setFadingEnabled()` always shows the overlay if not already shown
* in ` hidePopupPanel()` call `startFadeTimer()` instead of `setFadingEnabled(true)` now that the latter shows the overlay (this might not be needed but I left it in for feedback)
* removed calls to `show()` before calls to `setFadingEnabled()` in a few places
* removed showing overlay and enabling fading on activity resume. This prevents the overlay from immediately starting a fade timer when playback starts, hiding the overlay before playback finishes buffering, and then showing it again once playback actually begins.
afaik there isnt a situation where video can be playing, and have pausing and then resuming the activity occur without stopping/pausing playback.
* in `playbackController` use …
=> Fix irregular playback overlay showing and hiding

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/constant/NextUpBehavior.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpButtons.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/category/playback.kt, app/src/main/res/values/strings.xml
**Changes**
* in the preferences display class 0s is displayed as the infinity character
* in `nextUpButtons` if the value of the timer is 0s it won't start the timer
**Issues**
https://features.jellyfin.org/posts/1383/next-up-episode-queue-without-autoplay
**Notes**
100 is the actual value used to check if the timer is 0s. I'm not sure where that comes from but 0s = 100, 1s = 1100, etc
If this is an acceptable implementation then it might be good to add a migration for users who have their timeout set to 0s, and change it to 1s
=> allow setting the nextup timer duration to infinite

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* record the timestamp of the most recent error when it's caught
* in `OnProgressListener` check if more than 30 seconds has passed since the last player error, and reset the retry count if so
**Issues**
* users who experience repeated player errors that are recoverable would still have their stream stopped by the "too many errors, giving up" condition, despite the errors being recoverable.
**Expected behavior**
* Unrecoverable errors where the retries repeatedly fail in a short time will still end the session
* Repeated recoverable errors will not end the session until they either 1) happen too close to each other (within 30s) 2) the player does not recover within the 3 attempts allowed
=> reset player error count if playback stabilizes

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* use logic similar to `seek()` in `skip()` so that the overlay displays the seeked position (use `mSeekedPosition`)
* pause playback before performing skip(s) to allow for subsequent skip operations
* unified skip logic for transcoded and direct play sessions
* renamed "mSeekedPosition" to mSeekPosition
**Issues**
* skipping in a transcoded stream wouldn't update the seekbar position until after the seek completed
* skipping in a direct play stream would perform a seek for every skip operation even if multiple operations are performed
**Intended Behavior**
* Skipping operations can be stacked (multiple button presses) and only perform the `seek()` after the final operation
* The UI updates as the skip operations run, for each one the seekbar and timestamps reflect the user …
=> improved skip behavior - especially with repeated button presses

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
Runs the Android studio formatter over the playback controller. This
should make it easier to use automated tooling and clear up some diffs (#1302)
which have touched this file too.
=> Run formatter over playback controller

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* log player discontinuity events: player resetting/jumping back to default position in timeline, usually due to an error
* log timeline changes
* log buffer events to give additional context
**Issues this will help log**
* #1239 
* #400 
* #1260
=> added debug logging for player discontinuity, timeline change, and buffering events

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
fix photo albums
**Changes**
- Use item id as display preferences key in ItemLauncher when opening items without a display preferences key
- This fixes photo albums crashing the app
- not sure if there's other item types with the same issue
**Issues**
=> Fix app crash when opening photo albums

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/res/layout/vlc_player_interface.xml
**Changes**
* fixed leaks caused by the `runnable` report loop in `videomanager`
* clear references to `videomanager` and `overlay fragment` in `playbackcontroller` when playback ends
* disabled screensaver
* handle home button interrupting playback by ending the playback activity
**Validating fixes**
_Validated results with a heap dump_
* start playback and then end it by pressing back
* start playback and then end it by pressing "home" on the controller
* start playback and skip to the next or previous item
**Remaining leaks I found**
* stopping playback from the jellyfin remote
* the live tv player is full of leaks
* a leak in a `textClock` leftover from the playback session when nextup is shown
**Reproducing remaining leaks I found**
* start playback and skip to the end so nextup is …
=> fixed some playback leaks

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* protect `stopPlayback()` against null reference
**Issues**
* `destroy()` calls `stop()` just in case, and that causes a crash without the guard against the players being null
=> fixed crash when closing the player - introduced by leaks PR

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.java, app/src/main/java/org/jellyfin/androidtv/constant/ViewType.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentHelper.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
- Remove unused ViewType enum
- Remove unused StaticServers and Users QueryTypes
- Unused since new login UI
- Remove unused ContinueWatching QueryType 
- Never used
- Continue watching in the home screen uses a different type (probably StaticItems)
- Remove HomeFragmentHelper.hasResumeRow (always false)
**Issues**
=> Remove unused QueryType values

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
Replace the setPlaybackSpeed with the more modern setPlaybackParameters. 
This matches the current docs / examples I've seen for Exoplayer
See: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#setPlaybackParameters(com.google.android.exoplayer2.PlaybackParameters)
This also exposes the ability to shift pitches, which was how I noticed it whilst investigating pitch shifting issues reported in my original speed controls PR
=> Exoplayer: Replace setPlaybackSpeed with setPlaybackParameters

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* prevent NPE from pausing, playing, and seeking if the video isn't loaded due to an error
* prevent NPE from calling `mVideoManager.getCurrentPosition()` by using the internal `refreshCurrentPosition()` instead
* prevent NPE from referencing `mCurrentStreamInfo` if the server can't provide a stream
* added a generic "cannot play item" toast to `handlePlaybackInfoError()`
* wait a beat and then end the session in `handlePlaybackInfoError()`
**Notes**
The primary fixes in the PR were made prior to making the activity finish on error. For testing, that line could be removed. All the media controls should be interactive (but non functional) without any issues.
**Issues**
* fixes NPEs caused by accesing `videoManager` via pausing, playing, seeking, and reporting in situations …
=> fixed crashes on failing to start playback of an unsupported or unavailable video

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* added conditions for the new HLS behavior so it can be ignored in cases where exoplayer is used for transcodes but hls isn't used. This applies when the baseprofile instead of the exoplayerprofile is used.
**Notes**
It's likely that devices which aren't eligible to use exoplayerprofile could still use hls.
In that case I guess a new exoplayer profile could be created which adds basic exoplayer-specific features.
They could be renamed to exoplayer-base and exoplayer-enhanced, or something.
**Issues**
Fixes #1353
=> Bypass hls seeking behavior for devices not using exoplayerprofile

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/LeanbackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/shared/BaseActivity.java
**Changes**
* remove all direct references to `leanbackOverlayFragment` and `playerAdapter` from `CustomPlaybackTransportControlGlue`. Instead use its built in `getPlayerAdapter()`. This maintains the right relationship between fragment, videoAdapter, host, and glue. The host can be detached and will signal the adapter and glue to release their resources.
_This is done by using `playerAdapter` to store the references to `leanbackOverlayFragment` and `CustomPlaybackOverlayFragment`._
* kill runnables when finishing/detaching so they don't cause leaks via context
* on finish/detach, break the chain of keylisteners and message listener that tied `PlaybackOverlayActivity` <- -> `CustomPlaybackOverlayFragment` <- -> `LeanbackOverlayFragment` <- -> `CustomPlaybackTransportControlGlue` …
=> more playback leak fixes

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Causes**
* #1368 put logic in the fragment lifecycle methods that shouldnt have been there. The code in onStop() for the prior fragment would run after the new already session started.
* `onStop()` and other lifecycle related methods in the fragment can't be relied on to perform operations on the video queue
* In those same methods, it can be expected that by the time they run PlaybackController is using a new instance of the fragment and videoManager
* more generally, to get the intended behavior those operations needed to be done in a specific order - in this case when one session ends and before another starts.
**Changes**
* call `stop()` in `itemComplete()` to ensure that the stop position and `PlaybackPositionTicks`/resume time is set
* handle the queue related operations like …
=> patch bug where video queue can be messed up and item progress is incorrect after playback

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
**Changes**
* ensure either play or resume/next up gets focus in fullDetailsActivity after playback
**Issues**
* sometimes buttons like "watched" get focus instead
=> on resuming fulldetails activity give play button focus if resume button isnt eligible

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
As per the 2.16.0 release notes:
https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04
SimpleExoPlayer is deprecated, and all functionality has been moved to
ExoPlayer. This allows us to replace these calls as-is and future proofs
us too.
**Issues**
Noticed in #1369
=> Replace deprecated SimpleExoPlayer -> ExoPlayer

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/res/menu/menu_details_more.xml
**Notes**
* the row = mDetailsOverviewRow
* the main drawback to this approach is that it assumes all the less important buttons, which should be hidden first, are visible when they are sorted. If they're not, they will be shown first and the more important buttons would be hidden.
Currently though, it looks like all the buttons (or almost all) are visible when `showMoreButtonIfNeeded()` is called.
**Changes**
* given a set of buttons to consider showing or hiding, loop through them and hide buttons until there either is extra space available or the buttons are already shown. the hidden buttons become part of the "more options" menu.
* the more options menu only shows items that are hidden in the row
* added the shuffle button and play trailers button to the more options menu. The trailer …
=> FullDetailsActivity - dynamically fill button row and hide extra

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoSpeedController.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/test/java/org/jellyfin/androidtv/ui/playback/VideoSpeedControllerTest.kt
**Changes**
Cap speed at 1.0 when live TV is on
We could allow various things, like a speed less than 1 or greater than
until we exhaust the buffer.
Unfortunately I don't have the equipment to test more complex
interactions, so lets play it safe and force it always to 1.0
Additionally we hide the playback speed button in live TV too
**Issues**
Mentioned in #1302 
**To test**
Could someone check the button is hidden watching live TV, as I don't have this available locally
=> Cap playback speed to 1 watching live tv

app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
This is a shortcut to open the display preferences for user views
**Changes**
- Add "rebuild()" function to trigger a preferences screen rebuilding
- Useful when data is asynchronously loaded
- Add "UserViewsRepository"
- It's a layer between UI and API to get user view (library) specific things
- Add "LibrariesPreferencesScreen" to open display preference screens
- Move user view related logic to UserViewsRepository
- The list of (un)supported collection types
- The collection types that allow view selection
**Issues**
=> Add libraries link to customization preferences

app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt, app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
Fixes an issue in #1352 
**Changes**
- Allow `null` values in UserViewsRepository functions isSupported and allowViewSelection
- Remove `.orEmpty()` when calling UserViewsRepository functions from Kotlin
**Issues**
=> Fix nullability for UserViewsRepository.isSupported and UserViewsRepository.allowViewSelection

.github/workflows/repo-stale.yaml
This PR aims to add a replacement for the discontinued Stale-Bot (see #1363).
It currently replicates the old config for Stale-Bot and uses the Jellyfin-Bot token.
* add a basic GitHub action workflow to monitor, label, and close stale issues within this repository
* successor to the discontinued Stale-Bot config
=> add stale issue check workflow

.github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/repo-stale.yaml
**Changes**
- Add repository condition to stale workflow
- Now disabled for forks
- Change runs-on for gradle workflows (accidently used ubuntu-latest)
- Change cron schedule to trigger 30 minutes before the gradlew-update workflow
- If both workflows trigger GitHub notifications the gradle update notification will be on the top
**Issues**
=> Add repository condition to stale workflow

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java
**Changes**
* catch the `IllegalArgumentException` GetItemAsync throws when `itemId` is null or empty in this situation
**Issues**
* `command.getItemId()` could return a null or empty string when remote controlling the app from the android client and quickly pressing the back button (on the phone) until the app is closed
=> fix crash from empty or null browsecommand sent from android client

app/src/main/java/org/jellyfin/androidtv/di/UtilsModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeToolbarFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt, app/src/main/java/org/jellyfin/androidtv/util/ImageUtils.java
Most of the image url building in the app is done with the ImageUtils class. I've migrated all functions I could test (everything not live tv) to use the SDK. This generates slightly different URL's.
**Changes**
- Add ImageHelper to create image urls using the SDK
- Migrate all non-livetv image url builder functions in ImageUtils to new ImageHelper
- Remove apiclient parameter from ImageUtils functions
**Issues**
=> Initial ImageUtils SDK migration

app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt
Accidentally added a null check in #1377. It wasn't there in the previous ImageUtils implementation.
**Changes**
**Issues**
=> Fix ImageHelper returning wrong URL when preferParentThumb is true

app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingBug.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* in the `now playing bug`:
> * update the timestamp if the playstate is idle, at this time the position mediamanger reports will be 0.
* in `now playing activity` `onResume`:
> * always update the player buttons in now playing activity. This seems stable now - prior to recent changes it needed a runnable.
> * update the timestamp to 0 if the player isn't initialized. In this situation a given song will need to start from the beginning. Without this the timestamp won't show at all.
* in `MediaManager`:
> * **stop the audio playback session and release the player:**
> > * on player error
> > * on audio focus loss. This can be tested by playing music, switching to youtube, and starting a youtube video
> > * when the last item in the queue finishes playing
> * **when the playback …
=> fix handling of null music player, audio focus loss, and device going to sleep while playing audio

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
**Changes**
* allow `mediaManager` to manage shuffling a new audio queue. This means clicking "shuffle (all)" will create a queue with the shuffle button enabled, and toggling it off will give the user an un-shuffled queue.
* gave the relevant `playNow()` methods a `shuffle` (boolean) parameter
* bypassed `getItemsToPlay()` handling shuffling audio items. This could be done more cleanly by having it internally ignore the `shuffle` parameter for audio
* fixed the query sorting of MusicArtist so songs are sorted by album and are in order within the albums
**Issues**
* starting audio playback by using the "shuffle (all)" buttons didn't allow for truly un-shuffling
* clicking "play all" on a music artist would sometimes (but not always) queue the songs unordered
=> shuffle the audio queue locally

app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java
**Changes**
* update the row position in `onProgress` if the row isn't focused (so it doesn't jump around while a user is navigating within it)
* track the row being focused or not using a boolean set in the button row focus listener
* ensure `getCurrentAudioQueuePosition()` never returns -1
* use `getCurrentAudioQueuePosition()` in `getCurrentAudioQueueDisplayPosition()` so it never displays -1
**Issues**
* the user had to select a new button or move focus for the queue row to select the current queue item
**Notes**
* I'm not sure if querying `mediaManager` for the current position, and querying the row for its position, has a significant performance impact when its done this frequently.
Edit:
* I removed the nowplaying button changes via force push and they'll go in a new PR related to …
=> position the audio player queue row without user interaction

app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
Tested on Nvidia Shield Pro
**Changes**
- Add opus to ExoPlayer direct play profile when down mixing is disabled
**Issues**
=> Add opus as supported audio codec for ExoPlayer

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt, app/src/main/java/org/jellyfin/androidtv/util/ImageHelper.kt, app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt
Part 2 of #1377 migrating all other usages of apiClient.GetImageUrl to the SDK. There are only 3 usages left in ImageUtils, all of them are used in Live TV code only and thus I cannot test my changes. **Feel free to finish the migration by converting those 3**.
**Changes**
- Migrate BackgroundService to use SDK for images
- Migrate BaseItemUtils.buildChapterItems to use SDK for images
- Migrate NextUpViewModel to use SDK for images
**Issues**
=> Migrate remaining image url building to SDK

app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt, app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
**Changes**
- Fix ApiBinder calling callback twice when the success callback fails
- Make callback optional
**Issues**
=> Fix ApiBinder calling callback twice when the success callback fails

app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt
**Changes**
Fixes the default library sort options that were changed in #1011.
We use Name by default in all other clients, so it probably doesn't make sense to use something different here (although an app level settings for library options would probably be a good future enhancement).
**Issues**
N/A
=> Fix default values for library sorting

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java
**Changes**
Closed Captions and Subtitles are used far more than Playback speed. Especially
since the controller will preserve your speed between videos.
Moved the icon between chapter select and audio offset / zoom controls:
**Issues**
Fixes #1405 (Albeit one day late)
=> Move video speed controls to the right of secondary bar

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* put all the factory-related code in one place
* Replaced deprecated `DefaultDataSourceFactory` with `DefaultHttpDataSource.Factory`
* Replaced deprecated `Player.EventListener` with `Player.Listener`
* cut out unnecessary steps in setting the media
**Notes**
The `MediaSourceFactory` is only used to add the user agent (via `DefaultHttpDataSource`). If the user agent isn't actually necessary, that can be removed too. Then it would be all defaults, and would be a simple:
1) make the player builder, set the renderer, and build
2) set the media item and prepare
This cleanup was done while trying to figure out why the last few seconds of hls streams repeat. I tested adding a `DefaultExtractorsFactory` and setting:
`extractorsFactory.setFragmentedMp4ExtractorFlags(FragmentedMp4Extra …
=> simplified exoplayer code

app/src/main/java/org/jellyfin/androidtv/di/ActivityLifecycleCallbacksModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
The app would open the home screen after closing the screensaver when it caused the app to start. This fixes that. Unfortunately the Android SDK does not expose the DreamActivity so we need to hardcode the string to match with.
I've changed the when statement to an array of strings with the names of all ignored activities.
**Changes**
- Ignore DreamActivity in AuthenticatedUserCallbacks
- Check active user from sessionRepository in AuthenticatedUserCallbacks
**Issues**
=> Prevent DreamActivity (screensaver) from opening login screen

app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
After adding the search integration the app stopped showing item details when an item is opened from the leanback channels in the launcher. This was because the channels communicate the item id differently while also using the VIEW action in the intent. This PR changes that to check if the data is null and falling back to the extra. This way both ways of sending the item id work as expected.
**Changes**
- Fix opening app via leanback channels not showing the requested item
- Add debug log to show the data used to determine the next activity
**Issues**
=> Fix opening app via leanback channels not showing item

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.java
apiclient bad
timber good
**Changes**
- Use Timber instead of (legacy) apiclient logger in StopTranscodingResponse
**Issues**
=> Use Timber instead of (legacy) apiclient logger in StopTranscodingResponse

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
revert player.listener to player.eventlistener
**Issues**
the change to player.listener in #1401 caused the onpreparedlistener to not be called in a situation when playerstate == ready but playwhenready was false
=> revert to player.eventlistener

app/src/main/java/org/jellyfin/androidtv/util/AutoBitrate.kt
Ideally we'd create a coroutine scope for a user session so we can cancel all api calls connected to it but this will do for now.
**Changes**
- Fix AutoBitrate causing an app crash when switching users while detecting bitrate
**Issues**
=> Fix AutoBitrate causing an app crash when switching users while detecting bitrate

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/StopTranscodingResponse.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.java
**Changes**
* reformatted several methods so they are easier to read by converting ternary statements into if/else blocks
* removed libVLC ID <- -> Stream info ID conversion
* reworked the `VideoManager` `setVLCAudioTrack()` to only handle verifying the specified track index could be passed to the player
* in `PlaybackController` `getAudioStreamIndex()`, prioritize `mVideoManager.getAudioTrack()` before other methods for finding the current audio track. Its value is only used when direct playback first starts and libVLC defaults to an audio track that isn't known elsewhere, and in turn this allows it to be changed.
* rewrote the conditions to force transcoding for exoplayer in order to start playback with an audio track which isn't the first one
* update `mCurrentOptions` to keep track of …
=> fix crashes from changing audio tracks, fix exoplayer not using default audio track

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* reset vlc meta position in clearPlaybackSessionOptions
**Issues**
* if the stream goes from transcoding -> direct without ending the session, and vlc is used, the timestamp will be current pos + meta pos
* needed for #1406
=> reset vlc meta position in clearPlaybackSessionOptions

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java
**Changes**
* get the buffered position from exoplayer and use it to update the overlay's seekbar
this is disabled for libVLC since afaik it can't report buffered position.
* move getDuration from the VideoAdapter to PlaybackController
* removed check for finishedInitialSeek when setting mFragment.setCurrentTime. I think this was left in by mistake, and leaving it in causes the seekbar to show 0 until playback starts.
=> show buffered position in seekbar for exoplayer

app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java
**Changes**
* reverted the change to `VideoPlayerAdapter`'s `getDuration()` made in #1435 
**Issues**
* the change relied on getting the duration from the playback controller, which in turn got it from VideoManager. The duration is only used to update the UI in `VideoPlayerAdapter`'s updateDuration(). This is called in `LeanbackOverlayFragment`s `mediaInfoChanged()` when a new item is loaded. When this happens it is likely too early to reliably expect PlaybackController or VideoManager to provide the duration of the new item instead of the old one.
**Notes**
* another potential solution is to add `getCallback().onDurationChanged(this);` to `updateCurrentPosition()` and rework `mediaInfoChanged()`.
=> reverted VideoAdapter getDuration

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* made the `play()` parameter `transcodedSubtitle` a nullable Integer so that we can specifiy null to defer to the server default, -1 to disable subs, and >=0 to select burnt in/transcoded subs
* reworked the logic for determining if a newly started stream is using burnt in subs, and set relevant flags locally so no additional restarts are needed
* always set `mDefaultSubIndex` to the server default so that users will always get subs enabled by default if they have such a preference set.
**Issues**
* default subtitles for an item wouldn't turn on by default when direct playing
* turning on burnt in subtitles would start the stream twice. After the first startup, `switchSubtitleStream` would incorrectly assume that the stream didn't already have the burnt in subs enabled, and …
=> fix default subtitle not turning on when not transcoding, and burnt in subs not turning off

app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java, app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java, app/src/main/java/org/jellyfin/androidtv/ui/ProgramGridCell.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/CollectionFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/SuggestedMoviesFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/card/ChannelCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/ClosedCaptionsAction.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
Went from 313 to ~~180~~ 172 usages of TvApp.getApplication(). Most left now are to get the current user or to do other fancy stuff like storing the playbackcontroller etc.
**Changes**
- use getString from current context or closest context when possible
- use self or closest context as context parameter when possible
**Issues**
=> Remove more TvApp.getApplication usages

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
This prevents the app from crashing after recovering from a crash. It's a temporary solution until the current user data is moved to a repository and the activities are rewritten to make use of that.
**Changes**
- Add a check if the TvApp.currentUser value is null during onCreate() for home and details activities
- This fixes 2 of our most common crashes, hopefully causing ACRA to now report the actual crash before the app tried to recover.
**Issues**
=> Close Home and Details activities when no active user found

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/TvApiEventListener.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
With this change the only usages left of TvApp.getCurrentActivity() are in the TvApiEventListener, which will soon be replaced with the SDK (0.14 probably).
**Changes**
- Receive context in MediaManager.playNowInternal
**Issues**
=> Receive context in MediaManager.playNowInternal

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
Fix crash when opening video player
**Changes**
- Fix crash when opening video player
- getContext() is null when a fragment starts, so we shouldn't immediately initialize a variable. Fixed by inlining it.
**Issues**
=> Fix crash when opening video player

app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/RecordPopup.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java
More fixes just like in #1457. This time setting the vars from onCreate instead of inlining the values. I went trough all changes of #1453 to find the usages of getContext() in properties and updated those. Most of the issues were in the live tv code.
**Changes**
- Fix remaining context used before initialization crashes
**Issues**
=> Fix remaining context used before initialization crashes

app/src/main/java/org/jellyfin/androidtv/constant/HomeSectionType.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
The webui (jellyfin-web) added new section types to 10.8. This PR adds them to the app. Without this change the preferences and shown section will behave weirdly (using a new (unknown) section type will show the default value instead)
**Changes**
- Add RESUME_BOOK(resumebook)
- Add REWATCHING(rewatching)
**Issues**
**Dependencies**
Depends on jellyfin/jellyfin-web#3451
=> Add 10.8 home section types

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* set `mDefaultSubIndex` when a subtitle track is selected/cleared
* don't search for subtitle events if the current position is before the start of the first event
* clear subtitles  after seeking
**Issues**
* if subtitles were enabled and then disabled, they would be re-enabled after seeking
* a subtitle event might not clear after seeking, and would stay on screen until a new event is ready (new from #1455)
* if playback starts at the beginning/before the start of the first subtitle event, each call to `updateSubtitles()` would search through the whole list of events without doing anything (new from #1455)
=> subtitle fixes for PR 1455

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* rely on matching exoplayer track IDs (start at 1) to MediaStream IDs (start at 0) by subtracting 1
This definitely needs plenty of testing to verify the exoplayer track IDs can always be matched this way.
**Issues**
fixes #1460
=> use track id for exoplayer track selection instead of guessing

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
**Changes**
* remove the code that prevents seeking when the container is TS
* replaced MP4 with TS (still uses HLS) in `ExoplayerProfile`
* modify the TS search bytes to match what jellyfin-android does:
https://github.com/jellyfin/jellyfin-android/blob/6d42621e16bc38d805cf2861a6a10f65ca2d626c/app/src/main/java/org/jellyfin/mobile/app/AppModule.kt#L77
* update `addAc3Streaming` so it can enable AC3 for more than one container (mkv, ts)
**Issues**
* fixes #1410
=> use ts for exoplayer transcodes

app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
**Changes**
* Implemented fix suggested by @nielsvanvelzen in [#1290](https://github.com/jellyfin/jellyfin-androidtv/pull/1290#issuecomment-1054665937): 
removed `rotateBackdrops` loop because it conflicted with the app's background service. Starting the screensaver is handled in `onProgress()`
* increased `SLIDESHOW_DURATION` from 10 seconds to 30 seconds
* made some linter-suggested changes:
> * made `PositionableListRowPresenter` non static
> * made `mLoopHandler` final
**Issues**
* https://www.reddit.com/r/jellyfin/comments/t3k3to/android_tv_beta_artist_background_bug_wmult/
discussed in [#1290](https://github.com/jellyfin/jellyfin-androidtv/pull/1290#issuecomment-1054665937)
**Notes**
* I was able to reproduce the issue and test that this resolves it.
To reproduce I added a few …
=> fixed screensaver background cycling in music player

app/build.gradle.kts, gradle/libs.versions.toml
**Changes**
- Update Android Gradle Plugin to 7.1.2
- https://androidstudio.googleblog.com/2022/02/android-studio-bumblebee-202111-patch-2.html
- Notable fix: "Android Studio BumbleBee does not always deploy latest changes"
- Update app/build.gradle.kts to include the namespace and applicationId
- This _should_ allow us to remove the package attribute in the manifest but due too some bug it doesn't work for debug builds (appends the applicationIdSuffix to the namespace which shouldn't happen)
- According to Android Studio Chipmunk (beta) the package attribute in the manifest is being deprecated
**Issues**
=> Update Android Gradle Plugin to 7.1.2

app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
_technically a feature but let's sneak it in for 0.13..._
This is a bit of a hack, but it will do for now.
**Changes**
- Emit a "menu" key press when long pressing an LegacyImageCardView
- This causes the context menu to show for most cards
- Enables a feature previously unusable on remotes without a dedicated menu buttons (like the Nvidia Shield)
**Issues**
=> Open context menu on long press

app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/res/values/strings.xml
Remove the like/dislike functionality from the app. AFAIK we're the only client that used it and the like/dislike state was never shown in any UI.
**Changes**
- Remove "like", "dislike", "unlike" and "undislike" (lol) from the item menu
- Remove API calls to set like/dislike from the KeyProccessor
- Remove now unused strings related to likes/dislikes
- Also updated one string to not mention likes
- Remove some other unused variables from KeyProcessor
**Issues**
=> Remove like & dislike

app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java
oops
**Changes**
- Make sure the LegacyImageCardView is focused before triggering the menu keypress on it
- If it's not focused the app can crash because `activity.getCurrentFocus()` returns null
**Issues**
=> Fix an issue where long-touching can crash the app

app/src/main/java/org/jellyfin/androidtv/constant/HomeSectionType.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
_note: as always, weblate will automatically remove translations for removed strings_
**Changes**
- Update default home sections and remove rewatching type
**Issues**
**Related**
- #1462
- jellyfin/jellyfin#7378
- jellyfin/jellyfin#7383
- jellyfin/jellyfin-web#2610
- jellyfin/jellyfin-web#3473
=> Update default home sections and remove rewatching type

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* catch subtitle track events size being < 1
* catch `NumberFormatException` if an exoplayer track ID isn't/can't be parsed to an integer, and return -1 so another method is used to get the current track, and to switch tracks (transcoding).
**Issues**
* potentially fixes #1488 
* https://github.com/jellyfin/jellyfin-androidtv/pull/1469#issuecomment-1058027334
* https://github.com/jellyfin/jellyfin-androidtv/pull/1465#issuecomment-1058029794
=> fixes for crashes from subtitle rendering and audio track selection

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* guard against `item` (BaseItemDto) being null or `mItems` being null when play() is called
**Issues**
* tracepot issue `688e6a080001267b`
=> crash fix from item being null when playback controller play() is called

app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
I was testing some things and taking screenshots for the blog post when I encountered some issues.
**Changes**
- Hide "manage servers" in preferences when there are no servers
- Looked really stupid when opening the settings on first use of the app
- Close ServerFragment when the server is removed from preferences
- So this probably never happens for anyone (why would you remove a server you just opened?) but still a bug
**Issues**
=> Login screen bugfixes while testing for release

app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CustomListRowPresenter.java, app/src/main/res/drawable/ripple.xml, app/src/main/res/layout/view_card_default.xml, app/src/main/res/layout/view_card_legacy_image.xml
**Changes**
- Fix ripple effect in LegacyImageCardView
- (used pretty much everywhere in the app)
- Previously, the effect would go over the text underneath the image. This looked off.
- Now it only shows on top of the image part
- Add ripple effect to DefaultCardView
- (used for users in the login screen)
- Show ripple on top of the image part
- Remove some unused stuff from CustomListRowPresenter
**Issues**
=> Add ripple effect to DefaultCardView and fix the one in LegacyImageCardView

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
We should never hit this, unless someone is manually tweaking values in
the debugger or there's a random cosmic bit flip.... but it still results in a hard 
crash as %d is for an `int`, not a `double`.
I've also added something to the debug logs for when a user changes playback speed, 
as there is currently no logging to indicate if someone is using a custom speed from the logs
=> Fix a potential crash in VideoManager with invalid speed

app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragment.kt
Ideally we'd stop the music too but calling the MediaManager.stopAudio function will crash the app because it still uses the API. Until we have the playback rewrite code, which uses coroutines that we can await, there is no simple solution. So audio will keep playing for now and the state gets a bit funky after signing in again. (the audio still plays but the UI Doesn't show anything as playing..)
**Changes**
- Fix app crash when switching users while music is playing
**Issues**
=> Fix app crash when switching users while music is playing

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
**Changes**
* added mkv transcoding profile for exoplayer so AC-3 audio can still be played when HLS is disabled
* use playerErrorEncountered for live-tv
* simplified a statement
* added a null check for mFragment
**Issues**
* likely fixes #1514
> * playback failed due to a lack of AAC support. The user says they didn't have issues in beta 4 so it's likely that they 
relied on AC-3 support.
> * playback failing resulted in an infinite retry loop
* when live tv infinitely retries after errors, mfragment was used as context for the new session. I think this may have prevented the old instance from being GCd
=> add mkv transcoding profile for explayer, use playerErrorEncountered for live-tv to avoid infinite retries

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* modes that have the same resolution as the default mode will rank higher than other modes. This will hopefully result in the resolution changing in addition to the refresh rate only if there are no other options.
**Issues**
#1482 
**Notes**
* My display doesn't support the refresh rates needed for this feature. Someone else will need to test it.
=> prefer changing refresh rate without changing resolution

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/action/SelectAudioAction.java
**Changes**
* catch `leanbackOverlayFragment` being null in `setCurrentTime()`
* catch `StreamInfo info` being null in `getInPlaybackSelectableAudioStreams()`, and catch it then returning null in `SelectAudioAction`
* only clear `primaryActionsAdapter` and `secondaryActionsAdapter` if they are not empty
**Issues**
tracepot:
* https://app.tracepot.com/app/75387/release/1a07276a0001267b
`java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.playback.overlay.LeanbackOverlayFragment.updateCurrentPosition()' on a null object reference`
* https://app.tracepot.com/app/75387/release/1d115b860001267b
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList org.jellyfin.androidtv.data.compat.StreamInfo.GetSelectableAudioStreams …
=> three crash fixes from tracepot issues

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java, app/src/main/res/values/strings.xml
**Changes**
* clicking on an item in the audio queue on the home screen now either:
(for other actions, long click on the item to open the context menu)
> * opens the `NowPlayingActivity` if it's the first item in the row
> * otherwise, plays the item without opening `NowPlayingActivity`
* changed the buttons in the context menu for audio items:
> * only show 'play from here' if:
>> * if not in `NowPlayingActivity` since a single click on an item will play it
>> * the item isn't the currently playing one (the previous code didn't properly do this)
> * added a 'toggle shuffle' button
> * moved the 'favorite' button closer to the top
> * added a 'clear queue' button since we can now do this without crashing the app
* changed the values in `KeyProcessor` for MENU_MARK_FAVORITE, MENU_PLAY, …
=> reworked context menu for audio queue, removed buttons for video queue

app/src/main/java/org/jellyfin/androidtv/ui/AlphaPickerView.kt, app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt, app/src/main/java/org/jellyfin/androidtv/ui/ExpandableTextView.kt, app/src/main/java/org/jellyfin/androidtv/ui/FadeViewSwitcherLayout.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpButtonsView.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/DurationSeekBarPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListPreference.kt, app/src/main/res/layout/dream_library.xml, app/src/main/res/layout/fragment_next_up.xml
We have quite a bit custom views. A lot of them, unfortunately, still written in Java. This PR only focusses on the Kotlin based views.
**Changes**
- Use consistent naming for custom views
- End with "Layout" for layouting (FadeViewSwitcherLayout)
- End with "Preference" for preferences
- End with "View" for all other views
- Always use this particular constructor, with defStyleRes omitted if the extended view does not support it (like AppCompatTextView)
```kotlin
class MyAwesomeCustomView @JvmOverloads constructor(
context: Context,
attrs: AttributeSet? = null,
defStyleAttr: Int = 0,
defStyleRes: Int = 0,
) : View(context, attrs, defStyleAttr, defStyleRes)
```
**Issues**
=> Use consistent naming & constructors in custom views

app/src/main/java/org/jellyfin/androidtv/ui/preference/category/about.kt
Before
After
**Changes**
- Add app name and flavor to version in about section
- This is now consistent with the version shown in the server selection screen
**Issues**
=> Add app name and flavor to version in about section

app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/DurationSeekBarPreference.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/RichListPreference.kt
Fix regression from #1540. The preference views have default style attribute values which were accidentally removed causing the app to crash when a preference view was displayed.
**Changes**
- Set defStyleAttr for DurationSeekBarPreference, RichListPreference and ButtonRemapPreference
**Issues**
=> Fix preferences crashing

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
**Changes**
Select cancel by default on confirmation dialog
Select cancel so a user doesn't accidentally delete media by hitting
delete twice. Since we ask it's worth adding this extra step, if we need
to remove the extra step it's arguable we can completely remove alert
dialog all-together
**Testing**
Ensure that the user account can delete media
- Go to a random video
- Attempt to delete
- Ensure cancel is selected by default
=> Make cancel default on delete/clear

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
In #1377 I changed the value from `5.414` to `434 / 79` (`5.4936708861`) because I couldn't find the original values used to calculate the ratio. I've now found the values in jellyfin-web to be `1000 / 185` (`5.4054054054`).
**Changes**
- Change value of ASPECT_RATIO_BANNER to match jellyfin-web (and it's value before #1377)
**Issues**
Should fix #1548 but unable to test as I don't have any banner images.
=> Fix ASPECT_RATIO_BANNER

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoSpeedController.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/VideoPlayerAdapter.java, app/src/test/kotlin/ui/playback/VideoSpeedControllerTests.kt
**Changes**
- Add handling for updating end time based on playback speed. This is a bit hacky due to the current architecture:
```
Exoplayer is built on the assumption that we
have bi-directional communication to our UI layer. Instead the
CustomPlaybackTransportControlGlue is uni-directional polling the video
manager.
We unfortunately have to use hacky poll tricks to work-around the fact
we can't wire up on the "onPlaybackParametersChanged" call to notify the
glue class to update its value. However, in the short-term a 5s "delay" between setting 
and updating is more favourable than setting up reverse listening support.
```
**Issues**
Fixes #1509 
**Testing**
- Play a video, check the finish time
- Change the speed to 0.25 and/or 2x
- Check the finish time updates accordingly (after 5s)
=> Add handling for updating end time based on playback speed

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* store the current exoplayer audio track index/id and reuse it instead of parsing `TracksInfo` every time `getExoPlayerTrack()` is called
**Issues**
* every time `reportProgress()` runs it gets the current audio index (calls `getExoPlayerTrack()`), which currently parses `TracksInfo`. I'm not sure how expensive this is but some users have reported worse performance in 0.13 specifically with exoplayer. This may be contributing to that.
=> only parse exoplayer TracksInfo when needed - instead of once every 0.5-2 seconds

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
Follows the documentation examples for replacing EventListener. The main
change is dropping the custom logic from "onPlayWhenReadyChanged" to
"onIsPlayingChanged" which handles the pause logic.
This is recommended in
https://exoplayer.dev/listening-to-player-events.html#playback-state-changes
Part of the work in #1547
=> Replace deprecated EventListener with Listener

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
Fix regression from #1547. The video manager is null at the end of a video, causing a crash when the next up screen was being loaded.
**Changes**
- Fix player crashing when video ends
**Issues**
=> Fix player crashing when video ends

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
**Changes**
Fixes a crash on the item details screen trying to get a badge image when the base item is null
(I really have no idea _why_ it is null in some cases)
**Issues**
N/A
=> Fix crash getting badge image with null base item

app/src/main/java/org/jellyfin/androidtv/integration/dream/LibraryDreamService.kt, app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LiveTvPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/GridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
I wanted to check if all sort fields we use in the app were added in https://github.com/jellyfin/jellyfin/pull/7492. Noticed that we don't always use the constants from the apiclient (yeah sorry SDK doesn't have them :p).
**Changes**
- Use ItemSortBy constants instead of hardcoded strings
- Use "SortName" instead of non-existing "Number" sort field in Live TV
- I looked at the usages of the value and it's actually always compared with the DatePlayed value, so we could even put gibberish in here. I chose SortName because there is one place where it uses SortName if the value is not DatePlayed
**Issues**
=> Use ItemSortBy constants instead of hardcoded strings

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/MarkdownRenderer.kt, gradle/libs.versions.toml
This pull request adds Markdown support for item descriptions and the server disclaimer (on the login screen). The renderSubtitles function in the PlaybackOverlay still uses HTML.
**Changes**
- Add Markwon dependency
- Add `MarkdownRenderer` class to create Markdown
- Support markdown (+basic HTML) for server disclaimer
- Support markdown (+basic HTML) for item overviews (descriptions)
**Issues**
- related: jellyfin/jellyfin-web#3355
=> Add markdown support for item descriptions and server disclaimer

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
This matches libVLC's normal default. Looking back in the project
history this was set to no stretching from the very start @commit
9528b9a3eef1244e32a7f54ed603b2c063bc5981
Since libVLC uses it by default and this wasn't a bug fix I propose we
can opt in the audio stretching by default. This should only trigger when
a user selects a playback speed that isn't 1x anyway.
For future reference, the original changeset was here:
https://github.com/jellyfin/jellyfin-androidtv/commit/9528b9a3eef1244e32a7f54ed603b2c063bc5981#diff-226bb739f67bb7dbde6485e2433c55b1cc25fff3fea24029e5344b0c396657b6R232
**Issues**
None on GitHub, but I have seen it mentioned on Reddit and I was planning on doing this anyway so...
**Testing**
- Ensure libVLC is forced
- Change the speed to 2x 
- It should …
=> libVLC: Switch to using audio time stretching by default

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/res/values/strings.xml
**Changes**
* renamed `play(long position, Integer transcodedSubtitle)` to `play(long position, @Nullable Integer forcedSubtitleIndex)`
* always clear the current subtitles when trying to switch streams. This already done in most cases.
* refactored how the player knows which subtitle track it should load, and which one is currently loaded.
> * `mDefaultSubIndex` is the track it _should_ load, it is set right away so we can check what should be loaded
> * `mCurrentOptions`'s `SubtitleStreamIndex` is what is currently in use. It is set to null until `onPrepared()` tries to switch subtitle streams. The exception is when burning in subtitles, and in this case it is also set when playback starts (not a new change).
* reworded the string for loading burnt-in subtitles
**Issues**
fixes #1566
=> fixed subtitles not clearing properly when switching (again)

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
**Changes**
* fixed crash when calling playFrom() where the player was unintentionally released
* clicking on an audio item will now:
> * open NowPlayingActivity if it is the currently playing item
> * use `playFrom()` to skip within the queue (and not affect things like shufffle, etc) if the item belongs to the queue
> * otherwise, start a new session by adding the items in the row to the queue and playing from the selected item's index. This means we can easily play all "last played" songs
* `playNow()` will loop through its input list and create a new list of only audio items. This protects against accidentally adding video items if an entire row is added to the queue. I don't know of any rows that have mixed A/V items but better safe than sorry, and the methods for adding to the video …
=> fixed playFrom() crash, support queueing entire row (eg: last played)

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt
0.14 will only support Jellyfin 10.8 >=. This will be enforced via the SDK (version 1.3).
**Changes**
- Remove 10.8 check for HLS support
- Partially reverts #1501
**Issues**
=> Remove 10.8 check for HLS support

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
This is the banner I used:
This is how it looked in 0.13.2
And this is how it looks after my new fix:
**Changes**
- Fix ASPECT_RATIO_BANNER again
- 1000/185=5
- 1000.0/185.0=5.4054054054-ish
**Issues**
- Fixes #1589
=> Fix ASPECT_RATIO_BANNER again

app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
LiveData is no longer the recommended way for live updates in UI. The kotlinx.coroutine flow API is the way to go. Fortunately we already have a bunch of flows in our code (SDK/some repositories) so the migration should be relatively easy.
Some resources:
- https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb
- https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
- https://developer.android.com/kotlin/flow
- https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
This PR migrates the user views repository code. I'm probably redoing this one at some point to make it use a websocket listener (update the value when the server tells us the libraries have changed).
**Changes**
- Migrate …
=> Migrate UserViewsRepository to Kotlin flow

app/src/main/java/org/jellyfin/androidtv/auth/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/AddServerAlertFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginAlertFragment.kt
LiveData is no longer the recommended way for live updates in UI. The kotlinx.coroutine flow API is the way to go. Fortunately we already have a bunch of flows in our code (SDK/some repositories) so the migration should be relatively easy.
Some resources:
- https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb
- https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
- https://developer.android.com/kotlin/flow
- https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
This PR migrates the login view model and server repository code.
**Changes**
- Migrate LoginViewModel and ServerRepository to Kotlin flow
**Issues**
=> Migrate LoginViewModel and ServerRepository to Kotlin flow

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupActivity.kt
LiveData is no longer the recommended way for live updates in UI. The kotlinx.coroutine flow API is the way to go. Fortunately we already have a bunch of flows in our code (SDK/some repositories) so the migration should be relatively easy.
Some resources:
- https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb
- https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
- https://developer.android.com/kotlin/flow
- https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
This PR migrates the session repository code. Fortunately, most usages on the Java side used ".getValue()" which exists in both livedata & flow, so not many changes were required.
**Changes**
- Migrate SessionRepository to Kotlin flows …
=> Migrate SessionRepository to Kotlin flows

app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt
LiveData is no longer the recommended way for live updates in UI. The kotlinx.coroutine flow API is the way to go. Fortunately we already have a bunch of flows in our code (SDK/some repositories) so the migration should be relatively easy.
Some resources:
- https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb
- https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda
- https://developer.android.com/kotlin/flow
- https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
This PR migrates the next up code.
**Changes**
- Migrate NextUp code to Kotlin flows
**Issues**
=> Migrate NextUp code to Kotlin flows

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* in `getSubtitleStreamIndex()`, use index from `mCurrentOptions` if valid and -1 otherwise. Following the changes in #1571 mDefaultSubStreamIndex isn't used to determine what's actually being used.
* in `switchSubtitleStream()` only modify `mCurrentOptions SubtitleStreamIndex` and `mDefaultSubIndex` if the subtitles loaded without errors
**Issues**
* if subtitles failed to load, the popup menu for choosing subtitles would show the wrong value/not have "none" selected. I assume reports to the server also used the index for the subtitles that failed to load.
=> fix getSubtitleStreamIndex returning the wrong index

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java
**Changes**
* when checking if the chosen item is currently playing, compare item IDs and check if item is in the audio queue instead of comparing objects
**Issues**
* clicking on the currently playing item in the now playing row would often fail the condition that opens the audio now playing activity, and instead just play it (which makes it restart)
**Notes**
* patches code added in #1568
=> patch for clicking on the playing item in the audio now playing row sometimes restarting the song

app/src/main/java/org/jellyfin/androidtv/auth/SessionRepository.kt
**Changes**
- Fix SessionRepository trying to fetch user data when session is null
**Issues**
Fix #1598
=> Fix SessionRepository trying to fetch user data when session is null

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java, app/src/main/java/org/jellyfin/androidtv/util/Utils.java, app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt, app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
**Changes**
- Require context in Utils.downMixAudio()
- I tried to use a proper context where possible but some places use TvApp.getApplication right now because ItemLauncher/MediaManager have no context.
**Issues**
=> Require context in Utils.downMixAudio()

app/src/main/java/org/jellyfin/androidtv/ui/shared/AppThemeCallbacks.kt, app/src/main/java/org/jellyfin/androidtv/ui/shared/AuthenticatedUserCallbacks.kt
It's a bit difficult to test the AuthenticatedUserCallbacks one because it only triggers on crashes and we fixed most of those..
**Changes**
- Update activity lifecycle callbacks to act before activity lifecycle events trigger
- Update AuthenticatedUserCallbacks comment
**Issues**
=> Update activity lifecycle callbacks to act before activity lifecycle events trigger

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
- Refactors the video option building from `PlaybackController:play` into private methods. This first step was done as-is so no modifications were made to the actual methods
- Removes the three call sites to `Utils.getMaxBitrate` to a single location
This is a precursor to #1569 and should allow us to:
- Make sense of the diff in the next PR
- Allow us to easily refactor away deprecated `VideoOptions` when the replacement
- Makes the code more readable
**Testing**
- Try to play a video with libVLC and ExoPlayer
=> Refactor play logic in PlaybackController

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackControllerNotifiable.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
Builds on #1574 
**Changes**
Many call-backs already exist between the VideoManager and
PlaybackController. But they are created on an ad-hoc basis in various
methods.
By extracting these out to a method it means we can:
- Remove the boilerplate of @Override methods in PlaybackController
- Easily refactor these into a seperate class long-term
- Add new handlers
- Pass parameters around in the future
- Not have everything dispatch to a simple onEvent.
This also makes extending the interface easier where we have exoplayer
only notifications (such as onPlaybackSpeedChanged). Since the VLC code
can simply call the notifier without going through a PlaybackListener
--
I'm not super happy with `PlaybackControllerNotifiable` so I'm open to any/all suggestions on this front, maybe something along …
=> Refactor existing callbacks into interface

.github/workflows/app-build.yaml, .github/workflows/app-lint.yaml, .github/workflows/app-test.yaml, .github/workflows/gradlew-validate.yaml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

app/src/main/java/org/jellyfin/androidtv/data/eventhandling/SocketHandler.kt
The updateCredentials() function doesn't perform any action when the connection errored. It might also not do anything when disconnected when the credentials haven't changed. By checking for these states and calling the reconnect function we can be sure a new connection is attempted when updateSession() is called (app start / user switch).
**Changes**
- Construct SocketInstance early so we don't need to check for nullability
- Add public state to SocketHandler
- Improve updateSession() logic
**Issues**
=> Fix WebSocket connection not always reconnecting on session start

app/build.gradle.kts, app/src/main/java/org/jellyfin/androidtv/constant/HomeSectionType.kt, app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LiveTvPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemEnum.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemMutable.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/HomePreferencesScreen.kt, preference/build.gradle.kts, preference/src/main/AndroidManifest.xml, preference/src/main/kotlin/Preference.kt, preference/src/main/kotlin/PreferenceEnum.kt, preference/src/main/kotlin/migration/MigrationContext.kt, preference/src/main/kotlin/migration/MigrationEditor.kt, preference/src/main/kotlin/store/AsyncPreferenceStore.kt, preference/src/main/kotlin/store/PreferenceStore.kt, preference/src/main/kotlin/store/SharedPreferenceStore.kt, preference/src/test/kotlin/PreferenceStoreTests.kt, settings.gradle.kts
Another one from my "short term" list (was only added like 6 months ago!). This PR moves the core logic for preferences to a separate module. This is part of an effort for modularization of the app, just like how the new playback code is in it's own module.
**Changes**
- Move preference library code to it's own module
- this does not include the user interface code (yet)
- Update package from "org.jellyfin.androidtv.preference" to "org.jellyfin.preference"
- Move some stuff around in the PreferenceStoreTests
**Issues**
=> Move preference code to new preference module

app/src/main/java/org/jellyfin/androidtv/preference/AuthenticationPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LibraryPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/LiveTvPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/PreferencesRepository.kt, app/src/main/java/org/jellyfin/androidtv/preference/SystemPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserSettingPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/store/DisplayPreferencesStore.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/DisplayPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemEnum.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsItemMutable.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/HomePreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/CoroutineUtils.kt, preference/src/main/kotlin/Preference.kt, preference/src/main/kotlin/migration/MigrationEditor.kt, preference/src/main/kotlin/store/AsyncPreferenceStore.kt, preference/src/main/kotlin/store/PreferenceStore.kt, preference/src/main/kotlin/store/SharedPreferenceStore.kt, preference/src/test/kotlin/PreferenceStoreTests.kt
Some changes to make it easier to work with and maintain the preference code. Blocking function calls removed from the module and replaced with a utility function in the app (only needed for Java compat right now).
**Changes**
- Allow migrations in all store types
- Remove blocking functions from the preference module
- Move Preference.xx functions to global functions
**Issues**
Depends on ##1619
=> Refactor preference code

app/src/main/java/org/jellyfin/androidtv/di/PlaybackModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/rewrite/PlaybackForwardingActivity.kt, gradle/libs.versions.toml, playback/build.gradle.kts
This is a small PR bringing some of the changes from my WIP playback rewrite to the master branch. It's nothing fancy, mostly stuff that makes it easier to rebase the WIP branch.
**Changes**
- Update some formatting
- Changed some comments
- Added some dependencies
- Updated some build scripts
**Issues**
Part of #1057
=> Update playback rewrite build files

app/src/main/java/org/jellyfin/androidtv/ui/startup/LoginViewModel.kt
The storedServers was empty when the StartupActivity called getLastServer(). Fixed by loading the servers first.
**Changes**
- Load servers before searching the last active server
**Issues**
=> Fix not opening last active server on authentication clearance

app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
The getResumeItems operation includes the video you're watching when the cal is made, 10.8 added a new option to exclude those items and only show the resumable video that is not being watched at the time of calling the API.
**Changes**
- Add excludeActiveSessions optino to getResumeItems (introduced in 10.8)
**Issues**
=> Hide currently watching video from next up integration

app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
I've recently added a bunch of extras to various series I'm watching and for some reason when playing items it would automatically add the previews/trailers/etc to the video queue even though it's in  the extra folders. Fixed by specifying the season id when building the queue.
**Changes**
- Add season id when querying video queue based on episode
**Issues**
=> Add season id when querying video queue based on episode

app/src/main/java/org/jellyfin/androidtv/ui/preference/custom/ButtonRemapPreference.kt
The change listener was never called so the value was never saved. I guess this feature never worked since it was added lol.
**Changes**
- Fix button remapping not saving the new button
**Issues**
Fixes #1677
=> Fix button remapping not saving the new button

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* removed a debug log line that isn't useful anymore
* copied the video manager init logic and definition of `useDeinterlacing` into `onError()` from:
https://github.com/jellyfin/jellyfin-androidtv/blob/9feaf107b24b289718ab69b21953f6271674916d/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java#L677-L679
and
https://github.com/jellyfin/jellyfin-androidtv/blob/9feaf107b24b289718ab69b21953f6271674916d/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java#L634-L637
**Issues**
* With transcoding disabled for a user, playback of files with ASS subtitles in libVLC would fail to start. This is due to `getVideoStreamInfo()` failing to produce a valid stream URL for exoplayer because it isn't allowed to transcode. Where playback actually …
=> initialize video manager when falling back to vlc after getting stream info for exoplayer fails

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/preference/constant/RefreshRateSwitchingBehavior.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/res/values/strings.xml
**Changes**
* Changed refresh rate switching setting (boolean) to enum (`disabled`, `scale on tv`, `scale on device`) and added a migration that migrates an old value of `true` -> `scale on tv`. `scale on tv` is chosen because scaling on the device seems to only be useful for devices like Nvidia Shield, which has "AI upscaling".
* added some extra logging to `findBestDisplayMode()` so that every mode will be logged
* standardized the logging format for printing "resolution@refresh rate" in `findBestDisplayMode()`: `%dx%d@%f`
**Issues**
fixes #1646
**Notes**
My display config doesn't support refresh rate or resolution switching so someone else will need to test this.
=> Use enum for refresh rate switching setting - allow choosing between scaling on device or on tv

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/res/layout/vlc_player_interface.xml
**Changes**
* add an additional search and replace to convert newlines into `<br>`. Subtitles that use line-feed only (`\n`) can now be parsed in addition to CRLF (`\r` + `\n`), which was previously the only format parsed.
* removed `gravity="center"` for the subtitle TextView
**Issues**
* Fixes #1633 caused by #1572
* With `.srt` subtitles as an example, some use the "line-feed only" format, which wasn't handled. Because of this, subtitles which should be displayed as multiple lines could display as only one.
**Notes**
* I have tried a few things including adding an `AlignmentSpan` to get the `PaddedBackgroundSpan` to draw its background around the centered text. Unfortunately, this didn't work. Working with spans is a pain, and it seems like a solution that allows for centered text and …
=>  Fix srt newline parsing, revert subtitle alignment back to left align

.github/workflows/app-publish.yaml
This should fix the publish CI while keeping the default token read-only. Remind me to cherrypick it to the 0.13 branch if we do a 0.13.5 👀.
**Changes**
- Use JF_BOT_TOKEN in app-publish workflow
**Issues**
=> Use JF_BOT_TOKEN in app-publish workflow

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
So the "v" variable was not an instance of TextUnderButton but an ImageButton (the inner view of the TextUnderButton). This bug is already fixed in 0.14 because I remade the TextUnderButton.
The casting failed and threw an exception, but the apiclient onResponse handler catches all exceptions and ignores them lol.
**Changes**
- Fix favorite button in item list view in 0,13
**Issues**
=> Fix favorite button in 0.13.z

app/src/main/java/org/jellyfin/androidtv/ui/ServerButtonView.kt, app/src/main/java/org/jellyfin/androidtv/ui/card/DefaultCardView.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/util/MenuBuilder.kt, app/src/main/res/values/integers.xml
**Changes**
- Move DefaultCardView animation duration to integers.xml
- Add MenuBuilder and DefaultCardView.setPopupMenu to easily create context menus for cards
- Add context menu to the users in the server screen:
- Logout
- Remove
- Add context menu to stored servers in the server select screen:
- Remove
Just a popup menu
**Issues**
=> Add context menus to startup fragment

app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* Added a `VideoManager` method to offset stream indexes for player track index <- -> MediaStream list index mapping. This accounts for external streams being at the beginning of the list. When mapping a MediaStream index to a player index, the index is decremented by 1 for every external track found prior to the embedded tracks in the list. It's incremented by 1 going player -> MediaStream.
* rearranged `getAudioStreamIndex()` so that, similar to how we keep track of which subtitle index is currently in use, `mCurrentOptions.AudioStreamIndex` is used to query the current index after it's set. This avoids the potentially expensive calls to the player APIs and looping through all the tracks every time we want to get the index.
* removed `exoplayerAudioIndex` from …
=> fix player track selection - offset MediaStream indexes to account for external tracks

app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
**Changes**
* add Vimu external player support
* add better title support on external playback
* add filename to mx player extras
* fix mPosition conversion to int
* add detection for playback completion
=> Add Vimu external player support and fix some MX Player issues

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
Previously the app would occasionally show volley clienterror toasts that provide 0 feedback to the end-user about the issue. Now the error is propagated to the RetrieveFinishedListener (in StdGridGragment and SearchRunnable) which both casually ignore the error.
**Changes**
- Remove stupid volley clienterror toast
- Send exceptions to RetrieveFinishedListener where they can potentially be better handled
**Issues**
=> Propagate errors from ItemRowAdapter to RetrieveFinishedListener

app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt, app/src/main/java/org/jellyfin/androidtv/ui/GridButton.kt, app/src/main/java/org/jellyfin/androidtv/ui/NowPlayingView.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/card/DefaultCardView.kt, app/src/main/java/org/jellyfin/androidtv/ui/card/LegacyImageCardView.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpItemData.kt, app/src/main/java/org/jellyfin/androidtv/ui/playback/nextup/NextUpViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/GridButtonPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/res/layout/activity_audio_now_playing.xml, app/src/main/res/layout/fragment_next_up.xml, app/src/main/res/layout/view_card_default.xml, app/src/main/res/layout/view_card_legacy_image.xml, app/src/main/res/layout/view_now_playing.xml, app/src/main/res/layout/view_row_details.xml, app/src/main/res/layout/vlc_player_interface.xml
The AsyncImageView makes it easier to load images with an optional placeholder and blurhash. This change is a part of something bigger I'm working on, extracting it to make that PR smaller.
**Changes**
- Add AsyncImageView
- Use AsyncImageView in DefaultCardView
- Use AsyncImageView in NextUpFragment
- Use AsyncImageView in FullDetailsActivity poster
- Use AsyncImageView in AudioNowPlayingActivity poster
- Use AsyncImageView in LegacyImageCardView
- Use AsyncImageView in CustomPlaybackOverlayFragment logo
- Use AsyncImageView in NowPlayingView
- Use AsyncImageView in ItemListActivity
- Remove unused imageUrl from GridButton
**Issues**
=> Add AsyncImageView

app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/res/layout/guide_filter_popup.xml, app/src/main/res/layout/guide_options_popup.xml, app/src/main/res/layout/new_program_record_popup.xml, app/src/main/res/layout/popup_empty.xml, app/src/main/res/layout/program_detail_popup.xml, app/src/main/res/layout/settings_popup.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme_jellyfin.xml
**Changes**
- Use popup menu styling for popup windows
The AlphaPicker popup when using the purple theme.
The audio/sub delay thingy when using purple theme.
**Issues**
=> Use popup menu styling for popup windows

app/src/main/java/org/jellyfin/androidtv/ui/search/SearchActivity.kt, app/src/main/res/layout/fragment_search_text.xml, app/src/main/res/values/styles.xml
Depends on #1744 because I forgot to switch to master
**Changes**
- Check for RECORD_AUDIO permission in SearchActivity
- Add textColorHint to Input.Default
- Restyle TextSearchFragment
- Now uses new input style
- Shows the logo in the same position as home screen
**Issues**
=> Restyle TextSearchFragment

app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/AuthPreferencesScreen.kt
When opening the AuthPreferencesScreen without another part of the app (pre-)loading the stored servers the list would be empty. This issue never really showed until #1756 which skips the server selection screen.
**Changes**
- Fix AuthPreferencesScreen sometimes not showing any servers/users
**Issues**
=> Fix AuthPreferencesScreen sometimes not showing any servers/users

app/src/main/java/org/jellyfin/androidtv/util/profile/LibVlcProfile.kt
Fixes EAC3 transcoding in libvlc of 10.8.0-beta3
**Changes**
Previously, it would transcode when EAC3 files are played (especially audio channels ≥ 6), and if direct play is forced, they do not play at all with the error `Cannot play this video format`. Therefore, I added the codec EAC3 as an audio profile to the libVLC profile. This has fixed the issue where when EAC3 files are played using libvlc on Jellyfin, it resorts to transcoding on Jellyfin Server v10.8.0-beta3.
**Issues**
Fixes #1723
=> Fix EAC3 transcoding in libvlc on 10.8.0-beta3

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java
**Changes**
Make sure we reset the StartIndex, since the Query object is reused, otherwise all following queries will break.
**Issues**
Issue steps:
* start a library/grid view with a lib > 50 entries
* change focus until retrieveNext() is triggered via loadMoreItemsIfNeeded()
* now enable any filter like "watched" or "favorites"
* the "new" query will have the StartIndex, from the last retrieveNext() call and either display nothing or some single items or a mix of other stuff depending on the set "sortby" filter
PS: @nielsvanvelzen just a quick fix that drove me crazy, since i though my refactor stuff was the cause, yet turned out its a master branch bug.
=> Fix ItemRowAdapter.retrieveNext() Query StartIndex

app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/shared/PaddedLineBackgroundSpan.kt, app/src/main/res/layout/vlc_player_interface.xml
**Changes**
* Set the subtitle text alignment (gravity) to 'center'
* Get the alignment value from the TextView and pass that to the PaddedLineBackgroundSpan so it can set its rect size accordingly.
* Use the horizontal absolute gravity to create the size of the span background
**Issues**
* Fixes #1565
* PaddedLineBackgroundSpan only worked for left/start alignment
=> fix subtitle background alignment, center subtitle text

app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java
**Changes**
onResponse will set the wrong Countertext/pos if it was triggered by loadMoreItemsIfNeeded, resulting in a "1" position, instead of the current selected one.
=> Fix wrong counter/pos onResponse via loadMoreItemsIfNeeded

app/src/main/java/org/jellyfin/androidtv/ui/playback/GetPlaybackInfoResponse.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackManager.java
**Changes**
- fix server broken "-rangetype" behavior
- fix don't send -1 subIndex
- fix DlnaProfileType
**Issues**
In transcode cases the client will always trigger a video-stream transcode, since the rangetype is always missing.
Hotfix until jellyfin/jellyfin#8078 is merged and we get a new server release.
=> fix, don't send invalid sub/audio index

app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt
(Targets 0.13.z release branch)
**Changes**
- Disable current ACRA implementation because Tracepot is dead
- 0.14 introduces the new crash reporting so this is only temporary until 0.14 is released
**Issues**
=> Disable Tracepot crash reporting

app/src/main/java/org/jellyfin/androidtv/data/repository/NotificationsRepository.kt
**Changes**
- adjust TV detection logic
**Issues**
All TV media boxes running normal Android, instead of AndroidTV will fail this check. 
All none AndroidTV certified devices run Android, which is the largest segment for TV media devices. 
The main reason is the harder AndroidTV certification process and licensing cost, so this will not change in the future.
So we should never rely on anything specific AndroidTv related.
=> adjust TV detection logic

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/util/sdk/TrailerUtils.kt
From my observations this doesn't completely work in the emulator because the YouTube app crashes for some reason. It worked fine on my shield. The YouTube app also "traps" the user by going back to it's own home screen instead of our app when pressing back, so the UX is pretty terrible. Not much to do about that unfortunately. I expect third-party YouTube apps to behave better but haven't tested those.
The "trailer" row is not shown for external trailers, it's only the button that shows up for external ones. The code tries to play any of the remote trailers before falling back to local trailers. If nothing works it will show a toast that playback failed.
**Changes**
- Add ability to open external trailers
**Issues**
=> Add external trailer support

app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt, app/src/main/java/org/jellyfin/androidtv/di/AuthModule.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt, app/src/main/res/layout/fragment_server.xml, app/src/main/res/values/strings.xml
**Changes**
- Validate server version on session restore
- This prevents autologin from opening a 10.7 server (which is incompatible)
- Show notification when server version is not supported
- Shows on the user selection screen, it's kinda big:
Note that trying to add a user or selecting one also shows an error that the server is outdated. The server information update when opening this screen and when restoring a session (with a ratelimit of once every 10 minutes). So if the user updates their server and reopenens the app the info should update and go back to autologin.
**Issues**
=> Validate server version on session restore and show outdated server notification

app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreServer.kt, app/src/main/java/org/jellyfin/androidtv/auth/model/Server.kt, app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt, app/src/main/java/org/jellyfin/androidtv/data/service/BackgroundService.kt
10.8.1 change
**Changes**
- Save splashscreenEnabled property to server in authentication store
- Don't try to load splashscreen when disabled in branding options
**Issues**
=> Don't try to load splashscreen when disabled in branding options

app/src/main/java/org/jellyfin/androidtv/auth/repository/ServerRepository.kt
This issue only happens when using the function within a 10 minute window and causes login to fail (without any hints as to why)
**Changes**
- Properly return the original server info when there is no updated server info in ServerRepository.getServer
**Issues**
=> Fix serverRepository.getServer not working when server info is not refreshing

app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
We don't show them in that screen, so no need to flood the network
**Changes**
- Ignore server discovery in ServerFragment
**Issues**
=> Ignore server discovery in ServerFragment

app/src/main/java/org/jellyfin/androidtv/telemetry/TelemetryService.kt
Until the user signs in to a server the report url and token are not set. We throw an exception in this case so ACRA automatically retries sending the report later.. One issue though: the exception was thrown from the wrong place.
**Changes**
- Move throwing of ReportSenderException to the sender, this causes ACRA to retry the report later
**Issues**
=> Fix crash when reporting a crash

app/src/main/java/org/jellyfin/androidtv/auth/repository/SessionRepository.kt
We don't want to update the crash url/token when there is no session. That causes a crash.
**Changes**
- Don't update crash reporting url/token when session is null
**Issues**
=> Fix crash when not restoring a session

app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/SelectServerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
When switching between the user and server selection screens the process continuously restarted. This causes a lot of logs and network activity. Prevent this by running only one process at a time.
**Changes**
- Add mutex to only run one discovery process at a time
**Issues**
=> Avoid multiple discovery processes running at the same time

app/src/main/java/org/jellyfin/androidtv/util/apiclient/ReportingHelper.java
Issue found during final testing phase for 0.14. When music is playing while switching sessions the app would crash because it tried to report the music stopping to the server. At this point the session is already cleared so it caused an NPE.
Changed to check if the session is null and do nothing in that case. The music stopping is now not reported so the server does think the client is still playing, but this will timeout eventually.
Proper fix in playback rewrite at some point in time
**Changes**
- Fix app crash when switching users while playing music
**Issues**
=> Fix app crash when switching users while playing music

app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/ServerFragment.kt
Issue found during final testing phase for 0.14. When installing the client with no previous data you will likely use the following flow:
1. Add server via discovery
2. Press public user to sign in
This opened the password input instead of the quick connect screen because we can't limit a QC login to just a specific user. This is annoying though because you'd need to input a password.
I changed it to always show the quick connect screen. If you enter the code as a different user everything still works fine, just a bit confusing because you don't end up signed in as the user initially used.
**Changes**
- Always show quick connect screen
**Issues**
=> Always use Quick Connect

app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java
**Changes**
Prevents "null" from showing up in the info row / subheading while browsing. I noticed this in the live tv view when a (iptv) channel had no number.
**Issues**
N/A
=> Fix null text in info row

app/src/main/res/values/styles.xml
Amazon changes the platform Button widget to scale when pressed, this doesn't work nice with some of our custom button styles and is not consistent with other platforms. This change removes the animation.
**Changes**
- Remove stateListAnimator from button styles
**Issues**
=> Remove stateListAnimator from button styles

app/src/main/res/drawable/ic_record_series_red.xml, app/src/main/res/values/colors.xml
**Changes**
The recording icons were using two different shades of red. This updates the icons to both use the same (less harsh) red color.
**Issues**
N/A
=> Fix inconsistent red color for recordings

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/res/menu/menu_details_more.xml
**Changes**
Updates the button ordering on the item details screen to try to be more consistent:
1. Shuffle button is now before the Play Trailers button (this is the order in web and I think shuffle is more likely to be used more frequently)
2. Button order in the "Other Options" menu should better match their order when not in the menu
One oddity in the current code is that the Watched button never moves to the menu even though buttons preceding it do... Should this be updated so it will move to the menu before the others (primarily happens with the Play Trailers button for series)?
**Issues**
N/A
=> Update button order on item details screen

app/src/main/res/layout/live_tv_guide.xml
**Changes**
Fixes some styling issues with the filter/setting buttons on the live tv guide
* Fixes highlight tint of icon by using the `Button.Icon` style
* Increases the right margin to align with the clock and prevent buttons being in the overscan area
* Reduces the padding of the filter button so it is more consistent with the size of the other button icons
**Issues**
N/A
=> Fix live tv guide option button styles

app/src/main/java/org/jellyfin/androidtv/auth/repository/AuthenticationRepository.kt
**Changes**
This makes the "Unable to connect" message appear when trying to sign into an unavailable server instead of the one claiming invalid credentials by having `AuthenticationRepository` emit the `ServerUnavailableState` when authentication with credentials fails due to a network error.
Possibly this `catch` Block should also be added to the other authentication methods.
Depends on https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/442 for the appropriate exception to be raised.
**Issues**
None
=> Fix sign-in screen claiming invalid credentials when server is unavailable

app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java, app/src/main/java/org/jellyfin/androidtv/ui/GuidePagingButton.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
* Fixes the height of the load more/previous channels buttons in the live tv guide.
* Adds constant values for the guide row height and pixel per minute values, so they aren't defined 20 different times.
(I'll open a separate PR to address the terrible styling of the buttons)
**Issues**
Fixes #1543
=> Fix live tv guide load more button height

app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/res/drawable/tile_square_tv.xml, app/src/main/res/drawable/tile_tv.xml
**Changes**
* Makes the default aspect ratio for channels square (1.0)
* Changes the scale type to fit center so logos do not overflow the view
* Adds a square tv icon resource to use as a default
**Issues**
Fixes #1773
=> Fix channel logo display

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/livetv/TvManager.java
**Changes**
Fixes the sorting options not working in the live tv guide by removing the client side sorting and caching of channel orders... this matches the web implementation that just queries the channels endpoint when the order is changed
**Issues**
I couldn't find one, but it has annoyed me forever...
=> Fix live tv guide sorting

app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java
**Changes**
* `offsetStreamIndex()` can now account for a players indexing from 1 (exoplayer starts at 1, libVLC starts at 0)
* return `true` when trying to set a track with exoplayer and it is already selected. Returning false indicates an error/that transcoding may be needed so the stream is recreated, and that is not needed in this situation.
**Issues**
* fixes #619 
* exoplayer track indexes start at 1 but somewhere in the several refactors accounting for this was left out.
mentioned here:
https://github.com/jellyfin/jellyfin-androidtv/pull/1732#issuecomment-1159758029
=> handle exoplayer track selection indexes starting at 1

app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
**Changes**
Removes whitespace being prepended to the "No Program Data Available" message for reasons unknown
**Issues**
N/A
=> Remove whitespace prepended to the no gude data titles

app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/CustomizationPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt, app/src/main/res/values/strings.xml
Both were unused
**Changes**
- Remove seasonal greetings preference
- Remove libvlc subtitle delay preference
- Remove related strings
**Issues**
=> Remove seasonal greetings & libvlc subtitle delay preferences

app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditServerScreen.kt, app/src/main/java/org/jellyfin/androidtv/ui/startup/preference/EditUserScreen.kt
Update authentication preferences to throw errors instead of silently returning for invalid state. This should help us with debugging auth issues.
**Changes**
- Throw error when EditServerScreen and EditUserScreen open with invalid arguments
**Issues**
Should help with #1790
=> Throw error when EditServerScreen and EditUserScreen open with invalid arguments

app/build.gradle.kts
This should fix our reproducible builds for F-Droid.
**Changes**
- Remove generation timestamp from AboutLibraries data file
**Issues**
Fix #1639
Ref https://github.com/mikepenz/AboutLibraries/issues/784
=> Remove generation timestamp from AboutLibraries data file

detekt.yaml
It doesn't work properly because we don't have an org/jellyfin/androidtv package in the playback and preference modules
**Changes**
- Disable Detekt InvalidPackageDeclaration rule
**Issues**
=> Disable Detekt InvalidPackageDeclaration rule

app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java
**Changes**
Just wrap the refresh in a try() block, wont solve the root-cause, but at least the app does not crash anymore.
**Issues**
Fixes #1929
Fixes #1903
Fixes #1859
=> fix BaseRowItem.refresh() crash

app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java, app/src/main/res/menu/menu_details_more.xml, app/src/main/res/values/strings.xml
The scope Android TV client is to USE the Jellyfin server, not to MANAGE it. While it makes sense for some stuff to have a delete function (like Live TV recordings) it doesn't for actual media. This PR removes all item deletion except for Live TV stuff.
**Changes**
- Remove item delete functionality
**Issues**
=> Remove item delete functionality

app/src/main/java/org/jellyfin/androidtv/constant/QueryType.kt, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRecordingsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseRowDef.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/BrowseViewFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/EnhancedBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/GenericFolderFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdBrowseFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdRowsFragment.java, app/src/main/java/org/jellyfin/androidtv/ui/home/HomeFragmentBrowseRowDefRow.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemLauncher.java, app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/ItemRowAdapter.java, app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java, app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java, app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
Removed some old code that shouldn't be used anymore. See the attachment below for the diff I made for the item types between apiclient<>SDK. There is one special type "SeriesTimer" which I believe never existed in the server but was a lazy hack in FullDetailsActivity: https://github.com/jellyfin/jellyfin-androidtv/blob/fea1236559e5d9752f5105fed7821ead556a1619/app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java#L385-L393
So I kept that one for now.
**Changes**
- Remove usages of BaseItemType's that don't exist in the server/SDK
**Issues**
```
ChannelVideoItem
MovieGenre
MovieGenreFolder
MusicGenreFolder
RecordingGroup
SeriesTimer
AudioBook
BasePluginFolder
Book
LiveTvProgram
ManualPlaylistsFolder
PlaylistsFolder
TvProgram
UserRootFolder
Year
```
=> Remove usages of BaseItemType's that don't exist in the server anymore

app/src/main/java/org/jellyfin/androidtv/ui/playback/MediaManager.java, app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
**Changes**
* sync video queue pos between `playbackController` and `mediaManager`
set the video queue index in `mediaManager` via `playbackController` in `next()`, `prev()`, and `itemCompleted()`
* delete `removePreviousQueueItems()`
it was used to clear already-played items from `playbackController` before opening NextUp because there previously wasn't support for starting playback from a specific video queue index (added in #1939)
* simplified `itemComplete()`
**Issues**
* Needed for #1941 to be fully functional. As discussed there, the `previous` button will break if the previous video queue items have been removed by `removePreviousQueueItems()` 😂
**Notes**
* Managing the video queue and its position in both `playbackController` and `videoManager` and then syncing them is kinda lame. …
=> fix NextUp not working without clearing old video queue items

app/build.gradle.kts, playback/build.gradle.kts, preference/build.gradle.kts
Required for the new appcompat version (#1954)
**Changes**
- Bump Android compile and target SDK to 32 (Android 12L)
**Issues**
=> Bump Android compile and target SDK to 32 (Android 12L)

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/di/AppModule.kt, app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt, app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/PhotoPlayerActivity.java, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerActivity.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerFragment.kt, app/src/main/java/org/jellyfin/androidtv/ui/picture/PictureViewerViewModel.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/DeveloperPreferencesScreen.kt, app/src/main/java/org/jellyfin/androidtv/util/KeyHandler.kt, app/src/main/res/drawable/button_bar_back.xml, app/src/main/res/drawable/button_icon_tint_animated.xml, app/src/main/res/drawable/ica_play_pause.xml, app/src/main/res/layout/fragment_picture_viewer.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
I started work on this around 2 months ago but didn't completely finish it yet. It already uses a feature flag which is disabled in releases so it won't hurt to merge it. I've made a new column in my board (https://github.com/jellyfin/jellyfin-androidtv/projects/15#column-19021853) that shows the remaining tasks.
The biggest feature is that it doesn't depend on the media manager anymore so it's sort of a part of the playback rewrite (#1057).
**Changes**
- Add preference to enable new picture viewer
- Like the playback rewrite; only shows in development builds
- Add KeyHandler DSL to write readable key press handlers
- Add new picture viewer
- Supports portrait mode
- Sort of supports touch
- Supports slideshows
- Shows controls to make it easy to start slideshows and navigate …
=> Add new experimental picture viewer

app/src/main/java/org/jellyfin/androidtv/auth/store/AuthenticationStore.kt
Fixes corrupt JSON causing the app to crash
**Changes**
- Catch decoding exception in AuthenticationStore
**Issues**
Fixes #1963
=> Catch decoding exception in AuthenticationStore

app/src/main/res/layout/live_tv_guide.xml
Other screens use 20sp but live tv used 15sp offset 🤷‍♂️ 
**Changes**
- Fix alignment of ClockUserView in live TV guide
**Issues**
=> Fix alignment of ClockUserView in live TV guide

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/androidtv/JellyfinApplication.kt, app/src/main/java/org/jellyfin/androidtv/ProcessLifecycleInitializer.kt
This PR changes the way we create the DefaultLifecycleObserver that ends up injecting the activity callbacks (including the one that manages the theme). It now uses it's own initializer. This doesn't change any behavior, just moves the code to make it more managable.
**Changes**
- Migrate DefaultLifecycleObserver setup to androidx.startup
**Issues**
=> Migrate DefaultLifecycleObserver setup to androidx.startup

app/src/main/java/org/jellyfin/androidtv/data/repository/UserViewsRepository.kt, app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/LibrariesPreferencesScreen.kt
Only collection types that use the grid should open the DisplayPreferencesScreen in the settings (Customization->Libraries). Added a special case to open the Live TV (guide) settings as a bonus.
**Changes**
- Don't open library settings for unsupported types
**Issues**
=> Don't open library settings for unsupported types

app/src/main/java/org/jellyfin/androidtv/util/apiclient/BaseItemUtils.kt, app/src/main/res/values/strings.xml
Code behavior is the same as before except that it now handles season 0 as specials.
**Changes**
- Properly handle specials in item naming
- Slightly refactor the getFullName() function
**Issues**
Fixes #1961
=> Properly handle specials in item naming

app/src/main/java/org/jellyfin/androidtv/ui/AsyncImageView.kt, app/src/main/java/org/jellyfin/androidtv/ui/ClockUserView.kt, app/src/main/res/layout/clock_user_bug.xml, app/src/main/res/values/attrs.xml
We prefer AsyncImageView for displaying (networked) images since it allows us to easily set the fallback/blurhash and moves all Glide code to a single place. This PR migrates the ClockUserView.
**Changes**
- Support circle crop in AsyncImageView
- Use AsyncImageView in ClockUserView
**Issues**
=> Use AsyncImageView in ClockUserView

app/src/main/java/org/jellyfin/androidtv/ui/GuideChannelHeader.java, app/src/main/res/layout/channel_header.xml
We prefer AsyncImageView for displaying (networked) images since it allows us to easily set the fallback/blurhash and moves all Glide code to a single place. This PR migrates the GuideChannelHeader.
**Changes**
- Use AsyncImageView in GuideChannelHeader
**Issues**
=> Use AsyncImageView in GuideChannelHeader
